### ISSUE TITLE
Fix DocumentBasedFixAllProvider: Should not throw System.ArgumentException - An item with the same key has already been added.

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-dotnet#1109]
See SonarSource/sonarlint-visualstudio#507

**Comment by michalb-sonar** [comment]
@kinloongTong I couldn't reproduce the problem. Could you please post a short snippet of code on which you see the issue?

**Comment by Evangelink** [comment]
@michalb-sonar I don't know which code sample can produce that but if you look at the code you'll see we do `ToDictionary` without checking the unicity of keys: https://github.com/SonarSource/sonar-csharp/blob/master/sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Common/FixAllProviders/DocumentBasedFixAllProvider.cs#L125 so this error can happen.

**Comment by michalb-sonar** [comment]
@Evangelink thanks for pointers. I believe it is a real issue (we had problems with `ToDictionary` before) - but without a way to trigger it, the fix would be a stab in the dark.

**Comment by michalb-sonar** [comment]
@kinloongTong Thanks for quick response.

I presume the code is not on public github already. Could you find a case that breaks in connected mode and send it to us? (feel free to anonymize/simplify if code security is a concern) 

BTW, what is the version of the SonarVB.NET plugin on your SonarQube (in failing scenario)?

**Comment by kinloongTong** [comment]
Hi @michalb-sonar

I believe this is the version of SonarVB.net 6.7.0.4267

We are using TFS, the error happen whenever 'Or' change to 'OrElse' Rule [S2178](https://rules.sonarsource.com/vbnet/RSPEC-2178)  with Fix all occurrences in: Document

I'm not able to provide the source code now as i'm out of office.

Thanks!

**Comment by pavel-mikula-sonarsource** [comment]
I'm able to reproduce this issue with latest SonarLint 4.17 and SonarVB 8.3 and VS2019, as well as previous versions matching criteria below:

## Minimum reproducible scenario
Code with issue S2178
```vb
Public Class Triage
    Public Function Check(T As String) As Boolean
        Return T = "RM" Or T = "CM"
    End Function
End Class
```
- SonarLint must be installed. Or any other empty VSIX that will register MefComponent and one version of the Analyzer (8.3 in this case, embeded in SLVS or custom VSIX).
- Another version of the Analyzer must be plugged in. Either as NuGet package or direct reference
```xml
  <ItemGroup>
    <Analyzer Include="..\..\..\SonarVB 8.2\SonarAnalyzer.dll" />
    <Analyzer Include="..\..\..\SonarVB 8.2\SonarAnalyzer.VisualBasic.dll" />
  </ItemGroup>
```
In this scenario, there are two different analyzers analyzing the projects. Both raise the same issue on the same location. Roslyn will suppress the second DLL if there are two same versions.

Trying to execute the CodeFix will throw the exception.

**Comment by pavel-mikula-sonarsource** [comment]
Hi @kinloongTong,
this issue is now fixed and it should be released with next version of SonarLint and SonarQube 8.2.
