### ISSUE TITLE
Rule S4071: Unmanaged Win32 APIs should not be used

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-dotnet#1169]
[RSPEC-4071](https://jira.sonarsource.com/browse/RSPEC-4071)

An incorrectly defined platform invoke method (marked with System.Runtime.InteropServices.DllImportAttribute) can lead to runtime exceptions because of issues such as a misnamed function, faulty mapping of parameter and return value data types, and incorrect field specifications. If available, it is a lot less error prone, not to mention more secure and quite simpler, to call the equivalent managed method.

**Comment by Evangelink** [comment]
I would recommend to close this issue. I discussed it on [runtime](https://github.com/dotnet/runtime/issues/61964) (see CA2205) and they said it's not worth porting it as it makes a lot less sense now that .NET is cross-platform.

cc @andrei-epure-sonarsource

**Comment by andrei-epure-sonarsource** [comment]
thanks @Evangelink
