### ISSUE TITLE
Conditional (Branch) Coverage not reported

### ISSUE THREAD

**Issue by md1986** [SonarSource/sonar-dotnet#1213]
### Description

SonarQube provides a column named "Uncovered Conditions" in the coverage section of the Measures menu. Usually there should be either a number or a percentage of lines that have uncovered conditionals or code branches when OpenCover is being used. This metric is not being evaluated by SonarQube though.

### Expected behavior

Evaluate branch coverage of OpenCover report.

### Actual behavior

Branch coverage is disregarded by SonarQube.

### Related information

* SonarC# Version: 6.7
* Scanner for MSBuild Version: 4.0.2.892

**Comment by andrei-epure-sonarsource** [comment]
closing as it is a duplicate of  #1606
