### ISSUE TITLE
Fix S1871 FN:  Support single line conditional block

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonar-dotnet#1255]
[RSPEC-3923](https://jira.sonarsource.com/browse/RSPEC-3923) and [RSPEC-1871](https://jira.sonarsource.com/browse/RSPEC-1871) have been updated in sync to support two new exceptions (see the rule descriptions). The implementation of RSPEC-1871 must be updated accordingly. 

Relates to #1079 

[RSPEC-3923]: https://sonarsource.atlassian.net/browse/RSPEC-3923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RSPEC-1871]: https://sonarsource.atlassian.net/browse/RSPEC-1871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Evangelink** [comment]
Exceptions for S3923 were already handled in the implementation of #1079. I'll update S1871 from this ticket.

**Comment by gregory-paidis-sonarsource** [comment]
The exception seems to be implemented, but the exception OF THE exception is missing, resulting in an FN.
This is a quite probably pattern, for example because of copy-pasting.
