### ISSUE TITLE
Rule S4583: "BeginInvoke" should be paired with "EndInvoke"

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-dotnet#1330]
### Description

Using `BeginInvoke` without a closing `EndInvoke` can result in thread leaks. That's because when the invoked method throws an exception or returns a value, the thread that is used is never released back to the `ThreadPool`.

This rule raises an issue when a call to `BeginInvoke` is not paired with a call to `EndInvoke`.

Implements [RSPEC-4583](https://jira.sonarsource.com/browse/RSPEC-4583)

**Comment by andrei-epure-sonarsource** [comment]
Please open a separate ticket for the VB.NET implementation, I am removing the label from this one
