### ISSUE TITLE
SonarC# feeds SonarQube with test files and brings all related features (highlighting, issues)

### ISSUE THREAD

**Issue by agigleux** [SonarSource/sonar-dotnet#1355]
The technical impact on SonarC# is small because https://github.com/SonarSource/sonar-csharp/issues/1087 is already implemented.

We need to update https://github.com/SonarSource/sonar-csharp/blob/master/sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpSensor.java#L82 to not filter on MAIN files so that all files of all Modules (including Test MS Project) of a MS Solution are considered. 

We need to update the https://github.com/SonarSource/sonar-csharp/blob/master/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/ProtobufDataImporter.java#L71 to not save metrics related to Type.TEST files.

**Comment by andrei-epure-sonarsource** [comment]
should take some decision about #447 as well

**Comment by andrei-epure-sonarsource** [comment]
fixed in  #4208
