### ISSUE TITLE
Analyzer should be aware of SonarQube/SonarCloud configuration

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-dotnet#1381]
### Description

Some of the information stored in SonarQube/SonarCloud (e.g. `sonar.cpd.exclusions` or `sonar.exclusions`...) are currently only used to filter down results on the end step of the scanner for msbuild. Handling these information earlier would allow to improve performance by not computing data that will be disregarded after.

**Comment by pavel-mikula-sonarsource** [comment]
As a result of recent investigation [MMF-2384](https://jira.sonarsource.com/browse/MMF-2384), I'm closing this as Won't fix.
