### ISSUE TITLE
Rule S4635: String offset-based methods should be preferred for finding substrings from offsets

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-dotnet#1422]
### Description

Looking for a given substring starting from a specified offset can be achieved by such code: `str.Substring(startIndex).IndexOf(char1)`. This works well, but it creates a new string for each call to the `Substring` method. When this is done in a loop, a lot of strings are created for nothing, which can lead to performance problems if `str` is large.

To avoid performance problems, `string.Substring(startIndex)` should not be chained with the following methods:
```
IndexOf
IndexOfAny
LastIndexOf
LastIndexOfAny
```

For each of these methods, another method with an additional parameter is available to specify an offset.
Using these methods gives the same result while avoiding the creation of additional String instances.

Implements [RSPEC-4635](https://jira.sonarsource.com/browse/RSPEC-4635)

**Comment by mary-georgiou-sonarsource** [comment]
Closed as duplicate: https://github.com/SonarSource/sonar-dotnet/issues/2687
