### ISSUE TITLE
Add support for IsPatternExpressionSyntax to UCFG

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-dotnet#1782]
After the changes made in #157, the CFG could contain instructions with Kind SyntaxKindEx.IsPatternExpression, which should be represented in the UCFG.

Possible representation would be an assignment:
```
if (o is null)				// nothing
if (o is string s) 			// s := __id [ o ]
if (o is (int x, int y)) 	// this is invalid syntax, tuples cannot be declared in conditions
```

NOTE: don't forget that `o` could be field, property, etc.

**Comment by andrei-epure-sonarsource** [comment]
this should be moved to Jira as we don't generate the UCFG in this project anymore

**Comment by andrei-epure-sonarsource** [comment]
actually this has been implemented in the ucfg generation
