### ISSUE TITLE
Provide metrics for generated lines of code

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-dotnet#1808]
### Description

From [community thread](https://community.sonarsource.com/t/new-metric-for-number-of-generated-lines-of-code/1663).

**Comment by nicolas-harraudeau-sonarsource** [comment]
This metric is currently only implemented by SonarCobol. The use case [described on Jira](https://jira.sonarsource.com/browse/SONARCOBOL-28) is a mix of generated and manual code. This was developed for TELON support, which generates source code, including bits of custom code written by developers. SonarQube then raise issues on the manually written code only.

In my opinion we should provide the "Generated Lines of Code" metric only for such use cases. Generated code which does not contain any manually written code should never be analyzed.
**Thus I would postpone this ticket until we have use cases of tools generating code and including manually written code.**

**Comment by alexdrl** [comment]
Hello, the feature was requested because we have a Project in what Microsoft DSL Tools are used, which using T4 templates generate some C# code. Also, many of this classes are partial and can be modified, so at the moment, SonarQube only reports the manual code, not the generated code. This metric Will help us see we are we generating more code, less code, and the evolution of this metrics.

**Comment by Evangelink** [comment]
We are not able to implement this feature without a change on SonarQube/SonarCloud side. Indeed, this metric needs to be attached to a file BUT we are currently excluding the auto-generated files from the analysis. 

One easy solution to avoid polluting the database with the content of those auto-generated files would be to actually create an empty file at the correct location in the tree with a comment saying it's auto-generated. This way we could attach the number of generated LOC per file and have the per folder/module grouping done automatically.

**Comment by andrei-epure-sonarsource** [comment]
I'm coming with an update: we won't implement this metric. We have implemented the feature only for COBOL and don't have plans to use it for any other language. Also, as a side note, we recommend not to analyze generated code, so having a metric for this would be a contradiction from our side.
