### ISSUE TITLE
Update S2070: Add support for DSA, HMACMD5, HMACRIPEMD160 and RIPEMD-160

### ISSUE THREAD

**Issue by agigleux** [SonarSource/sonar-dotnet#1844]
Implements [RSPEC-2070](https://jira.sonarsource.com/browse/RSPEC-2070)

**Comment by Evangelink** [comment]
The idea of this improvement is to cover the following algo `DSA`, `HMACMD5`, `HMACRIPEMD160` and `RIPEMD-160`.
