### ISSUE TITLE
Compatibility documentation for the plugin

### ISSUE THREAD

**Issue by habdank** [SonarSource/sonar-dotnet#1916]
### Description

Would be very handy to add to te release information with which version of the SonarQube plugin ist compatible.

### Expected behavior

The list of release contains additional information, which points to SQ version, where the plugin is expected to work.

### Actual behavior

It is not clear which version of plugin works with, which version of SQ :-).

### Known workarounds

Try and error method by deploying plugin on different SQ servers.

**Comment by andrei-epure-sonarsource** [comment]
hi @habdank and please accept my apologies for the really, really late reply.

The compatibility matrix for all our plugins is here https://docs.sonarqube.org/display/PLUG/Plugin+Version+Matrix 

Do you think it is really necessary to add the compatibility in our release notes, given we have it on the website? Maybe put the URL in our release notes?
