### ISSUE TITLE
SonarQube 8.0 - Remove deprecated metrics

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-dotnet#1971]
### Description

The following metrics:

- FILE_COMPLEXITY_DISTRIBUTION
- FUNCTION_COMPLEXITY_DISTRIBUTION
- COMPLEXITY_IN_CLASSES
- COMPLEXITY_IN_FUNCTIONS
- PUBLIC_API
- PUBLIC_UNDOCUMENTED_API

are deprecated and will need to be removed on the next major version of SonarQube.

This task will require:
- to stop processing the metrics in the analyzer
- updating the protobuf to remove the fields
- updating the plugin to stop reading/pushing those metrics

### TODO
* backwards compatibility? Might need check the version of the server to decide whether or not to upload the deprecated metrics
* some of the metrics already cannot be retrieved once they have been uploaded -> might be able to drop support for them immediately
  - LE: they have been deprecated since SQ 6.7 LTS. We only have to support SQ 7.9 LTS so it's fine to stop uploading them.

**Comment by Evangelink** [comment]
Remove the IT-specific coverage properties https://github.com/SonarSource/sonar-dotnet/blob/master/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/CodeCoverageProvider.java#L53

**Comment by andrei-epure-sonarsource** [comment]
these seem to have been deprecated in 6.7 (dissapeared from the [SQ 6.7 docs](https://docs.sonarqube.org/display/SONARqube67/Metric+Definitions))
