### ISSUE TITLE
Rule S1994 (for loop increment) - update to focus on misplaced increments

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonar-dotnet#198]
This rule has been re-worked to focus on increments that happen only outside of the expected location. To cover the bug aspect this rule used to have, #199 has been entered to implement [RSPEC-2189](https://jira.sonarsource.com/browse/RSPEC-2189)

**Comment by gregory-paidis-sonarsource** [comment]
Close as duplicate of https://github.com/SonarSource/sonar-dotnet/issues/199.
More details there.
