### ISSUE TITLE
Change documentation/error to show that C# is not supported by sonar-scanner cli

### ISSUE THREAD

**Issue by SebastianDietrich** [SonarSource/sonar-dotnet#2018]
https://docs.sonarqube.org/display/SCAN and https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner do not mention that C# is no longer supported since Sonar C# 6.0 (https://github.com/SonarSource/sonar-csharp/issues/374)

When running sonar-scanner cli on a c# project the resulting information is misleading: "Property missing: 'sonar.cs.analyzer.projectOutPaths'. No protobuf files will be loaded for this project."

So please update the documentation and the error.

btw. not everyone can run scanner for MSBuild - e.g. my laptop has not enough free space to install everything needed for MSBuild; I just need to analyze the C# project, I don't need to work on it.
So I had to revert to sonarqube 5.6.7 to quickly analyze a C# project

**Comment by lfraile** [comment]
I'm having the same problem analyzing .NET Core projects from Azure Devops, and as they are just build with dotnet build, it seems I can't use msbuild integrated scanner, so no way to analyze it

**Comment by SebastianDietrich** [comment]
Workaround is still possible to download an old version of SonarQube and the c# plugin. Worked perfectly for me

**Comment by valhristov** [comment]
@SebastianDietrich I agree that the error/warning messages that are displayed during the analysis with Scanner CLI are not very user friendly.

@lfraile, there is a separate download for cross-platform Scanner for MSBuild, that runs through the `dotnet` command (you could install it as a global tool as well). You can find a link to the package and instructions how to use it here:
https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+MSBuild

**Comment by lfraile** [comment]
Thanks @SebastianDietrich  which version are you currently using?

And thanks @valhristov is there any documentation on how to integrate it with Azure DevOps builds? is it possible?

**Comment by SebastianDietrich** [comment]
@lfraile - I'm using the latest 5.x version - https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-5.6.7.zip and the corresponding C# plugin (just put it in extensions/plugins) https://binaries.sonarsource.com/Distribution/sonar-csharp-plugin/ (5.9.0.1001)

**Comment by valhristov** [comment]
@lfraile, you just need to install the Azure DevOps (e.g. VSTS) extension for SonarQube in your workspace and then use the tasks in your pipeline (they work on both Windows and Linux agents):
https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarqube
https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarcloud

Documentation and how to use:
https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Extension+for+VSTS-TFS
https://blogs.msdn.microsoft.com/premier_developer/2018/04/11/sonarqube-integration-with-vsts/

**Comment by lfraile** [comment]
I'm aware of that, I mean if I use this tasks with a dotnet core project in Azure DevOps I get the fail when I try to use Msbuild integration, if I just use the stand alone scanner it fails. So it seems the it is not correctly integrated to be usedwith .NET Core projects

**Comment by lfraile** [comment]
@valhristov is there any way to talk to you in private to show you the experience and provide you logs of it?

**Comment by valhristov** [comment]
I am afraid I am not available for private chat (that's a feature of our support :)), but you could share the logs here (a Dropbox file request - if you upload files here they will be accessible only to me) and I will check them out as soon as possible:
https://www.dropbox.com/request/CszJAO1ZNXFVl1gwo5hA

**Comment by lfraile** [comment]
Ok, I uploaded the logs

**Comment by valhristov** [comment]
Thanks @lfraile I got the files. Could you please, open a new issue here and describe your problem in detail? I am a bit confused - from the logs it seems that the analysis succeeded and I can also see two warnings that come from SonarC#... I see two warnings for `projectOutPaths` but they are for a test project (UserStories.AcceptanceTest) and that's expected, as we don't generate those for test projects.

**Comment by lfraile** [comment]
So I can just exclude the tests projects with sonar.exclusions and the analysis is valid? hmmm ok I will try, maybe it is just a misunderstanding from my side

**Comment by lfraile** [comment]
Still have this warning ...

**Comment by LittleColin** [comment]
FWIW I was using SonarC# plugin at version 6.5 (build 3766) and despite no errors, no lines of C# were shown in the analysis. Upgrading the SonarC# plugin to 7.8 fixed this.

**Comment by andrei-epure-sonarsource** [comment]
closing this issue as now the docs [clearly state](https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner)

> Property missing: 'sonar.cs.analyzer.projectOutPaths'. No protobuf files will be loaded for this project.
> 
> Scanner CLI is not able to analyze .NET projects. Please, use Scanner for MSBuild. If you are running Scanner for MSBuild, ensure that you are not hitting a known limitation.
