### ISSUE TITLE
Lower/remove duplications between c# and vb.net plugins code

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-dotnet#2036]
### Description

When doing the merge of SonarVB into this repository we mainly copy-pasted the code. It would be nice (it would simplify maintenance + future work) to refactor the code to extract most/all of the common logic.

**Comment by valhristov** [comment]
We can discuss that later - I think we need to unify the SQ properties for test results and coverage import, so that we don't have to duplicate sensors, etc. (and we will avoid the problems that occur when users specify both cs and vbnet test import properties in the same build).
