### ISSUE TITLE
Rule S1144: Unused "private" methods should be removed

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-dotnet#2049]
### Description

Implements https://jira.sonarsource.com/browse/RSPEC-1144

**Comment by pavel-mikula-sonarsource** [comment]
Rule is already implemented

**Comment by andrei-epure-sonarsource** [comment]
This ticket was meant to implement S1144 for VB .NET @pavel-mikula-sonarsource - is it implemented now?

**Comment by pavel-mikula-sonarsource** [comment]
The VB-only was not clear from the description. I've reopened #2245 when I was closing this one.
