### ISSUE TITLE
Rule S107: Functions should not have too many parameters

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-dotnet#2058]
### Description

Implements https://jira.sonarsource.com/browse/RSPEC-107

**Comment by nicolas-harraudeau-sonarsource** [comment]
Testing the NonCompliant code example does not raise any issue.

**Comment by nicolas-harraudeau-sonarsource** [comment]
Nervermind I missed that the example had a different max number of parameters than the default value. I just added a small fix to the rule's code example.
