### ISSUE TITLE
Scanner for MSBuild ignores base sonar properties

### ISSUE THREAD

**Issue by dwayne-mss** [SonarSource/sonar-dotnet#2086]
### Description

Analysis of .NET project with MSBUILD seems to ignore some SonarQube properties

### Repro steps

Using the "SonarScanner for MSBUILD - Begin Analysis" step... and additional arguments to exclude files from analysis... such as...

/d:'sonar.exclusions=**/FireConnect.Web/libs/*.js,**/FireConnect.Web/src/vendor/*.js'
/d:'sonar.verbose=true'

### Expected behavior

Should not see results from directory

### Actual behavior

See results in output

### Known workarounds

Please provide a description of any known workarounds.

### Related information

Snippet of logs...
21:13:02.901 INFO: Excluded sources: 
21:13:02.901 INFO:   **/FireConnect.Web/libs/*.js
21:13:02.901 INFO:   **/FireConnect.Web/src/vendor/*.js
.
.
.
21:13:18.177 DEBUG: 'FireConnect.Web/src/vendor/jquery.validate.js' generated metadata  with charset 'UTF-8'
21:13:19.426 DEBUG: 'FireConnect.Web/src/vendor/pikaday.js' generated metadata  with charset 'UTF-8'
21:13:21.129 DEBUG: 'FireConnect.Web/src/vendor/rollbar.js' generated metadata  with charset 'UTF-8'

* SonarC# Version
* Visual Studio Version
* If running through the Scanner for MSBuild, its version
[FDD] $ d:\sonar-scanner\SonarScanner.MSBuild.exe end
SonarScanner for MSBuild 4.3.1

**Comment by Evangelink** [comment]
Moved to https://github.com/SonarSource/sonar-scanner-msbuild/issues/646
