### ISSUE TITLE
dotnet-sonarscanner not showing scan results on SQ server

### ISSUE THREAD

**Issue by dnbr2002** [SonarSource/sonar-dotnet#2127]
### Description

I do not think this scanner is submitting results properly to the sonarqube server.  I think I should have bugs and vulnerabilities as well as coverage on my SQ Server but all are 0.  I do have code smells.  But based on these warnings I feel this may not be getting all scan results to the server properly??

**Relevant log entries**

- 09:59:14 SonarScanner for MSBuild 4.4.2
- 09:59:14 Using the .NET Core version of the Scanner for MSBuild
- 09:59:14 Default properties file was found at /opt/jenkins/workspace/shift_feature_initialCommit-KZFTSKCSHZN7MDDUBLRIXHMY5QQPIT7BWYKHLQQKJLL3GA7CKL4A@tmp/76997dfa-2b50-46a4-b42e-d1966bf6aacb/SqScanner/.store/dotnet-sonarscanner/4.4.2/dotnet-sonarscanner/4.4.2/tools/netcoreapp2.1/any/SonarQube.Analysis.xml
- 09:59:14 Loading analysis properties from /opt/jenkins/workspace/shift_feature_initialCommit-KZFTSKCSHZN7MDDUBLRIXHMY5QQPIT7BWYKHLQQKJLL3GA7CKL4A@tmp/76997dfa-2b50-46a4-b42e-d1966bf6aacb/SqScanner/.store/dotnet-sonarscanner/4.4.2/dotnet-sonarscanner/4.4.2/tools/netcoreapp2.1/any/SonarQube.Analysis.xml
- 09:59:14 Post-processing started.
- 09:59:14 WARNING: File '/home/ec2-user/.nuget/packages/xunit.runner.visualstudio/2.3.1/build/netcoreapp1.0/xunit.runner.visualstudio.dotnetcore.testadapter.dll' is not located under the root directory '/opt/jenkins/workspace/shift_feature_initialCommit-KZFTSKCSHZN7MDDUBLRIXHMY5QQPIT7BWYKHLQQKJLL3GA7CKL4A' and will not be analyzed.
- 09:59:14 WARNING: File '/home/ec2-user/.nuget/packages/xunit.runner.visualstudio/2.3.1/build/netcoreapp1.0/xunit.runner.reporters.netcoreapp10.dll' is not located under the root directory '/opt/jenkins/workspace/shift_feature_initialCommit-KZFTSKCSHZN7MDDUBLRIXHMY5QQPIT7BWYKHLQQKJLL3GA7CKL4A' and will not be analyzed.
- 09:59:14 WARNING: File '/home/ec2-user/.nuget/packages/xunit.runner.visualstudio/2.3.1/build/netcoreapp1.0/xunit.runner.utility.netcoreapp10.dll' is not located under the root directory '/opt/jenkins/workspace/shift_feature_initialCommit-KZFTSKCSHZN7MDDUBLRIXHMY5QQPIT7BWYKHLQQKJLL3GA7CKL4A' and will not be analyzed.
- 09:59:14 SONAR_SCANNER_OPTS is not configured. Setting it to the default value of -Xmx1024m
- 09:59:14 Calling the SonarQube Scanner...
- 09:59:14 INFO: Scanner configuration file: /opt/jenkins/workspace/shift_feature_initialCommit-KZFTSKCSHZN7MDDUBLRIXHMY5QQPIT7BWYKHLQQKJLL3GA7CKL4A@tmp/76997dfa-2b50-46a4-b42e-d1966bf6aacb/SqScanner/.store/dotnet-sonarscanner/4.4.2/dotnet-sonarscanner/4.4.2/tools/netcoreapp2.1/any/sonar-scanner-3.2.0.1227/conf/sonar-scanner.properties
- 09:59:14 INFO: Project root configuration file: /opt/jenkins/workspace/shift_feature_initialCommit-KZFTSKCSHZN7MDDUBLRIXHMY5QQPIT7BWYKHLQQKJLL3GA7CKL4A/.sonarqube/out/sonar-project.properties
- 09:59:14 INFO: SonarQube Scanner 3.2.0.1227

### Repro steps

Please provide the steps required to reproduce the problem

In my Jenkins pipe I install the dotnet-scanner in my dotnet tool path.

`dotnet tool install --tool-path ${tempDirectory} -v n dotnet-sonarscanner`

then 
`					dotnet-sonarscanner begin /d:sonar.host.url=https://sonar.ba.ssa.gov /d:sonar.cs.opencover.reportPaths="${tempDirectory}/TestResults/coverage.opencover.xml" /key:${getSonarProjectKey()} /n:${getSonarProjectName()}
`
`					dotnet test ${dotNetYamlSCM.getTestdir()} -v m --logger:trx --results-directory ${tempDirectory}/TestResults /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=${tempDirectory}/TestResults
`
`dotnet-sonarscanner end`

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

I expect full scan with and code coverage

### Actual behavior

I only see code smells

### Known workarounds

None

### Related information

Im running this through a Jenkins groovy pipeline
My project is .Net Core 2..1.5

**Comment by Evangelink** [comment]
Moved to https://github.com/SonarSource/sonar-scanner-msbuild/issues/623
