### ISSUE TITLE
S3900 - should ignore extensions

### ISSUE THREAD

**Issue by dragonfly75** [SonarSource/sonar-dotnet#2128]
I have an extension method:
public static void formatDate(this GridColumn column, string format)
        {
            column.DisplayFormat.FormatString=format;
.....

I get a warning "Refactor this method to add validation of parameter 'column' before using it."

Because it's an extension method, it's impossible to call it from a null-object.

Please modify S3900 in order to check if there is an extension method.

**Comment by Evangelink** [comment]
Hi @dragonfly75,

You can actually pretty easily call an extension method on a null object as the extension method is only bound to a type not to its value.

```csharp
GridColumn gc = null;
gc.formatDate(""); // NullReferenceException
```

**Comment by Corniel** [comment]
As you - as @Evangelink showed - can easily get a null reference exception, I would advise not to exclude extensions.
