### ISSUE TITLE
Do not report Security Hotspots as external rules when analyzing PRs and short-living branches

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonar-dotnet#2131]
### Description

Issues raised by SonarC# rules are reported as "external" in PRs.

### [Example PR](https://github.com/SonarSource/sonar-scanner-msbuild/pull/625):

![image](https://user-images.githubusercontent.com/10757559/49218152-93e37900-f3c7-11e8-8483-121659df5643.png)

### Related information

* SonarC# Version 7.10 (build 7601)
* SonarQube DCE Version 7.5 (build 19742)

* this seems to only affect hotspot rules.
* it looks like issues are reported correctly when the branch is analysed (i.e. only a problem on PRs)

**Comment by nicolas-harraudeau-sonarsource** [comment]
Impact of this bug: Pull Requests cannot be merged.
https://community.sonarsource.com/t/unable-to-suppress-pull-request-issue-because-drop-down-option-missing/4768

Thus the Security Hotspot rules will be deactivated until a fix is found.

**Comment by valhristov** [comment]
SonarC# uses `SensorContext.activeRules()` to find the repository key of each rule ID that's found in a Roslyn JSON report. When the repository key is not found, the rule is considered external.

However, `activeRules()` does not contain security hotspot rules when analyzing PR and short-living branches, which makes SonarC# to report the issues from our own hotspot rules as external.
