### ISSUE TITLE
TypeHelper.IsMatch should check OriginalDefinition as well to work with generics

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#2132]
[TypeHelper.IsMatch](https://github.com/SonarSource/sonar-dotnet/blob/5e4c6988273ab51d1974dce014b2feaeafeebb1d/sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/TypeHelper.cs#L60) checks only the typeSymbol.

However, this won't work for generic collections for which the `typeSymbol.SpecialType` contains the concrete type - e.g. `List<string>`, whereas the generic type definition is `List<T>`.

To fix this, the `OriginalDefinition.SpecialType` should be compared as well, like below.

        return type.Matches(typeSymbol.SpecialType) ||
                type.Matches(typeSymbol.OriginalDefinition.SpecialType) ||
                type.Matches(typeSymbol.ToDisplayString()) ||
                type.Matches(typeSymbol.OriginalDefinition.ToDisplayString());
        }

**Comment by Evangelink** [comment]
@andrei-epure-sonarsource The current approach that was taken, was to say that when calling this method, if you can have generics, then you should ensure the `OriginalDefinition` is passed.
