### ISSUE TITLE
No issues on Linux

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-dotnet#2133]
Running into a similar issue...

OS: Ubuntu 18.04
Host: Appveyor
dotnet-sonarscanner: 4.4.2
dotnet-sdk: 2.1.500
java-jdk: 8

Any suggestions to fix this? script listed below image
(note: if i run the same code from my windows machine, it works fine)
(also note: code coverage works, but thats from my coverlet)

![image](https://user-images.githubusercontent.com/461852/49271636-675d4a80-f423-11e8-8ac5-6fbe4eb9d1bc.png)

`
dotnet tool install --global dotnet-sonarscanner

dotnet test --filter "Category=Unit|Category=Integration" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

dotnet build-server shutdown
dotnet sonarscanner begin /k:$PROJECT /v:$VERSION /d:sonar.host.url=$SONAR_HOST /d:sonar.login=$SONAR_USER /d:sonar.password=$SONAR_PASS /d:sonar.cs.opencover.reportsPaths="test/*/coverage.opencover.xml" 

dotnet build

dotnet sonarscanner end /d:sonar.login=admin /d:sonar.password=admin
`

_Originally posted by @DR9885 in https://github.com/SonarSource/sonar-dotnet/issues/535#issuecomment-443102544_

**Comment by Evangelink** [comment]
Hi @DR9885,

I don't understand why you run the tests before the build, I would expect the following sequence of commands:
```
dotnet tool install --global dotnet-sonarscanner
dotnet sonarscanner begin /k:$PROJECT /v:$VERSION /d:sonar.host.url=$SONAR_HOST /d:sonar.login=$SONAR_USER /d:sonar.password=$SONAR_PASS 
dotnet build
dotnet test --filter "Category=Unit|Category=Integration" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
dotnet sonarscanner end /d:sonar.login=admin /d:sonar.password=admin
```
and optionnaly
`dotnet build-server shutdown`

Besides, do you see any `warning SXXX` in the build logs? If so, could you provide the logs of the end step (ideally after you passed `/d:sonar.verbose=true` in the begin step.

**Comment by Evangelink** [comment]
You are using SonarC# 6.5 which doesn't support cross-platform analysis (and is really outdated, we are currently at 7.9).

Please update the version of C# you are using to at least 6.7+.

**Comment by DR9885** [comment]
how do I get version 6.7+?

currently using the following command to get the tool:
```
dotnet tool install --global dotnet-sonarscanner
```

**Comment by Evangelink** [comment]
This command only allows installing the scanner for msbuild. The SonarC# version is based on your SonarQube server, I invite you to get back to your SonarQube admin to ask an update.

**Comment by DR9885** [comment]
awesome thanks for the quick responses, I'll check in with my dev-ops guy.

**Comment by Evangelink** [comment]
I am closing the issue but feel free to ping if you have any more problem on this topic.

**Comment by DR9885** [comment]
Just Updated to latest
![image](https://user-images.githubusercontent.com/461852/49280049-f8411f80-f43d-11e8-84b8-6e1b3498ed04.png)

it fixed code smell which is nice, but it doesn't seem to have bugs or vulnerability:
![image](https://user-images.githubusercontent.com/461852/49280095-16a71b00-f43e-11e8-9d90-d94b156ed3fb.png)

**Comment by DR9885** [comment]
well earlier when I ran the windows version, I had 2 bugs 1 vulnerability, and 1 duplicate, but that was on 6.5. After upgrading from 6.5 to 7.2, those are all zero.

I'm using the default quality profile, it was a brand new install from Stable Helm chart.
https://github.com/helm/charts/tree/master/stable/sonarqube

as for public endpoints, we plan to lock it down once we have it setup. This was more for testing the build process we want. 

I'm guessing this is a non-issue now that windows and linux publish the same details.

**Comment by Evangelink** [comment]
Can you make a test and add some code where you are sure it should raise a bug to confirm everything is working as expected?

For example a `ToString` returning `null`.

**Comment by DR9885** [comment]
Tried the ToString returning null, that works

**Comment by Evangelink** [comment]
Alright, so everything is set up! Enjoy!
