### ISSUE TITLE
Very slow analysis on large projects

### ISSUE THREAD

**Issue by WebDucer** [SonarSource/sonar-dotnet#2154]
### Description

We use Sonarqube as a docker container. Till last wee we used Sonarqube 7.1 with the last compatible C# plugin to this version. This week we swiched to the new version Sonarqube 7.4 and the latest C# plugin. All our large projects now run into timeout. Here one example for times (sonarqube run, and build without analysis)  from mid size project (12k LOC):

##### Sonarqube Analysis

```
Task                          Duration            
--------------------------------------------------
_cleanup                      00:00:00.0410357    
_restore                      00:00:02.2419166    
_startSonarQube               00:00:00.6358490    
_buildForSonar                00:01:46.4784181    
_endSonarQube                 00:00:09.4912884    
--------------------------------------------------
Total:                        00:01:58.8886545  
```

##### Build without Analysis

```
Task                          Duration            
--------------------------------------------------
_cleanup                      00:00:00.0394238    
_restore                      00:00:02.3300724    
_fixVersion                   00:00:00.2573063    
_buildLibrary                 00:00:10.6252127    
--------------------------------------------------
Total:                        00:00:13.2521862      
```

##### Sonarqube Analysis

```
Task                          Duration            
--------------------------------------------------
_cleanup                      00:00:00.0553016    
_restore                      00:00:02.8736038    
_startSonarQube               00:00:00.8892317    
_buildForSonar                00:00:20.6894544    
_endSonarQube                 00:00:10.4990138    
--------------------------------------------------
Total:                        00:00:35.0068337    
```

##### Build without Analysis

```
Task                          Duration            
--------------------------------------------------
_cleanup                      00:00:00.0426061    
_restore                      00:00:02.2465944    
_fixVersion                   00:00:00.2578240    
_buildLibrary                 00:00:10.8398578    
--------------------------------------------------
Total:                        00:00:13.3870700  
```

The analysis grows from 20 seconds with Sonarqube 7.1 to 1:45 minutes with Sonarqube 7.4.

I can not run our large solution (near 1M LOC). With 7.1 it take 16 minutes, now I stopped analysis after 4 hours without result.

During the switch from 7.1 to 7.4 no new rules was added to the projects.

### Repro steps

1. Create mid or large size project
2. Run analysis against Sonarqube 7.1
3. Run analysis against Sonarqube 7.4
4. Compare the analysis time

### Expected behavior

The analysis time should be near the same (or better) with the same rules.

### Actual behavior

The analysis takes a lot more time. On small projects, the time is the same. On mid size projects it raises with factor 6. Large size projects run in timeout.

### Known workarounds

No known workaroud

#### Sonarqube: 7.4

* SonarC# Version: 7.9.1.7622
* Visual Studio Version: 2017 15.8
* If running through the Scanner for MSBuild, its version: 4.3.1

#### Sonarqube 7.1

* SonarC# Version: 7.3.0.5690
* Visual Studio Version: 2017 15.8
* If running through the Scanner for MSBuild, its version: 4.3.1

**Comment by valhristov** [comment]
Hi @WebDucer, could you share the ruleset file that's generated in `<root>\.sonarqube\conf\*.ruleset` from both builds? Between SonarC# 7.3 and 7.9 there were quite a few changes and we added some new rules, which shouldn't be super slow, but could significantly affect the performance of the analysis.

**Comment by WebDucer** [comment]
@valhristov Here are the both rule sets

[SonarQube.zip](https://github.com/SonarSource/sonar-dotnet/files/2690467/SonarQube.zip)

**Comment by valhristov** [comment]
Thanks for the rulesets. Indeed, you have only the 21 new rules enabled. We know they are not the fastest rules we have, but they are not slow either and in general should not slow the analysis so much. For example, our Symbolic Execution rules are usually taking roughly 40-50s each on our test project, while the hotspots usually take less than a second each.

We are aware that there is a significant slow down in build times, the projects we analyze as part of our integration testing show 6-8 times slower build times with analysis. I cannot say when we are going to address this problem, but it is definitely something we want to do.

To be sure what exactly is causing the builds to be so much slower, I would like to ask you to run two builds - one on 7.1 and one on 7.4 (I hope you still have both), while adding the following parameters to the MSBuild command lines `/fl /flp:"logFile=sonar-diag.log;verbosity=diag" /p:ReportAnalyzer=true`. This will create a new file `sonar-diag.log` in the current directory (feel free to specify another path) with diagnostic logs and analyzer performance metrics.

Depending on the project the logs could become pretty big, so you could upload them here (it's a private space, available only to me): https://www.dropbox.com/request/CszJAO1ZNXFVl1gwo5hA

**Comment by WebDucer** [comment]
@valhristov Thanks for help. I uploaded the logs from two builds (20 minutes with 7.1 and over 4h with 7.4).

**Comment by valhristov** [comment]
Thanks for the logs @WebDucer. It seems that the analysis of two of the projects is super slow because of S1144 (Unused private member). It was rewritten to reduce the false positive/negative rate, but it seems we broke the performance...

Does the project that generates `RSAG.WinUI.Recy.dll` have `InternalsVisibleTo` attributes? I suspect that's the problem, but I'll need some time to investigate. I'll keep you posted.

As a simple workaround you could disable the rule and the builds should not be super slow anymore.

**Comment by WebDucer** [comment]
Thanks @valhristov . After deactivating the rule "S1144" the analysis build takes 18 minutes (like in 7.1).

No, we don't use `InternalsVisibleTo` attribute. In none of our projects.

I hope, the rule "S1144" will be perfomant again in the future. If you need some tests, I can do them on our test docker environment.

I am on vacations an will be available again afte January the 7th.

**Comment by valhristov** [comment]
Hi @WebDucer, Happy New Year!

Attached is [a new build of SonarC#](https://github.com/SonarSource/sonar-dotnet/files/2724507/sonar-csharp-plugin-7.10.0.7840.zip), which addresses the performance of S1144 in your project. I would be glad if you could try it and let me know the results (if could you run the commands from https://github.com/SonarSource/sonar-dotnet/issues/2154#issuecomment-448536640 and upload the result would be excellent).

**Comment by WebDucer** [comment]
@valhristov I tried the new version (7.10 (build 7840)) with activated S1144. The analysis build take over 3h. So there seems no perfomance win in the new version.

I uploaded the logs from today's run.

**Comment by valhristov** [comment]
We saw significant improvement in the analysis time after the change we made (the rule was putting a lot of pressure on the memory and we made it much less demanding), but apparently it is not the problem on your side...

I noticed that your slowest projects are WinForms applications with a lot of resources and `.Designer` files, e.g. autogenerated code. I suspect this could be the problem, as far as I can remember, these files could become pretty large... I changed the rule to exclude autogenerated code from analysis, could you try to run it?

This is the updated SonarC#: [sonar-csharp-plugin-7.10.0.7887.zip](https://github.com/SonarSource/sonar-dotnet/files/2733177/sonar-csharp-plugin-7.10.0.7887.zip)

**Comment by WebDucer** [comment]
@valhristov Thanks. This version works. Now it takes 26 minutes to complete.

In addion, I will exclude resource and designer files explicitly from analysis `/d:sonar.exclusions=**/*.Designer.cs,**/*.resx`

**Comment by LordDelacroix** [comment]
What's the status on this? I have 2,108 files in 17 projects in my solution. The analysis took 38 hours 23 minutes last time I ran it using the SonarWay ruleset.

**Comment by andrei-epure-sonarsource** [comment]
@LordDelacroix could you please open a new issue (as this specific one has been fixed with the respective version of sonar-csharp). In the new issue, please specify more details - what version of SonarQube you are using / or if you use SonarCloud, version of sonar-csharp, version of msbuild, what integration you are using. Thank you.

**Comment by LordDelacroix** [comment]
I was able to resolve on my own.
To fix I deleted the RuleSet with the issue and recreated it from scratch.
That tells me that somehow the RuleSet got corrupted.

Thank you!
________________________________
