### ISSUE TITLE
Fix S3937: FP for numbers with type suffixes (i.e. 1_000_000UL)

### ISSUE THREAD

**Issue by antrv** [SonarSource/sonar-dotnet#2196]
### Description

All numbers with literal suffix and thousands separator cause false positive S3937 error.

### Repro steps

Compile the code:
ulong a = 1_000_000UL;

### Expected behavior

There should be no errors.

### Actual behavior

I'm getting the following error message:
S3937 Review this number; its irregular pattern indicates an error.
The use of punctuation characters to separate subgroups in a number can make the number more readable. For instance consider 1,000,000,000 versus 1000000000. But when the grouping is irregular, such as 1,000,00,000; it indicates an error. 

### Related information

* SonarC# Version 7.9.1.7622
* Visual Studio Version 2017 15.9.4

**Comment by Evangelink** [comment]
Hi @antrv,

Thanks for the feedback! We forgot to remove the type specifier (e.g. `UL`) so we end up with one group of length 3 and one group of length 5, that's why the rule is reporting.

Cheers,
Amaury
