### ISSUE TITLE
Rule S1128: Useless usings should be removed

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-dotnet#2210]
### Description

Implements https://jira.sonarsource.com/browse/RSPEC-1128

**Comment by nicolas-harraudeau-sonarsource** [comment]
@christophe-zurn-sonarsource Is it possible to deduplicate issues raised by this rule with rule roslyn:CS0105 from roslyn? Both will raise when an import is done twice.

**Comment by andrei-epure-sonarsource** [comment]
reopening. As discussed with @nicolas-harraudeau-sonarsource , to avoid duplicate issues caused by CS0105 , we will remove the detection of `duplicate usings` and only keep `unused usings`

**Comment by andrei-epure-sonarsource** [comment]
closed (again) in #2671
