### ISSUE TITLE
Update S1172: Rule should handle 'virtual' methods

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-dotnet#2226]
### Description

Currently, the rule won't raise any issue on a method marked as `virtual` as changing it could lead the developer to break sub-classes.

Most of the times, an unused parameter is the result of a refactoring hence a change of behavior is quite likely. Besides, it should be the developer responsibility to know whether is class is a library (API) and so could lead to breaking change.

**Comment by pavel-mikula-sonarsource** [comment]
This would probably cause too many FPs
