### ISSUE TITLE
Rule S1858: "ToString()" calls should not be redundant

### ISSUE THREAD

**Issue by Corniel** [SonarSource/sonar-dotnet#2232]
### Description
Calling ToString() on an instance of a string is redundant. Best case nothings happens, worst case a null reference exception is thrown.

### Expected behavior
``` C#
public class Test
{
    public string DoSomehting(string member)
    {
        return member.ToString(); // Not compliant
    }

    public string DoSomehting(object member)
    {
        return member.ToString(); // compliant
    }
}
```

``` VB
Public Class Test

    Public Function DoSomehting(member as String) As String
        Return member.ToString() ' Not compliant
    End Function

    Public Function DoSomehting(member as Object) As String
        Return member.ToString() ' compliant
    End Function
End Class
```

**Comment by Evangelink** [comment]
Hi @Corniel,

Thank you for the suggestion, this is indeed a rule we already thought about but haven't had time to implement yet. 

See [RSPEC-3463](https://jira.sonarsource.com/browse/RSPEC-3463)

**Comment by Corniel** [comment]
It should be easy to do so. :)

**Comment by Evangelink** [comment]
Hi @Corniel,

I am closing this ticket as the implementation is already done (I misread the rules definition website).

Please turn on the rule [S1858](https://rules.sonarsource.com/csharp/RSPEC-1858) on your Quality Profile and enjoy!
