### ISSUE TITLE
sonar.coverageReportPaths is not declared as multi-values/property set

### ISSUE THREAD

**Issue by pablosanchez84** [SonarSource/sonar-dotnet#2246]
### Description

WARN: Property 'sonar.coverageReportPaths' is not declared as multi-values/property set but was read using 'getStringArray' method. The SonarQube plugin declaring this property should be updated.

### Repro steps

Run sonar-scanner with the sonar.coverageReportPaths property set either via a -Dsonar.coverageReportPaths argument or in the .properties file.

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

No WARNs should be printed.

### Actual behavior

sonar-scanner execution prints:
WARN: Property 'sonar.coverageReportPaths' is not declared as multi-values/property set but was read using 'getStringArray' method. The SonarQube plugin declaring this property should be updated.

### Known workarounds

N/A

### Related information

INFO: SonarQube Scanner 3.3.0.1492
INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
INFO: Linux 3.10.0-957.1.3.el7.x86_64 amd64

**Comment by valhristov** [comment]
Hi @pablosanchez84, what are the versions of SonarQube, SonarC# and Scanner for MSBuild you are using? Could also send us the full debug logs of the analysis (put `/d:sonar.verbose=true` on the **begin** step of Scanner for MSBuild command)?

**Comment by Evangelink** [comment]
Hi @pablosanchez84,

I am closing this thread due to lack of activity. Please feel free to comment/reopen if you are still facing the issue.

**Comment by pablosanchez84** [comment]
I'm sorry folks, this is not related to the dotnet version and just now I now I realized  that. This can be closed.
