### ISSUE TITLE
WrongEncodingFileFilter has unsatisfied dependency with SonarQube 7.6

### ISSUE THREAD

**Issue by dungba88** [SonarSource/sonar-dotnet#2257]
### Description

After upgrading SonarQube server to 7.6 (using `sonarqube` docker image), the maven plugin stopped working when running the following the command:

```mvn test sonar:sonar -Dsonar.projectName=xxx -Dsonar.host.url=OUR_LOCAL_SONARQUBE_SERVER -Dsonar.login=xxx```

The exception is:

```
Unable to load component class org.sonar.scanner.scan.filesystem.ProjectFileIndexer: Unable to load component class org.sonar.scanner.scan.filesystem.FileIndexer: Unable to load component class org.sonarsource.dotnet.shared.plugins.WrongEncodingFileFilter: org.sonarsource.dotnet.shared.plugins.WrongEncodingFileFilter has unsatisfied dependency 'class org.sonarsource.dotnet.shared.plugins.AbstractConfiguration' for constructor 'public org.sonarsource.dotnet.shared.plugins.WrongEncodingFileFilter(org.sonarsource.dotnet.shared.plugins.EncodingPerFile,org.sonarsource.dotnet.shared.plugins.AbstractConfiguration)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@6f1d799:447<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@10a064bd:50<| -> [Help 1]
```

The project is entirely written in Java, I'm not sure why it's trying to use .NET plugin.

### Related information

- SonarQube server version: 7.6
- Sonar Maven plugin: 3.6.0.1398 (3.5.x and 3.4.x also doesn't work)

**Comment by henryju** [comment]
Hi,

You probably have to update the SonarC# plugin to 7.9.1 or newer. Older versions are not compatible with SonarQube 7.6.

**Comment by vprudnikov** [comment]
I have exactly the same problem. All sonar plugins are up to date.

**Comment by henryju** [comment]
@vprudnikov can you run the analysis in verbose mode (`/d:sonar.verbose=true`) and report the version of the SonarC# plugin? It should be logged during the 'end' phase.

**Comment by vprudnikov** [comment]
> @vprudnikov can you run the analysis in verbose mode (`/d:sonar.verbose=true`) and report the version of the SonarC# plugin? It should be logged during the 'end' phase.

sorry, I'm building a java project but the problem is also with ComponentContainer$ExtendedDefaultPicoContainer.

Should I post my problem somewhere else?

**Comment by vandrewskis** [comment]
same issue here

**Comment by Evangelink** [comment]
Hi @vprudnikov, hi @vandrewskis,

As stated by @henryju you have to update the SonarC# and/or SonarVB plugins on your SonarQube server to be at least `7.9.1`. Even if you are not using any C# the scanner downloads all language plugins and ask them if they need to execute for this set of files.

Could you please ensure the versions of SonarC# and SonarVB installed on your server?

**Comment by vandrewskis** [comment]
Thanks @Evangelink, @henryju , upgrading the plugins solved it!

**Comment by LaiHoangLe** [comment]
Hi, i suffer from the same problem but i use sonarcloud on Azure DevOps. Do you have any suggestions to solve this problem?

**Comment by andrei-epure-sonarsource** [comment]
hi @LaiHoangLe , for Azure DevOps integration please open a topic on https://community.sonarsource.com/
