### ISSUE TITLE
Trx parsing fails: Illegal character entity: expansion character (code 0xc

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-dotnet#2259]
### Description

Original post:
https://github.com/SonarSource/sonar-scanner-msbuild/issues/652

I am using the sonarcloud 1.5.1 vats plugin but analysis fails due to a problem reading the trx file.

From log
```
Error while parsing the XML file: D:\a\1\s\TestResults\VssAdministrator_fv-az40 2019-01-09 21_39_02.trx

ERROR: Caused by: Illegal character entity: expansion character (code 0xc

at [row,col {unknown-source}]: [1179,22]
```

For full log and all steps see https://svensson-daniel.visualstudio.com/OpenRiaServices/_build/results?buildId=239

I have searched a bit for the error message and it might be the case that the XML needs to be opened as XML 1.1 and not 1.0

### Repro steps

Try to parse trx file attached:
[VssAdministrator_fv-az40.2019-01-09.21_39_02.zip](https://github.com/SonarSource/sonar-dotnet/files/2821514/VssAdministrator_fv-az40.2019-01-09.21_39_02.zip)

Long steps:
1. Fork openriaserices/openriaservices at github
2. Edit azure pipelines yaml so that it uses vstest v1 instead of v2
3. Build via azure pipelines (need to setup a sonarcloud endpoint first)

### Expected behavior

I expect 
1. analysis to be uploaded to sonarcloud without issues.
2. Trx parsing to succeed

### Actual behavior

Trx reading fails and while upload analysis is aborted.

### Known workarounds

None 

### Related information

* SonarC#
* Usage: vsts sonarcloud 1.5.1

**Comment by valhristov** [comment]
This is not actually a bug in SonarC# but a problem in VSTest, which generates invalid XML.

Since we don't need most of the content in the TRX, possible solution would be to just strip the invalid characters while reading the XML. Here are several types that could be of help (or the corresponding streams):
- https://docs.oracle.com/javase/7/docs/api/java/io/PushbackReader.html
- https://docs.oracle.com/javase/7/docs/api/java/io/FilterReader.html

Other options that seem worse:
- https://stackoverflow.com/questions/2997255/how-to-tell-java-sax-parser-to-ignore-invalid-character-references
- https://stackoverflow.com/questions/4237625/removing-invalid-xml-characters-from-a-string-in-java

**Comment by mediawolf** [comment]
XML parser from .NET throws exception with such message:
**'{0}', hexadecimal value {1}, is an invalid character.**
where {0} is a bad character and {1} is its code.
Thus when a test report contains such exception dump (result of exception.ToString()), what is absolutely legal case, Sonar analysis fails. I used corrupted XML to ensure that my service handles bad input properly.

So technically, indeed, result TRX file becomes invalid, according to XML 1.0. It could be an opt-out setting in this extension to enable pre-pass on generated TRX that will replace disallowed characters with, for instance, DISALLOWED_CODEPOINT_N.
