### ISSUE TITLE
[Infra] Document and clean up CI build scripts

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonar-dotnet#2264]
Part of the initiative to make DotNet builds simpler, repeatable and more reliable

* if possible, remove external dependencies e.g. by replacing simple .ps1 scripts with MSBuild equivalents
* document remaining external dependencies required for release builds e.g. PowerShell
* document any remaining CI-scripts required by the CI build

Note: no need to remove optional scripts that are used by developers locally.
The focus is on simplifying the automated CI builds.

### Related issue(s)
https://github.com/SonarSource/sonarlint-visualstudio/issues/811
https://github.com/SonarSource/sonar-scanner-msbuild/issues/678

**Comment by pavel-mikula-sonarsource** [comment]
@andrei-epure-sonarsource Wasn't this done by migrating to AZP yml?

**Comment by andrei-epure-sonarsource** [comment]
Yes I think so, @pavel-mikula-sonarsource . Now the build doesn't have the level of indirections in had in Jenkins and the dependencies and execution is clear from the AZP yaml script. 

Closed in #2826
