### ISSUE TITLE
Migrate to common XML parser provided by sonar-analyser-commons

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [SonarSource/sonar-dotnet#2283]
We should use the common XML parser provided by sonar-analyser-commons instead of having our own parser. See https://github.com/SonarSource/sonar-dotnet/blob/8adc7af1b57e6023e84cf189da0a18401373a03c/sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/XmlParserHelper.java#L44-L48

**Comment by Evangelink** [comment]
@m-g-sonar Could you give us a quick intro on how we can do this change?
