### ISSUE TITLE
Update S126: Rule should handle exceptions listed in the main RSPEC

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [SonarSource/sonar-dotnet#2284]
Rule [RSPEC-126](https://jira.sonarsource.com/browse/RSPEC-126) does not implement in sonar-dotnet the same exceptions as the main rule description.

However this rule is not in sonarway and it is not clear why. Let's wait to have more information on the false positives rate on SonarCloud, or complaints from users before updating the rule implementation.

**Comment by andrei-epure-sonarsource** [comment]
This has been on hold for some time - any updates for the sonarcloud stats, @nicolas-harraudeau-sonarsource ?

**Comment by nicolas-harraudeau-sonarsource** [comment]
@andrei-epure-sonarsource No updates, I was waiting for some news regarding the tools developed to retrieve stats from SonarCloud. We can fix this for consistency but it has a low priority.

**Comment by CauchyAbel** [comment]
This is still not in production I guess....? I have some verbatim string literals and the rules are still complaining...
