### ISSUE TITLE
Cognitive Complexity score should not penalize with nesting for C# local functions

### ISSUE THREAD

**Issue by rjgotten** [SonarSource/sonar-dotnet#2288]
### Description

Currently the rule `S3776 - Cognitive Complexity of methods should not be too high` intentionally penalizes C# local functions with a +1 for nesting.

### Repro steps

Create any method of suitable complexity that uses a local function definition.

### Expected behavior

Local functions should not be penalized with nesting.
Or atleast the *first level* of local function should not be penalized.

### Actual behavior

Local functions are penalized with nesting.

### Known workarounds

Discard cognitive complexity warnings and/or disable the rule altogether.

As far as I'm concerned, *not* using local functions is not an option and neither is promoting them to private methods, as the entire intent of local functions is to provide a way to break down logic into parts while maintaining a "private even for other private members" scope.

Some of its strongest use cases are in the implementation of inner `yield` or `async` behavior and due to this nesting penalty those methods now get an artificially greatly inflated complexity score, to the point of nonsense.

### Related information

SonarC# Version : 7.10

**Comment by Evangelink** [comment]
Hi @rjgotten,

We had a lot of internal conversations about this but we ended up with this choice because when local functions reference some parameters or variables from the outer scope you actually have to keep more things in your mind to understand these local functions.

If you often end up with methods with higher score maybe you should update the threshold to a higher value so that it fits with your architecture.

**Comment by rjgotten** [comment]
> @Evangelink 
> If you often end up with methods with higher score maybe you should update the threshold to a higher value so that it fits with your architecture.

That's not acceptable for us. What you're suggesting is unmaintainable. For methods that implement an inner yield or async, you're basically saying: "just double the allowed code complexity"

No. Period.
Doing so will mess with allowed code complexity for methods which do not use local functions and involves a lot of per-project futzing about to find a setting 'which works' for each individual project.

In that case I'm going to start an internal discussion with our development teams to disable the code complexity rule altogether and get rid of the noise. 


Also; rather than internal discussion, you _could_ just introduce a switch/setting that allows for both behaviors, you know? Could even make it configurable for everyone to pick at what nesting level they want local functions to actually start counting towards complexity.
This isn't terribly complicated. You _CAN_ have your cake _AND_ eat it, here.

**Comment by Evangelink** [comment]
Hi @rjgotten,

I do understand your point and as I said, this went through some internal discussion raising pros and cons.

Regarding the idea of a switch, we avoid adding extra parameters to the rules as we have noticed that most users don't use them. In the end, this creates un-needed maintenance and source of errors.

If you really think this is a MUST HAVE then I encourage you to either create your own rule with the values you want OR to create some post under the `suggest new feature` page of our community forum => https://community.sonarsource.com/c/suggestions/features

Thank you for your feedback!

**Comment by andrei-epure-sonarsource** [comment]
Some docs to help create custom rules: 
- [Importing Issues from Third-Party Roslyn Analyzers](https://docs.sonarqube.org/pages/viewpage.action?pageId=11640944)
- [SDK for SonarQube Roslyn Analyzer Plugins](https://github.com/SonarSource/sonarqube-roslyn-sdk)
- our implementation of the [CognitiveComplexity rule](https://github.com/SonarSource/sonar-dotnet/blob/c6abd066b90df6d5b9f2fe484fb21d61ea404a30/sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CognitiveComplexity.cs)

**Comment by rjgotten** [comment]
Afaict the code that actually requires editing is here:

https://github.com/SonarSource/sonar-dotnet/blob/c6abd066b90df6d5b9f2fe484fb21d61ea404a30/sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Metrics/CSharpCognitiveComplexityMetric.cs#L47-L57

It's called from aforementioned `CognitiveComplexity` class's `Initialize` method, where a few different actions are being hooked in. Changing the logic means calling to a different implementation of `CSharpCognitiveComplexityMetric` for a method declaration, which from the looks of it means writing a completely new walker, as the current one is a private inner class.

Even if I _could_ build all that (and I probably could) - that means any custom rule here would have to opt in to maintaining parity with the official walker, which is a maintainance burden I'm really not looking forward to.
