### ISSUE TITLE
SonarAnalyzer: 4 unit tests are failing

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-dotnet#2289]
Builds like a charm. 4 tests fail:
```C#
ExecutingSqlQueries_CS_Disabled()
ExecutingSqlQueries_CS_NetCore()
ExecutingSqlQueries_VB_Disabled()
ExecutingSqlQueries_VB_NetCore()
```

Can not find the file specified.

_Originally posted by @Corniel in https://github.com/SonarSource/sonar-dotnet/issues/2223#issuecomment-463144842_

**Comment by Evangelink** [comment]
@Corniel Thanks for the feedback!

Could you let us know what is failing for those 4 tests?

**Comment by Evangelink** [comment]
Doing a fresh clone of the project I don't have the issue with those tests (maybe something is still in some cache or something). I will try from home tonight.

In the meantime, some more logs would be useful :D

**Comment by Corniel** [comment]
It suggests it can't find the *.cs files that should be analysed.

**Comment by Evangelink** [comment]
I will really need some more info to try and fix this issue because I can't repro this issue.
