### ISSUE TITLE
Update S100: Allow two-letter acronyms

### ISSUE THREAD

**Issue by saciervo** [SonarSource/sonar-dotnet#2290]
### Description

Rule S101 was updated to allow two-letter acronyms (#174). I think the same should be done with rule S100, with the same justification:

From [Microsofts Capitalization Conventions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions)

> A special case is made for two-letter acronyms in which both letters are capitalized, as shown in the following identifier: `IOStream`

Also the message of the analyzer should be corrected (see screenshot). The method name should be in pascal case (instead of camel case):

![image](https://user-images.githubusercontent.com/707898/52786164-76cf5580-305a-11e9-95a2-47706c5a27f1.png)

**Comment by Evangelink** [comment]
Makes sense to me!
