### ISSUE TITLE
Update S2933: Rule should not suggest adding readonly modifier for fields of type struct

### ISSUE THREAD

**Issue by freza-tm** [SonarSource/sonar-dotnet#2291]
### Description

Sonar suggest adding `readonly` modifier to field of type `SpinLock`, but this should not be done and is mentioned in .NET documentation https://docs.microsoft.com/en-us/dotnet/api/system.threading.spinlock?view=netframework-4.7.2 in remarks section.

### Repro steps

Have class with `SpinLock` field that is assigned only in constructor or initialized directly

`private System.Threading.SpinLock _lock = new System.Threading.SpinLock();`

### Expected behavior

do not raise S2933 in this situation, perhaps this should be done for all structs?

### Actual behavior

S2933 is raised

### Known workarounds

no workaround

### Related information

* SonarC# Version 4.8.0.4040
* Visual Studio Version VS2017

**Comment by Evangelink** [comment]
OMG! Thank you for the feedback!

I am linking this blog post from Eric Lippert to give some explanation about the why:
https://ericlippert.com/2008/05/14/mutating-readonly-structs/
