### ISSUE TITLE
SonarQube with Telerik

### ISSUE THREAD

**Issue by rahulc2012** [SonarSource/sonar-dotnet#2296]
### Description
I am working on soraqube with one of my websites where the code is written with telerik controls

when i am doing the build, it showing no bugs, no coverage and code just 242, even though its a huge web site. Please help not sure what changes i need to do

![image](https://user-images.githubusercontent.com/47803753/53064603-09725900-348e-11e9-825f-72b9bbb8b943.png)

**Comment by Evangelink** [comment]
Hi @rahulc2012,

Have you used the `Scanner for MSBuild` to analyze your project?

Could you check on the `Code` tab if you can actually see which files are missing and if they are listed in the logs?

If you can't find anything useful, please could you share the logs?

Cheers,
Amaury
