### ISSUE TITLE
SQL queries should not be vulnerable to injection attacks is not available in SonarAnalyzer.CSharp 7.11.0.8083

### ISSUE THREAD

**Issue by mrlokeshagarwal** [SonarSource/sonar-dotnet#2310]
### Description
While adding SonarAnalyzer.CSharp 7.11.0.8083 nuget package into Asp.net Core 2.0 project, "SQL queries should not be vulnerable to injection attacks" rule is not available.

### Expected behavior

"SQL queries should not be vulnerable to injection attacks" rule should be available in rule list.

### Actual behavior

"SQL queries should not be vulnerable to injection attacks" rule is not available.

### Related information

* SonarC# Version: 7.11.0.8083
* Visual Studio Version : 15.9.7
* If running through the Scanner for MSBuild, its version

**Comment by mrlokeshagarwal** [comment]
@Evangelink : Can you please help me with this?

**Comment by Evangelink** [comment]
Hi @mrlokeshagarwal,

These rules are not available in the NuGet, they are only available as part of our commercial edition or on SonarCloud.
