### ISSUE TITLE
Why there are so few naming convention rules for C#

### ISSUE THREAD

**Issue by twenzel** [SonarSource/sonar-dotnet#2315]
Why there are so few naming convention rules for C# (3) compared to Visual Basic.NET (18)?

**Comment by Evangelink** [comment]
Hi @twenzel,

Naming conventions rules are not a priority for the team and company at the moment. Regarding the difference between C# and VB.NET I guess this is just bound to the fact that VB.NET was only targeting naming convention rules at first.
