### ISSUE TITLE
FeatureRequest. Add a rule that ConfigureAwait should be called on every await

### ISSUE THREAD

**Issue by YairHalberstadt** [SonarSource/sonar-dotnet#2330]
In order to improve performance and avoid deadlocks, it is best practice to call ConfigureAwait(false) after every call to await Task.

The exception is when the continuation code needs to run on the UI thread, in which case best practice is to do so explicitly by calling ConfigureAwait(true).

A rule and and analyzer which checked this would be useful.

**Comment by Corniel** [comment]
Note that this not relevant for .NET core. Although it still advised to do so (due to potential usage with the .NET classic stack).
http://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html

**Comment by Evangelink** [comment]
Hi @YairHalberstadt and @Corniel,

Have you seen the rule [S3216](https://rules.sonarsource.com/csharp/RSPEC-3216)? I think that's what you are looking for.

Cheers,
Amaury

**Comment by YairHalberstadt** [comment]
@Evangelink
Could that be added to the Sonaranalysers nuget package?

**Comment by Evangelink** [comment]
Hi @YairHalberstadt,

This is already available. This is just not activated by default.
