### ISSUE TITLE
Improve generated code detection

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [SonarSource/sonar-dotnet#2331]
### Problem
We currently detect generated code using some regular expressions (see #905). However these regular expressions are too generic and mark non-generated code as generated (see #2228).

### Solution
We decided to improve this regular expression so that it matches the most common tools generating code.

The goal is not to detect generated code blocks among non generated code.

### Priority
This is a medium priority task and will wait after SonarQube 7.8 LTS.

**Comment by gregory-paidis-sonarsource** [comment]
Closed since the generated code detection does not use a regex anymore.
