### ISSUE TITLE
Error about missing ProjectGuid for .NET Core projects

### ISSUE THREAD

**Issue by bitbonk** [SonarSource/sonar-dotnet#2335]
### Description

SonarQube is not able to correctly handle the "new" csproj format. It always requires the otherwise useless `<ProjectGuid>` entry in the csproj.

The "new" csproj format is all about conciseness and minimalism adding back all those useless XML elements defeats its whole purpose.

### Repro steps

1. Create a new .NET Core project using *dotnet new* or Visual Studio including a Solution file.

2. Run it through SonarQube Analysis

### Expected behavior

SonarQube correctly analyzes and reports the analysis about my solution. Without having to add a `<ProjectGuid>` to the csproj. 

### Actual behavior

The projects are not analysed and the following error occurs:

> WARNING: The following projects do not have a valid ProjectGuid and were not built using a valid solution (.sln) thus will be skipped from analysis...

### Known workarounds

Add a `<ProjectGuid>` to the csproj with an arbitrary unique guid value as described [here](https://mohitgoyal.co/2018/09/08/sonarqube-fails-to-analyze-dotnet-core-code-with-error-duplicate-projectguid-00000000-0000-0000-0000-000000000000/) and [here](https://stackoverflow.com/a/52557954/4227).

### Related information

* SQ Version 7.6 (build 21501)
* Visual Studio 2019 RC

**Comment by Evangelink** [comment]
Hi @bitbonk,

I am closing this issue as duplicates of this issue https://github.com/SonarSource/sonar-dotnet/issues/2335

Feel free to subscribe to the other issue to get notified about the fix!

Cheers,
Amaury

**Comment by ikemtz** [comment]
If it helps anyone, this PowerShell script will find all of your .csproj files and add a ProjectGuid if it's missing.

https://github.com/ikemtz/NRSRx/blob/master/sonarqube-create-project-guids.ps1

**Comment by brunomartinsprointelliflo** [comment]
> If it helps anyone, this PowerShell script will find all of your .csproj files and add a ProjectGuid if it's missing.
> 
> https://github.com/ikemtz/NRSRx/blob/master/sonarqube-create-project-guids.ps1

The updated link is [https://github.com/ikemtz/NRSRx/blob/master/tools/sonarqube-create-project-guids.ps1](https://github.com/ikemtz/NRSRx/blob/master/tools/sonarqube-create-project-guids.ps1)

**Comment by brunomartinspro** [comment]
> If it helps anyone, this PowerShell script will find all of your .csproj files and add a ProjectGuid if it's missing.
> 
> https://github.com/ikemtz/NRSRx/blob/master/sonarqube-create-project-guids.ps1

The updated link is https://github.com/ikemtz/NRSRx/blob/master/tools/sonarqube-create-project-guids.ps1
