### ISSUE TITLE
BUG: S2683 reported incorrectly for Nullable<bool> ?? false

### ISSUE THREAD

**Issue by YairHalberstadt** [SonarSource/sonar-dotnet#2337]
### Repro steps

Install SonarAnalyzer.CSharp and compile the following code:

```csharp
using System;

class Program
{
	static void Main(string[] args)
	{
		var obj = args.Length > 0 ? new Program() : null;

		if (obj?.Cond ?? false)
		{
			Console.WriteLine("Foo");
			Console.WriteLine("Bar");
		}
	}

	private bool Cond = new Random().Next() % 2 == 1;
}
```

### Expected behavior

No warning

### Actual behavior

Warning S2583 on line 9:
> Change this condition so that it does not always evaluate to 'false'; some subsequent code is never executed.

### Related information

#152 and #162 are similar, but have been fixed

**Comment by andrei-epure-sonarsource** [comment]
fixed in #2497
