### ISSUE TITLE
Implement SonarQube with MSBuild

### ISSUE THREAD

**Issue by vibgyor17** [SonarSource/sonar-dotnet#2340]
### Description

We need help to implement Sonaqube(SonarAnalysis) with MSBuild

### Repro steps

We have followed steps as mentioned in https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+MSBuild

Downloaded "Download for .NET Framework 4.6+" and extracting the file then copied to ProgramFiles  and running below command.
SonarScanner.MSBuild.exe begin /k:"project-key"
We are getting timeout when running above command. And also our another question is after this do we need to create a service connection in Project Settings in VSTS?
Kindly provide details  this is causing lot of delay for our Build to proceed further.
### Related information

* SonarC# Version  4.5
* Visual Studio Version :VS2015
* If running through the Scanner for MSBuild, its version  MSBuild14

**Comment by Evangelink** [comment]
Hi @vibgyor17,

I am moving your issue to the scanner for msbuild repository: https://github.com/SonarSource/sonar-scanner-msbuild/issues/717
