### ISSUE TITLE
Fix S4158: Rule should consider .NetCore 2.0+ 'Dictionary.TryAdd' method

### ISSUE THREAD

**Issue by evan-h** [SonarSource/sonar-dotnet#2341]
Quality check misunderstands 'Dictionary.TryAdd' and raises the following issue

> Remove this call, the collection is known to be empty here

Example:

var contents = new Dictionary<string, CmsContent>();

if (!contents.TryAdd(item.ID, new CmsContent { Text = item.Value.Value }))
{
//do something 
}

**Comment by Corniel** [comment]
This correct. You just can add the item without first trying if it is already there.

**Comment by Evangelink** [comment]
Hi there,

Thank you for the feedback!
I confirm that I can reproduce the issue and that this is a False Positive on our side. The problem is that we actually don't cover this `TryAdd` method as it is a .NetCore specific method.

I'll create, shortly, a PR to fix this problem.
