### ISSUE TITLE
Usage of ReSharper .DotSettings configuration

### ISSUE THREAD

**Issue by ale7canna** [SonarSource/sonar-dotnet#2343]
Is there any way to use the `{SolutionName}.DotSettings` file during the build/analysis? I'm struggling to have SonarQube ignoring name related issues (such as abbreviations or new words)

**Comment by Evangelink** [comment]
Hi @ale7canna,

I am not sure to understand your question. Could you elaborate a bit more?

**Comment by ale7canna** [comment]
Hi @Evangelink,

After I run the SonarQube analysis, the report contains naming-related issues. For example `Rename class 'APISettings' to match camel case naming rules, consider using 'ApiSettings'.`
In my solution, I added API to the [ReSharper abbreviations list](https://www.jetbrains.com/help/resharper/Coding_Assistance__Naming_Style.html), so `API` is no longer an error.
The addition of such abbreviations reflects on the ReSharper [`.Dotsettings`](https://www.jetbrains.com/help/resharper/Sharing_Configuration_Options.html) file. In particular, when settings are shared among the team, this file will be placed beside the solution and named after it (`MySolution.sln.DotSettings`).

Is there a way to use these ReSharper settings when performing the SonarQube analysis?

**Comment by Evangelink** [comment]
Hi @ale7canna,

This is clear now, thanks for the explanation.

We don't see this as a high priority on our side so I'll close the ticket as `Won't Fix` but we will keep it in mind for future releases.

Thank you!

**Comment by ale7canna** [comment]
Thanks for the kind answer @Evangelink!

Hope to have this feature in future!

**Comment by delepster** [comment]
same
