### ISSUE TITLE
Update S3874: FP with interface implementations

### ISSUE THREAD

**Issue by Corniel** [SonarSource/sonar-dotnet#2344]
### Description
When implementing an interface or abstract method (or overriding a method), you should not be faced with an error on the defined contract by that interface or method that is overwritten. It is not the place where it can be fixed, and in a lot of cases it even impossible because that contract is not in your control.

### Repro steps
As an example I took rule S3874, which triggered me:

``` CSharp
namespace SonarAnalyzer.Experiments.CSharp
{
    public class S3874 : I3874
    {
        public void Set(ref S3874 obj) // compliant
        {
            obj = new S3874();
        }
    }

    public interface I3874
    {
        void Set(ref S3874 obj); // non-compliant
    }
}
```
### Related information
* SonarC# Version 7.11.0.8083
* https://github.com/Corniel/SonarAnalyzer.Experiments/blob/master/src/SonarAnalyzer.Experiments.CSharp/S3874.cs

**Comment by Corniel** [comment]
@Evangelink I assume this also true for VB.NET rules?

**Comment by Evangelink** [comment]
@Corniel the rule is currently not implemented for VB.NET but yes it would!
