### ISSUE TITLE
add rule for field names that begin with an underscore

### ISSUE THREAD

**Issue by ynauls** [SonarSource/sonar-dotnet#2349]
### Description

Unless I am missing the doc, I can't fine an existing rule field names that begin with a prefix, like underscore

### Repro steps

declaring the following should raise a rule violation event

`private string _myString`

### Expected behavior

* SonarC# Version 7.11.0.8083
* Visual Studio Version 2017

**Comment by Corniel** [comment]
Why? This is a convention that is often applied for private fields. #justmy2cts

**Comment by Evangelink** [comment]
Hi @ynauls,

Thank you for the suggestion but this is not a rule we are willing to implement.

There are some other analyzers like StyleCop or the Visual Studio rules that could help you with this.

**Comment by ynauls** [comment]
I understand, i was trying to avoid adding another analyzer, thank you,
