### ISSUE TITLE
Update S4261: Rule should handle 'ValueTask'

### ISSUE THREAD

**Issue by JeremyMorton** [SonarSource/sonar-dotnet#2354]
### Description

The implementation of S4261 considers only methods that return Task or Task<TResult> as asynchronous, but it should also realize that methods returning ValueTask or ValueTask<TResult> are also asynchronous.

* SonarC# Version - 7.11.0.8083

**Comment by Evangelink** [comment]
Hi @JeremyMorton,

The analyzer already handles `ValueTask<T>` but you are right that it doesn't handle `ValueTask` which is a NetCore 2.2+ new type.

Thank you for the feedback!
