### ISSUE TITLE
Make sure that exposing this HTTP endpoint is safe here.

### ISSUE THREAD

**Issue by matheusmaximo** [SonarSource/sonar-dotnet#2391]
### Description

I'm creating a Controller using C# .NetCore and once I submit my code to SonarCloud, I'm seeing an security issue regards to this Controller.

### Repro steps

```
    [ApiController]
    [Route("[controller]")]
    public class KeepWarmController : ControllerBase
    {
        [HttpGet]
        [ProducesResponseType(200)]
        public ValueTask<IActionResult> Get()
        {
            return new ValueTask<IActionResult>(Ok());
        }
    }
```

### Expected behavior

It should have no issues related to this

### Actual behavior

I'm getting an issue related to security of parameters for a parameterless method Get: "Make sure that exposing this HTTP endpoint is safe here."

### Related information

* SonarC# Version - SonarCloud
* Visual Studio Version - 2019
* If running through the Scanner for MSBuild, its version

**Comment by andrei-epure-sonarsource** [comment]
Hi @matheusmaximo. The security issue you are describing ([S4529](https://rules.sonarsource.com/csharp/RSPEC-4529)) is a Security Hotspot, which is intended to be reviewed during security audits of the code. It is not a Vulnerability and it does not affect the Quality Gate or the Technical Debt.

Please read about [Security Reports](https://docs.sonarqube.org/latest/user-guide/security-reports/) and [Security-related Rules](https://docs.sonarqube.org/latest/user-guide/security-rules/) in our documentation.
