### ISSUE TITLE
Fix S2589: FP with null coalesce operator

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonar-dotnet#2407]
### Description

sonarlint warnings ?? operator as S2589

### Repro steps

class A
{
public bool booleanVal { get; set; }
}

A aObj = null;
if(aObj?booleanVal ?? false)

You can observe the problem via the code above

### Notes
Moved from https://github.com/SonarSource/sonarlint-visualstudio/issues/880
Reported by @ilkerkaran
Possible duplicate of #2164

**Comment by andrei-epure-sonarsource** [comment]
Indeed looks like duplicate of #2164, will close it. I moved the example to that ticket.
