### ISSUE TITLE
Build hangs takes very long time

### ISSUE THREAD

**Issue by michelandre** [SonarSource/sonar-dotnet#2420]
### Description

Newly released version hangs in buildstep indefinetly. Since 4 days my project cannot build with Sonar. It hangs on dotnet build if sonar is enabled.

### Expected behavior

Build succeeds

### Actual 

Build hangs

### Known workarounds

None. (How do u specify a version of scanner to use with the yaml tasks?)

### Related information
SonarCloudPrepare_14d9cde6-c1da-4d55-aa01-2965cd301255\1.6.0\classic-sonar-scanner-msbuild\SonarScanner.MSBuild.exe
  
 plugin: csharp version 7.14.0.8411

Vs2019
.Net core 2.2

Is there a way to find out which rule causes issue when I run with non rules it works, I run Sonarway default.

Regards

**Comment by michelandre** [comment]
It doesnt hang it takes ~6 hours to complete and some files take a long long time so it seems hanged, before the new release it to ~3minutes to build. I am now waiting on the unit test phase but it also have grown improportionally.

**Comment by michelandre** [comment]
Seems to be an issue with
SonarAnalyzer.Rules.CSharp.UnusedPrivateMember

Sample diagnostic
     Total analyzer execution time: 21996.412 seconds.
     NOTE: Elapsed time may be less than analyzer execution time because analyzers can run concurrently.
     Time (s)    %   Analyzer
     21971.954   99   SonarAnalyzer.CSharp, Version=7.14.0.0, Culture=neutral, PublicKeyToken=c5b62af9de6d7244
     21735.002   98      SonarAnalyzer.Rules.CSharp.UnusedPrivateMember

Is this a new rule or have the behaviour changed, or is it something with the project structure that hits?

**Comment by andrei-epure-sonarsource** [comment]
hey @michelandre , thanks for moving the discussion on [our community forum](https://community.sonarsource.com/t/slow-build-times/9556/3), where you said the build time went to normal after disabling S1144 (UnusedPrivateMember).

Unfortunately without a reproducer it is hard to move the investigation forward, so I will close this ticket.
