### ISSUE TITLE
Configure GeneratedFileFilters to allow some files

### ISSUE THREAD

**Issue by semtos** [SonarSource/sonar-dotnet#2422]
I would like to analyze csharp files with **.g.cs** extention. This is actually not a generated file but our convention. How can I escape from getting this error: 

'SomeDirectory/ETitle.g.cs' excluded by org.sonarsource.dotnet.shared.plugins.GeneratedFileFilter

**Comment by andrei-epure-sonarsource** [comment]
Could be ignored using the same parameter as #2324

**Comment by andrei-epure-sonarsource** [comment]
I am closing this one as we will be adding a SQ setting to allow analysis of generated code #2324

**Comment by semtos** [comment]
How can I set this configuration, help plz.

**Comment by andrei-epure-sonarsource** [comment]
@semtos issue #2324 is in progress, it will be ready in the next release
