### ISSUE TITLE
S2219 FP: `is object` is not always allowed for null-check

### ISSUE THREAD

**Issue by Jetski5822** [SonarSource/sonar-dotnet#2424]
### Description

`is object` is the canonical non-null test in C#, but in SonarQube it throws a clumsy warning.

### Repro steps

```
if (obj is object)
{
....
}
```

Throws a "Use a 'null' check instead"

### Expected behavior

Should not throw a null check exception.

### Actual behavior

Throws a "Use a 'null' check instead"

### Known workarounds

none

### Related information

More information here https://twitter.com/FransBouma/status/1115201371182071808 but essentually... using `is object` isstead of != null gives better IL and has less side effects.

**Comment by Corniel** [comment]
We're disussing [RSPEC-2219](https://rules.sonarsource.com/csharp/RSPEC-2219) here.

This means a null check should always be written as `arg is null` and a not null check as `arg is object`. 

``` C#
public class S2219
{
    public S2219(object arg)
    {
        if(arg == null) // Not-compliant
        {
        }
        if(arg != null) // Not-compliant
        {
        }
        if (arg is null) // Compliant
        {
        }
        if (arg is object) // Compliant
        {
        }
    }
}
```

**Comment by andrei-epure-sonarsource** [comment]
Thanks @Jetski5822 for the detailed repro and the explanation in the link. And thanks @Corniel for discussing this.

We've discussed internally and indeed it makes sense to allow `is object` for null check. In the same time, `arg == null` and `arg != null` should also be allowed (where the type is known), as it is readable. [RSPEC-2219](https://rules.sonarsource.com/csharp/RSPEC-2219) is a `code smell` rule, so about maintainability, not performance.
