### ISSUE TITLE
Collect analyzer execution timings in analyses on Peach

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonar-dotnet#2430]
### Description

Add instrumentation to Peach analyses so we can measure how much time each analyzer adds to the overall execution time.

This will allow us to measure the overall impact that the rules have on the build time, and to identify any rules that have an excessive impact. It will also help us identify and investigate issues like #2429.

### Notes
Adding the following MSBuild parameters will cause the compiler to output the execution time for each rule: `/p:reportanalyzer=true /v:d`

An execution report will be output per-project. The report can be found in the log by searching for `Total analyzer execution time:`.

**Comment by pavel-mikula-sonarsource** [comment]
Discussion was already started on this topic and specification of HOW is planned:
https://trello.com/c/6JirlX1A/219-specify-the-how-part-of-the-performance-tooling-solution

I'll close this issue because we won't use it to track progress.
