### ISSUE TITLE
Update sonar-plugin-api to 7.9

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#2437]
### Description

Currently, we use `sonar-plugin-api` version `7.3` and `7.4-alpha1` in our plugins (shared, csharp and vbnet). We should update it to `7.9` and clean up, if possible, the usage of deprecated APIs, or open tickets for what involves significant work.

* SonarC# Version 7.14

**Comment by costin-zaharia-sonarsource** [comment]
CSharp plugin integration tests are failing on master. If I got things right it's due to this:
`SonarAnalyzer.Rules.CSharp.UnusedPrivateMember, 711ms  TIMED OUT`
