### ISSUE TITLE
Remove rule "Rule S3693: Exception constructors should not throw exceptions"

### ISSUE THREAD

**Issue by jinek** [SonarSource/sonar-dotnet#2468]
### Description
Rule "Rule S3693: Exception constructors should not throw exceptions" is against c# guides:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/exceptions/creating-and-throwing-exceptions under "Programmers should throw exceptions when one or more of the following conditions are true:".
.NET itself is made in the way base class of all exceptions System.Exception and others throw exceptions, it means any inheritor throws exceptions as-well.
Furthermore, exceptions can be thrown by .NET runtime itself in any place which is hard to predict:

```
public MyException()
{
     var buffer = new int[int.Max]; // can throw OutOfMemoryException
}
```
or
```
public SerializationException(object failedObject) : base(Resources.SerializationFailed) //Resources.SerializationFailed can throw BadImageFormat for exampel
{
    this.ObjectType = failedObject.GetType(); // NullReferenceException, OutOfMemoryException etc
    this.SerializationAttribute = failedObject.GetSerializationAttribute(); // Also BadImageFormatException, FileLoadException etc
}
```

### Expected behavior

No warnings about throwing exception from exceptions constructor, for example of **System.Exception** https://referencesource.microsoft.com/#mscorlib/system/exception.cs,f092fb2b893a0162

### Actual behavior

```
class SerializationException: Exception
{
    public void SerializationException(Type failedObjectType)
    {
         if (failedObjectType==null)         
             throw new ArgumentNullException(nameof(failedObjectType), "Type of failed object must be provided, otherwise this exception loses its meaning");
    }
}
```
shows warning according to the rule Rule S3693
### Known workarounds

Wrap "throw" in to a method:

```
    public void SerializationException(Type failedObjectType)
    {
         if (failedObjectType==null)         
             ThrowException();
    }
    
    public void ThrowException()
    {
              throw new ArgumentNullException(nameof(failedObjectType), "Type of failed object must be provided, otherwise this exception loses its meaning");
    }
```

### Related information
Rule: https://rules.sonarsource.com/csharp/RSPEC-3693
Task: https://github.com/SonarSource/sonar-dotnet/issues/584
Specs: https://jira.sonarsource.com/browse/RSPEC-3693
Idea: https://www.acodersjourney.com/top-15-c-exception-handling-mistakes-avoid/

**Comment by costin-zaharia-sonarsource** [comment]
This rule will be deprecated starting with Sonar C#/VB **8.0.0** (it will be removed in a future version).

**Comment by pavel-mikula-sonarsource** [comment]
Rule has been deleted in #4630 few years ago
