### ISSUE TITLE
Remove `sonar.cs.mstest.reportsPaths` from plugin coverage documentation

### ISSUE THREAD

**Issue by IGx89** [SonarSource/sonar-dotnet#2529]
https://docs.sonarqube.org/latest/analysis/coverage/ advertises a "sonar.cs.mstest.reportsPaths" property, but it doesn't appear to work and I didn't find any reference to that property in your source code either (see https://github.com/SonarSource/sonar-dotnet/blob/master/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/UnitTestResultsProvider.java#L42).

If I rename mstest to vstest (sonar.cs.vstest.reportsPaths) it works great however. The latter causes "Sensor C# Unit Test Results Import" to appear in the logs but the former does not.

**Comment by andrei-epure-sonarsource** [comment]
Hi @IGx89 . Both `sonar.cs.vstest.reportsPaths` and `sonar.cs.mstest.reportsPaths` are mentioned on the docs page you gave. If `sonar.cs.vstest.reportsPaths` works for you, it means you are using VSTest to run the unit tests.

Could you please tell me in more details what the problem is and how we could improve the documentation?

**Comment by IGx89** [comment]
Hi! In a nutshell, I'm saying that I don't believe the sonar.cs.mstest.reportsPaths option would work for anyone, based on both my personal testing and analysis of your source code (see link above). If you set that parameter, even if the file isn't a valid MSTest report, it should still have a log entry saying it was looking for it: it doesn't.

**Comment by IGx89** [comment]
Steps to reproduce:

1. Run a SonarScanner-MSBuild scan, setting sonar.cs.mstest.reportsPaths to an XML file (shouldn't matter if it's valid MSTest or not)

Expected Behavior:
- An entry in the console output saying "Sensor C# Unit Test Results Import", along with details on the import

Actual Behavior:
- No "Sensor C# Unit Test Results Import" entry in the console output -- exact same behavior as if the parameter wasn't specified.

**Comment by andrei-epure-sonarsource** [comment]
Thanks a lot, @IGx89 - I confirm we don't support that and we have to update the documentation. I appreciate your answers.

**Comment by andrei-epure-sonarsource** [comment]
I opened a PR in SonarSource/sonar-enterprise#2126

**Comment by andrei-epure-sonarsource** [comment]
fixed
