### ISSUE TITLE
Rule S4433 LDAP: connections should be authenticated (false positive)

### ISSUE THREAD

**Issue by gfox1984** [SonarSource/sonar-dotnet#2537]
### Description

When the authentication type is set to a secure values using the ternary operator, Sonar triggers a false positive.

### Repro steps

```
AuthenticationTypes authTypes = condition ? AuthenticationTypes.SecureSocketsLayer : AuthenticationTypes.Secure;
DirectoryEntry entry = new DirectoryEntry(connectionString, null, null, authTypes); 
```

### Expected behavior

> This rule raises an issue when an LDAP connection is created with AuthenticationTypes.Anonymous or AuthenticationTypes.None.

### Actual behavior

An issue is raised despite not using AuthenticationTypes.Anonymous or AuthenticationTypes.None.

### Related information

* SonarC# 7.15.0.8572

**Comment by andrei-epure-sonarsource** [comment]
I was wrong when labeling `taint-analysis`, this is actually a vulnerability rule from sonar-dotnet, see [LdapConnectionShouldBeSecure ](https://github.com/SonarSource/sonar-dotnet/blob/3d6d2303b7afbd40bcac8aff1a48b4f8bc8a8d48/sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/LdapConnectionShouldBeSecure.cs)
