### ISSUE TITLE
We should allow CFG build exceptions to find out what syntax we do not support

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#2541]
Currently in [CSharpControlFlowGraph.cs ](https://github.com/SonarSource/sonar-dotnet/blob/7.15.0.8572/sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/ControlFlowGraph/CSharpControlFlowGraph.cs#L53) we are eating the exceptions we throw during the Control Flow Graph build process.

This means we have hidden errors or syntax we don't support that we may not be aware of.

We should log the stacktrace (on a single line) and enable these failures to catch them during our QA steps.

SonarCsharp version 7.15

**Comment by alban-auzeill** [comment]
The progress on this issue is paused, see #2676 comment.

**Comment by pavel-mikula-sonarsource** [comment]
Note while cleaning old branches: This can be restarted since CFG is extracted already. In case it's still valid.

**Comment by pavel-mikula-sonarsource** [comment]
Old CFG is deprecated. We won't need to know what we don't support anymore, as new syntax will be (eventually) handled exclusively by the new CFG.
