### ISSUE TITLE
Coverage: non-touched code is treated as new code on sonarcloud

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#2579]
### Description

When making changes to a file with low code coverage, SonarCloud will treat the code of the whole file as being new. I.e. even if I have 100% coverage on the newly added code, SonarCloud will still raise lack of coverage warnings.

### Repro steps

Modify a class outside of the leak period which has low coverage. Add coverage for the added code.

### Expected behavior

No warning is given.

### Actual behavior

Warning for the non-touched code is given.

### Related information

* SonarC# Version 7.15

**Comment by costin-zaharia-sonarsource** [comment]
@andrei-epure-sonarsource, do you know if this is valid anymore?

**Comment by andrei-epure-sonarsource** [comment]
I'll close it and ask the team if they encountered it to be on the safe side.
