### ISSUE TITLE
Fix S3216 FP: the rule is not relevant for .NET Core

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#2588]
### Description

See [this community thread](https://community.sonarsource.com/t/exclude-s3216-from-net-core/13001)

If the app is a .NET Core app, this rule should not run.

### Related information

* SonarC# Version 7.16

**Comment by AlbertoMonteiro** [comment]
According with own microsoft content this is not true

https://devblogs.microsoft.com/dotnet/configureawait-faq/#ive-heard-configureawaitfalse-is-no-longer-necessary-in-net-core-true

## I’ve heard ConfigureAwait(false) is no longer necessary in .NET Core. True?
**False**. It’s needed when running on .NET Core for exactly the same reasons it’s needed when running on .NET Framework. Nothing’s changed in that regard.

What has changed, however, is whether certain environments publish their own SynchronizationContext. In particular, whereas the classic ASP.NET on .NET Framework has its own SynchronizationContext, in contrast ASP.NET Core does not. That means that code running in an ASP.NET Core app by default won’t see a custom SynchronizationContext, which lessens the need for ConfigureAwait(false) running in such an environment.

It doesn’t mean, however, that there will never be a custom SynchronizationContext or TaskScheduler present. If some user code (or other library code your app is using) sets a custom context and calls your code, or invokes your code in a Task scheduled to a custom TaskScheduler, then even in ASP.NET Core your awaits may see a non-default context or scheduler that would lead you to want to use ConfigureAwait(false). Of course, in such situations, if you avoid synchronously blocking (which you should avoid doing in web apps regardless) and if you don’t mind the small performance overheads in such limited occurrences, you can probably get away without using ConfigureAwait(false).

**Comment by pavel-mikula-sonarsource** [comment]
Hi @AlbertoMonteiro,

The article says that `ConfigureAwait(false)` is needed in some special cases when you introduce your own `SynchronizationContext`. The rule doesn't forbid using `ConfigureAwait(false)` so it's aligned with that.

We will have a False Negative in that special case. But it will still make sense not to raise an issue under .NET Core to reduce number of False Positives there.
