### ISSUE TITLE
S3900 FP: Re-assignment of parameters is ignored 

### ISSUE THREAD

**Issue by saciervo** [SonarSource/sonar-dotnet#2591]
### Description

Code in question:

    public string Foo(string name)
    {
        if (name == null)
        {
            name = Guid.NewGuid().ToString("N");
        }

        return string.Join("_", name.Split(Path.GetInvalidFileNameChars()));
    }

Sonar C# falsely complains about the parameter `name` not getting validated. 

### Repro steps

You can clone [this repo](https://github.com/saciervo/sonar-S3900) to reproduce the error. The project won't compile.

### Expected behavior

No complaints, because there is a null-check in place.

### Actual behavior

Code is marked as non-compliant

### Known workarounds

None, besides suppression

### Related information

* SonarC# Version: 7.16.0.8981
* Visual Studio Version: 2019 (16.2.0)

**Comment by andrei-epure-sonarsource** [comment]
thanks @saciervo I confirm the FP

**Comment by Bosch-Eli-Black** [comment]
We're seeing this as well.
