### ISSUE TITLE
Investigate why S1854 does not trigger with new C# 8 syntax

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#2607]
### Description

C#8 introduces the concept of Index. See details in [docs](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#indices-and-ranges). 

I analyzed andrei-epure-sonarsource/CSharp8Demo [on SonarCloud](https://sonarcloud.io/dashboard?id=Cs8Demo). Note [that the csproj](https://github.com/andrei-epure-sonarsource/CSharp8Demo/blob/master/CSharp8Demo/CSharp8Demo.csproj) has the `NullableContextOptions` enabled.

Rule [S1854](https://rules.sonarsource.com/csharp/RSPEC-1854) doesn't behave normally with easy-to-find cases.

### Repro steps

Look at [this line on sonarcloud](https://sonarcloud.io/code?id=Cs8Demo&line=14&selected=Cs8Demo%3ACSharp8Demo%2F01_IndicesAndRanges.cs). It is clearly a deadstore

### Expected behavior

The analyzer should raise S1854 at the lines marked as Noncompliant

### Actual behavior

No S1854 issues are raised

### Known workarounds

None.

### Related information

* SonarC# Version 7.16

**Comment by andrei-epure-sonarsource** [comment]
The `CSharpControlFlowGraphBuilder` is not constructing the CFG  because of unknown `PrefixUnaryExpressionSyntax` of kind `IndexExpression` . So it throws a `NotSupportedException` in the `BuildExpression` switch default case.

The `CSharpControlFlowGraph` has a catch in `TryGet` which handles silently these expressions.

**Comment by pavel-mikula-sonarsource** [comment]
This seems to be fixed by #2871 and C# 8 support.
