### ISSUE TITLE
`FxCop` and `sonar-dotnet` rules mapping

### ISSUE THREAD

**Issue by SK1469** [SonarSource/sonar-dotnet#2608]
Hi ,

In reference to the issue
https://github.com/SonarSource/sonarqube-roslyn-sdk/issues/72

We are also interested in the mapping between the fxcop rules and sonarqube rules , but the link
http://dist.sonarsource.com/reports/coverage/fxcop_c%23.html
seems to be not active. Will it be possible to share the mapping ?

Thanks

**Comment by andrei-epure-sonarsource** [comment]
@SK1469 @BrightLight thanks for raising the point - we need to do another analysis based on the new Roslyn FxCop implementation. We'll share the results once we do that.

**Comment by andrei-epure-sonarsource** [comment]
hi @SK1469 @BrightLight , I am coming back on this one :)

What exactly are you interested in:
- By FxCop, do you mean the legacy FxCop or the new FxCopAnalyzers?
- what do you understand by rule mapping - each rule of FxCopAnalyzers and its equivalent in SonarCSharp? 
- what is the use-case of your ask? are you interested in using both analyzers together? 

Thanks!

**Comment by andrei-epure-sonarsource** [comment]
I am closing this one due to lack of activity.
