### ISSUE TITLE
CFG branch blocks may have several times the same node as successor

### ISSUE THREAD

**Issue by christophe-zurn-sonarsource** [SonarSource/sonar-dotnet#2621]
### Description

When creating the control flow graph (CFG), the graph is cleaned up by removing the empty blocks found (See [RemoveEmptyBlocks method](https://github.com/SonarSource/sonar-dotnet/blob/ff7413922f6565eccccda028d0d89f22d2a11c68/sonaranalyzer-dotnet/src/SonarAnalyzer.Common/ControlFlowGraph/AbstractControlFlowGraphBuilder.cs#L60)). When doing this, it will replace empty blocks in the graph by their next non-empty successor, which is done by calling [`ReplaceSuccessors`](https://github.com/SonarSource/sonar-dotnet/blob/ff7413922f6565eccccda028d0d89f22d2a11c68/sonaranalyzer-dotnet/src/SonarAnalyzer.Common/ControlFlowGraph/AbstractControlFlowGraphBuilder.cs#L82) on blocks. However, the [`ReplaceSuccessors` method of BranchBlock](https://github.com/SonarSource/sonar-dotnet/blob/ff7413922f6565eccccda028d0d89f22d2a11c68/sonaranalyzer-dotnet/src/SonarAnalyzer.Common/ControlFlowGraph/Blocks/BranchBlock.cs#L42) directly replaces the empty block by its replacement, without checking whether the list already contains the suggested replacement block. This can lead to duplicate blocks in the CFG successor list.

### Repro steps

The following code
```
before();
try
{
    inside();
}
finally
{
    fin();
}
```
will result in a CFG with a finally block having twice the exit block in its list of successors.

### Expected behavior

CFG branching blocks should not have a node more than once as a successor. Moreover, if a binary branch node has the same true and false successor, it should not be a branch block but a simple block instead.

### Actual behavior

Same blocks can appear more than once in the successor list of a branch block.

### Known workarounds

None

### Related information

* SonarC# Version 7.16

**Comment by gregory-paidis-sonarsource** [comment]
Closed as we do not improve the old SE engine.
