### ISSUE TITLE
vstest coverage does not distinguish between getters and setters in SQ/SC

### ISSUE THREAD

**Issue by HofmeisterAn** [SonarSource/sonar-dotnet#2622]
### Description

SonarQube does not distinguish between getters and setters in abbreviated form for code coverage.

### Repro steps

1. Create a class with a simple property like `public int Timeout { get; set; }`.

2. Create a test and access the getter **or** setter.

3. Run the test and create a coverage file.

4. Upload the result to SonarQube.

### Expected behavior

SonarQube shows whether getter or setter has been tested.

### Actual behavior

SonarQube displays the property as **fully tested**, the code coverage file instead distinguish between getter and setter. Here is the example from the code coverage file (VS Test with Microsoft.CodeCoverage).

```xml
<function id="8449" token="0x6000007" name="get_Timeout()" namespace="Blank" type_name="SimpleModel" block_coverage="0.00" line_coverage="0.00" blocks_covered="0" blocks_not_covered="1" lines_covered="0" lines_partially_covered="0" lines_not_covered="1">
  <ranges>
    <range source_id="0" covered="no" start_line="63" start_column="26" end_line="63" end_column="30" />
  </ranges>
</function>
<function id="8457" token="0x6000008" name="set_Timeout(int)" namespace="Blank" type_name="SimpleModel" block_coverage="100.00" line_coverage="100.00" blocks_covered="1" blocks_not_covered="0" lines_covered="1" lines_partially_covered="0" lines_not_covered="0">
  <ranges>
    <range source_id="0" covered="yes" start_line="63" start_column="31" end_line="63" end_column="35" />
  </ranges>
</function>
```
Here is an example how SonarQube displays the coverage compared to Visual Studio:

![SonarQube-vs-Visual-Studio](https://user-images.githubusercontent.com/9199345/64332373-bf3d6900-cfd4-11e9-917d-5d2dd34cda8c.png)

### Known workarounds

Not known.

### Related information

* Sonar Version: 7.7.0.23042
* SonarC# Version: 7.11.0.8083
* Visual Studio Version: 16.2.3
* If running through the Scanner for MSBuild, its version: 4.6.0.1930

**Comment by andrei-epure-sonarsource** [comment]
thanks. might be related to [this community thread](https://community.sonarsource.com/t/code-coverage-discrepancy/7738) as well. We need to in investigate

**Comment by andrei-epure-sonarsource** [comment]
repo with repro https://github.com/andrei-epure-sonarsource/GetSetCoverage 

commands steps to get coverage in SQ (note that `vstest.console.exe` and `CodeCoverage.exe` folders must be in the PATH) - details on https://community.sonarsource.com/t/coverage-test-data-generate-reports-for-c-vb-net/9871

```
> SonarScanner.MSBuild.exe begin /k:"GetSetCoverage" /d:sonar.cs.vscoveragexml.reportsPaths="VisualStudio.coveragexml"

> msbuild .\GetSetCoverage.sln /t:Rebuild

> vstest.console.exe /EnableCodeCoverage .\GetSetTests\bin\Debug\GetSetTests.dll

> CodeCoverage.exe analyze /output:"VisualStudio.coveragexml" "TestResults\7ebbf36f-73c2-45e4-b8c1-5c7547d54183\Andrei_ANDREI-WINDOWS 2020-03-17 18_51_46.coverage"

> SonarScanner.MSBuild.exe end
```

Indeed Visual Studio shows

![image](https://user-images.githubusercontent.com/38876598/76886347-f5f81400-6880-11ea-81c4-46ed52d2c0d0.png)

while sonarqube shows 

![image](https://user-images.githubusercontent.com/38876598/76886373-014b3f80-6881-11ea-8423-82f8952ad306.png)

**Comment by andrei-epure-sonarsource** [comment]
the full VSTest coverage XML is at https://gist.github.com/andrei-epure-sonarsource/a182380252e537f2c4469dbeb016f829

**Comment by andrei-epure-sonarsource** [comment]
An update on this: the problem resides in the fact that in the coverage XML there are 2 distinct entries for the same line.

In SQ/SC we don't support highlighting the syntax elements that are (not) covered, we only provide information per line. For branch coverage, we show some additional information: "2 out of 4 conditions are covered".

We've discussed and, in order to provide more information, we're going to use the "branch coverage" when having multiple pieces of coverage information for the same line - for the getter/setter example, we will tell "1 out of 2 conditions are covered" when only the getter has coverage. It's not ideal and it's a workaround, but it will highlight in SQ / SC the properties (and lines, in general) which aren't properly covered.
