### ISSUE TITLE
S3927 should not treat public methods as bug

### ISSUE THREAD

**Issue by Daniel-Svensson** [SonarSource/sonar-dotnet#2689]
### Description

I have a few false positive bugs with sonaranalyzer S3927.
See https://sonarcloud.io/project/issues?id=OpenRIAServices_OpenRiaServices&resolutions=FALSE-POSITIVE

The rule requires methods to be private, but that is not a requirement from the framework.
See source at https://referencesource.microsoft.com/#mscorlib/system/runtime/serialization/serializationeventscache.cs,41

On the contrary in medium trust scenarios (not that common anymore) and some older implementations the methods cannot be private but must be public (or internal with internal access granted to different framework assemblies). However in that scenario it is recommended to hide it using editorbrowsable attribute just as in the code refered to below.

If you really want to warn against public methods you should change it to a code smell.

Another side issue (not important to me personally) is that **virtual is not allowed for the methods**, which would probably be better to raise bugs for.

I understand if this is not a top priority for you, but I want to record the issue so that you are aware of it. Also adding a check for virtual might be nice to have and be very easy for your developers to do.

### Repro steps

Please provide the steps required to reproduce the problem

See code at 
https://sonarcloud.io/project/issues?id=OpenRIAServices_OpenRiaServices&open=AWf-_5guXONnvcWDclJp&resolutions=FALSE-POSITIVE

repository is availible at github OpenRiaServices/OpenRiaServices

### Expected behavior

Please provide a description of the behavior you expect.

Having public serialization methods with `[EditorBrowsable(EditorBrowsableState.Never)]` should not be a bug. It is a with acceptable with a code smell however.

Or at least update documentation to say that it is bad practice but not a bug to have it public.

### Actual behavior

Please provide a description of the actual behavior you observe.

The usage is reported as a bug.

### Known workarounds

Please provide a description of any known workarounds.

*

### Related information

Last sonarcloud and azure devops sonarcloud plugin as per 2019-09-28

**Comment by christophe-zurn-sonarsource** [comment]
@Daniel-Svensson Thanks for reporting this!
Indeed, it is not a bug to have a non-private access modifier on such a method.
Note however that it is not possible with our analyzer to raise an issue as `code smell` in certain cases and as a `bug` in other cases.
What we could do is: not raise an issue when such method has a `EditorBrowsable(EditorBrowsableState.Never)]` attribute, or we could update the message.

**Comment by Daniel-Svensson** [comment]
> What we could do is: not raise an issue when such method has a `[EditorBrowsable(EditorBrowsableState.Never)]` attribute, or we could update the message.

I think the easiest way is to not check accessibility at all but allowing public when EditorBrowsable is specified would also be acceptable. In any case you should update the rules documentation with the valid/invalid code samples to ensure they are in sync with the rule
