### ISSUE TITLE
Unnecessary usings (S1128) analyzer should have a way of whitelisting namespaces

### ISSUE THREAD

**Issue by rickardp** [SonarSource/sonar-dotnet#2701]
### Description

The S1128 analyzer is useful to detect leftover usings, but our code standard allows for some default namespaces to always be there (to make intellisense more useful for developers). These include System, System.Linq, System.Collection.Generic etc.

### Known workarounds

Resharper has support for this, but we want to run the same analyzer on the dev machines as on the build server, and now we have to disable rule S1128 since generate tons of useless warnings.

### Related information

* SonarC# Version 7.17.0.9346
* Visual Studio Version VS2019 16.2.2
* If running through the Scanner for MSBuild, its version

**Comment by Corniel** [comment]
I hope this will be opt-in, because I don't like the feature.

**Comment by nicolas-harraudeau-sonarsource** [comment]
Hi @rickardp,

I am a little confused by your use-case. There are solutions to complete types and add the right `using` automatically (ex: [Auto-Using for C#](https://marketplace.visualstudio.com/items?itemName=Fudge.auto-using)). What are the reasons for not using them and instead add unused `using` statements?

I ask this because this looks more like a tooling issue. It is usually not recommended to make the code more complex because of the tools you use.

**Comment by andrei-epure-sonarsource** [comment]
Closing this issue as 'won't fix' as there was no answer from the user

**Comment by rickardp** [comment]
@andrei-epure-sonarsource  Sorry, I missed the notification on your previous response.

I agree this is more of a tooling issue, but the tool at hand (Visual Studio 2019) does not support this in its current version. In its default configuration, Visual Studio will not complete on Linq extension methods if the System.Linq using has been cleaned up, which is a pain since then you would have to type the full name of the method, then Ctrl+.

There is a workaround, which is to install Resharper that has cross-namespace completions. I personally prefer a "clean" visual studio, but many devs prefer to use Resharper, so I suppose this is a matter of taste. Anyway I realize this improvement suggestion is not for everyone, but it would have been great to have the choice.

**Comment by andrei-epure-sonarsource** [comment]
In addition, there's the [Auto-Using for C#](https://marketplace.visualstudio.com/items?itemName=Fudge.auto-using) @nicolas-harraudeau-sonarsource  mentioned. ReSharper is quite heavy-weight if used just for this purpose.

**Comment by rickardp** [comment]
@andrei-epure-sonarsource Yes, there are plenty of solutions. I asked around in the dev teams here and most devs here either use vanilla VS or use a more customized environment (and those tend to prefer Resharper).

But since VS 2019 will get this functionality I think the usefulness of this feature request diminishes quite a lot.
