### ISSUE TITLE
Improve S2699: add custom assertion support

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#2713]
### Description

Currently the assertion matching is done by searching in a list with hard-coded keywords  (e.g.  **Assert**, **Check**, **Expect**, **Must**, **Should**, **Verify**, **Validate**) but this is not flexible enough to support all the possible test frameworks.

Similar with what was done on the java side, make the rule parameterized to define specific methods that will also be considered as assertions. No issue will be raised when such methods are found in test cases. The parameter value should have the following format `<FullyQualifiedClassName>#<MethodName>`, where MethodName can end with the wildcard character. For constructors, the pattern should be `<FullyQualifiedClassName>#<ctor>`.

E.g. `NUnit.Framework.Assert#IsNull`, `NUnit.Framework.Assert#Is*`, `TestFrameworkNamespace.Class#<ctor>`

**Comment by ohadschn** [comment]
Another option would be to take a page out of Resharper's book - detect decoration of custom test methods with some attribute. They actually have an attribute exactly for such methods (though for control flow purposes): `AssertionMethodAttribute`.

**Comment by costin-zaharia-sonarsource** [comment]
Fixed by #3634
