### ISSUE TITLE
Make sonar dotnet run on MsBuild 16

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#2732]
### Description

Currently the integration checks are failing if running with MsBuild 16 and this is not happening with MsBuild 15. 

### Reproduction steps:

Set/update **MSBUILD_PATH** environment variable to **MsBuild 16 path**  and run `.\regression-test.ps1` as described here https://github.com/SonarSource/sonar-dotnet/blob/master/docs/contributing-analyzer.md

The regression tests with fail due to differences between the actual and the expected values but this is not happening with MsBuild 15.

`ERROR: There are differences between the actual and the expected issues.`

* SonarC# Version 7.17.0.9346

**Comment by andrei-epure-sonarsource** [comment]
related to #2489

**Comment by costin-zaharia-sonarsource** [comment]
Ah, I've missed the one you mentioned, then this one is a duplicate. I will close it.
