### ISSUE TITLE
Fix NRE in VisualBasicCognitiveComplexityMetric due to null ParameterList

### ISSUE THREAD

**Issue by W3bCorp** [SonarSource/sonar-dotnet#2738]
### Description

With a DevOps Server build, i got a NullReferenceException in SonarAnalyzer.VisualBasic/Metrics/VisualBasicCognitiveComplexityMetric.cs

With Verbose on sonar, msbuild or vbc, we have no additionals informations.

I have debug the process vbc.exe and i have identified the problem (i think).

On the method VisitInvocationExpression(InvocationExpressionSyntax node) the first test generate the null reference exception because "State.CurrentMethod.ParameterList" is null : 

![image](https://user-images.githubusercontent.com/4007634/67108045-edb28480-f1cd-11e9-9d00-5954a3b0789d.png)

Callstack : 

SonarAnalyzer.VisualBasic.dll!SonarAnalyzer.Metrics.VisualBasic.VisualBasicCognitiveComplexityMetric.CognitiveWalker.VisitInvocationExpression(Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax node)
Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxWalker.Visit(Microsoft.CodeAnalysis.SyntaxNode node)
Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxWalker.DefaultVisit(Microsoft.CodeAnalysis.SyntaxNode node)
Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxWalker.Visit(Microsoft.CodeAnalysis.SyntaxNode node)
Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxWalker.DefaultVisit(Microsoft.CodeAnalysis.SyntaxNode node)
SonarAnalyzer.VisualBasic.dll!SonarAnalyzer.Metrics.VisualBasic.VisualBasicCognitiveComplexityMetric.CognitiveWalker.VisitMethodBlock(Microsoft.CodeAnalysis.VisualBasic.Syntax.MethodBlockSyntax node)
Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxWalker.Visit(Microsoft.CodeAnalysis.SyntaxNode node)
Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxWalker.DefaultVisit(Microsoft.CodeAnalysis.SyntaxNode node)
Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxWalker.Visit(Microsoft.CodeAnalysis.SyntaxNode node)
Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxWalker.DefaultVisit(Microsoft.CodeAnalysis.SyntaxNode node)
Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxWalker.Visit(Microsoft.CodeAnalysis.SyntaxNode node)
SonarAnalyzer.VisualBasic.dll!SonarAnalyzer.Helpers.VisualBasicSyntaxWalkerHelper.SafeVisit(Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxWalker syntaxWalker, Microsoft.CodeAnalysis.SyntaxNode syntaxNode)
SonarAnalyzer.VisualBasic.dll!SonarAnalyzer.Metrics.VisualBasic.VisualBasicCognitiveComplexityMetric.GetComplexity(Microsoft.CodeAnalysis.SyntaxNode node)
SonarAnalyzer.VisualBasic.dll!SonarAnalyzer.Metrics.VisualBasic.VisualBasicMetrics.GetCognitiveComplexity(Microsoft.CodeAnalysis.SyntaxNode node)
SonarAnalyzer.dll!SonarAnalyzer.Common.MetricsBase.CognitiveComplexity.get()
SonarAnalyzer.dll!SonarAnalyzer.Rules.MetricsAnalyzerBase.CalculateMetrics(SonarAnalyzer.Common.MetricsBase metrics, string filePath, bool ignoreHeaderComments)
SonarAnalyzer.dll!SonarAnalyzer.Rules.MetricsAnalyzerBase.GetMessage(Microsoft.CodeAnalysis.SyntaxTree syntaxTree, Microsoft.CodeAnalysis.SemanticModel semanticModel)
SonarAnalyzer.dll!SonarAnalyzer.Rules.UtilityAnalyzerBase<SonarAnalyzer.Protobuf.MetricsInfo>.Initialize.AnonymousMethod__1_0(Microsoft.CodeAnalysis.Diagnostics.CompilationAnalysisContext c)
SonarAnalyzer.dll!SonarAnalyzer.Helpers.SonarAnalysisContext.RegisterContextAction.AnonymousMethod__0(Microsoft.CodeAnalysis.Diagnostics.CompilationAnalysisContext c)
Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteCompilationActionsCore.AnonymousMethod__37_1((System.Action<Microsoft.CodeAnalysis.Diagnostics.CompilationAnalysisContext> action, Microsoft.CodeAnalysis.Diagnostics.CompilationAnalysisContext context) data)
Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock<System.ValueTuple<System.Action<Microsoft.CodeAnalysis.Diagnostics.CompilationAnalysisContext>, Microsoft.CodeAnalysis.Diagnostics.CompilationAnalysisContext>>(Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer, System.Action<(System.Action<Microsoft.CodeAnalysis.Diagnostics.CompilationAnalysisContext>, Microsoft.CodeAnalysis.Diagnostics.CompilationAnalysisContext)> analyze, (System.Action<Microsoft.CodeAnalysis.Diagnostics.CompilationAnalysisContext>, Microsoft.CodeAnalysis.Diagnostics.CompilationAnalysisContext) argument, Microsoft.CodeAnalysis.Diagnostics.AnalysisContextInfo? info)
Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows<System.ValueTuple<System.Action<Microsoft.CodeAnalysis.Diagnostics.CompilationAnalysisContext>, Microsoft.CodeAnalysis.Diagnostics.CompilationAnalysisContext>>(Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer, System.Action<(System.Action<Microsoft.CodeAnalysis.Diagnostics.CompilationAnalysisContext>, Microsoft.CodeAnalysis.Diagnostics.CompilationAnalysisContext)> analyze, (System.Action<Microsoft.CodeAnalysis.Diagnostics.CompilationAnalysisContext>, Microsoft.CodeAnalysis.Diagnostics.CompilationAnalysisContext) argument, Microsoft.CodeAnalysis.Diagnostics.AnalysisContextInfo? info)
Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteCompilationActionsCore(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.CompilationAnalyzerAction> compilationActions, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer, Microsoft.CodeAnalysis.Diagnostics.AnalysisState.AnalyzerStateData analyzerStateOpt)
Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.TryExecuteCompilationActions(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.CompilationAnalyzerAction> compilationActions, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer, Microsoft.CodeAnalysis.Diagnostics.CompilationEvent compilationEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt)
Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.TryExecuteCompilationActions(System.Collections.Immutable.ImmutableDictionary<Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.CompilationAnalyzerAction>> compilationActionsMap, Microsoft.CodeAnalysis.Diagnostics.CompilationEvent compilationEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, System.Threading.CancellationToken cancellationToken)
Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.TryProcessEventCore(Microsoft.CodeAnalysis.Diagnostics.CompilationEvent e, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, System.Threading.CancellationToken cancellationToken)
Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsCoreAsync(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool prePopulatedEventQueue, System.Threading.CancellationToken cancellationToken)
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<ProcessCompilationEventsCoreAsync>d__70>(ref Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<ProcessCompilationEventsCoreAsync>d__70 stateMachine) Line 471
	at f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\AsyncMethodBuilder.cs(471)
Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsCoreAsync(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool prePopulatedEventQueue, System.Threading.CancellationToken cancellationToken)
Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsAsync.AnonymousMethod__1()
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.(ref Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<>c__DisplayClass69_0.<<ProcessCompilationEventsAsync>b__1>d stateMachine) Line 471
	at f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\AsyncMethodBuilder.cs(471)
Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsAsync.AnonymousMethod__1()
mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.Task<Microsoft.CodeAnalysis.Diagnostics.CompilationCompletedEvent>>.InnerInvoke() Line 680
	at f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Future.cs(680)
mscorlib.dll!System.Threading.Tasks.Task.Execute() Line 2498
	at f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Task.cs(2498)
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954
	at f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs(954)
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902
	at f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs(902)
mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Line 2827
	at f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Task.cs(2827)
mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Line 2767
	at f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Task.cs(2767)
mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 820
	at f:\dd\ndp\clr\src\BCL\system\threading\threadpool.cs(820)

Sonar version : 7.9.1
SonarVB : 7.17 (build 9346)

**Comment by W3bCorp** [comment]
I have found why the Parameter List is null. The source code was old and the function does not have () in her signature :

Public function AsCollection As IIsiCollection(Of String, String)
        ...
End function

If I add parentheses, it works: 
Public function AsCollection**()** As IIsiCollection(Of String, String)
        ...
End function

**Comment by andrei-epure-sonarsource** [comment]
thanks @W3bCorp . related to #2594 as well
