### ISSUE TITLE
Fix S1128 FP: when using GetAwaiter() extension method

### ISSUE THREAD

**Issue by altso** [SonarSource/sonar-dotnet#2747]
### Description

`await` support can be added to any type by providing `GetAwaiter()` extension method. For example, `TaskTupleAwaiter` adds support for awaits on `ValueTuple`s (see https://github.com/buvinghausen/TaskTupleAwaiter/blob/a568b46692c317b851e3df2ccb517ae2160b7a15/src/TaskTupleAwaiter/TaskTupleExtensions.cs#L11).

`SonarAnalyzer.CSharp` gives a S1128 warning when `GetAwaiter()` extension method is used implicitly by compiler.

### Repro steps

Use `await` on `ValueTuple` with the help of `TaskTupleAwaiter` nuget package.

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SonarAnalyzer.CSharp" Version="8.0.0.9566" />
    <PackageReference Include="TaskTupleAwaiter" Version="1.2.0" />
  </ItemGroup>

</Project>

```

```cs
using System;
using System.Threading.Tasks;
using TaskTupleAwaiter;

namespace Sample
{
    public class SampleClass
    {
        public async Task SampleMethod()
        {
            (string str, Guid guid) = await (GetStringAsync(), GetGuidAsync());
        }

        private static Task<string> GetStringAsync() => Task.FromResult("Sample");

        private static Task<Guid> GetGuidAsync() => Task.FromResult(Guid.NewGuid());
    }
}
```

Build with `dotnet build`

Sample git repo: https://github.com/altso/S1128

### Expected behavior

No warnings at build.

### Actual behavior

```
Sample.cs(1,1): warning S1128: Remove this unnecessary 'using'. [.\S1128\S1128.csproj]
```

### Known workarounds

Suppress warning
```cs
#pragma warning disable S1128
using TaskTupleAwaiter;
#pragma warning restore S1128
```

### Related information

* SonarC# Version: 8.0.0.9566
* Visual Studio Version: N/A
* If running through the Scanner for MSBuild, its version: N/A

**Comment by christophe-zurn-sonarsource** [comment]
@altso Thanks for reporting this issue!
For reference, here is a self-contained reproducer:
```
using System;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

namespace Test
{

    internal static class ExtensionHolder
    {
        public static TaskAwaiter<int> GetAwaiter(this Func<int> function)
        {
            Task<int> task = new Task<int>(function);
            task.Start();
            return task.GetAwaiter();
        }
    }
}

namespace Test2
{
    using Test;
    class Ns3_0 {
        async void m()
        {
            var result = await new Func<int>(() => 0);
        }
    }
}
```
