### ISSUE TITLE
sonar-project.properties files are not understood by the SonarScanner for MSBuild

### ISSUE THREAD

**Issue by bapuji** [SonarSource/sonar-dotnet#2748]
### Description

Please provide a succinct description of your issue.

### Repro steps

Please provide the steps required to reproduce the problem

1. Step A

2. Step B

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

Please provide a description of the behavior you expect.

### Actual behavior

Please provide a description of the actual behavior you observe.

### Known workarounds

Please provide a description of any known workarounds.

### Related information

* SonarC# Version
* Visual Studio Version
* If running through the Scanner for MSBuild, its version

**Comment by andrei-epure-sonarsource** [comment]
please open an issue (with a better description that this...) on https://github.com/SonarSource/sonar-scanner-msbuild or open an issue on our [community forum](https://community.sonarsource.com/)
