### ISSUE TITLE
S1854 False Positive useless assignment to local variable

### ISSUE THREAD

**Issue by jcurl** [SonarSource/sonar-dotnet#2760]
### Description

The warning S1854 should not be thrown in the case that a variable is set a value, and might be updated in a try/catch block.

### Repro steps

See the following code. The warning is raised about the variable `ports`.

```csharp
public static string[] GetSerialPorts()
{
    string[] ports = new string[0];

    try {
        ports = SerialPortStream.GetPortNames();
    } catch (DllNotFoundException) {
        /* Do nothing */
    } catch (PlatformNotSupportedException) {
        /* Do nothing */
    }

    if (ports.Length == 0) {
        Assert.Inconclusive("No serial ports found. Cannot proceed with unit test.");
    }

    return ports;
}
```

The variable is set a default value. A function is called, that if an exception occurs then it is ignored and the previous set value is still valid. But if no exception occurs, the variable is updated.

```csharp
[Test]
[Platform(Include = "Win32NT")]
public void MiniDumpException_Windows_DefaultDump()
{
    Deploy.CreateDirectory("Dumps");
    string dumpName = Path.Combine(Deploy.WorkDirectory, "Dumps", "defaultdumpexception.dmp");
    bool result;

    Exception exception;
    try {
        throw new InvalidOperationException("Test Throw");
    } catch (InvalidOperationException ex) {
        // Capture the exception, so we can analyse it in the minidump.
        exception = ex;
        result = Dump.MiniDump(dumpName);
    }
    Assert.That(result, Is.True);
    Assert.That(exception, Is.Not.Null);
    CheckFile(dumpName);
}
```

In this example, the error is raised about `dumpName`. Clearly it must be defined here, as it's used in the `catch` block, falls through outside of the try/catch. It should not warn here also.

```csharp
[Test]
public void FirstChanceException()
{
    int exceptions = 0;
    bool success = AppDomain.CurrentDomain.SetFirstChanceException((o, e) => {
        exceptions++;
    });

    try {
        throw new InvalidOperationException("This is a test");
    } catch (InvalidOperationException) {
        /* Do nothing, we check the exception counter later */
    }

    Console.WriteLine("Success = {0}", success);
    if (exceptions == 0)
        Console.WriteLine("No FirstChanceException executed");

    if (success) {
        if (Platform.IsMonoClr()) {
            Assert.That(exceptions, Is.EqualTo(0).Or.EqualTo(1), "Mono runtime, some unexpected number of exceptions");
        } else {
            Assert.That(exceptions, Is.EqualTo(1), "Successfully registered, but no exception");
        }
    } else {
        Assert.That(exceptions, Is.EqualTo(0), "Unsuccessfully registered, but there was an exception");
    }
}
```

and in the example above, it complains about `success`.
### Expected behavior

The catch paths are also analyzed to ensure that they fall through. If they fall through and the code afterwards uses the variable, the warning is a false positive.

### Actual behavior

A false positive is raised when it shouldn't be.

### Known workarounds

Code has to be unnecessarily refactored.

### Related information

* SonarC# Version 4.13.0.1687
* Visual Studio Version 2019 version 16.3.6
* If running through the Scanner for MSBuild, its version

**Comment by Thieum** [comment]
Same case with this snippet of code:

        void onCommunicationSupervisorElapsed(object sender, ElapsedEventArgs e)
        {
            DateTime currentTime = _lastSeen;  // <= S1854 False positive here
            try
            {
                currentTime = Controller.ControllerTime;
            }
            catch (SocketException ex)
            {
                Logger.Log(LogLevels.Error, ex);
                Logger.Log(LogLevels.Error,
                           $"Smart Controller {UniqueIdentifier} communication supervisor failed!");
                Disconnected?.Invoke(this, EventArgs.Empty);
            }

            if (_lastSeen.Equals(currentTime))
            {
                Disconnected?.Invoke(this, EventArgs.Empty);
                return;
            }
            RemoveErrors((int)Notifications.ControllerDisconnected);
            refreshState();
            _lastSeen = currentTime;
        }

**Comment by pavel-mikula-sonarsource** [comment]
This was fixed in https://github.com/SonarSource/sonar-dotnet/releases/tag/8.22.0.31243
