### ISSUE TITLE
S2583 FP in try/catch

### ISSUE THREAD

**Issue by jcurl** [SonarSource/sonar-dotnet#2761]
### Description

The S2583 warning sometimes occurs as a false positive (note, a lot of other fixes since 4.12 has made it in, thankyou! so this is new since 4.12).

### Repro steps

Consider the following code block:

```csharp
public static void CreateDirectory(string directory)
{
    string fullPath = GetFullPath(directory, WorkDirectory);

    if (Directory.Exists(fullPath)) return;

    bool created = false;
    int attempts = CopyWaitAttempts;

    DeleteFile(fullPath);
    do {
        try {
            Directory.CreateDirectory(fullPath);
            created = true;
        } catch (AccessViolationException) {
            if (attempts == 0) throw;
        } catch (UnauthorizedAccessException) {
            // On windows occurs if the file is already open.
            if (attempts == 0) throw;
        }

        if (!created) {
            // If the copy failed, it's because it's probably already open somewhere else. So we
            // wait 250ms and try again.
            --attempts;
            Thread.Sleep(CopyWaitInterval);
        }
    } while (!created);
}
```

It complains that the variable `created` always evaluates to `false`. This is not the case, as we see that in the try/catch block it is set to true if successful, and only on some specific exceptions with some specific conditions, the catch blocks fall through and the variable remains `false`. So come to the `if (!created)` line, the variable `created` is true if the directory was created, or false if there was an exception.

### Expected behavior

S2583 is able to analyze that an exception can occur anywhere within the try section, fall through a catch section, and so a variable may change, or it may not change.

### Actual behavior

See the description, false warning.

### Known workarounds

None.

### Related information

* SonarC# Version 4.13.0.1687
* Visual Studio Version 2019 16.3.6
* If running through the Scanner for MSBuild, its version

**Comment by antrv** [comment]
The same situation is about S2589 False Positive. The issue is in try/catch statement.

```csharp
object obj = null;
try
{
    obj = GetObject(); // the method that can throw
    DoSomething(obj.ToString()); // this is important line, obj is dereferenced
}
catch
{
}

if (obj != null) // false positive S2589 here
{
    // do something
}
```

**Comment by pavel-mikula-sonarsource** [comment]
Shorter version of original code for reproduciton:

```csharp
public static void CreateDirectory(string directory)
{
    const int CopyWaitInterval = 250;
    bool created = false;
    int attempts = 10;

    do
    {
        try
        {
            Directory.CreateDirectory(directory);
            created = true;
        }
        catch (UnauthorizedAccessException)
        {
            if (attempts == 0)
            {
                throw;
            }
        }

        if (!created)
        {
            // If the copy failed, it's because it's probably already open somewhere else. So we
            // wait 250ms and try again.
            --attempts;
            System.Threading.Thread.Sleep(CopyWaitInterval);
        }
    } while (!created);
}
```

**Comment by andrei-epure-sonarsource** [comment]
maybe related to #2590 or #2600 ...

**Comment by pavel-mikula-sonarsource** [comment]
This is caused by bad CFG shape for Try/Catch statements as described in #2600. Every statement should branch to catch block.
