### ISSUE TITLE
S1854 FP: Variable assignment in catch block is not recognized

### ISSUE THREAD

**Issue by sm-g** [SonarSource/sonar-dotnet#2766]
### Description

Variable assignment in `catch` should be allowed.

### Repro steps

https://github.com/sm-g/AnalyzerIssues/blob/master/AnalyzerIssues/S1854.cs

Notice, that there is no false positive when `try` without `return`.

### Related information

* SonarC# Version 8.0.0.9566
* Visual Studio Version 16.3.6

**Comment by s-kip** [comment]
I have an other simple example with try-catch-finally:

    public async Task SonarTest(int i)
    {
        var pause = 1000; // S1854 Remove this useless assignment to local variable 'pause'.
        try
        {
            // do something than can throw an exception
            DoSomething(i);
    
            pause = 50;
        }
        catch
        {
            // log exception
        }
        finally
        {
            await Task.Delay(pause); // if i = 0, pause is 50, else pause is 1000
        }
    }
    
    private void DoSomething(int i)
    {
        if (i > 0)
            throw new NotSupportedException();    
    }
