### ISSUE TITLE
Code Coverage for Xamarin Forms

### ISSUE THREAD

**Issue by NipunKalra** [SonarSource/sonar-dotnet#2767]
Does Sonar Cloud support Xamarin Form Platform Specific code coverage? I am getting an error for updating existing Web Renderer in iOS project.
Help needed.

Thanks

**Comment by andrei-epure-sonarsource** [comment]
hi @NipunKalra . We do not.
we support
- Visual Studio Code Coverage
- ncover3
- opencover
- dotcover

you can read the [[Coverage & Test Data] Generate Reports for C#, VB.net](https://community.sonarsource.com/t/coverage-test-data-generate-reports-for-c-vb-net/9871) guide
