### ISSUE TITLE
S1128 showing up when reference is inside exception summary

### ISSUE THREAD

**Issue by AlessandroDalMas** [SonarSource/sonar-dotnet#2780]
### Description

Hello,
in my project I reference ArgumentException and ArgumentNullException in comment section like this:
`
        /// <summary>
        ///     Converts a string
        /// </summary>
        /// <param name="stringToConvert">String to convert</param>
        /// <returns>Converted string</returns>
        /// <exception cref="ArgumentNullException">If string is null</exception>
        /// <exception cref="ArgumentException">if string is invalid</exception>
        string Converted(string stringToConvert);
`
 and in my warning list I have:

S1128 Remove this unnecessary 'using'

### Repro steps

```
namespace MyProject.Converters
{
    using System;

    /// <summary>
    ///     String converter
    /// </summary>
    public interface IStringConverter
    {
        /// <summary>
        ///     Converts a string
        /// </summary>
        /// <param name="stringToConvert">String to convert</param>
        /// <returns>Converted string</returns>
        /// <exception cref="ArgumentNullException">If string is null</exception>
        /// <exception cref="ArgumentException">if string is invalid</exception>
        string Converted(string stringToConvert);
    }
}

```

### Related information

* SonarLint for VS Version: 4.13.0.11687
* Visual Studio Version: Professional 15.9.17

**Comment by andrei-epure-sonarsource** [comment]
thanks @AlessandroDalMas , we track this on #2694

closing as duplicate
