### ISSUE TITLE
How to see SonarAnalyzer Securityhotspot rules in VS IDE? I have downloaded Sonardotet and SonarAnalyzer source and built SonarAnalyzer.vsix.  This has installed SOnarAnalyzer.CSHarp ruleset but do not see SonarAnalyzer.Common ruleset etc.. How to enable other packages?

### ISSUE THREAD

**Issue by sodeshpa** [SonarSource/sonar-dotnet#2792]
### Description

Please provide a succinct description of your issue.

### Repro steps

Please provide the steps required to reproduce the problem

1. Step A

2. Step B

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

Please provide a description of the behavior you expect.

### Actual behavior

Please provide a description of the actual behavior you observe.

### Known workarounds

Please provide a description of any known workarounds.

### Related information

* SonarC# Version
* Visual Studio Version
* If running through the Scanner for MSBuild, its version

**Comment by andrei-epure-sonarsource** [comment]
Security Hotspots are disabled in the IDE. They would be too noisy - read details here https://www.sonarqube.org/features/security/

**Comment by sodeshpa** [comment]
I do not see in Sonar either? how to enable there?

**Comment by andrei-epure-sonarsource** [comment]
what version of sonarqube are you using?

**Comment by sodeshpa** [comment]
7.4

**Comment by andrei-epure-sonarsource** [comment]
in that version, security hotspots appear in a separate section - Security Reports https://docs.sonarqube.org/7.4/user-guide/security-reports/

although I suggest you upgrade to SQ 7.9 LTS to get the security hotspots on the main project overview page

**Comment by sodeshpa** [comment]
No I have written custom analyzers compatible to sonar 7.4. The link which you have provided does not tell how to see on Sonar C# rulesets?

**Comment by andrei-epure-sonarsource** [comment]
> This has installed SOnarAnalyzer.CSHarp ruleset but do not see SonarAnalyzer.Common ruleset

`SonarAnalyzer.Common` is just a common set of classes which is shared between the CSharp and the VB .NET analyzers. There are no rules in the Common package.
