### ISSUE TITLE
Get-MsBuildPath powershell function should not always return the latest MSBuild path

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#2793]
### Description

The `Get-MsBuildPath` function in [build-utils.ps1](https://github.com/SonarSource/sonar-dotnet/blob/master/scripts/build/build-utils.ps1#L11) receives `$msbuildVersion` as parameter but only uses it to get the path for MSB `14.0` (which is not supported by `vswhere`). Otherwise, it will return the latest MSB version which is installed.

The problem is that when called in [`Invoke-MSBuild`](https://github.com/SonarSource/sonar-dotnet/blob/3ba0e19896fdd3e46c555daef809041cb564240a/scripts/build/build-utils.ps1#L101) , it will ignore the argument and use the latest MSB.

And `Invoke-MSBuild` is used in
- sonaranalyzer-dotnet/its/regression-test.ps1
- scripts/build/ci-build.ps1
- scripts/build/dev-build.ps1

So we cannot control the used version of MSBuild when doing the dev & CI build or when running the regression tests.

### Expected behavior

We should be able to control the version of MSB when doing builds, in order to reproduce issues which happen with older MSB versions.

### Actual behavior

The latest MSB is used.

### Related PR
See comments on  #2789

**Comment by cristian-ambrosini-sonarsource** [comment]
`msbuildVersion` parameter was removed with #8595, we'll close this issue for now. 
This issue has been open for 4 years and it seems there hasn't been a significant demand for reproducing issues with older MSBuild versions. If there's a need for this feature in the future, we'll revisit this and potentially implement it in a different manner, given that the parameter and `scripts/build/ci-build.ps1` no longer exist.
