### ISSUE TITLE
RSPEC-2077 not triggered

### ISSUE THREAD

**Issue by mickael-caro-sonarsource** [SonarSource/sonar-dotnet#2800]
Following this community forum post : https://community.sonarsource.com/t/sql-injection-not-caught-by-sonarqube/16755/9

I tested on my side, and the rule is not triggered (See my sample SonarCloud project/test https://sonarcloud.io/project/issues?id=sql-hotspot&open=AW6HlyAraLOi3N3W4fft&resolved=false&types=SECURITY_HOTSPOT) whereas it should have been. 

Thanks !

**Comment by pavel-mikula-sonarsource** [comment]
I've copy/pasted the RSPEC example and the rule did not fire in my local SQ as well.

**Comment by andrei-epure-sonarsource** [comment]
in addition, on the following SQL string manipulation , the issues are not triggered (akka.net project)

- akka.netcontrib/.../Akka.Persistence.Sqlite/DbHelper.cs
- contrib/.../Journal/SqliteQueryBuilder.cs
- contrib/.../Snapshot/QueryBuilder.cs

**Comment by costin-zaharia-sonarsource** [comment]
> in addition, on the following SQL string manipulation , the issues are not triggered (akka.net project)
> 
> * akka.netcontrib/.../Akka.Persistence.Sqlite/DbHelper.cs
> * contrib/.../Journal/SqliteQueryBuilder.cs
> * contrib/.../Snapshot/QueryBuilder.cs

Hi @andrei-epure-sonarsource. The issue is not triggered in this case because Akka.net is using Sqlite and currently we don't cover that.

@eric-therond-sonarsource: what do you think? Are there any plans for covering Sqlite (http://system.data.sqlite.org/index.html/doc/trunk/www/index.wiki)?

**Comment by eric-therond-sonarsource** [comment]
Hello
I sink SQlite will be covered with this ticket:
https://jira.sonarsource.com/projects/SONARSEC/issues/SONARSEC-828

**Comment by andrei-epure-sonarsource** [comment]
@eric-therond-sonarsource sonar-security is different than sonar-dotnet.

**Comment by eric-therond-sonarsource** [comment]
Of course I didn't see I was on sonar-dotnet repository
Ideally all c# database librairies supported on SonarSecurity (S3649 SQLI rule) should be supported in sonar-dotnet  (S2077 Formatted queries rule) and vice-versa.

I will take a look.
