### ISSUE TITLE
Replace '<iconUrl>' by '<icon>' in .nuspec files

### ISSUE THREAD

**Issue by christophe-zurn-sonarsource** [SonarSource/sonar-dotnet#2806]
The `<iconUrl>` metadata element of .nuspec files has been deprecated. (See: https://docs.microsoft.com/en-us/nuget/reference/nuspec#iconurl).

The element should be replaced by the `<icon>` element instead.

Prerequisite: NuGet version >= 5.3 (this version must be installed on the build machines)

**Comment by pavel-mikula-sonarsource** [comment]
Duplicate to fixed #2370

**Comment by andrei-epure-sonarsource** [comment]
it wasn't fixed..

> As discussed and agrred on, we will keep <iconUrl> element until we update NuGet version on our build pipeline. I will update the PR accordingly

**Comment by pavel-mikula-sonarsource** [comment]
Additional information:
Upload of nuget package gives this warning, menioning `PropertyGroup` / `PackageIcon`:

> The <iconUrl> element is deprecated. Consider using the <icon> element instead.
> https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packageiconurl

**Comment by costin-zaharia-sonarsource** [comment]
On build pipeline we are using now version: 5.7.0.
