### ISSUE TITLE
Update rspec2resx.ps1 for .NET 4.8 SDK or the latest

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#2813]
Script `rspec2resx.ps1` depends explicitly on .NET SDK 4.6.1 or 4.7.2.

Add support for latest 4.8 or add general support for the latest bigger than 4.6.1

Update error message

>You need to install the Windows SDK before using this script.

to match with Visual Studio installer packages

>You need to install the .NET Framework 4.6.1 SDK or higher before using this script.

**Comment by andrei-epure-sonarsource** [comment]
duplicate of #2763?

**Comment by pavel-mikula-sonarsource** [comment]
Oops, problem in my task list.
