### ISSUE TITLE
RSPEC-138 | JS | Functions should not have too many lines of code | React Functional Component  

### ISSUE THREAD

**Issue by VovaSv** [SonarSource/sonar-dotnet#2841]
### Description

We have this issue in our projects on each React Functional Component which can be more than 200 line of code.

### Repro steps

Please provide the steps required to reproduce the problem

1. Run this rule of any React Functional Component which more than 200 line of code

### Expected behavior

Ignore for React Functional Component

### Actual behavior

Applied on each React Function Component

**Comment by andrei-epure-sonarsource** [comment]
This is the `sonar-dotnet` repo for our C# and  VB .NET analyzers.
For JS, please open a topic on https://community.sonarsource.com/ or on [SonarSource/SonarJS](https://github.com/SonarSource/SonarJS)
