### ISSUE TITLE
Add C# 8 unit tests to the CFG-based rules

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#2849]
### Description

Part of https://jira.sonarsource.com/browse/MMF-1808

This is a big task (which can be split into multiple issues) which requires:

- changes to the unit test framework to support C# 8 syntax w/ netcore3 and/or netframework4.8 dependencies
- adding unit tests with relevant C# 8 syntax for the following rules which are using the Control Flow Graph

Symbolic execution rules: 
1. - ConditionEvaluatesToConstant / S2583 , S2589
2. - EmptyCollectionsShouldNotBeEnumerated / S4158
3. - EmptyNullableValueAccess / S3655
4. - InvalidCastToInterface / S1944
5. - NullPointerDereference / S2259
6. - ObjectsShouldNotBeDisposedMoreThanOnce / S3966
7. - PublicMethodArgumentsShouldBeCheckedForNull / S3900

Non-SE CFG rules:

1. - DeadStores / S1854
2. - InfiniteRecursion / S2190
3. - MemberInitializerRedundant / S3604
4. - MethodParameterUnused / S1172
5. - RedundantJumpStatement / S3626

**Comment by pavel-mikula-sonarsource** [comment]
I'm closing this based on offline discussion with @andrei-epure-sonarsource. We've agreed that this issue is not needed anymore. It has been divided into partial issues referenced above. C#8 support in unit test framework was done as well.
