### ISSUE TITLE
Add C# 8 ruling integration tests

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#2850]
### Description

Part of https://jira.sonarsource.com/browse/MMF-1808

In addition to akka.net and all the other ruling integration tests, we also need a C# 8 project.

Probably it will need to be hand-written with parts of the UTs added in #2849

**Comment by costin-zaharia-sonarsource** [comment]
I've added `openiddict-core` project to peach in order to increase the coverage of C# 8 features:  https://peach.sonarsource.com/dashboard?id=openiddict-core
