### ISSUE TITLE
Rule S5659 JWT should be signed and verified with strong cipher algorithms

### ISSUE THREAD

**Issue by eric-therond-sonarsource** [SonarSource/sonar-dotnet#2866]
Implements [RSPEC-5659](https://jira.sonarsource.com/browse/RSPEC-5659)

Code examples: https://github.com/SonarSource/security-expected-issues/blob/master/dotnet/wip/basic-rules/RSPEC_5659/Rule5659.cs

**Comment by andrei-epure-sonarsource** [comment]
hey Eric, I see that the file you mention has been removed

we can still see it in the commit (https://github.com/SonarSource/security-expected-issues/commit/0a544add4aff9fa76a41542dbe0197d1fa6753a9) - but has it been moved (and possibly updated) somewhere else?

**Comment by eric-therond-sonarsource** [comment]
Hey @andrei-epure-sonarsource 
link is now fixed
