### ISSUE TITLE
Update *.ps1 src files to have unix style line ending 

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#2882]
Update PowerShell scripts for unified unix line endings. 

Inspired by #2810 : git configuration and coding style.

**Comment by andrei-epure-sonarsource** [comment]
This isn't related in any way to #3925, right? That was only about the encoding?

**Comment by pavel-mikula-sonarsource** [comment]
Yes @andrei-epure-sonarsource
#3925 was about encoding that we use when we update the C# file in our UTs.
This one is about having our powershell scripts with unix EOLs.
