### ISSUE TITLE
Add support for TupleExpressions in CSharpExplodedGraph

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#2933]
### Description

We need to add support for handling TupleExpressions in CSharpExplodedGraph.

### Repro steps

Currently the TupleExpressions are just ignored when processing code like:
```
public class Address
{
    public string Name { get; }

    public string State { get; }

    public void Deconstruct(out string name, out string state) =>
        (name, state) = (Name, State);
}
```

### Additional notes

Once the tuples are supported by CFG and semantic execution we need to update the DeadStores rule (S1854) and remove the check added by #3113.

**Comment by andrei-epure-sonarsource** [comment]
closing as this will be fixed with the new Roslyn CFG

**Comment by pavel-mikula-sonarsource** [comment]
@andrei-epure-sonarsource I'd prefer to keep this documented as opened issue until we support it.

**Comment by andrei-epure-sonarsource** [comment]
@pavel-mikula-sonarsource can we close this now?
