### ISSUE TITLE
Fix CFG generation for the last branch of switch arm

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#2938]
### Description

The generated CFG for the last branch of the switch arm needs to be improved: currently there are 2 simple nodes created for the last branch but only one is needed and this makes the symbolic execution difficult.

e.g.
```
public int Test(string str)
{
    return str switch { null => 1, """" => 2, _ => 3};
}
```

In this example the node with "str" instruction is redundant and needs to be removed.

![image](https://user-images.githubusercontent.com/56015273/71519017-e090d080-28b5-11ea-81bc-c53598c7ef3a.png)

**Comment by christophe-zurn-sonarsource** [comment]
Fixed by #2943
