### ISSUE TITLE
Improve S2259: Fill basic constraints for SE of Switch Expressions

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#2949]
Symbolic Execution: SwitchArms of C# 8 switch statements does not build constraints for their symbolic value. Basic constraints for simple cases (true / false literals, non-null constraints) should be added. Any complex case found when implementing this should be documented in a new ticket.

Affected rules:
- [ ] S3655 EmptyNullableValueAccess 
- [ ] S2583, S2589 ConditionEvaluatesToConstant
- [ ] S3900 PublicMethodArgumentsShouldBeCheckedForNull
- [ ] S1944 InvalidCastToInterface
- [x] S2259 NullPointerDereference

**Comment by pavel-mikula-sonarsource** [comment]
Most of this was implemented by #5860

ToDo: 
* var positive = value is null;       // ispattern & constant pattern
* var negative = value is not null;   // is pattern & negated pattern & constant pattern
* var negative = value is not { };   // is pattern & negated pattern &  recursive pattern

**Comment by martin-strecker-sonarsource** [comment]
#6029 set BoolConstraint for conditions that always or never matched a pattern. This issue is about branching: In the branches, we know more about the pattern values.
