### ISSUE TITLE
Convert analyzer projects to target framework `netstandard`

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#2961]
### Description

We want to be [netstandard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) compatible (TargetFramework Moniker - `netstandardX.Y`), given that
- The .NET Framework support for .NET Standard is fixed at .NET Standard 2.0 i.e. it won't ever support newer versions of .NET Standard.
- in autumn 2020, .NET 5 will be released and NET Framework will be in maintenance mode
- we want our analyzer to be cross-platform (we currently are as we are netstandard 1.3 compatible, but we don't enforce this compatibility in the build), and want to avoid using APIs which haven't been ported to netstandard

We need to evaluate whether we choose:
- netstandard1.3 - to still be compatible with 4.6 as we are now
- netstandard2.0

This is connected to the work done in #569

*IMPORTANT* : when this will be done, we'll have to do manual testing w/ various flavours of net framework and visual studio versions - ask @duncanp-sonar for some VMs which are already configured for that

**Comment by andrei-epure-sonarsource** [comment]
also read [this comment](https://github.com/SonarSource/sonar-dotnet/issues/2871#issuecomment-568424201) about netstandard 1.3 and backwards compatibility

**Comment by andrei-epure-sonarsource** [comment]
regarding this - we use `Environment.OSVersion.Platform` (see #3080 and discussion on #3085) which is not part of NET Standard 1.3.

It's only part of .NET Standard 2.0

**Comment by costin-zaharia-sonarsource** [comment]
Fixed by #3410
