### ISSUE TITLE
Rule S1117 - add tests with static local functions 

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#2978]
### Description

Add tests with static local functions. Part of https://jira.sonarsource.com/browse/MMF-1842

**Comment by christophe-zurn-sonarsource** [comment]
This rule already behaves as defined in the RSPEC : https://jira.sonarsource.com/browse/RSPEC-2910

I believe we should close it, and remove the FN comment [here](https://github.com/SonarSource/sonar-dotnet/blob/a9f67db914583c5fc2cb3147ee67bcdb730be34c/sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/VariableShadowsField.cs#L103), as making it work as defined in the unit test would update the actual rule implementation

**Comment by andrei-epure-sonarsource** [comment]
fair point @christophe-zurn-sonarsource  - I've opened https://github.com/SonarSource/sonar-dotnet/issues/3038 for that
