### ISSUE TITLE
Rule S2857 - update to support interpolated string syntax

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#2986]
### Description

`$""`, `$@""` and `@$""` are not yet handled

part of https://jira.sonarsource.com/browse/MMF-1842

____________________________________________________________

LATER EDIT:
Looking better at the rule, indeed the scope is outside of the "support for C#8" features.

The idea would be to support interpolated strings, and not verbatim interpolated strings - because a verbatim string contains newlines inside and I think it's overkill to analyze all SQL verbatim strings. And anyway, it's quite a big change.

I see two separate opportunities to improve the rule:

- Support interpolated strings
- Support verbatim strings (simple and interpolated) - this would mean to parse the verbatim string and analyze the newlines inside it, as well as prepared queries.

**Comment by andrei-epure-sonarsource** [comment]
@costin-zaharia-sonarsource  - I see that we intentionally ignore interpolated and multi-line verbatim strings in [the tests](https://github.com/SonarSource/sonar-dotnet/blob/ba82a424a249eb9848315c9c09940dda53d96570/sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/SqlKeywordsDelimitedBySpace.cs#L157) - do you think we should stop doing that?

**Comment by costin-zaharia-sonarsource** [comment]
I've missed the fact that these were intentionally ignored. Presumably due to the fact that it will increase the chance to have false positives.

I think it will be nice to extend the rule in the future but currently it's not in the scope of the C# 8 improvements. We can update this issue and let it for the future. WDYT?

**Comment by andrei-epure-sonarsource** [comment]
after the stand-up discussion we decided to apply the C# 8 changes to the rule and also raise on interpolated strings just as for regular strings

**Comment by andrei-epure-sonarsource** [comment]
Looking better at the rule, indeed the scope is outside of the "support for C#8" features.

The idea would be to support interpolated strings, and not verbatim interpolated strings - because a verbatim string contains newlines inside and I think it's overkill to analyze all SQL verbatim strings. And anyway, it's quite a big change.

I see two separate opportunities to improve the rule:
1. Support interpolated strings
2. Support verbatim strings (simple and interpolated) - this would mean to parse the verbatim string and analyze the newlines inside it, as well as prepared queries.

**Comment by andrei-epure-sonarsource** [comment]
as discussed in today's stand-up, I'm not sure of the value this change would bring compared to other issues pending in our backlog
