### ISSUE TITLE
Sonar not showing any coverage for unit test cases.

### ISSUE THREAD

**Issue by RituMishra18** [SonarSource/sonar-dotnet#3045]
### Description
Everything is successful still i am not able to see code coverage for nunit test cases.
Code is visible but no coverage.

### Repro steps

Executing these steps:
Begin
C:\Users\LENOVO\Downloads\sonar-scanner-msbuild-4.7.1.2311-net46\SonarScanner.MSBuild.exe begin /k:"Util:TestSonarKey" /d:sonar.host.url="http://localhost:9000" /d:sonar.login="---" /d:sonar.cs.dotCover.reportsPaths="C:\Users\LENOVO\source\repos\TestApp\AppCoverageReport.html" /d:sonar.cs.nunit.reportsPaths="C:\Users\LENOVO\source\repos\TestApp\TestResult.xml" /d:sonar.verbose=true

Build

"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe" /t:Rebuild

nunitStep

C:\Users\LENOVO\source\repos\TestApp\packages\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe "C:\Users\LENOVO\source\repos\TestApp\UnitTestProject1\bin\Debug\UnitTestProject1.dll"

C:\Users\LENOVO\Downloads\JetBrains.dotCover.CommandLineTools.2019.3.1\dotCover.exe analyse /TargetExecutable="C:\Users\LENOVO\source\repos\TestApp\packages\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe" /TargetArguments="C:\Users\LENOVO\source\repos\TestApp\UnitTestProject1\bin\Debug\UnitTestProject1.dll" /Output="AppCoverageReport.html" /ReportType="HTML"

end

C:\Users\LENOVO\Downloads\sonar-scanner-msbuild-4.7.1.2311-net46\SonarScanner.MSBuild.exe end /d:sonar.login="----"

If possible then please create a git repository with a repro sample or attach a zip to the issue.
[TestApp.zip](https://github.com/SonarSource/sonar-dotnet/files/4066436/TestApp.zip)

### Expected behavior

Should generate coverage report.

### Actual behavior

i can see only source files but coverage is still 0%

* SonarC# Version--sonar-application-8.1.0.31237
* Visual Studio Version-2017
Scanner for MSBuild -4.7.1

**Comment by andrei-epure-sonarsource** [comment]
hi, to get help on using our products we have a community forum , it's better to move your topic there > https://community.sonarsource.com/c/help/sq/10

**Comment by RituMishra18** [comment]
But i think it's a bug as i am not able to see code coverage % after getting success message.

**Comment by andrei-epure-sonarsource** [comment]
please use the [8.1 version](https://github.com/SonarSource/sonar-dotnet/releases/tag/8.1.0.13383) which has enhanced debugging for code coverage importing

run the commands in verbose mode, and if the logs are not enough to figure our why code coverage doesn't get imported, please open a topic on the community forum community.sonarsource.com/c/help/sq/10

As you can see , we have lots of topics with [code coverage](https://community.sonarsource.com/search?q=csharp%20coverage) and your problem may already have an answer on the community forum
