### ISSUE TITLE
S2583: NullCoalesceOperator ??= for ConditionEvaluatesToConstant

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#3066]
### Description

Add support for `??=` operator to rule S2583 and S2589 and update RSPEC .

This point was removed from S3240 specification in favor of these rules:

> * removing the {{??}} when the left operand is known to be {{null}}, or known to be definitely not {{null}}.

It should be applied to SE rules and extended to ??= as well.

**Comment by christophe-zurn-sonarsource** [comment]
Can be merged as soon as master CI is finished and is green
