### ISSUE TITLE
Update S4426 to match RSPEC

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#3089]
### Description

New RSPEC version of S4426 describes key requirements in more detailed way. We should update the rule to match the specification.

### Original version

> When generating cryptograpic keys (or key pairs), it is important to use a key length that provides enough entropy against brute-force attacks. For the RSA algorithm the key should be at least 2048 bits long.
> This rule raises an issue when a RSA key-pair generator is initialized with too small a length parameter.

### Current version

> Digital Signature Generation and Verification:
> 
> p ≥ 2048 AND q ≥ 224 for DSA (p is key length and q the modulus length)
> n ≥ 2048 for RSA (n is the key length)
> Key Agreement:
> 
> p ≥ 2048 AND q ≥ 224 for DH and MQV
> n ≥ 224 for ECDH and ECMQV (Examples: secp192r1 is a non-compliant curve (n < 224) but secp224k1 is compliant (n >= 224))
> Encryption and Decryption:
> 
> AES-128, 192, 256
> This rule will not raise issues for ciphers that are considered weak (no matter the key size) like DES, Blowfish.

**Comment by Tim-Pohlmann** [comment]
This ticket is outdated. The current version of RSPEC matches the old version:
RSA & DSA: 2048
AES: 128
ECC: 224
The rule implementation follows these requirements.
