### ISSUE TITLE
Update rules metadata for 8.4 release

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#3091]
### Description

Before the 8.4 release, update the rule descriptions metadata.

**Comment by pavel-mikula-sonarsource** [comment]
I consider this as part of every release process. We might be more explicit about it in _Sonar* release process_ page. We might put it as separate step before "Check for Releasability"?

**Comment by andrei-epure-sonarsource** [comment]
Yes I agree.

I added a ticket as this is a visible change to the users. Basically, I would like to have in the milestone (= release notes) whatever has impact or is visible to users.

I think the release process page is ok.
