### ISSUE TITLE
Rule S2755: XML parsers should not be vulnerable to XXE attacks - XmlDocument and XmlTextReader

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#3096]
[RSPEC-2755](https://jira.sonarsource.com/browse/RSPEC-2755), [MMF-1918](https://jira.sonarsource.com/browse/MMF-1918)

This initial implementation will not use Symbolic Execution, but rather the approach SonarJava currently has - see [XmlExternalEntityProcessingCheck](https://github.com/SonarSource/sonar-java/blob/6.0.2.20657/java-checks/src/main/java/org/sonar/java/checks/security/XmlExternalEntityProcessingCheck.java)

For each XML API, the code should raise an issue:
- for APIs that are vulnerable, if DTD processing is not deactivated
- for APIs that are safe by default, DTD processing is activated

XML Parser | Safe by default?
-- | --
XmlDocument |  
...prior to 4.5.2 | No
...in versions 4.5.2+ | Yes
XmlTextReader |  
...prior to 4.5.2 | No
...in versions 4.5.2+ | Yes
XmlReader | Yes
XPathNavigator |  
...prior to 4.5.2 | No
...in versions 4.5.2+ | Yes

Based on the above, we'd need more integrations tests: .NET 3.5, .NET 4, .NET 4.5.2+

STEPS:
- [x] Deliver implementation for XmlTextReader and XmlDocument
- [x] Improve NetFrameworkVersionProvider

- The implementation for  XmlReader and XPathNavigator is postponed
- Refactor the ITs and UTs to be manageable (maybe use the same approach from the SonarSecurity ITs where the "Noncompliant S1234" gets parsed from the file - would need to move them to the Java ITs) https://github.com/SonarSource/sonar-dotnet/issues/3130

**Comment by andrei-epure-sonarsource** [comment]
for the framework detection, one idea comes from @Corniel from #2383 

```
var version = c.Compilation.Assembly.GetAttributes().GetCustomAttribute<TargetFrameworkAttribute>()?.FrameworkName;
```

**Comment by Corniel** [comment]
@andrei-epure-sonarsource Feel free to send met a code review. (or I can do a propasal myself).

**Comment by andrei-epure-sonarsource** [comment]
no need to do a code change for this @Corniel , I am on it. I should have a PR in a few days

**Comment by andrei-epure-sonarsource** [comment]
I moved XmlReader and XPathNavigator to #3125

@Corniel - in the end this is how we detect the framework: https://github.com/SonarSource/sonar-dotnet/blob/andrei/S2755-xxe-firstCR/sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/NetFrameworkVersionProvider.cs#L33
