### ISSUE TITLE
Reuse the same SonarQube instance in the integration tests in order to reduce test time

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#3103]
Currently the **SonarQube** server is started and killed 2 times during the integration tests execution and this increase the time taken by running integration tests.

I think this is not necessary and that it would be great to reuse the instance in order to avoid spending precious time just on starting and stopping the server.

**Comment by andrei-epure-sonarsource** [comment]
(removing the performance tag to keep it just for product-related perf issues)

**Comment by costin-zaharia-sonarsource** [comment]
This is no longer a problem since we run the Csharp and VB.Net ITs on concurrent jobs.
