### ISSUE TITLE
Make it easier to find the source code location to reproduce analyzer exceptions

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonar-dotnet#314]
Currently, when an analyzer throws an exception, that exception gets wrapped in the rule `AD0001`, and we can see its exception message easily in Visual Studio and in the MSBuild logs (when the SonarQube Scanner for MSBuild is used with MSBuild >= 14).

`CSC : error AD0001: Analyzer 'SonarLint.Rules.CSharp.DelegateSubtraction' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\projects\nemo-roslyn\roslyn\src\Compilers\Core\Portable\CodeAnalysis.csproj]`

We can also see its stack trace in Visual Studio, by expanding the error message:
!https://cloud.githubusercontent.com/assets/1132601/12196620/5f84e1c4-b600-11e5-88b4-4613650722ca.png!

However, we cannot easily what input source code causes the issue, making it harder to reproduce the problem:

1. When starting only from the exception message, one must manually look for all the potential places the exception might have been thrown in the analyzer's source code, and then try to come up with some code that triggers the issue. With this approach, there is a slight chance of fixing a different problem than the one initially reported (perhaps there were 2 or more locations which could trigger that exception).
2. When starting from the exception and stacktrace, the source code potentially throwning the exception is either reduced to a single line (when PDBs are available), or to a single method (when PDBs are not available). However it still is a challenge to come up with code that triggers the issue, which is needed to update its unit test case.

Instead, it would be better find the source code that allows the issue to be reproduced. If we have that, then we don't need the exception message nor the stacktrace, as we can get it back anytime we want by debugging the analyzer on the given source code.

What I have in mind is to derive all analyzers from a common one, which would add a try-rethrow block around each method to add a bit of contextual message such as the current's node location in the source code (file and line) for syntax node events.

It would be somehow similar to https://github.com/SonarSource/sonarlint-vs/blob/dfa56b11a37916e19fd734bcb5bbb73330cab3a6/src/SonarLint/Helpers/ParameteredDiagnosticAnalyzer.cs

**Comment by Evangelink** [comment]
We might get some feedback from roslyn team on this: [issue on Roslyn](https://github.com/dotnet/roslyn/issues/21404)

**Comment by RalfKoban** [comment]
Hi, I just met that issue.

Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'SonarAnalyzer.Rules.CSharp.MemberShouldBeStatic' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	MiKo Aspects		1	Active	Analyzer 'SonarAnalyzer.Rules.CSharp.MemberShouldBeStatic' threw the following exception:
'Exception occurred with following context:
Compilation: MiKoSolutions.Aspects
SyntaxTree: D:\Private\MiKo Solutions\MiKo Aspects\Source\MiKo Aspects\Internals\Extensions\ReflectionExtensions.cs
SyntaxNode: Compile(); [MethodDeclarationSyntax]@[16871..16881) (354,74)-(354,84)

System.NullReferenceException: Object reference not set to an instance of an object.
   at SonarAnalyzer.Rules.CSharp.MemberShouldBeStatic.GetMethodDescendants(MethodDeclarationSyntax methodDeclaration)
   at SonarAnalyzer.Rules.CSharp.MemberShouldBeStatic.CheckIssue[TDeclarationSyntax](SyntaxNodeAnalysisContext context, Func`2 getDescendants, Func`2 getIdentifier, String memberKind)
   at SonarAnalyzer.Rules.CSharp.MemberShouldBeStatic.<Initialize>b__6_2(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.DiagnosticAnalyzerContextHelper.<>c__DisplayClass0_0`1.<RegisterSyntaxNodeActionInNonGenerated>b__0(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.SonarAnalysisContext.<>c__DisplayClass16_0`1.<RegisterSyntaxNodeAction>b__0(SyntaxNodeAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.


The source code that produces the exception is a nested class in an extension class:

        /// <summary>
        /// Provides a mechanism to create <see cref="Delegate"/>s based on <see cref="MethodInfo"/>s via <see cref="Expression"/> trees.
        /// </summary>
        private static class DelegateCreator
        {
            [Pure]
            public static Delegate Create(MethodInfo method)
            {
                var instance = Expression.Parameter(method.DeclaringType, "instance");
                var arguments = CreateParameterExpressions(method);
                var body = CreateBodyExpression(method, instance, arguments);
                return Expression.Lambda(body, instance.Including(arguments)).Compile();
            }

            [Pure]
            private static Expression CreateBodyExpression(MethodInfo method, Expression instance, ParameterExpression[] arguments)
            {
                Expression methodCall = Expression.Call(instance, method, arguments);
                return method.ReturnType == typeof(void) ? methodCall : Expression.Convert(methodCall, method.ReturnType);
            }

            [Pure]
            private static ParameterExpression[] CreateParameterExpressions(MethodInfo method)
            {
                var parameters = method.GetParameters();
                var arguments = new ParameterExpression[parameters.Length];
                for (var i = 0; i < arguments.Length; i++)
                {
                    var parameter = parameters[i];
                    arguments[i] = Expression.Parameter(parameter.ParameterType, parameter.Name);
                }

                return arguments;
            }
        }

**Comment by Evangelink** [comment]
Hi @RalfKoban I moved your comment to a separate issue.

**Comment by Evangelink** [comment]
@andrei-epure-sonarsource Just to let you know that the ticket on roslyn side got closed as they are now displaying more info when building with command line. I don't know if that's enough to ensure you have most of the time enough info to understand the failure but that's certainly better than it was. Feel free to reopen or create a new ticket if you are still facing issues on new VS.

**Comment by andrei-epure-sonarsource** [comment]
thanks a lot, @Evangelink !

**Comment by pavel-mikula-sonarsource** [comment]
I just needed this functionality and msbuild output log with `/v:detailed` contained enough information to get the source file and source node:
```
  SyntaxTree: C:\Projects\_External\BenchmarkDotNet\src\BenchmarkDotNet.Core\Exporters\RPlotExporter.cs
  SyntaxNode: new ProcessStartInfo { UseShellExecute ... [ObjectCreationExpressionSyntax]@[2652..3023) (63,24)-(71,13)
```
So we can close this issue, as the functionality comes out of the box.
