### ISSUE TITLE
False positives in RSPEC-4564, input validation checks.

### ISSUE THREAD

**Issue by JJonesNXT** [SonarSource/sonar-dotnet#3160]
### Description

RSPEC-4564 is reporting false positives for HttpPost functions without ValidateInput..

### Repro steps

I am getting a lot of false positives for this rule, claiming I need ValidateInput(true) to be set, which I know I don't.

First issue is that this rule is triggering on posts that do not accept strings as parameters. For example, the rule is triggering on this function:
[HttpPost]
public JsonResult Delete(int id)

Second issue is that since ASP.NET 4.0, HTML input is validated by default unless explicitly disabled in web.config or by using ValidateInput(false). We are doing neither. When testing on an HttpPost function that does accept a string, we proved that the input is being validated fine without needing ValidateInput(true), but Sonar is not recognizing this.

### Expected behavior

* I expect this rule to not trigger on HttpPost functions with no string parameters.
* I expect this rule to not trigger on ASP.NET 4.0+ projects unless input validation has been explicitly disabled.

### Actual behavior

* This rule is triggering on HttpPost functions that only have integer or boolean parameters.
* This rule is triggering on an ASP.NET 4.0 project, and input validation has not been explicitly disabled.

### Known workarounds

* None, save for manually mitigating each function as a false positive after we proved malicious input is not possible.

### Related information

* SonarC#: 8.4
* Visual Studio Version: 16.4.5
* Operating System: Windows Server 2016

**Comment by andrei-epure-sonarsource** [comment]
thanks @JJonesNXT 
we're currently re-evaluating https://jira.sonarsource.com/browse/RSPEC-4564 and the rule may become a [Security Hotspot](https://docs.sonarqube.org/latest/user-guide/security-hotspots/) soon (rather than a Vulnerability) - https://jira.sonarsource.com/browse/RSPEC-5753

linking to #3185

**Comment by andrei-epure-sonarsource** [comment]
marking it "on hold" as it will be solved probably together with #3185
