### ISSUE TITLE
Fix S4275 Bug: C# auto-implemented property with AggressiveInlining throws NRE

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#3182]
Recent update of S4275 introduced a bug with NRE.

Methods with AggressiveInlining do not have setter.Body instance set.
```
public int WithAttributeWithoutBody
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    get;
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private set;
}
```

**Comment by Corniel** [comment]
I assume this is more generic? Every attribute on the `get` and `set` body should be allowed.

**Comment by pavel-mikula-sonarsource** [comment]
Yes, it's presence of any attribute that changes the behavior of Roslyn data for `setter.Body`. 

Implementation of the fix doesn't care why it happened. So all attributes are allowed.
