### ISSUE TITLE
Code coverage report is not generated for some methods

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#3191]
### Description

VSTest.console.exe does not include covered methods into report file. Not even as 0% covered. Theese methods are not seen by SC as covered and QG fails.

### Methods

* SonarAnalyzer.Helpers.StringExtensions.SplitCamelCaseToWords
* SonarAnalyzer.Helpers.SymbolHelper.GetAllNamedTypes

### Other

* Renaming file, class and method to `OtherFileName.SplitCamelCaseTxWords` reproduces the issue. 
* Adding second method into file forces it to work as expected with 100% coverage.
* VS Enteprise is needed for local run of `VSTest.console /EnableCodeCoverage`
* Might be related to yield iterators  (see [this comment](https://github.com/SonarSource/sonar-dotnet/pull/3188#issuecomment-596580340))

**Comment by andrei-epure-sonarsource** [comment]
maybe linked to https://community.sonarsource.com/t/adding-another-test-run-halves-the-code-coverage/15087/16 , there are some reproducers there as well

**Comment by andrei-epure-sonarsource** [comment]
From what we've discussed, we should:
- double check that the coverage info doesn't get generated by the vscover tool
- come up with a reproducer project
- report the issue to vstest

unless we realize there's a parsing error on our side

**Comment by Tim-Pohlmann** [comment]
1. I recreated the issue by creating a test solution with only two projects:
  - .NET 8 Class library
    - contains a single file with the content of [StringExtension](https://github.com/SonarSource/sonar-dotnet/blob/afc06e378219175e944e5fa68609136d0cc6f577/analyzers/src/SonarAnalyzer.CFG/Helpers/StringExtensions.cs).
  - .NET 8 MS Test project
    - contains a single UT calling `"thisIsAName".SplitCamelCaseToWords().ToList()`.
2. Run local SQ 10.5.1.90531 Enterprise
3. `dotnet sonarscanner begin /k:"Local-Sandbox" /d:sonar.host.url="http://localhost:9000"  /d:sonar.token="<token>" /d:sonar.cs.vscoveragexml.reportsPaths=**/*.coveragexml`
4. `dotnet build`
5. `dotnet test --collect "Code Coverage;Format=xml"`
6. `dotnet sonarscanner end /d:sonar.token="<token>"

A possible cause is how `yield` methods are reported in the .xml file:
```
<function block_coverage="82,22" line_coverage="70,59" blocks_covered="37" blocks_not_covered="8" lines_covered="24" lines_partially_covered="0" lines_not_covered="10" id="8360" token="0x6000005" name="MoveNext()" namespace="SonarAnalyzer.Helpers" type_name="StringExtensions.&lt;SplitCamelCaseToWords&gt;d__0">
```
Note that the method name is `MoveNext()` and not `SplitCamelCaseToWords()`.

**Comment by mary-georgiou-sonarsource** [comment]
I tried Tim's repro but it does not work for me.
 If I copy and paste exactly these commands, there are no coverage results because the file pattern cannot be found. Once I set the pattern to be any XML file, then coverage is normally found and reported.
Additionally, opening the coverage file, I can see the method `SplitCamelCaseToWords` is there.

@costin-zaharia-sonarsource do you have maybe any advice which direction I can go here?

**Comment by costin-zaharia-sonarsource** [comment]
I think this might depend on the versions of the dotnet runtime and of the coverage tool. How about Pavel's example? Is the issue still reproducible when analyzing out code?

**Comment by mary-georgiou-sonarsource** [comment]
I cannot reproduce this.
Additionally, both methods mentioned in the issue description
SonarAnalyzer.Helpers.StringExtensions.SplitCamelCaseToWords
SonarAnalyzer.Helpers.SymbolHelper.GetAllNamedTypes (now refactored to be INamedTypeSymbolExtensions.GetAllNamedTypes)
see to both be covered on SC (see [here](https://sonarcloud.io/code?id=sonaranalyzer-dotnet&selected=sonaranalyzer-dotnet%3Aanalyzers%2Fsrc%2FSonarAnalyzer.Common%2FExtensions%2FINamedTypeSymbolExtensions.cs&line=1) and [here](https://sonarcloud.io/code?id=sonaranalyzer-dotnet&selected=sonaranalyzer-dotnet%3Aanalyzers%2Fsrc%2FSonarAnalyzer.CFG%2FHelpers%2FStringExtensions.cs&line=1)).
