### ISSUE TITLE
Run CBDE multi-platform

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#3192]
Currently, the CBDE rule is ran only on Windows.

Once we add [cross-platform integration tests](https://trello.com/c/YxTYaU70/29-add-cross-platform-and-cross-msbuild-integration-tests-for-sonar-dotnet) for sonar-dotnet, we should make CBDE run multi-platform.

Steps to do:
- add the unix and macos binaries to the SonarAnalyzer DLL
- update the `CbdeHandler` to [unpack them](https://github.com/SonarSource/sonar-dotnet/blob/master/sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/CBDE/CbdeHandler.cs#L159) depending on the underlying OS
- update `CbdeHandlerRule` [to use the correct binary](https://github.com/SonarSource/sonar-dotnet/blob/master/sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CbdeHandlerRule.cs#L73) depending on the platform
- add CBDE integration tests for Linux and Mac OS
- update the S3949 rule description and [remove this comment](https://github.com/SonarSource/sonar-dotnet/blob/master/sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/CbdeHandlerRule.cs#L39)

**Comment by pavel-mikula-sonarsource** [comment]
Won't fix, will be reimplemented.
