### ISSUE TITLE
Update Test Framework to support ASP.NET Core 3.x packaging 

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#3195]
NetCore 3.1 is the current LTS.

ASP.NET Core has introduced [many breaking changes between 2.2 and 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#framework-reference), and one regarding packaging is affecting our current UT test infrastructure for rules. Lots of what was available via nuget packages is now available via the SDK.

> Features of ASP.NET Core that were available through one of the packages listed above are available as part of the Microsoft.AspNetCore.App shared framework. The shared framework is the set of assemblies (.dll files) that are installed on the machine and includes a runtime component and a targeting pack. For more information, see The shared framework.

**Possible solutions**

**Idea A**

For 3.0, we could reference the [Microsoft.AspNetCore.App.Ref](https://www.nuget.org/packages/Microsoft.AspNetCore.App.Ref/) in our tests, however there's work to be done in the [NugetMetadataFactory](https://github.com/SonarSource/sonar-dotnet/blob/8.4.0.15306/sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestFramework/NugetMetadataFactory.cs) to allow this.

The main change is that lots of DLLs, for example `Microsoft.AspNetCore.Http.Extensions.dll` needed by this rule, are present now in `packages\Microsoft.AspNetCore.App.Ref.3.1.0\ref\netcoreapp3.1` (lots of DLLs in this nuget, which is used internally by Microsoft for its SDK) whereas they were present in 2.2.0 in a folder pattern like `packages\Microsoft.AspNetCore.Diagnostics.2.2.0\lib\netstandard2.0` - one DLL per nuget.

This is the line that uses `lib` (valid for 2.2.0), and the UT framework must be extended to search various DLLs in the `Microsoft.AspNetCore.App.Ref.3.1.0\ref` folder.

**Idea B**

Rely on the installed `Project Sdk="Microsoft.NET.Sdk.Web"`, if possible. However we'd like to avoid adding web dependencies on the `UT` project and build machines. To be discussed.

**Comment by andrei-epure-sonarsource** [comment]
Note: the work done here will have to be ported to sonar-security as well (and I'm not sure it's worth to create a library for this)

**Comment by andrei-epure-sonarsource** [comment]
Also check #3674

**Comment by pavel-mikula-sonarsource** [comment]
This was already implemented in the past as a side effect of PR #3583. Solution: https://github.com/SonarSource/sonar-dotnet/blob/68eee4117874b14e22850725d2cbf7867e82d64b/analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj#L26-L29
