### ISSUE TITLE
Add documentation for coverlet integration

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#3221]
- [x]  - [the community forum guide](https://community.sonarsource.com/t/coverage-test-data-generate-reports-for-c-vb-net/9871)
- [x]  - [sonarcloud static docs](https://github.com/SonarSource/sonarcloud-core/tree/master/server/sonar-docs/src/pages)
- [x]  -  [sonarqube static docs](https://github.com/SonarSource/sonar-enterprise/tree/master/server/sonar-docs/src/pages)
- [x]  -  our readme
- [x]  -  [sonarsource website](https://www.sonarsource.com/products/codeanalyzers/sonarcsharp.html)

**Comment by costin-zaharia-sonarsource** [comment]
In case it helps: https://xtranet-sonarsource.atlassian.net/wiki/spaces/~695977691/pages/225574963/sonar-dotnet+-+code+coverage+coparison#Coverlet
