### ISSUE TITLE
Add UT with the opencover XML generated by coverlet 

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#3232]
(using the OpenCover format)

It would be useful to have a UT with the OpenCover.xml generated by the coverlet tool, just for documentation purposes

**Comment by andrei-epure-sonarsource** [comment]
@costin-zaharia-sonarsource  - given that your OpenCover improvement hasn't been released yet, does this ticket make sense anymore?

**Comment by costin-zaharia-sonarsource** [comment]
> @costin-zaharia-sonarsource - given that your OpenCover improvement hasn't been released yet, does this ticket make sense anymore?

I've updated the thread from: https://community.sonarsource.com/t/coverage-test-data-generate-reports-for-c-vb-net/9871 in order to mention the support of coverlet using the OpenCover format and I think we can close this issue.
