### ISSUE TITLE
ConditionEvaluatesToConstant crashes

### ISSUE THREAD

**Issue by Corniel** [SonarSource/sonar-dotnet#3242]
### Description
> Analyzer 'SonarAnalyzer.Rules.CSharp.EmptyCollectionsShouldNotBeEnumerated' threw an exception of type 'SonarAnalyzer.SymbolicExecution.SymbolicExecutionException' with message 'Error processing method: LoadAsync 
>  Method file: C:\code\sonar-experiments\src\SonarAnalyzer.Experiments.CSharp\ConditionEvaluatesToConstantException.cs 
>  Method line: 10,8 
>  Inner exception: System.NullReferenceException: Object reference not set to an instance of an object. 
>     at SonarAnalyzer.SymbolicExecution.CSharpExplodedGraph.VisitDefaultExpression(SyntaxNode instruction, ProgramState programState) 
>     at SonarAnalyzer.SymbolicExecution.CSharpExplodedGraph.VisitInstruction(ExplodedGraphNode node) 
>     at SonarAnalyzer.SymbolicExecution.AbstractExplodedGraph.Walk() 
>     at SonarAnalyzer.Rules.CSharp.EmptyCollectionsShouldNotBeEnumerated.CheckForEmptyCollectionAccess(CSharpExplodedGraph explodedGraph, SyntaxNodeAnalysisContext context) 
>     at SonarAnalyzer.SymbolicExecution.FlowAnalysisExtensions.Analyze(CSharpSyntaxNode declarationBody, ISymbol symbol, Action`2 analyze, SyntaxNodeAnalysisContext context)

### Repro steps
This snippet will do:

``` C#
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace SonarAnalyzer.Experiments.CSharp
{
    public class ConditionEvaluatesToConstantThrows
    {
        public ConditionEvaluatesToConstantThrows(object header, object body)
        {
            Header = header;
            Body = body;
        }

        public object Header { get; }

        public object Body { get; }


        public static async Task<ConditionEvaluatesToConstantThrows> LoadAsync(Stream stream, Type headerType, Type bodyType)
        {
            var root = await XElement.LoadAsync(stream, LoadOptions.None, default);

            var header = root.Element(root.Name.Namespace + nameof(Header))?
                .Elements()
                .FirstOrDefault()
                .Deserialize(headerType);

            var body = root.Element(root.Name.Namespace + nameof(Body))?
                .Elements()
                .FirstOrDefault()
                .Deserialize(bodyType);

            return new ConditionEvaluatesToConstantThrows(header, body);
        }
    }

    public static class SoapMessageExtensions
    {
        public static object Deserialize(this XNode node, Type type)
        {
            return new object();
        }
    }
}
```

### Related information

* SonarC# Version 8.5

**Comment by Corniel** [comment]
Hmm, I can not reproduce it myself anymore. :( Nevertheless, I could in the original, as in the reproduced code.

**Comment by pavel-mikula-sonarsource** [comment]
Hi @Corniel ,

I can't reproduce this one as well. It's probably different piece of code causing this.
`VisitDefaultExpression` is related to DefaultExpression or DefaultLiteralExpression.

First suspect is that instruction type info cannot be found.

**Comment by Corniel** [comment]
As it is the same repro, I asume this is a reproduction scenario:

https://github.com/Corniel/ivory-net-soap/
commit-id: aea84dfd4b86cf0efac1a2bff168dc1265f5a15e

**Comment by pavel-mikula-sonarsource** [comment]
I can't reproduce the issue on that branch. If you can isolate minimal reproducible scenario, please let us know and we can reopen this.

I saw different bug there: #3245
