### ISSUE TITLE
Links to CONTRIBUTING.md result in a 404

### ISSUE THREAD

**Issue by milbrandt** [SonarSource/sonar-dotnet#3261]
In [docs/contributing-analyzer.md#Contributing](https://github.com/SonarSource/sonar-dotnet/blob/master/docs/contributing-analyzer.md#Contributing) and [docs/contributing-plugin.md#Contributing](https://github.com/SonarSource/sonar-dotnet/blob/master/docs/contributing-plugin.md#Contributing) there is a link `Contributing Code` which leads to a 404 trying to open [CONTRIBUTING.md](https://github.com/SonarSource/sonar-dotnet/blob/master/CONTRIBUTING.md)

**Comment by pavel-mikula-sonarsource** [comment]
Hello @milbrandt ,

Thank you for spotting and reporting this. Fix is on it's way in #3258 update.
