### ISSUE TITLE
SonarC# 8.5+ throws AD0001 in MSBuild with NETFx v4.6.1

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonar-dotnet#3286]
### Description

Using SonarC# v8.5/v8.6 on a machine with only .NETFx v4.6.1 installed produces AD0001 errors due to a missing dependency (`System.ValueTuple v4.0.2.0`)

See also [this community thread](https://community.sonarsource.com/t/scanner-for-msbuild-via-jenkins-not-analyzing-cs-files/21872).

### Repro steps

1. Create a C# project
2. Add a NuGet ref to SonarAnalyzer.CSharp v8.5 or v8.6
3. Add the following code, then build (from the command line or in VS)

```
using System.Xml;

namespace ValTupTst
{
    class XmlReaderIssue
    {
        // https://jira.sonarsource.com/browse/RSPEC-5656
        // S2755
        public void Noncompliant()
        {
            // .NET Framework 4.5.2+
            XmlReaderSettings settings = new XmlReaderSettings();
            settings.DtdProcessing = DtdProcessing.Parse;
            settings.XmlResolver = new XmlUrlResolver();
            XmlReader reader = XmlReader.Create("xxe.xml", settings); // Noncompliant: XmlReader is safe by default and becomes unsafe if DtdProcessing = Parse and XmlResolver is not null
            while (reader.Read())
            { }

        }
    }
}
```

### Expected
No AD0001

### Actual

![image](https://user-images.githubusercontent.com/10757559/78551183-3225f100-77fd-11ea-9a6a-b04dcf60025b.png)

```
1>CSC : warning AD0001: Analyzer 'SonarAnalyzer.Rules.CSharp.XmlExternalEntityShouldNotBeParsed' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.'.
```

### Known workarounds

Install .NET FX 4.7.2

### Related information

* C#/VB.NET Plugins Version: v8.5, v8.6
* Visual Studio Version: n/a
* Operating System: Windows

**Comment by andrei-epure-sonarsource** [comment]
> This default choice also ensures you don't use a language that requires types or runtime behavior not available in your target framework. Choosing a language version newer than the default can cause hard to diagnose compile-time and runtime errors.

See https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version - maybe related

**Comment by andrei-epure-sonarsource** [comment]
we need to first understand if this has been introduced when we changed the lang version.

This is simple to do: remove the lang version and see if some tests break or not.

Other big problems are
- using the Tuple library, w/o copying it in packaging - how can we guard against this sort of regressions in the future?
- we have no regression test on old vanilla platforms - note that the tests must actually execute all the code of the rules - so should be something like our UTs, but able to run on .NET 4.6.1

**Comment by pavel-mikula-sonarsource** [comment]
We can add target to old .NET Framework just as we now do on SonarAnalyzer.Security.Tests and some `#IF` for problematic cases. And run those tests on vanilla machine.

**Comment by costin-zaharia-sonarsource** [comment]
I've added #3299 to have automated tests on an environment with only .Net 4.6.1 installed in order to avoid this kind of issues in the future.

**Comment by christophe-zurn-sonarsource** [comment]
Note: the code sample above will both raise AD0001 warning, and raise S2755 warning as well. This comes from the fact tuples are only used in 2 out of 3 code path for S2755 rule detection, the following snippet will raise AD0001 warning as well as have the FN on S2755 due to rule failure.
```
        public void Noncompliant()
        {
            XmlDocument xmlDoc = new XmlDocument(); // Noncompliant - not raised because of AD0001
        }
```
