### ISSUE TITLE
Fix S4784 FN: Process const regex

### ISSUE THREAD

**Issue by alaincroisetiere** [SonarSource/sonar-dotnet#3298]
### Description

Security hotspot **S4784 : Using regular expressions is security-sensitive** is not detected when regex value is a const.

### Repro steps

```csharp
    public static class ReDoSAttack
    {
        private const string UnsafeRegex = @"^([(?>\.\-)*|\w]+)@\w+(?>(([\.-]?\w+)(?!$)))*(\.\w{2,3})+$";

        public static bool IsValid(string input)
        {
            var regex = new Regex(UnsafeRegex);
            return regex.IsMatch(input);
        }
    }
```

### Expected behavior

A new security hotspot is detected.

### Actual behavior

Security hotspot is not detected.

### Known workarounds

Hard code regex value into the constructor.

### Related information

* Visual Studio 2019 (16.5.4)
* dotnet version 3.1
* SonarScanner 4.9 for MSBuild 4.8
* Microsoft Windows Server 2019 Standard 10.0.17763

Could I provide anythings else to help with my issue ?
Thanks

**Comment by andrei-epure-sonarsource** [comment]
@pavel-mikula-sonarsource for this type of false negative, I'm not sure how it's best to keep track of FNs

I'm pretty sure we have this FN accross all our codebase, and it would be nice at some point to centralize ...

Nothing actionable for now, but it's a thing to keep in mind.

**Comment by pavel-mikula-sonarsource** [comment]
@andrei-epure-sonarsource  For this, there was `GetStringValue` extension as a single point where to fix it for this rule. It could fix other places as well and this repro will allow us to find such cases.
