### ISSUE TITLE
S3626: Reports throwing an Exception only if written as lambda expression

### ISSUE THREAD

**Issue by saciervo** [SonarSource/sonar-dotnet#3301]
### Description

Not sure about this one. https://github.com/saciervo/Try.S3626/blob/master/Try.S3626/UnitTest1.cs

L14 and L22 are essentially the same code. But on L22 it's written as a lambda expression. The analyzer should report violations on both lines, or none.

### Repro steps

Build [this project](https://github.com/saciervo/Try.S3626). S3626 is configured as error so it will fail. 

### Related information

* SonarAnalyzer.CSharp v8.6.0.16497

**Comment by pavel-mikula-sonarsource** [comment]
Hi @saciervo ,

None of the lines should be reported. Issue with throw inside lambdas was already reported in #3105 so I'll close this one.
