### ISSUE TITLE
Does not show test name beside covered source code

### ISSUE THREAD

**Issue by captainjono** [SonarSource/sonar-dotnet#3309]
### Description

I am trying to enable the situation where a developer is looking at source code, and wants to navigate to the unit test that is validating said source code. I cannot find any information anywhere with regards to the required cfg to enable this feature with c#

The best i can acheive is the tooltip to say "fully covered by unit tests"
![image](https://user-images.githubusercontent.com/6093646/80454542-92780080-896d-11ea-8747-cbeae8b30116.png)

![image](https://user-images.githubusercontent.com/6093646/80454344-4036df80-896d-11ea-980e-68c5e3f87524.png)

### Related information
C# Code Quality and Security Analyzer for C# | 8.6 (build 16497)

**Comment by pavel-mikula-sonarsource** [comment]
Hi @captainjono ,

There's no such functionality in our Analyzer for C#. This looks like suggestion for new feature of SonarQube itself. Our [community forum](https://community.sonarsource.com/) would be a place to suggest it with some use case description.
