### ISSUE TITLE
S1481: FP with new using

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-dotnet#3311]
### Description

The following code is raising a `S1481` which is a FP. I could rewrite the code to use the `using() {}` syntax but if I want to keep the current using syntax I can't get rid of the variable name.

### Repro steps

```csharp
class BeginEndActionDisposable : IDisposable {}

[Fact]
public void Ctor_CallsBeginAction()
{
	// Arrange
	int beginCallCount = 0;
	int endCallCount = 0;

	Action beginAction = () => beginCallCount++;
	Action endAction = () => endCallCount++;

	// Act
	using var subject = new BeginEndActionDisposable(beginAction, endAction); // FP here

	// Assert
	beginCallCount.Should().Be(1);
	endCallCount.Should().Be(0);
}
```

### Related information

* C#/VB.NET Plugins Version: latest
* Visual Studio Version: 16.5
* MSBuild / dotnet version: 16.5 / 4.8
* Operating System: Win 10

**Comment by pavel-mikula-sonarsource** [comment]
Hi Amaury, 

We already have this case reported in #3137 so I'll close this one.
