### ISSUE TITLE
S3626: FP with action

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-dotnet#3312]
### Description

The following code is raising a FP for `S3626` remove the redundant jump. This isn't a redundant jump.

### Repro steps

```csharp
Action beginAction = () => throw new InvalidOperationException(exceptionMessage); // FP
```

### Related information

* C#/VB.NET Plugins Version: latest
* Visual Studio Version: 15.6
* MSBuild / dotnet version: 15.6 / 4.8
* Operating System: Win10

**Comment by pavel-mikula-sonarsource** [comment]
Hi Amoury, 

This issue was already reported in #3105 so I'll close this one. The reproducer we've added there was almost exactly the same as your example.
