### ISSUE TITLE
S2589: False positive when a variable is modified inside of a local function

### ISSUE THREAD

**Issue by eduherminio** [SonarSource/sonar-dotnet#3320]
### Description

S2589 seems to be triggered inaccurately when a variable is modified inside of a local function.

### Repro steps

[SonarCloud link](https://sonarcloud.io/project/issues?id=SheepTools&issues=AXHXtK-sSeCmK-YA77PS&open=AXHXtK-sSeCmK-YA77PS).

### Expected behavior

No issue raised.

### Actual behavior

False positive.

### Related information

* SonarCloud.

**Comment by pavel-mikula-sonarsource** [comment]
Hello @eduherminio ,

Thank you for reporting this issue. I can confirm your findings. Similar case with local function was already reported in #3161 for S2583 that shares main part of implementation with S2589. I'll close this one in favor of the original post.
