### ISSUE TITLE
SonarQube on Azure DevOps is not generating any results for Xamarin Forms

### ISSUE THREAD

**Issue by soydachi** [SonarSource/sonar-dotnet#3333]
I have integrated SonarQube with Azure DevOps for Xamarin Forms projects.

The build ran successfully but in sonarqube it dosen't appears any bugs or code smells.

![image](https://user-images.githubusercontent.com/1771785/81401923-a6bbba80-9130-11ea-8dcc-566b5d864f56.png)

The question here is, does sonarqube works with Xamarin Forms? 

Is the standalone scanner the right way in Azure DevOps?

![image](https://user-images.githubusercontent.com/1771785/81402020-e2ef1b00-9130-11ea-802f-35e0ddcc5cce.png)

**Comment by andrei-epure-sonarsource** [comment]
hi,
we don't have support for Xamarin Forms, only for C# and VB .NET.

Also, please read in our README file that this sort of questions should go on our community forum
- https://github.com/SonarSource/sonar-dotnet#do-you-have-a-question-or-feedback
- https://community.sonarsource.com/

thanks for using our products!
