### ISSUE TITLE
Fix S2933 FP: Null-coalescing assignment is not recognized

### ISSUE THREAD

**Issue by SiSc1285** [SonarSource/sonar-dotnet#3339]
Ruleset tells me to make _value readonly but this is not what I want.
The following is just an easy example.

(In my real scenario the inherited class is doing some expensive calculation with an object other than string.)

    public abstract class SampleS2933Issue
        {
            private string? _value = null;
            public string Value => _value ??= Generate();

            protected abstract string Generate();
        }

**Comment by pavel-mikula-sonarsource** [comment]
Hi @SiSc1285 ,

Thank you for reporting this issue, fix is already on it's way to version 8.8. We've also identified False Negatives in S1854, S3010, S2696, S2934 thanks to your report.
