### ISSUE TITLE
Rule S4790: its content should be replaced by S2070

### ISSUE THREAD

**Issue by eric-therond-sonarsource** [SonarSource/sonar-dotnet#3360]
For hashing algorithms, several rules exist, in particular these two:
- A security-hotspot: https://jira.sonarsource.com/browse/RSPEC-4790
- That supersedes this vulnerability: https://jira.sonarsource.com/browse/RSPEC-2070

It's not possible to maintain two rules on exactly the same subject, for us and the end users, so:
- S2070 will be deprecated
- the content/implementation of S2070 is more relevant than S4790 because S4790 raises everywhere a hash function is used (even when secure hash function, like SHA-256 is used) and S2070 raises only when a weak hash function is used (like MD5)
- so the content/implementation of S2070 should "be moved" to S4790 (the key of the rule should be updated in Sonar-dotnet), because the type of issue (hotspot) is more relevant

**Comment by costin-zaharia-sonarsource** [comment]
Hi @eric-therond-sonarsource. Shouldn't we mark [RSPEC-2070](jira.sonarsource.com/browse/RSPEC-2070) as superseded by [RSPEC-4790](jira.sonarsource.com/browse/RSPEC-4790)?

**Comment by eric-therond-sonarsource** [comment]
Hey @costin-zaharia-sonarsource in the past S2070 was superseded by S4790 but now S2070 it's deprecated by S4790 ([see this comment)](https://jira.sonarsource.com/browse/RSPEC-2070?focusedCommentId=238093&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-238093)

**Comment by costin-zaharia-sonarsource** [comment]
> Hey @costin-zaharia-sonarsource in the past S2070 was superseded by S4790 but now S2070 it's deprecated by S4790 ([see this comment)](https://jira.sonarsource.com/browse/RSPEC-2070?focusedCommentId=238093&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-238093)

@eric-therond-sonarsource:

They kind of switched roles 😄.

My concern is that if we deprecate S4790 with the intention of replacing it with S2070, marking it as superseded will be the best way to let the users know the rule replacement.

If we mark the rule as deprecated, is there an easy way for the user to know it's replacement?

**Comment by eric-therond-sonarsource** [comment]
When a rule is deprecated in the UI you have its replacement, for instance see here at the bottom:
https://peach.sonarsource.com/coding_rules?open=java%3AS3510&types=VULNERABILITY

I can't remember why superseded was not enough for s2070, but it has been deprecated for all languages, so we should follow the same strategy for C#

`My concern is that if we deprecate S4790 with the intention of replacing it with S2070`
- S2070 should be deprecated (not S4790)
- the implementation of S2070 should be moved to S4790 (so we will have two rules with the same implementation, it's not really clean at first, but in the future S4790 will be improved over time (with support of more hash algorithms for instance ...) and not S2070 that will stay deprecated and not maintained

**Comment by costin-zaharia-sonarsource** [comment]
> When a rule is deprecated in the UI you have its replacement, for instance see here at the bottom:
peach.sonarsource.com/coding_rules?open=java%3AS3510&types=VULNERABILITY

Thanks, I forgot about that. I see now the comment from the bottom:
> This rule is deprecated; use S5527 instead.

I understand what you mean now. Thanks for all clarifications!
