### ISSUE TITLE
Deterministic Source Paths Breaks Coverage

### ISSUE THREAD

**Issue by iamwyza** [SonarSource/sonar-dotnet#3362]
### Description

If deterministic source paths are enabled during the builds, the scanner will fail to find the code coverage for the code.  (The coverage reports will be indexed, but it will say 0 files matched).  This happens by default with the Microsoft.SourceLink package.

### Repro steps

Create a dotnet core project with 1 class and 1 unit test project, add the Microsoft.SourceLink package, and then run the sonar scanner against it.  It will fail to produce code coverage.

### Known workarounds

Turn deterministic source paths off.

### Related information
* see https://github.com/dotnet/sourcelink/issues/615
* see https://github.com/dotnet/roslyn/issues/43476
* C#/VB.NET Plugins Version - 8.3.1
* Visual Studio Version - N/A
* MSBuild / dotnet version - Core 3.1
* If running through the Scanner for MSBuild, its version - dotnet-scanner 4.8
* Operating System - Win 10.

**Comment by andrei-epure-sonarsource** [comment]
Also https://github.com/dotnet/roslyn/issues/37379

**Comment by andrei-epure-sonarsource** [comment]
Hi @iamwyza 

I tried to come up with a reproducer and created as you said a project - https://github.com/andrei-epure-sonarsource/TestSourceLink .

And it seems code coverage works fine https://sonarcloud.io/dashboard?id=DeterministicSourcePath .

- C# Plugin 8.10 (latest)
- dotnet SDK 3.1.301
- sonar-scanner-msbuild-4.8.0.12008-netcoreapp2.0

The commands I've used:

```
dotnet "C:\SonarQube\sonar-scanner-msbuild-4.8.0.12008-netcoreapp2.0\SonarScanner.MSBuild.dll" begin /k:"DeterministicSourcePath" /d:sonar.verbose=true /d:sonar.login=<TOKEN> /d:sonar.host.url="https://sonarcloud.io" /o:"andrei-epure-sonarsource-github"  /d:sonar.ws.timeout=300 /d:sonar.cs.opencover.reportsPaths="opencover.xml"

dotnet build .\ClassLibrary3.sln /t:Rebuild /maxcpucount /nr:false /p:DeployExtension=false /warnaserror:AD0001 /clp:Summary

OpenCover.Console.exe -output:"opencover.xml" -register:administrator -target:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:".\UnitTestProject1\bin\Debug\netcoreapp3.1\UnitTestProject1.dll"

dotnet "C:\SonarQube\sonar-scanner-msbuild-4.8.0.12008-netcoreapp2.0\SonarScanner.MSBuild.dll" end /d:sonar.login=<TOKEN>
```

What code coverage tool have you used?
Could you update to the latest version of SonarCSharp and try to reproduce?

**Comment by iamwyza** [comment]
I'm using dotnet test, so it'd be the built-in one for dotnet (I think that's just vstest under the covers).

```dotnet test somesolution.sln --no-restore --no-build -c Debug --logger trx --results-directory SomeDir\TestResults --collect:"Code Coverage" -s sourceDir\tests\CodeCoverage.runsettings /m:1```

A segment of that output would look like:

```
Test run for SomeProject.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.6.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Microsoft (R) Coverage Collection Tool Version 16.0.30319.3002


Copyright (c) Microsoft Corporation.  All rights reserved.




Results File: c:\SomeDir\TestResults\VssAdministrator-00000_2020-07-01_00_00_00.trx

Attachments:
  c:\SomeDir\TestResults\3abe04cb-ae84-4962-ad8b-50f2b33c4baf\VssAdministrator_00000_2020-07-01.00_00_00.coverage
Test Run Successful.
Total tests: 4
     Passed: 4
 Total time: 2.6735 Seconds```

**Comment by costin-zaharia-sonarsource** [comment]
I've added a small project on which we can reproduce this issue: https://github.com/costin-zaharia-sonarsource/Repro3362

Steps: https://github.com/costin-zaharia-sonarsource/Repro3362#steps

**Comment by andrei-epure-sonarsource** [comment]
### Initial investigation

1. Run with `dotnet build --no-incremental -p:DeterministicSourcePaths=true`

in filename-deterministic-sources.coveragexml

        <source_file id="0" path="/_/Repro3362/Foo.cs" checksum_type="unknown">

under `module name="repro3362.dll`

When running in debug mode, we can see the below line (note that it's `C:\_\` , not `/_/` !!)

> DEBUG: Skipping file with path 'C:\_\Repro3362\Foo.cs' because it is not indexed or does not have the supported language.

Unfortunately, in the statistics at the end, we don't mention skipped files

> INFO: Coverage Report Statistics: 1 files, 0 main files, 0 main files with coverage, 1 test files, 0 project excluded files, 0 other language files.

2. Run without `DeterministicSourcePaths`

in filename-simple.coveragexml

        <source_file id="0" path="C:\Workspace\external-projects\private_customer_reproducers\Repro3362\Repro3362.Tests\FooTests.cs" checksum_type="unknown">

under `module name="repro3362.dll`

3. Added the property mentioned in [this comment](https://github.com/dotnet/roslyn/issues/37379#issuecomment-513371985) and built with `-p:DeterministicSourcePaths=true`, but had the same behavior as point 1.

### Possible plan

Before moving forward:
- I need to test the behavior of `DeterministicSourcePaths=true` with `dotcover` and `opencover`
- however, as an initial baby step, I can only fix it for VS Coverage

Action items:
- count skipped files (due to indexing/language) and print them in the statistics
- add a new analysis parameter to be passed to the plugin via the scanner (e.g. `sonar.cs.vscoveragexml.rootfolder` or `sonar.cs.coverage.rootfolder`) and try to use that as a replacement for `_` . However, the docs for [SourceRoot](https://github.com/dotnet/sourcelink/blob/master/docs/README.md#sourceroot) say that it's 

>Item group that lists all source roots that the project source files reside under and their mapping to source control server URLs. This includes both source files under source control as well as source files in source packages.

I need to understand what that means, first.

- when seeing the `\_\` or `/_/` pattern inside a path in `org/sonar/plugins/dotnet/tests/VisualStudioCoverageXmlReportParser.java`, count them separately, and write a WARN message that `DeterministicSourcePaths` may be turned on, and that the special parameter must be passed for code coverage to work

**Comment by andrei-epure-sonarsource** [comment]
Actually, before any action, I need to read what coverlet did to support this https://github.com/coverlet-coverage/coverlet/pull/863 and https://github.com/dotnet/roslyn/issues/43476.

**Comment by andrei-epure-sonarsource** [comment]
SourceRoot

[InitializeSourceRootMappedPaths](https://github.com/dotnet/roslyn/blob/8637000fc35f01a453349147b71d5ecdae8d0bff/src/Compilers/Core/MSBuildTask/Microsoft.Managed.Core.targets#L183) - This target collects all SourceRoots from various sources.

Work done on Coverlet:
- Fix deterministic build+source link bug https://github.com/coverlet-coverage/coverlet/pull/895
- remove the hack for 3.1.300+ SDK https://github.com/coverlet-coverage/coverlet/pull/965
- see [Coverage.cs#L385](https://github.com/coverlet-coverage/coverlet/blob/master/src/coverlet.core/Coverage.cs#L385) and [GetSourceLinkUrl](https://github.com/coverlet-coverage/coverlet/blob/b63ab2adf7970fe074232622cb58ae1928aa7717/src/coverlet.core/Coverage.cs#L449)

Other links
- how to [enable SourceLink](https://lurumad.github.io/using-source-link-in-net-projects-and-how-to-configure-visual-studio-to-use-it)
- pre .NET Core SDK 3.1.300 needs [a hack](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/DeterministicBuild.md)
- [interesting comment](https://github.com/coverlet-coverage/coverlet/issues/951#issuecomment-708019108) on what could go wrong when using .NET Framework

**Comment by andrei-epure-sonarsource** [comment]
hi @iamwyza  - did you have the chance to test the Scanner for MSBuild with deterministic source paths enabled for your project(s)?

**Comment by TimHess** [comment]
@andrei-epure-sonarsource  I updated Steeltoe to use the latest package but I'm still seeing 0% coverage in SonarCloud ([sample build](https://dev.azure.com/SteeltoeOSS/Steeltoe/_build/results?buildId=4815&view=logs&j=a6da9520-a2a0-5057-d4d2-19a633f87e36&t=466cb378-52eb-5cb1-1a29-c5524331e903))

The SonarScanner Context says `C# Code Quality and Security 8.16.0.25740 (csharp)`

I'd be happy to provide any additional info or try things out

**Comment by andrei-epure-sonarsource** [comment]
Hi @TimHess , thanks a lot for the feedback. We currently support Deterministic Builds with VS Coverage reports. I updated the release notes for clarity now.

I saw in your logs that you're using OpenCover reports. I've opened #3976 to close this gap. I added a note in the issue to ask you after the release that all works well.

**Comment by mrt181** [comment]
Hi, I am still facing this issue. See my report here: [SourceLink breaks coverage report generation](https://community.sonarsource.com/t/sourcelink-breaks-coverage-report-generation/85321)
