### ISSUE TITLE
S2583: FP when using the new "using statement" from C# 8

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#3374]
### Description

FP (S2583) when using the new "using statement" from C# 8.

### Repro steps

```
public static void Main()
{
    using var resource = GetNullResource();

    if (resource == null) // Noncompliant - FP resource can be null
    { throw new Exception(); }
//  ^^^^^^^^^^^^^^^^^^^^^^^^^^ Secondary
}

private static IDisposable GetNullResource() => null;
```

### Expected behavior

The issue (_Change this condition so that it does not always evaluate to 'false'; some subsequent code is never executed._) should not be raised since the resource can be null.

### Actual behavior

FP for S2583 (`ConditionEvaluatesToConstant`) is raised

### Known workarounds

Replace using statement with `using ( var resource = GetNullResource())`

Issue is reproducible on 8.8 master.

**Comment by costin-zaharia-sonarsource** [comment]
The source of the problem can be found on `SymbolicValueConstraints.SetConstraint` https://github.com/SonarSource/sonar-dotnet/blob/master/sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/Constraints/SymbolicValueConstraints.cs#L71

Together with DisposableConstraint, ObjectConstraint.NotNull is added by default and this is wrong when disposable statements are used.

**Comment by andrei-epure-sonarsource** [comment]
wow that's so hidden
