### ISSUE TITLE
S4261 should not report for SignalR hub methods

### ISSUE THREAD

**Issue by neolution-ch** [SonarSource/sonar-dotnet#3378]
Similar to solved issue #1875 (Fix S4261: rule should not report for MVC controller methods) it would be great to have SonarSource not reporting when a SignalR hub method does not have the "Async" suffix.

**Comment by costin-zaharia-sonarsource** [comment]
Hi @neolution-ch

I'm trying to get a better understanding of what's needed here and I have a few questions:
- the desired change is to consider the types derived from `Microsoft.AspNetCore.SignalR.Hub` an exception and not raise issues for their public methods?
- why is this needed?

Thank you,
Costin

**Comment by neolution-ch** [comment]
> the desired change is to consider the types derived from Microsoft.AspNetCore.SignalR.Hub an exception and not raise issues for their public methods?

That was my intention when I was writing this issue, because I assumed all SignalR hub methods return a `Task`, so they are always async. I'm not sure anymore after reading the docs. Is it possible to return other types that are not wrapped in `Task`? I haven't had time yet to test it and in our code, all the methods do return `Task`.

> why is this needed?

If all SignalR hub methods require to return a `Task` it would mean that they are always asynchronous. This is what I assumed and based on that I thought we could spare the `Async` suffix for every method in these classes because it would already be clear when you call a SignalR hub method, it is always async.

**Comment by costin-zaharia-sonarsource** [comment]
Hi @neolution-ch 

> Is it possible to return other types that are not wrapped in `Task`?
Yes, that it possible but it's not a problem in our case.

I think the issue makes sense and, since the hubs are very similar with controllers, we should be consistent and not raise S4261.

Thanks!

**Comment by andrei-epure-sonarsource** [comment]
In addition, it's also worth mentioning what [the official docs](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-3.1) say:

> The Async suffix isn't stripped from the method name. Unless your client method is defined with .on('MyMethodAsync'), you shouldn't use MyMethodAsync as a name.
