### ISSUE TITLE
Improve SE performance for a long OR chain condition

### ISSUE THREAD

**Issue by franciscodua** [SonarSource/sonar-dotnet#3395]
### Description

Some files take forever to be analyzed under specific patterns. It appears to be related to multiple bitwise `OR` operations inside an if condition.

### Repro steps

```csharp
namespace Test
{
    public enum Helper
    {
        A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P
    }
    public static class Test
    {
        public static void TestStuff()
        {
            var helper = Helper.A;
            if (helper == Helper.A | helper == Helper.B | helper == Helper.C | helper == Helper.D |
               helper == Helper.E | helper == Helper.F | helper == Helper.G | helper == Helper.H |
               helper == Helper.I | helper == Helper.A | helper == Helper.B | helper == Helper.C |
               helper == Helper.D | helper == Helper.E | helper == Helper.F | helper == Helper.G |
               helper == Helper.H | helper == Helper.I | helper == Helper.A | helper == Helper.B | 
               helper == Helper.C | helper == Helper.D | helper == Helper.E | helper == Helper.F |
               helper == Helper.G | helper == Helper.H | helper == Helper.I)
            {
                System.Console.WriteLine("");
            }
        }
    }
}

```

**Note:** There's a bit of repetition but the idea is the number of bitwise ORs.
This file is not being analyzed when using these rules: S2259, S3655, S1944, S2583.

### Known workarounds

- Either disabling these patterns
- Removing some of the ORs (it seems that half of these bitwise ORs doesn't fail)
- Assigning the result of the expression to a variable before the if
- Changing the bitwise OR (`\`) by an OR (`||`)

### Related information

* C#
* SonarAnalyzer.CSharp: 8.7.0.17535

**Comment by pavel-mikula-sonarsource** [comment]
Hi @franciscodua,

Thank you for reporting this case. All rules are based on Symbolic Execution so the problem will be somewhere there. From a rough estimate, there are about 2^27 = 134217728 paths to explore in this case.

**Comment by costin-zaharia-sonarsource** [comment]
Theoretically, the exploration should [stop after 1500 steps](https://github.com/SonarSource/sonar-dotnet/blob/8001d7e1e591e11db1c7c6787987884f7dbb9545/sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/Common/AbstractExplodedGraph.cs#L35). We need to investigate what is causing this slowness.
