### ISSUE TITLE
S3900 FP: when parameter reassigned from a method

### ISSUE THREAD

**Issue by s-kip** [SonarSource/sonar-dotnet#3400]
### Description

The rule S3900 raises on an out parameter in a function after assigned with a new instance of an object.

### Repro steps

I have a class with a static method to create a new instance:

    public class MyClass
    {
        public int SomeProperty { get; set; }

        public static MyClass Create()
        {
            return new MyClass();
        }
    }

And I have a function with a out parameter of type `MyClass`:

    public class MyOtherClass
    {
        public bool TryGetMyClass(int i, out MyClass myClass)
        {
            myClass = null;

            if (i > 1)
            {
                return false;
            }

            myClass = MyClass.Create();
            myClass.SomeProperty = 10;

            return true;
        }
    }

### Expected behavior

No rule raises on the line `myClass.SomeProperty = 10`

### Actual behavior

The rule S3900 raises on the line `myClass.SomeProperty = 10` for `myClass`.
It also raises with SonarLint in Visual Studio:
![grafik](https://user-images.githubusercontent.com/43069339/85669420-1a555f00-b6c0-11ea-95cd-28d357047fb9.png)

### Known workarounds

None.
The behavior didn't change if I move the `myClass = null` into the if-clause.

### Related information

* SonarQube 8.2.0.32929
* C# Analyzer 8.6 (build 16497)
* VS 2019 16.6.2
* SonarLint 4.22.0.18519
* dotnet 3.1.301

**Comment by tbutler-qontigo** [comment]
Are there any plans to address this issue?  It has been outstanding for about two years now.
Thanks

**Comment by pavel-mikula-sonarsource** [comment]
We plan to address this in next 2 months. The rule runs on Symbolic Execution engine that we're rewriting from scratch.
