### ISSUE TITLE
The bug of undetected null pointer caused by case number

### ISSUE THREAD

**Issue by 93910676wangd** [SonarSource/sonar-dotnet#3404]
### Description
When the number of cases is less than or equal to 16 (excluding default), it can be detected that the variable type is null（'type' is null on at least one execution path）,

But when the number of cases is greater than or equal to 17, the problem that the variable type is null cannot be detected.（'type' is null on at least one execution path）

Why is that? Please let us know the solution or reason. Thank you very much.

![Case-16-OK](https://user-images.githubusercontent.com/19505572/85848493-cfc90500-b7db-11ea-9b44-e007284923ac.png)
![Case-17-NG](https://user-images.githubusercontent.com/19505572/85848498-d192c880-b7db-11ea-91e2-36462cc9ad0d.png)
sonarqubu：Community Edition 8.3.1 (build 34397)
plugin：sonar-csharp-plugin-8.6.1.17183.jar
lang:c#.net

**Comment by 93910676wangd** [comment]
Nobody help me？

**Comment by costin-zaharia-sonarsource** [comment]
Hi @93910676wangd 

[S3655](https://rules.sonarsource.com/csharp/RSPEC-3655) rule is executed by our [symbolic execution](https://en.wikipedia.org/wiki/Symbolic_execution) engine which explores all the possible paths to see how a variable is used. For very long methods the performance degrades significantly and we decided to stop the exploration after a fixed number of steps and it seems that this method hits that limit.
