### ISSUE TITLE
Fix S1128 FP: System namespace is needed for tuple deconstruction

### ISSUE THREAD

**Issue by RobertSimonsSMA** [SonarSource/sonar-dotnet#3408]
### Description

The Rule S1128 marks "using System" with "Remove this unnecessary 'using'. While Deconstructor of System.Tuple in foreach loop depends on it.

### Repro steps
Analyze attached classes with rule S1128 enabled
[SonarRuleS1128AndDeconstructedTuples.zip](https://github.com/SonarSource/sonar-dotnet/files/4862943/SonarRuleS1128AndDeconstructedTuples.zip)

### Expected behavior

Since the compiler needs "using System" to find System.TupleExtensions.Deconstruct, it is expected that Rule S1128 does not mark the using as unneccessary in ClassUsingSystemNamespace.

### Actual behavior

Rule S1128 marks "using System" with "Remove this unnecessary 'using'." in ClassUsingSystemNamespace

### Known workarounds

Do not deconstruct inside the foreach statement header, but instead deconstruct inside the statement body.
E.g: 
// ..
foreach (var tuple  in inputs) {
   var (x, y) = tuple;
   // .. do stuff
}

### Related information
Reproduced using
 * Visual Studio 2019 
 * NuGet package SonarAnalyzer.CSharp 8.9.0.19135 target framework 4.7.2
 * C# Project  with target framework .net 4.7.2 and C# Version 7.3
 * Windows 10 / 1809

**Comment by costin-zaharia-sonarsource** [comment]
Hi @RobertSimonsSMA,

thanks for the feedback. 

I can confirm the issue. We should not raise a warning in this case since `using System` is needed for tuple deconstruction.
