### ISSUE TITLE
Fix ConstructorArgumentValueShouldExistTest WPF support

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#3425]
Some tests, like `ConstructorArgumentValueShouldExistTest` reference `WPF` types and currently cannot be run while targeting .Net Core.

**Comment by pavel-mikula-sonarsource** [comment]
We'll need to reference Assembly System.Xaml, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 that is stored in a separate pack:
```
C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\5.0.0\ref\net5.0\System.Xaml.dll
```

Dirty solution could be to reference the assembly based on relative path `..\..\..\..\..\packs\Microsoft.WindowsDesktop.App.Ref\5.0.0\ref\net5.0\System.Xaml.dll`

A clean solution would be to create another UT project with
```
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
```

**Comment by pavel-mikula-sonarsource** [comment]
Or we can just fake it 😆
