### ISSUE TITLE
Add WinForms support in unit tests when targeting .Net Core

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#3426]
Some tests, like `DoNotCallExitMethodsTest` reference `WinForms` types and currently cannot be run while targeting .Net Core.

**Comment by andrei-epure-sonarsource** [comment]
Also see `PropertiesAccessCorrectFieldTest`

**Comment by pavel-mikula-sonarsource** [comment]
Also `MarkWindowsFormsMainWithStaThread` for noncompliant example of TopLevelStatements

**Comment by csaba-sagi-sonarsource** [comment]
`PropertiesAccessCorrectFieldTest` needs WPF support, #4883 was created to add supprot for WPF.

**Comment by pavel-mikula-sonarsource** [comment]
WPF support can be scaffolded the same way as it is in #4765
