### ISSUE TITLE
S3928 reports "the parameter name '<my param>'  is not declared in the argument list" and that doesnt make sense

### ISSUE THREAD

**Issue by StingyJack** [SonarSource/sonar-dotnet#3444]
### Description
I get an S3928 when trying to throw an `ArgumentOutOfRangeException` as depicted in this screencap. 

![image](https://user-images.githubusercontent.com/15381181/87619177-948a6980-c6e9-11ea-842b-9b744830a7e3.png)

Its seems to be the more appropriate exception since I'm reporting that the specified row and column are apparently not in the range of column headers in the worksheet. If I change this to `ArgumentNullException` or `ArgumentException` I dont get the violation, but they arent as appropriate.  

I think the message is referring to the arguments I'm specifying for the constructor, but I've clearly got the that parameter in the constructor, so I dont know if the rule is bugged or the message is trying to tell me something else. This and other rule problems (and that I cant configure them globally, a week of this and so sick of editorconfig churn in every solution) have lead me to the workaround of just disabling the extension for now. 

### Related information

* C#/VB.NET Plugins Version   
4.23.0.19399

* Visual Studio Version  
16.6.3

* MSBuild / dotnet version  
net472

* Operating System 
Windows 10 18363

**Comment by pavel-mikula-sonarsource** [comment]
Hi @StingyJack ,

I'm unfortunately unable to reproduce the issue with the piece of code you've provided. Can you please share one more line of your code where/how the argument `columnIndex` is declared in your constructor? Or create a minimal reproducible scenario?

Are you sure your line of code isn't embedded inside a lambda?

I've tried:
```
public class Repro
{
    public Repro(int columnIndex, int rowIndex)
    {
        throw new ArgumentOutOfRangeException(nameof(columnIndex), $"Cannot find {columnIndex} message {rowIndex}");
    }
}
```

**Comment by StingyJack** [comment]
Its not in a constructor, and its not a parameter. Here is a bit more context and an expanded example that should help. 

The function's intention is to get the column header indexes for each text label (in case the user re-orders columns)
`ExcelWorkbook inputSheet` is a function parameter. 
`int columnHeaderRowIndex` is a local variable that gets a value of either 1,2, or 3 depending on what worksheet is being read

``` csharp

for (var columnIndex = 1; columnIndex <= inputSheet.Dimension.Columns; columnIndex++)
{
	var headerCell = inputSheet.Cells[columnHeaderRowIndex, columnIndex];
	if (headerCell.Value == null)
	{
		throw new ArgumentOutOfRangeException(nameof(columnIndex), $"Unable to find any value to use for header matching at row {columnHeaderRowIndex} and col {columnIndex}");
	}
       ...
```

**Comment by pavel-mikula-sonarsource** [comment]
In that case, the rule S3928 behaves as expected and the issue should be raised here. The [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception?view=netcore-3.1)  states that

>The exception that is thrown when the value of an argument is outside the allowable range of values as defined by the invoked method.

so this exception should only be used when the method's argument value is out of range. Also the `paramName` argument refers to the parameter of current method.

`IndexOutOfRangeException` would be more appropriate exception in your case.

**Comment by StingyJack** [comment]
Then I would expect the same if I replaced that exception with ArgumentException, but that exception type does not trigger the warning.

**Comment by pavel-mikula-sonarsource** [comment]
`ArgumentException` in this sample triggers the warning as expected:
```C# 
var columnIndex = 0;
throw new ArgumentException($"Cannot find {columnIndex} message {rowIndex}", nameof(columnIndex));
```
The `paramName` is a second argument in this class contrary `ArgumentOutOfRangeException`.

Please share your sample if you have some scenario that doesn't behave as expected.
