### ISSUE TITLE
False positive on S4462 when using WhenAll

### ISSUE THREAD

**Issue by DrDelete** [SonarSource/sonar-dotnet#3452]
### Description

To get a better performance when reading several web services, I kick off several tasks. I use the WhenAll function to wait until all tasks are completed. Then I take the result out of each task.

The Sonar marks the read of the result as a S4462 violation which is a false positive; it is safe to read the contents of the task because each task is completed.

### Repro steps

```
using System;
using System.Threading.Tasks;

namespace S4462_reproduce_step
{
    public static class Program
    {
        static async Task Main(string[] args)
        {
            var getValue1Task = GetValue1Async();
            var getValue2Task = GetValue2Async();

            await Task.WhenAll(getValue1Task, getValue2Task).ConfigureAwait(false);

            var result1 = getValue1Task.Result;
            var result2 = getValue2Task.Result;

            Console.WriteLine($"Result of task 1: {result1}, result of task 2: {result2}.");
        }

        public static Task<int> GetValue1Async()
        {
            return Task.FromResult(1);
        }
        public static Task<int> GetValue2Async()
        {
            return Task.FromResult(2);
        }

    }
}
```

### Expected behavior

No Sonar S4462 violation (blocker)

### Actual behavior

Sonar S4462 violation (blocker)

### Known workarounds

Suppress the warning, but that should not be done, because of a false positive.

### Related information

* C#
* Visual Studio Version: 2019 Enterprise
* MSBuild / dotnet version: .NET Core 3.1
* Sonar Qube 6.7 (build 33306)
* Operating System: Win10 Pro 1909

**Comment by costin-zaharia-sonarsource** [comment]
Hi @DrDelete,

thanks for the feedback. I can confirm the issue. Indeed, when `var result1 = getValue1Task.Result;` is executed, the value is safe to read since the task is completed.
