### ISSUE TITLE
"Constructor has 8 parameters, which is greater than the 7 authorized"  for .NET Core framework class constructors

### ISSUE THREAD

**Issue by Shyam268** [SonarSource/sonar-dotnet#3459]
This issue is reported many times .NET core framework class constructors due to DI.

**Comment by andrei-epure-sonarsource** [comment]
Please provide:
- version of SQ
- version of SonarCSharp plugin
- a reproducer

**Comment by Shyam268** [comment]
SQ version - 7.9 LTS
SonarCSharp plugin version - 5.11.0

**Comment by andrei-epure-sonarsource** [comment]
I'm afraid we cannot do anything with this ticket if you don't provide the actual problem that you're facing with a reproducer (snippet of code that we can reproduce the problem with).

Also, please update to the latest SonarCSharp plugin - 8.10, before posting this.

**Comment by costin-zaharia-sonarsource** [comment]
Hi @Shyam268,

This rule (https://rules.sonarsource.com/csharp/RSPEC-107) is configurable. By default the maximum number of parameters is 7 but this can be changed in SoarQube.

**Comment by Shyam268** [comment]
Code snippet to reproduce the problem:

`public sealed class ExampleService : IExampleService 
	{
		private readonly IService1 m_service1;
		private readonly IService2 m_service2;
		private readonly IService3 m_service3;
		private readonly IService4 m_service4;
		private readonly IService5 m_service5;
		private readonly IService6 m_service6;
		private readonly IService7 m_service7;
		private readonly IService8 m_service8;

		public ExampleService(
			IService1 service1,
			IService2 service2,
			IService3 service3,
			IService4 service4,
			IService5 service5,
			IService6 service6,
			IService7 service7,
			IService8 service8)
		{
			m_service1 = service1;
			m_service2 = service2;
			m_service3 = service3;
			m_service4 = service4;
			m_service5 = service5;
			m_service6 = service6;
			m_service7 = service7;
			m_service8 = service8;
		}
            }`
This ExampleService requires 8 Services. Sonar Cube allows maximum of 7 parameters and reports an error that '**Constructor has 8 parameters, which is greater than the 7 authorized.**'
note: We are using dotnet Sonar scanner [https://www.nuget.org/packages/dotnet-sonarscanner/](url) to publish sonar cube data to the server
We are in situation that [https://github.com/SonarSource/sonar-dotnet/issues/1015](url)

**Comment by Shyam268** [comment]
How can i change this rule settings. ?

**Comment by pavel-mikula-sonarsource** [comment]
@Shyam268 Please refer to your https://community.sonarsource.com/ to get help with your question.
