### ISSUE TITLE
Can not add the same measure twice on [moduleKey=...]

### ISSUE THREAD

**Issue by bmorenc** [SonarSource/sonar-dotnet#3466]
We are seeing a java.lang.UnsupportedOperationException: Can not add the same measure twice...

As mentioned in the releted post we are on an older version so currently this is not easy for us to test the latest scanner nor for you to issue a patch on 7.17 of the scanner because it's out of support. However, you may check the code referenced below for exception handling while saving metrics to mitigate the risk of multiple plugins adding the same metric for a given file.

I wanted to explore any option of a workaround such as any way to control the plugin scanner execution from the command line.  The conflict in our environment is with coverity-sonar-plugin and it has the exception handling on save of the metric so if I could force the coverity plugin to run last, I could potentially mitigate this issue.

Any thoughts are greatly appreciated.  I will update here as well if/when we upgrade to a supported version.

Best regards,
Bryan

[Original post in related issue](https://github.com/SonarSource/sonar-dotnet/issues/838#issuecomment-663288666)

[MetricsImporter not catching exception](https://github.com/SonarSource/sonar-dotnet/blob/8bc919e7bd6dc0cb71433aac48d7674a3c12fe2b/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporter.java#L81)

**Comment by andrei-epure-sonarsource** [comment]
Ok, from what I can see from here, we can look if the MetricsImporter should catch exceptions or not. If we cannot import metrics, I believe we may want a hard failure, but we'll need to clarify this.

**Comment by bmorenc** [comment]
I can understand a desire to give 1st party plugins the priority on metrics. In that case (and maybe the later versions already work like this) you’d want to ensure the order of execution of installed plugins always puts the 1st party first.  Or get more fancy and have all plugins register the metrics they populate and provide the administrative interface to configure priorities. 

If there is any way for me to force the order of scanners on the command line I would love to know that.

**Comment by andrei-epure-sonarsource** [comment]
Hi @bmorenc , I will close this issue as there's nothing we will do on our plugin side.

I will mention the "force the coverity plugin to run last" idea internally to our product management team. This is not in our hands, anyway, but on the scanner side.

Thanks for letting us know of this situation!
