### ISSUE TITLE
Feed the line of test code metric for SQ >= 8.5

### ISSUE THREAD

**Issue by m-g-sonar** [SonarSource/sonar-dotnet#3467]
With SQ 8.5, we should start to compute the NCLOC (number of line of code) and NCLOC_DATA metrics for test files as well. It is currently only computed for main files. Note that we should feed the metric ONLY for **SQ >= 8.5**, in order to not feed it to SonarCloud.

For reference, SonarQube ticket: https://jira.sonarsource.com/browse/SONAR-13596

**Comment by andrei-epure-sonarsource** [comment]
This is also related to #1355 where there are some hints on how to do this - ProtobufDataImporter.java

**Comment by m-g-sonar** [comment]
Updated on SQ request to also cover NCLOC_DATA metrics

**Comment by m-g-sonar** [comment]
Request dropped by SQ team.
