### ISSUE TITLE
Compute and aggregate coverage for all .Net frameworks added as project target

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#3471]
Currently the test project is targeting both .Net Framework 4.8 and .Net Core 3.1 but the coverage is computed only based on .Net Framework 4.8 tests. 

On the CI pipeline .Net 5 target is added too (although, at this moment, there is no conditional compiled code related to it).

We need to change the build script to run and aggregate the coverage for all these frameworks in order to have a correct representation.

**Comment by andrei-epure-sonarsource** [comment]
this is done now, right @costin-zaharia-sonarsource ?

**Comment by costin-zaharia-sonarsource** [comment]
Yes, this is now done!
