### ISSUE TITLE
S2068 FN - not all custom values are taken into consideration

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#3489]
### Description

S2068 has been fixed in  #3101  to consider the values from SonarQube. However, there has been a regression discovered in #3484 and tested manually as well with SQ 8.4.1.

### Repro steps

1. Install SonarQube 8.4.1 developer edition.
2. Create a new C# Quality Profile (I named it "Sonar++") and modify the S2068 rule to have "password, passwd, pwd, passphrase, senha" as parameters. Make the "Sonar++" profile the default.
3. checkout sonar-dotnet commit 8c00b08e993c5a6da6ed4126c07a3dc9b0100f85
4. Go to `sonar-dotnet\its\projects\DefaultRuleParametersCanBeCustomized`.
5. Run the analysis:
```
SonarScanner.MSBuild.exe begin /k:"customize-rule" /d:sonar.verbose=true
MSBuild.exe /t:Rebuild /maxcpucount /v:d /nr:false /p:DeployExtension=false /warnaserror:AD0001  /clp:Summary .\DefaultRuleParametersCanBeCustomized.sln
SonarScanner.MSBuild.exe end
```

### Expected behavior

There should be 2 raised security hotspots on `DefaultRuleParametersCanBeCustomized.cs` - one at line 6 (for "Password") and one at line 7 ("Senha").

### Actual behavior

There is only one Security hotspot raised on line 7 (Senha).

### Known workarounds

none

### Related information

* C#/VB.NET Plugins Version 8.11
* MSBuild / dotnet version 16.7
* If running through the Scanner for MSBuild, its version 4.8.0.12008
* Operating System Windows 10
* SonarQube 8.4.1 Developer Edition

**Comment by costin-zaharia-sonarsource** [comment]
This seems to be a feature 😄. Please see https://github.com/SonarSource/sonar-dotnet/issues/2868.
