### ISSUE TITLE
False Positive unnecessary 'using'

### ISSUE THREAD

**Issue by mitchello** [SonarSource/sonar-dotnet#3587]
### Description
When using Tuple in a C# class/method, the scanner consider the using System as unnecessary.
However Tuple is in System namespace.

### Current Behavior
Code Smell csharpsquid:S1128 is present

### Expected Behavior
No more code smell.
![issue](https://user-images.githubusercontent.com/6321971/92078300-52fb6e00-edbe-11ea-9377-6a895d8e7dbe.png)

**Comment by pavel-mikula-sonarsource** [comment]
Hi @mitchello ,

Thank you for reporting this case, I confirm it's a False Positive. We already have an issue reported for tuple deconstruction in #3408 so I'll close this one. You can follow the previous issue.

**Comment by mitchello** [comment]
@pavel-mikula-sonarsource thank you for your reply.
