### ISSUE TITLE
java.lang.UnsupportedOperationException: Can not add the same measure twice on [key=Calculate]

### ISSUE THREAD

**Issue by dlt-lee** [SonarSource/sonar-dotnet#3596]
### Description

##[section]启动: Complete SonsrQube analysis
==============================================================================
Task         : 命令行
Description  : 在 Linux 和 macOS 上使用 Bash、在 Windows 上使用 cmd.exe 运行命令行脚本
Version      : 2.151.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
正在生成脚本。
========================== Starting Command Output ===========================
##[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "E:\vsts-agent-win-x64-2.153.1\_work\_temp\c2f86674-1c4c-45a7-a00d-302f4b5011ec.cmd""
Write your commands here
Use the environment variables input below to pass secret variables to this script
SonarScanner for MSBuild 4.10
Using the .NET Framework version of the Scanner for MSBuild
Post-processing started.
09:56:51.46  Fetching code coverage report information from TFS...
09:56:51.462  Attempting to locate a test results (.trx) file...
09:56:51.574  Looking for TRX files in: E:\vsts-agent-win-x64-2.153.1\_work\2\TestResults, E:\vsts-agent-win-x64-2.153.1\_work\2\s\TestResults
09:56:51.575  The following test results files were found: E:\vsts-agent-win-x64-2.153.1\_work\2\s\TestResults\LIZHUO-GUST$_LIZHUO-GUST_2020-09-07_09_55_05.trx
09:56:51.695  The following code coverage attachments were found from the trx files: E:\vsts-agent-win-x64-2.153.1\_work\2\s\TestResults\LIZHUO-GUST$_LIZHUO-GUST_2020-09-07_09_55_05\In\LIZHUO-GUST\LIZHUO-GUST$_LIZHUO-GUST 2020-09-07 09_54_56.coverage
09:56:51.697  Found corresponding Binary-to-XML conversion output file for E:\vsts-agent-win-x64-2.153.1\_work\2\s\TestResults\LIZHUO-GUST$_LIZHUO-GUST_2020-09-07_09_55_05\In\LIZHUO-GUST\LIZHUO-GUST$_LIZHUO-GUST 2020-09-07 09_54_56.coverage, no conversion will be attempted.
Calling the SonarQube Scanner...
INFO: Scanner configuration file: E:\vsts-agent-win-x64-2.153.1\_work\_tasks\SonarQubePrepare_15b84ca1-b62f-4a2a-a403-89b77a063157\4.11.0\classic-sonar-scanner-msbuild\sonar-scanner-4.4.0.2170\bin\..\conf\sonar-scanner.properties
INFO: Project root configuration file: E:\vsts-agent-win-x64-2.153.1\_work\2\.sonarqube\out\sonar-project.properties
INFO: SonarScanner 4.4.0.2170
INFO: Java 11.0.5 Oracle Corporation (64-bit)
INFO: Windows 10 10.0 amd64
INFO: User cache: C:\Windows\ServiceProfiles\NetworkService\.sonar\cache
INFO: Scanner configuration file: E:\vsts-agent-win-x64-2.153.1\_work\_tasks\SonarQubePrepare_15b84ca1-b62f-4a2a-a403-89b77a063157\4.11.0\classic-sonar-scanner-msbuild\sonar-scanner-4.4.0.2170\bin\..\conf\sonar-scanner.properties
INFO: Project root configuration file: E:\vsts-agent-win-x64-2.153.1\_work\2\.sonarqube\out\sonar-project.properties
INFO: Analyzing on SonarQube server 7.9.4
INFO: Default locale: "zh_CN", source code encoding: "GBK" (analysis is platform dependent)
INFO: Load global settings
INFO: Load global settings (done) | time=112ms
INFO: Server id: A7EE8CF2-AXQfwJBfz1J1AgEu8hkW
INFO: User cache: C:\Windows\ServiceProfiles\NetworkService\.sonar\cache
INFO: Load/download plugins
INFO: Load plugins index
INFO: Load plugins index (done) | time=75ms
INFO: Load/download plugins (done) | time=167ms
WARN: Plugin SonarQube CNES Report [cnesreport] uses a child first classloader which is deprecated
INFO: Process project properties
INFO: Execute project builders
INFO: Execute project builders (done) | time=73ms
INFO: Project key: Calculate
INFO: Base dir: E:\vsts-agent-win-x64-2.153.1\_work\2\s
INFO: Working dir: E:\vsts-agent-win-x64-2.153.1\_work\2\.sonarqube\out\.sonar
INFO: Load project settings for component key: 'Calculate'
INFO: Load project settings for component key: 'Calculate' (done) | time=25ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=46ms
INFO: Detected Azure DevOps
INFO: Load active rules
INFO: Load active rules (done) | time=669ms
WARN: SCM provider autodetection failed. Please use "sonar.scm.provider" to define SCM of your project, or disable the SCM Sensor in the project settings.
INFO: Indexing files...
INFO: Project configuration:
INFO: Indexing files of module 'CalculateTest'
INFO:   Base dir: E:\vsts-agent-win-x64-2.153.1\_work\2\s\01_Calculator\CalculateTest
INFO:   Test paths: CalculateTest.cs, Properties/AssemblyInfo.cs, App.config, packa...
INFO: Load project repositories
INFO: Load project repositories (done) | time=21ms
INFO: Indexing files of module 'Calculate'
INFO:   Base dir: E:\vsts-agent-win-x64-2.153.1\_work\2\s\01_Calculator\Calculate
INFO:   Test paths: Calculate.cs, Properties/AssemblyInfo.cs, App.config, packages....
INFO: Indexing files of module 'Calculate'
INFO:   Base dir: E:\vsts-agent-win-x64-2.153.1\_work\2\s
INFO:   Source paths: 01_Calculator/packages/NUnit3TestAdapter.3.17.0/build/net35/N...
INFO: 13 files indexed
INFO: Quality profile for cs: SourceMeter C#
INFO: ------------- Run sensors on module Calculate
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=46ms
WARNING: WARNING: An illegal reflective access operation has occurred
WARNING: WARNING: Illegal reflective access by net.sf.cglib.core.ReflectUtils$1 (file:/C:/Windows/ServiceProfiles/NetworkService/.sonar/cache/866bb1adbf016ea515620f1aaa15ec53/sonar-javascript-plugin.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: WARNING: Please consider reporting this to the maintainers of net.sf.cglib.core.ReflectUtils$1
WARNING: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: WARNING: All illegal access operations will be denied in a future release
INFO: Sensor C# Properties [csharp]
INFO: Sensor C# Properties [csharp] (done) | time=4ms
INFO: Sensor JavaXmlSensor [java]
INFO: Sensor JavaXmlSensor [java] (done) | time=1ms
INFO: Sensor com.sourcemeter.analyzer.csharp.batch.SourceMeterCSharpSensor [SourceMeterAnalyzercsharp]
INFO:       Graph: E:\vsts-agent-win-x64-2.153.1\_work\2\s\01_Calculator\Calculate\result\Calculate_Calculate_F3B778E0-5434-4006-882F-04B3FA45F5C4\csharp\2020-09-07-09-56-58\Calculate_Calculate_F3B778E0-5434-4006-882F-04B3FA45F5C4.graph
INFO:       * Initialization...
INFO:       * Initialization done: 6 ms
INFO:       * Processing LogicalTree...
INFO:       * Processing LogicalTree done: 0 ms
INFO:       * Processing PhysicalTree...
INFO:       * Processing PhysicalTree done: 0 ms
INFO:       * Saving LogicalTree...
INFO:       * Saving LogicalTree done: 8 ms
INFO:       * Saving CloneTree...
INFO:       * Saving CloneTree done: 0 ms
INFO:     Load data from graph bin and save resources and metrics done: 114 ms
INFO: Sensor com.sourcemeter.analyzer.csharp.batch.SourceMeterCSharpSensor [SourceMeterAnalyzercsharp] (done) | time=23382ms
INFO: Sensor JaCoCo XML Report Importer [jacoco]
INFO: Sensor JaCoCo XML Report Importer [jacoco] (done) | time=4ms
INFO: ------------- Run sensors on module CalculateTest
INFO: Sensor C# Properties [csharp]
INFO: Sensor C# Properties [csharp] (done) | time=1ms
INFO: Sensor JavaXmlSensor [java]
INFO: Sensor JavaXmlSensor [java] (done) | time=0ms
INFO: Sensor com.sourcemeter.analyzer.csharp.batch.SourceMeterCSharpSensor [SourceMeterAnalyzercsharp]
INFO:       Graph: E:\vsts-agent-win-x64-2.153.1\_work\2\s\01_Calculator\CalculateTest\result\Calculate_Calculate_A73CAEDE-6908-48AE-9277-9EC231138B77\csharp\2020-09-07-09-57-21\Calculate_Calculate_A73CAEDE-6908-48AE-9277-9EC231138B77.graph
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 51.714s
INFO: Final Memory: 12M/44M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarScanner execution
java.lang.UnsupportedOperationException: Can not add the same measure twice on [key=Calculate]: DefaultMeasure[component=[key=Calculate],metric=Metric[id=<null>,key=SM:csharp_license,description=<null>,type=STRING,direction=0,domain=<null>,name=C# license,qualitative=false,userManaged=false,enabled=true,worstValue=<null>,bestValue=<null>,optimizedBestValue=false,hidden=true,deleteHistoricalData=false,decimalScale=<null>],value={"full":["Duplicated Code","FxCop","MetricHunter","Metrics"],"limited":[],"inactive":[]},fromCore=false]
	at org.sonar.scanner.sensor.DefaultSensorStorage.saveMeasure(DefaultSensorStorage.java:172)
	at org.sonar.scanner.sensor.DefaultSensorStorage.store(DefaultSensorStorage.java:132)
	at org.sonar.api.batch.sensor.measure.internal.DefaultMeasure.doSave(DefaultMeasure.java:95)
	at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:45)
	at com.sourcemeter.analyzer.base.batch.SourceMeterSensor.saveLicense(SourceMeterSensor.java:220)
	at com.sourcemeter.analyzer.csharp.batch.SourceMeterCSharpSensor.saveLicense(SourceMeterCSharpSensor.java:160)
	at com.sourcemeter.analyzer.csharp.batch.SourceMeterCSharpSensor.loadDataFromGraphBin(SourceMeterCSharpSensor.java:172)
	at com.sourcemeter.analyzer.csharp.batch.SourceMeterCSharpSensor.execute(SourceMeterCSharpSensor.java:130)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:400)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:395)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:392)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
ERROR: 
The SonarQube Scanner did not complete successfully
09:57:43.988  Post-processing failed. Exit code: 1
##[error]Cmd.exe 已退出，代码为“1”。
##[section]完成: Complete SonsrQube analysis

### Repro steps
------Calculate.sln
  |----Calculate.csproj
  |----CalculateTest.csproj
Sonarqube+SourceMeter
SonarScanner.MSBuild.exe begin /k:"Calculate" /n:"Calculate" /v:"1.0" /d:sm.csharp.input=../Calculate.sln

### Expected behavior

No excdeption

### Actual behavior

java.lang.UnsupportedOperationException: Can not add the same measure twice on [key=Calculate]: DefaultMeasure[component=[key=Calculate],metric=Metric[id=<null>,key=SM:csharp_license,description=<null>,type=STRING,direction=0,domain=<null>,name=C# license,qualitative=false,userManaged=false,enabled=true,worstValue=<null>,bestValue=<null>,optimizedBestValue=false,hidden=true,deleteHistoricalData=false,decimalScale=<null>],value={"full":["Duplicated Code","FxCop","MetricHunter","Metrics"],"limited":[],"inactive":[]},fromCore=false]

### Known workarounds

SourMeter generate two folder for calculte and calculateTest. SoanQube will trow exception when pasering these two result folder
Success:graph: E:\vsts-agent-win-x64-2.153.1\_work\2\s\01_Calculator\Calculate\result\
Failed:Graph: E:\vsts-agent-win-x64-2.153.1\_work\2\s\01_Calculator\CalculateTest\result\

### Related information

* C#/VB.NET Plugins Version
* Visual Studio Version:VS2019
* MSBuild / dotnet version
* If running through the Scanner for MSBuild, its version:4.10
* Operating System win10

**Comment by andrei-epure-sonarsource** [comment]
hi @dlt-lee , sorry for the delay. did you manage to find the isuse?

**Comment by andrei-epure-sonarsource** [comment]
I am closing this, as I didn't get an answer.

If you encounter errors with setting up SQ analysis, please open a ticket on our forum in the Get Help category  https://community.sonarsource.com/c/help/8 , as we mention in our README: https://github.com/SonarSource/sonar-dotnet#do-you-have-a-question-or-feedback

As a general remark: this sort of exception can happen when you have multiple SonarQube plugins that try to provide the same measure for a particular language. By default, SQ comes with our SonarCSharp and SonarVB analyzers. If you try and use a 3rd party analyzer that provides the same measures for C# and/or VB .NET  that our analyzers provide, you will get an exception. We expect from 3rd party analyzers to provide only issues, not measures.
