### ISSUE TITLE
Improve S2971 message to use AsEnumerable in LINQ database query

### ISSUE THREAD

**Issue by mitchello** [SonarSource/sonar-dotnet#3604]
### Description

S2971

When calling ToList or ToArray in the middle of a LINQ chain, the rule raised, which is correct in a way but there is an exception that should be managed. When using Entity Framework Core (3.x), it's recommended to manage data on client side as some features can't be parse into SQL.
See: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client 

### Repro steps

Using EF Core: 
`return portLinq.OrderBy(v => v.Date).ToList().Select(x => new HistoricalValue(x.Date, x.Value)).ToList();`

If we don't retrieve data on client side with the ToList in the middle of the chain, the Select will throw an exception at runtime as it's impossible for EF Core to parse what's in the Select statement.

### Expected behavior

Rule shouldn't be raised

### Actual behavior

Rule raised

**Comment by pavel-mikula-sonarsource** [comment]
Hi @mitchello ,

Can you please provide some small, but complete reproducer for this case? I tried to reproduce it with similar select-to-local-class but EF 3.1.8 handled that without an exception.

**Comment by mitchello** [comment]
Hi @pavel-mikula-sonarsource , you will find a small project reproducing our issue.

[DemoEFCore.zip](https://github.com/SonarSource/sonar-dotnet/files/5259800/DemoEFCore.zip)

Here's some more information regarding this behavior : https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/#linq-overhaul

**Comment by mitchello** [comment]
Hi @pavel-mikula-sonarsource,
Thank you for your answer.

Regards

**Comment by pavel-mikula-sonarsource** [comment]
ToDo: 
* Detect Linq sources of type `DbSet<T>`
* Update message to suggest `AsEnumerable` for first `ToArray` occurance in the middle of the chain.
