### ISSUE TITLE
Add support for VarPattern inside switch expressions

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#3611]
### Description

`VarPattern` inside switch expressions is not supported.

### Repro steps

Build the CFG for the following snippet: `string a = taintedString switch {var x => null};`

A `NotSupportedException` is thrown for the var pattern.

### Related information

* C#/VB.NET Plugins Version: 8.13

**Comment by mary-georgiou-sonarsource** [comment]
SE engine has been rewritten and varpattern is supported there.
We won't support the legacy engine.
