### ISSUE TITLE
CFG generation throws StackOverlowException when syntax tree is too deep

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#3630]
### Description

CFG generation can throw `StackOverlofException` that will break the build of analyzed project.

Project `Lucene.NET` has [a funny file](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Analysis.Common/Analysis/CharFilter/HTMLStripCharFilter.cs) with constants initialized to 1800 string concatenations. When we generate CFG for such syntax node with a very deep structure, it fails on `StackOverflowException`. 

Same problem occurs for all `BinaryExpressionSyntax` (&&, ||, ...). Maximum depth varies on .NET Framework vs .NET Core build.
### Reproducer

Issue is reproducible with simple test:
```C#
[TestMethod]
public void CauseStackOverflow()
{
    const int count = 2000;
    const string dna = "ACGT";
    var concatenations = Enumerable.Repeat($@"""{dna}""", count).JoinStr(" +\n");
    var cfg = Build($"var x = {concatenations};");
    VerifyMinimalCfg(cfg);
    VerifyAllInstructions(cfg.EntryBlock);
}
```

Note: `StackOverflowException` cannot be caught. Failure of the test is visible in Test output window.
### Possible solutions

1. Use Roslyn CFG
2. Validate and limit nesting depth of supported CFG
3. Process BinaryExpressionSyntax in non-recursive way
4. Do both 2. and 3.

### After it's fixed

Once this is fixed, we need to:
* Create issue on SONARSEC side to update `SonarAnalyzer.CFG.dll` version to the latest released
* Remove `SupportedNodeCountLimit` from Sonar-Securify C# FE `ConstructorUcfgBuilder.ProcessInitializerValue`

**Comment by andrei-epure-sonarsource** [comment]
Related to SONARSEC-1471.

**Comment by pavel-mikula-sonarsource** [comment]
[SONARSEC-1832](https://jira.sonarsource.com/browse/SONARSEC-1832) created
