### ISSUE TITLE
The official  Noncompliant demo of  RSPEC-2223 was not recognized by sonarqube

### ISSUE THREAD

**Issue by chucklu** [SonarSource/sonar-dotnet#3653]
### Description
We are using the sonarqube Community EditionVersion 8.4.2 (build 36762)

use the official demo of[ 2223](https://rules.sonarsource.com/csharp/RSPEC-2223), **Non-constant static fields should not be visible**
And it could not be recoginzed.
```C#
 public class Math
    {
        public static double Pi = 3.14;
    }

    public class Shape
    {
        public static Shape Empty = new EmptyShape();

        private class EmptyShape : Shape
        {
        }
    }
```

### Repro steps

just the the above official demo code

### Known workarounds

none

### Related information

* C#/VB.NET Plugins Version
.net 4.7.2
* MSBuild version
16.6.0
* If running through the Scanner for MSBuild, its version
4.10
Code Analyzer for C#
8.4 (build 15306)installed
* Operating System
windows server 2016 version 1607

**Comment by chucklu** [comment]
What I got for the above demo code, is Add a 'protected' constructor or the 'static' keyword to the class declaration,
which map to "Utility classes should not have public constructors" https://rules.sonarsource.com/csharp/RSPEC-1118 .
I believe the sample code should not contains non-relevant issue.

**Comment by chucklu** [comment]
I add static keyword for class Math, and the 1118 issue disappeared. And there is no issue for the code
```C#
 public static class Math
    {
        public static double Pi = 3.14;
    }

    public class Shape
    {
        public static Shape Empty = new EmptyShape();

        private class EmptyShape : Shape
        {
        }
    }
```

**Comment by chucklu** [comment]
I tried to analysis a demo project with sonar cloud, and there is no issue too.
https://sonarcloud.io/project/issues?id=ChuckTest_SonarqubeTest&resolved=false

@pavel-mikula-sonarsource

**Comment by chucklu** [comment]
It seems I did not configure sonar cloud correctly, I got error "The main branch has no lines of code."

**Comment by chucklu** [comment]
I just make the sonar cloud work with travis ci successfully, and this is no issue in project with the above code.
https://sonarcloud.io/dashboard?id=ChuckTest_SonarqubeTest

**Comment by pavel-mikula-sonarsource** [comment]
Hi @chucklu,

I've tried to reproduce your scenario and there are 7 different issues reported for your code fragment including two occurrences of S2223, as you can [see here](https://sonarcloud.io/project/issues?id=Repro_3653).

Your issue comes probably from bad integration with the Travis CI, it's probably not using the correct scanner for MSBuild. Please consult [our documentation](https://sonarcloud.io/documentation/integrations/ci/travis-ci/) or [community forum](https://community.sonarsource.com/) for help with the integration.

**Comment by chucklu** [comment]
@pavel-mikula-sonarsource  Finally I find that the output *.dll file should not contains word "test".
The weird thing is , it recognized a static keyword missing problem before, which makes me think it works.
