### ISSUE TITLE
Deprecate Security Hotspots that are noisy for developers or overlap with SQ DE

### ISSUE THREAD

**Issue by agigleux** [SonarSource/sonar-dotnet#3662]
Here is the list of Security Hotspots to deprecate for C# and VB.NET:

- S4829
- S4823
- S4818
- S4787
- S4784
- S2255

**Comment by andrei-epure-sonarsource** [comment]
#3287 should be fixed together with this, so that the "deprecated" status can be shown on rules.sonarsource.com
