### ISSUE TITLE
Add test cases for all rules with relevant C# 9 syntax

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#3668]
Back in summer we've evaluated what rules need to be updated ("Implement"), or at least sanity-checked ("Add UT") in [C#9 Affected rules](https://docs.google.com/spreadsheets/d/1kSWhy6R1al2bJl9JwnzT2oMnhwZH7d1uwidl01SONX0/edit#gid=547594608).

We need to go one by one and add in the existing unit tests the C# 9 syntax we believe may affect these rules.

**Important**: in the [C#9 Affected rules](https://docs.google.com/spreadsheets/d/1kSWhy6R1al2bJl9JwnzT2oMnhwZH7d1uwidl01SONX0/edit#gid=547594608) table, please change "Add UT" to "Implement" when you realize that something doesn't work out of the box.
- highlight with yellow, to underline the need to implement has been confirmed when adding a UT
- if, after adding the UTs, there's no need for an implementation, highlight "Add UT" with green (to know we did it)

![image](https://user-images.githubusercontent.com/38876598/97457912-7d8b2280-193a-11eb-8c9f-5214d982a16b.png)

- [x] S3442	AbstractTypesShouldNotHaveConstructors.cs
- [x] S4432	AesManagedShouldBeWithSecureMode.cs
- [x] S3244	AnonymousDelegateEventUnsubscribe.cs
- [x] S2330	ArrayCovariance.cs
- [x] S2306	AsyncAwaitIdentifier.cs
- [x] S3168	AsyncVoidMethod.cs
- [x] S1200	AvoidExcessiveClassCoupling.cs
- [x] S110	AvoidExcessiveInheritance.cs
- [x] S4583	BeginInvokePairedWithEndInvoke.cs
- [x] S3343	CallerInformationParametersShouldBeLast.cs
- [x] S4462	CallToAsyncMethodShouldNotBeBlocking.cs
- [x] S3247	CastShouldNotBeDuplicated.cs
- [x] S4830	CertificateValidationCheck.cs
- [x] S3928	CheckArgumentException.cs
- [x] S1451	CheckFileLicense.cs
- [x] S100, S101	ClassAndMethodName.cs
- [x] S3453	ClassNotInstantiatable.cs
- [x] S1694	ClassShouldNotBeAbstract.cs
- [x] S3897	ClassWithEqualityShouldImplementIEquatable.cs
- [x] S1118	ClassWithOnlyStaticMember.cs
- [x] S3776	CognitiveComplexity.cs
- [x] S4004	CollectionPropertiesShouldBeReadOnly.cs
- [x] S2971	CollectionQuerySimplification.cs
- [x] S3240	ConditionalSimplification.cs
- [x] S1862	ConditionalStructureSameCondition.cs
- [x] S2760	ConditionalsWithSameCondition.cs
- [x] S2583, S2589	ConditionEvaluatesToConstant.cs
- [x] S4260	ConstructorArgumentValueShouldExist.cs
- [x] S3330	CookieShouldBeHttpOnly.cs
- [x] S2092	CookieShouldBeSecure.cs
- [x] S4426	CryptographicKeyShouldNotBeTooShort.cs
- [x] S3869	DangerousGetHandleShouldNotBeCalled.cs
- [x] S1854	DeadStores.cs
- [x] S3346	DebugAssertHasNoSideEffects.cs
- [x] S3903	DeclareTypesInNamespaces.cs
- [x] S4524	DefaultSectionShouldBeFirstOrLast.cs
- [x] S3172	DelegateSubtraction.cs
- [x] S2931	DisposableMemberInNonDisposableClass.cs
- [x] S2930	DisposableNotDisposed.cs
- [x] S2997	DisposableReturnedFromUsing.cs
- [x] S4002	DisposableTypesNeedFinalizers.cs
- [x] S2952	DisposeFromDispose.cs
- [x] S2953	DisposeNotImplementingDispose.cs
- [x] S3902	DoNotCallAssemblyGetExecutingAssemblyMethod.cs
- [x] S3885	DoNotCallAssemblyLoadInvalidMethods.cs
- [x] S1147	DoNotCallExitMethods.cs
- [x] S1215	DoNotCallGCCollectMethod.cs
- [x] S3971	DoNotCallGCSuppressFinalizeMethod.cs
- [x] S1696	DoNotCatchNullReferenceException.cs
- [x] S2221	DoNotCatchSystemException.cs
- [x] S3981	DoNotCheckZeroSizeCollection.cs
- [x] S2365	DoNotCopyArraysInProperties.cs
- [x] S4015	DoNotDecreaseMemberVisibility.cs
- [x] S3956	DoNotExposeListT.cs
- [x] S4019	DoNotHideBaseClassMethods.cs
- [x] S2183	DoNotShiftByZeroOrIntSize.cs
- [x] S3060	DoNotTestThisWithIsOperator.cs
- [x] S1048	DoNotThrowFromDestructors.cs
- [x] S3874	DoNotUseOutRefParameters.cs
- [x] S881	DontMixIncrementOrDecrementWithOtherOperators.cs
- [x] S3875	DotNotOverloadOperatorEqual.cs
- [x] S1186	EmptyMethod.cs
- [x] S1116	EmptyStatement.cs
- [x] S2291	EnumerableSumInUnchecked.cs
- [x] S2197	EqualityOnModulus.cs
- [x] S4035	EquatableClassShouldBeSealed.cs
- [x] S4220	EventHandlerDelegateShouldHaveProperArguments.cs
- [x] S3877	ExceptionShouldNotBeThrownFromUnexpectedMethods.cs
- [x] S1067	ExpressionComplexity.cs
- [x] S4226	ExtensionMethodShouldBeInSeparateNamespace.cs
- [x] S2387, S4025	FieldShadowsParentField.cs
- [x] S2933	FieldShouldBeReadonly.cs
- [x] S2357	FieldShouldNotBePublic.cs
- [x] S1104	FieldsShouldNotBePublic.cs
- [x] S3880	FinalizerShouldNotBeEmpty.cs
- [x] S1541	FunctionComplexity.cs
- [x] S134	FunctionNestingDepth.cs
- [x] S3464	GenericInheritanceShouldNotBeRecursive.cs
- [x] S2934	GenericReadonlyFieldPropertyAssignment.cs
- [x] S2955	GenericTypeParameterEmptinessChecking.cs
- [x] S2326	GenericTypeParameterUnused.cs
- [x] S3249	GetHashCodeEqualsOverride.cs
- [x] S2328	GetHashCodeMutable.cs
- [x] S2219	GetTypeWithIsAssignableFrom.cs
- [x] S3397	GuardConditionOnEqualsOverride.cs
- [x] S3881	ImplementIDisposableCorrectly.cs
- [x] S3925	ImplementISerializableCorrectly.cs
- [x] S3927	ImplementSerializationMethodsCorrectly.cs
- [x] S3973	IndentSingleLineFollowingConditional.cs
- [x] S5766	InsecureDeserialization.cs
- [x] S2278, S5547	InsecureEncryptionAlgorithm.cs
- [x] S2070	InsecureHashAlgorithm.cs
- [x] S4039	InterfaceMethodsShouldBeCallableByChildTypes.cs
- [x] S3220	InvocationResolvesToOverrideWithParams.cs
- [x] S1309	IssueSuppression.cs
- [x] S5659	JwtSigned.cs
- [x] S4433	LdapConnectionShouldBeSecure.cs
- [x] S4055	LiteralsShouldNotBePassedAsLocalizedParameters.cs
- [x] S2184	LossOfFractionInDivision.cs
- [x] S4210	MarkWindowsFormsMainWithStaThread.cs
- [x] S3052	MemberInitializedToDefault.cs
- [x] S3604	MemberInitializerRedundant.cs
- [x] S1185	MemberOverrideCallsBaseMember.cs
- [x] S3218	MemberShadowsOuterStaticMember.cs
- [x] S2325	MemberShouldBeStatic.cs
- [x] S3427	MethodOverloadOptionalParameter.cs
- [x] S4136	MethodOverloadsShouldBeGrouped.cs
- [x] S3600	MethodOverrideAddsParams.cs
- [x] S1006	MethodOverrideChangedDefaultValue.cs
- [x] S3262	MethodOverrideNoParams.cs
- [x] S3450	MethodParameterMissingOptional.cs
- [x] S1172	MethodParameterUnused.cs
- [x] S4144	MethodsShouldNotHaveIdenticalImplementations.cs
- [x] S138	MethodsShouldNotHaveTooManyLines.cs
- [x] S3242	MethodsShouldUseBaseTypes.cs
- [x] S4200	NativeMethodsShouldBeWrapped.cs
- [x] S1199	NestedCodeBlock.cs
- [x] S3459	NotAssignedPrivateMember.cs
- [x] S3937	NumberPatternShouldBeRegular.cs
- [x] S1123	ObsoleteAttributesNeedExplanation.cs
- [x] S4069	OperatorOverloadsShouldHaveNamedAlternatives.cs
- [x] S4050	OperatorsShouldBeOverloadedConsistently.cs
- [x] S3466	OptionalParameterNotPassedToBaseCall.cs
- [x] S3447	OptionalRefOutParameter.cs
- [x] S1206	OverrideGetHashCodeOnOverridingEquals.cs
- [x] S1226	ParameterAssignedTo.cs
- [x] S927	ParameterNamesInPartialMethod.cs
- [x] S4428	PartCreationPolicyShouldBeUsedWithExportAttribute.cs
- [x] S3251	PartialMethodNoImplementation.cs
- [x] S4214	PInvokesShouldNotBeVisible.cs
- [x] S4000	PointersShouldBePrivate.cs
- [x] S1450	PrivateFieldUsedAsLocalVariable.cs
- [x] S4275	PropertiesAccessCorrectField.cs
- [x] S4049	PropertiesShouldBePreferred.cs
- [x] S2292	PropertyToAutoProperty.cs
- [x] S2376	PropertyWriteOnly.cs
- [x] S3926	ProvideDeserializationMethodsForOptionalFields.cs
- [x] S2339	PublicConstantField.cs
- [x] S3603	PureAttributeOnVoidMethod.cs
- [x] S4829	ReadingStandardInput.cs
- [x] S3253	RedundancyInConstructorDestructorDeclaration.cs
- [x] S3254	RedundantArgument.cs
- [x] S3440	RedundantConditionalAroundAssignment.cs
- [x] S3257	RedundantDeclaration.cs
- [x] S1939	RedundantInheritanceList.cs
- [x] S3626	RedundantJumpStatement.cs
- [x] S2333	RedundantModifier.cs
- [x] S4201	RedundantNullCheck.cs
- [x] S3235	RedundantParenthesesObjectsCreation.cs
- [x] S1858	RedundantToStringCall.cs
- [x] S1168	ReturnEmptyCollectionInsteadOfNull.cs
- [x] S2201	ReturnValueIgnored.cs
- [x] S2757	ReversedOperators.cs
- [x] S4212	SerializationConstructorsShouldBeSecured.cs
- [x] S4057	SetLocaleForDataTypes.cs
- [x] S3449	ShiftDynamicNotInteger.cs
- [x] S4159	ShouldImplementExportedInterfaces.cs
- [x] S2437	SillyBitwiseOperation.cs
- [x] S122	SingleStatementPerLine.cs
- [x] S2743	StaticFieldInGenericClass.cs
- [x] S3263	StaticFieldInitializerOrder.cs
- [x] S2223	StaticFieldVisible.cs
- [x] S3010	StaticFieldWrittenFromInstanceConstructor.cs
- [x] S2696	StaticFieldWrittenFromInstanceMember.cs
- [x] S2156	StaticSealedClassProtectedMembers.cs
- [x] S1192	StringLiteralShouldNotBeDuplicated.cs
- [x] S3876	StringOrIntegralTypesForIndexers.cs
- [x] S3234	SuppressFinalizeUseless.cs
- [x] S3458	SwitchCaseFallsThroughToDefault.cs
- [x] S2187	TestClassShouldHaveTestMethod.cs
- [x] S2699	TestMethodShouldContainAssertion.cs
- [x] S3433	TestMethodShouldHaveCorrectSignature.cs
- [x] S1607	TestMethodShouldNotBeIgnored.cs
- [x] S3366	ThisShouldNotBeExposedFromConstructors.cs
- [x] S3005	ThreadStaticNonStaticField.cs
- [x] S2996	ThreadStaticWithInitializer.cs
- [x] S2436	TooManyGenericParameters.cs
- [x] S2225	ToStringNoNull.cs
- [x] S4041	TypeNamesShouldNotMatchNamespaces.cs
- [x] S4052	TypesShouldNotExtendOutdatedBaseTypes.cs
- [x] S2761	UnaryPrefixOperatorRepeated.cs
- [x] S3353	UnchangedLocalVariablesShouldBeConst.cs
- [x] S3264	UninvokedEventDeclaration.cs
- [x] S1128	UnnecessaryUsings.cs
- [x] S1144, S4487	UnusedPrivateMember.cs
- [x] S3241	UnusedReturnValue.cs
- [x] S3908	UseGenericEventHandlerInstances.cs
- [x] S4047	UseGenericWithRefParameters.cs
- [x] S2148	UseNumericLiteralSeparator.cs
- [x] S4061	UseParamsForVariableArguments.cs
- [x] S2178	UseShortCircuitingOperator.cs
- [x] S3994, S3995, S3996, S3997, S4005	UseUriInsteadOfString.cs
- [x] S3237	UseValueParameter.cs
- [x] S2123	ValuesUselesslyIncremented.cs
- [x] S1117	VariableShadowsField.cs
- [x] S1481	VariableUnused.cs
- [x] S2290	VirtualEventField.cs
- [x] S2755	XmlExternalEntityShouldNotBeParsed.cs

**Comment by pavel-mikula-sonarsource** [comment]
I've moved - S1944 `InvalidCastToInterface.cs`, `InvalidCastToInterfaceRuleConstants.cs`,  `InvalidCastToInterfaceSymbolicExecution.cs` to SE issue #3693

**Comment by AraHaan** [comment]
I got to nit about S2333:

When using codacy production it throws this for code that uses partial for my tests as it splits it's contents into 3 separate files (removing like it suggests would result in compile error).

Not sure if it is flagged with latest version or if version 8.30 is the current latest.
