### ISSUE TITLE
Add .NET 5.0 Examples to IT and Peach

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#3669]
See the official samples from Microsoft: 
- https://gist.github.com/richlander/50c34a8714eb3436e5d9d4d5d420776e
- https://gist.github.com/richlander/c911b8e3a0aefcefee9e01ee338a5fdd#file-program-cs

Add them to the existing project, or create a new one, depending on what suits best.

**Comment by costin-zaharia-sonarsource** [comment]
PR for peach: https://github.com/SonarSource/peachee-languages/pull/69
