### ISSUE TITLE
Update AZP config to build with the net5 compiler by default

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#3684]
Build with the dotnet tool instead of msbuild.

We may need to move [the install of the .NET 5 sdk](https://github.com/SonarSource/sonar-dotnet/blob/8.14.0.22654/azure-pipelines.yml#L155) to the build job. Currently, it's on the QA job.

**Comment by costin-zaharia-sonarsource** [comment]
This is out of date. We are no longer use the `UseDotNet` task and the dotnet versions are already installed on the Vms
