### ISSUE TITLE
CBDE should not create duplicate folders with the same executable

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#3706]
See [this community thread](https://community.sonarsource.com/t/azure-devops-task-keeps-duplicating-temp-files-in-appdata/33476).

> We had one of our build agent’s disks fill up entirely, and as part of our investigation we found that there were a number of folders containing dotnet-symbolic-execution.exe that had not been cleaned up. In total it reached 2893 folders containing what seemed to be the same executable. The oldest of these seemed to be from the 10th of February. This meant that there was about 3.82 GB of temporary files that were cached here.

When designing CBDE, we probably made an assumption that Temp folders should be cleaned on a regular basis.

We should do better and either check if the executable we need is already there, or delete the existing folders and create a new one in case we don't have a way to tell the correct version of the CBDE executable.

**Comment by loic-joly-sonarsource** [comment]
The current behaviour ensures that if several programs try to extract/run the executable at the same time, it will still work (this is why the process ID was used in the path).

**Comment by bbrueckmann-codesys** [comment]
We stumbled across the same problem.

Cleaning these files lead to errors in the following runs.

**Comment by pavel-mikula-sonarsource** [comment]
Won't fix, will be reimplemented.

**Comment by bbrueckmann-codesys** [comment]
@pavel-mikula-sonarsource are there any follow up issues for the re-implementation?

**Comment by pavel-mikula-sonarsource** [comment]
@bbrueckmann-codesys we will specify how exactly are we going to do it, so there's no issue or MMF to follow yet.

We'll remove the CBDE dependency from the analyzer and we'll reimplement the rule in the embedded symbolic execution engine. I expect this to happen around end of this year.
