### ISSUE TITLE
Rule S3981 : should also check `<0`

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#3735]
The [RSPEC for S3981](https://jira.sonarsource.com/browse/RSPEC-3981) says

>So testing that a size or length is greater than or equal to zero doesn't make sense, since the result is always true. Similarly testing that it is less than zero will always return false. 

Currently, the rule only checks for `>=0`, not also for `<0`.

**Comment by Corniel** [comment]
Consider pattern matching similar to what have been introduced in #3857:
```
count() <= 0
count() < 0
count() <= negative
count() < negative
// reverse too
```
