### ISSUE TITLE
Run C#9 tests only `#if NET`

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#3738]
There's no use case where C# 9 is going to be able to run under .NET Framework, so no need to run tests there. Or in NETCOREAPP 3.x.

**Comment by costin-zaharia-sonarsource** [comment]
From official documentation:
> C# 9.0 is supported only on .NET 5 and newer versions.

> Choosing a language version newer than the default can cause hard to diagnose compile-time and runtime errors.

More details about can be found here: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version

**Comment by pavel-mikula-sonarsource** [comment]
We should use this
```
#if NET
```
since we run `FromCSharp9` onwards

**Comment by costin-zaharia-sonarsource** [comment]
> We should use this
> 
> ```
> #if NET
> ```
> 
> since we run `FromCSharp9` onwards

I was looking in the [documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if) and I could not find `NET` mentioned. I'm not sure about it.

**Comment by pavel-mikula-sonarsource** [comment]
@costin-zaharia-sonarsource I've reported this to a docs repo and it was confirmed as an docs issue:
https://github.com/dotnet/docs/issues/21520

I've also created a PR on their side to fix it.
