### ISSUE TITLE
Fix S3877 FN: Support for arrow methods

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#3754]
S3877 ExceptionShouldNotBeThrownFromUnexpectedMethods

Should have support for arrow methods.

    class ArrowMethods : IDisposable
    {
        static ArrowMethods() => throw new Exception(); // FN, needs support for throw expressions
        public void Dispose() => throw new Exception(); // FN
    }

**Comment by pavel-mikula-sonarsource** [comment]
High priority, because it's a very common case in modern C# and it's easy to fix
