### ISSUE TITLE
Apply SecurityCodeScan rules into the plugin

### ISSUE THREAD

**Issue by javixeneize** [SonarSource/sonar-dotnet#3773]
Hi

I have seen you have released a new version of the plugin, but i still see that SecurityCodeScan has more rules than sonar. Is there any plan to adapt those rules into the sonar plugin?

https://security-code-scan.github.io/#Rules

Thanks

**Comment by pavel-mikula-sonarsource** [comment]
Hi @javixeneize ,

As your question is more a generic discussion one, that cannot be translated into a PR, I suggest you raise it in our [community forum](https://community.sonarsource.com/) to target audience better.

Thank you for understanding.
