### ISSUE TITLE
Fix S3881: "Implement IDisposable correctly" should not ask for GC.SuppressFinalize(this) when there is no finalizer (or destructor)

### ISSUE THREAD

**Issue by ericbl** [SonarSource/sonar-dotnet#3786]
### Description

This is a follow-up partly against the fix that followed the issue:
Fix S3881: "Implement IDisposable correctly" should allow calling GC.SuppressFinalize(this) even when there is no destructor

The fixed implementation is following Microsoft CA1816 and CA1063, but this is not 100% correct as I wrote here:
dotnet/docs#21734

As stated by Stephen Cleary in his blog here:
https://blog.stephencleary.com/2009/08/second-rule-of-implementing-idisposable.html
a class implementing IDisposable with only managed objects should NOT have any finalizer, and thus do NOT need a call to CG.SuppressFinalize

Adding CG.SuppressFinalize will not harm:
https://docs.microsoft.com/en-us/dotnet/api/system.gc.suppressfinalize?redirectedfrom=MSDN&view=net-5.0#System_GC_SuppressFinalize_System_Object_

> If obj does not have a finalizer or the GC has already signaled the finalizer thread to run the finalizer, the call to the SuppressFinalize method has no effect.

but this is just useless: every .NET developer dealing mostly with managed code is adding a line of code for nothing in his code.

IMHO, it would be much better to detect if the class has a finalizer, and if no finalizer, do not ask for SuppressFinalize !
Even better would be to detect for unmanaged ressources and only then ask for a finalizer and possibly SuppressFinalize as in the 3rd rule of implementing IDisposable:
https://blog.stephencleary.com/2009/08/third-rule-of-implementing-idisposable.html

**Comment by costin-zaharia-sonarsource** [comment]
Hi @ericbl, 

thanks for the feedback. Indeed the `GC.SuppressFinalize` is not always needed and in a lot of cases can be safely removed. 

That being said, making a clear distinction between these cases is not always easy. We do this for sealed classes and I think we could do a good enough guess for internal classes too but, as far as I can tell, this is not feasible for public ones. This is also a tradeoff between a bit more noise and CPU cycles (checking all the derived classes comes with a price) and we want to be careful with that.

We will let this open for a while to see if it gets some traction from community but it is not a priority for now.

**Comment by pavel-mikula-sonarsource** [comment]
We're closing this as there was no traction since
