### ISSUE TITLE
Consider converting .NET 4.8 to .NET standard 2.0

### ISSUE THREAD

**Issue by Corniel** [SonarSource/sonar-dotnet#3787]
The solution is multi-target (for good reasons). However, .NET standard 2.0 is fully supported since .NET 4.7.2, it might be worth converting to .NET standard 2.0 completely. Making development easier.

**Comment by pavel-mikula-sonarsource** [comment]
Hi @Corniel, what project do you have in mind? As we target net46 for backward compatibility reasons.

**Comment by Corniel** [comment]
@pavel-mikula-sonarsource if that is the case, then nothing should change. Because all targets within the solution are no set to 4.8 (if I'm not mistaken) I thought, that 4.8 was the minimum version you support. If it is still 4.6, I would not take the risk breaking things for pre 4.7.2.

**Comment by pavel-mikula-sonarsource** [comment]
With our analyzers, we target `net46;netstandard2.0` and reference old Roslyn 1.3.2 for backward compatibility reasons. That makes life little complicated and bring support for VS 2015 / MSBuild 14.

And we target latest `net48;net5.0` with reference to Roslyn 3.8.0 in our unit test projects.
