### ISSUE TITLE
FP S1121 with C#9 records

### ISSUE THREAD

**Issue by eduherminio** [SonarSource/sonar-dotnet#3788]
### Description

Seems the same to https://github.com/SonarSource/sonar-dotnet/issues/3774.
If that hasn't been released yet, this may just be a duplicated issue.

### Repro steps

[SonarCloud project](https://sonarcloud.io/project/issues?id=SheepTools&pullRequest=26&resolved=false&types=CODE_SMELL).
### Expected behavior

No warning triggered.

### Actual behavior

S1121 triggered.

### Related information

* SonarCloud

**Comment by pavel-mikula-sonarsource** [comment]
Hi @eduherminio, 

Thank you for reporting this case. I confirm it as a False Positive. And yes, it's the same issue as #3774, so I'll close this one.

To put more light on the situation: C# 9 is not supported yet and we didn't fix the problem. We just documented the behavior for now (see release notes https://github.com/SonarSource/sonar-dotnet/releases/tag/8.15.0.24505 ) in our tests to be able to implement it in the future.

Full C# 9 support is planned in [MMF-2105](https://jira.sonarsource.com/browse/MMF-2105), Records are in [MMF-2223](https://jira.sonarsource.com/browse/MMF-2223) at the top of the list. It should be supported in 2021.
