### ISSUE TITLE
Improve S2068: Detect constant concatenation

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#3802]
```
            using (var conn = OpenConn("Server = " + server + "; Database = Test; User = SA; Password =" + "Secret123")) { } // FN
            var mySecret = "123";
            using (var conn = OpenConn("Server = " + server + "; Database = Test; User = SA; Password =" + mySecret)) { } // FN
```

We are currently able to detect when a `private const string secret = "constantValue";` is passed (see where `secret` is used in [the test](https://github.com/SonarSource/sonar-dotnet/blob/50e3d6240212086a5ec9cfd7887bfbf265f79860/analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotHardcodeCredentials_DefaultValues.cs#L13)), but not with variables initialized with a constant.

```
            new NetworkCredential("username", secret); // Noncompliant {{Please review this hard-coded password.}}
```

This should probably be done in 2 steps:
- first fix the concatenation of hardcoded strings and with `const` fields or variables
- fix concatenation with variables which are not `const`

**Comment by pavel-mikula-sonarsource** [comment]
This issue implements only support for concatenation with const. Other issues were spin off:
#3883 Detect fields and local variables initialized to constant
#3884 Detect `String.Format` with constant (and fields and variables) in conjunction with #3883
#3885 Detect interpolated strings with constant (and fields and variables) in conjunction with #3883
