### ISSUE TITLE
S126: Do not report when "else" keyword in "else if" is redundant

### ISSUE THREAD

**Issue by neoscie** [SonarSource/sonar-dotnet#3827]
### Description
Consider this function

    public string Foo(string name)
    {
        if (name == null)
        {
            return "Foo";
        }
        else if (name == string.Empty)
        {
            return "Bar";
        }

        return "FooBar";
    }

S126 wants us to add a final `else` after the `else if` to reach logical completeness. But because of the `return` statements, it is actually not needed. Even more, the `else` part of the `else if` is redundant and should be removed:

    public string Foo(string name)
    {
        if (name == null)
        {
            return "Foo";
        }
        
        if (name == string.Empty)
        {
            return "Bar";
        }

        return "FooBar";
    }

### Repro steps

Check out [this repo](https://github.com/neoscie/Repro.S126) to reproduce the problem (S126 is set as Error).

### Expected behavior

S126 should not require a final ´else´ if it is redundant.

### Related information

* SonarAnalyzer.CSharp Version 8.15.0.24505

**Comment by pavel-mikula-sonarsource** [comment]
Hi @neoscie, this rule is specified as defensive and behaves as specified.

You should either not use `else if` in your coding style, or use `if / else if / else` to be consistent. Using `if / else if` is inconsistent and therefore prone to errors that this rule is trying to prevent from doing. Using `if / else if / else` with all branches returning value also helps to keep the overall flow of the method easy to understand - you don't need to inspect scenarios where N-th `else if` doesn't return.

**Comment by neoscie** [comment]
Hi @pavel-mikula-sonarsource 

So, you would recommend bringing all the devs in my team on the same page? 

This would subsequently mean 
- To deactivate this rule and tell the devs they should avoid `else if` at all
- Or to keep this rule and thus enforce a final `else` whenever an `else if` was used

Correct?

**Comment by pavel-mikula-sonarsource** [comment]
I'm not sure why you would deactivate the rule and avoiding the `else if` at the same time. As the rule would not raise with no `else if`.

I would recommend to align your team on uniform coding style in order to have higher code quality and easier maintainability of your code base. 

You can, of course, deactivate the rule if it doesn't match your coding style.
