### ISSUE TITLE
OutOfMemoryError possible using wildcard pattern with alternative path separators

### ISSUE THREAD

**Issue by rossbeehler** [SonarSource/sonar-dotnet#3852]
### Description

If you provide a wildcard pattern on Windows with forward slashes, the analyzer may search too high in the directory structure, eventually causing an OutOfMemoryError. It should support paths containing any acceptable path separator, not just the default.

### Repro steps

On Windows, provide an analyzer property such as:

> sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/**/*.trx

Note that my example is on an Azure Pipelines self-hosted agent, so $(Agent.TempDirectory) is similar to `C:\agent_work9`.  

During analysis, you see the following DEBUG output:

```
18:40:23.959 INFO: Sensor C# Unit Test Results Import [csharp]
18:40:23.959 DEBUG: Pattern matcher extracted prefix/absolute path 'C:\agent_work9' from the given pattern 'C:\agent_work9\_temp/**/*.trx'.
18:40:23.959 DEBUG: Gathering files for wildcardPattern '_temp/**/*.trx'.
18:52:34.401 INFO: ------------------------------------------------------------------------
18:52:34.401 INFO: EXECUTION FAILURE
18:52:34.401 INFO: ------------------------------------------------------------------------
18:52:34.401 INFO: Total time: 12:18.950s
18:52:34.448 INFO: Final Memory: 9M/895M
18:52:34.448 INFO: ------------------------------------------------------------------------
##[error]18:52:34.448 ERROR: Error during SonarScanner execution
##[debug]Processed: ##vso[task.logissue type=error;]18:52:34.448 ERROR: Error during SonarScanner execution
18:52:34.448 ERROR: Error during SonarScanner execution
##[error]java.lang.OutOfMemoryError: Java heap space
	at java.io.WinNTFileSystem.resolve(Unknown Source)
	at java.io.File.<init>(Unknown Source)
	at java.io.File.listFiles(Unknown Source)
	at org.sonar.plugins.dotnet.tests.WildcardPatternFileProvider.listFiles(WildcardPatternFileProvider.java:140)
```

Note that the file search starts at `C:\agent_work9` and not `C:\agent_work9\_temp`, which causes it to search through every build ever conducted by this agent, including ancillary tools and packages, etc.

The root cause for this is that the [WildcardPatternFileProvider](https://github.com/SonarSource/sonar-dotnet/blob/8.15.0.24505/sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/WildcardPatternFileProvider.java) class constructor accepts a `directorySeparator` parameter, which is only being provided as the default path separator (File.separator). Perhaps it should take [the same approach as .NET](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#canonicalize-separators) to accept both forward and back slashes.

### Known workarounds

Switch to the default Windows path separators:

> sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/**/*.trx

And it will search at the correct level:
```
22:10:40.179 DEBUG: Pattern matcher extracted prefix/absolute path 'C:\agent_work1\_temp' from the given pattern 'C:\agent_work1\_temp\**\*.trx'.
```

### Related information

* SonarScanner for AzurePipelines 4.17.0
* Azure Pipelines Windows self-hosted agent
* C#
* netcoreapp3.1

**Comment by costin-zaharia-sonarsource** [comment]
Hi @rossbeehler, thanks a lit for reporting this.

Notes for the team:
I was able to reproduce this our part with an unit test in https://github.com/SonarSource/sonar-dotnet/blob/1af2e34548c0873aa437a11d02f9d51373ed7177/sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/WildcardPatternFileProviderTest.java:

```
@Test
public void given_pattern_with_windows_folder_separator_listFiles_detects_wrong_pattern(){
  File tmpRoot = tmp.getRoot();
  String givenPattern = tmpRoot + File.separator + "agent_work9" + File.separator + "_temp/**/*.trx";

  listFiles(givenPattern);

  List<String> debugLogs = logTester.logs((LoggerLevel.DEBUG));
  assertThat(debugLogs.get(1)).isEqualTo("Gathering files for wildcardPattern '_temp/**/*.trx'.");
}
```

The correct wildcard pattern should be `**/*.trx` instead of `_temp/**/*.trx`.
