### ISSUE TITLE
Describe how GeneratedCode is recognized in embedded docs

### ISSUE THREAD

**Issue by StingyJack** [SonarSource/sonar-dotnet#3872]
This seems obvious that it should be, but I cant find documentation stating it is..

**Comment by pavel-mikula-sonarsource** [comment]
Hi @StingyJack ,

I'm not sure what the question or issue is. We have several ways to detect if code is generated. And most of the rules don't trigger on them.

`GeneratedCode` attribute is supported, see:
https://github.com/SonarSource/sonar-dotnet/blob/977428ad3ada90f4cffea0ca7ff184c235f5e9e4/analyzers/src/SonarAnalyzer.Common/Helpers/GeneratedCodeRecognizer.cs#L52-L60

Does it address your issue?

**Comment by StingyJack** [comment]
@pavel-mikula-sonarsource  yes. It would be nice if the docs would include this note.   I wouldnt have thought the first two would be in that list, but its not an attribute I use so w/e. Thanks!

**Comment by pavel-mikula-sonarsource** [comment]
I'm reopening this to add a mention to the embedded docs.

**Comment by StingyJack** [comment]
@pavel-mikula-sonarsource someone shared with me the link to what the compiler considers generated code.  https://github.com/dotnet/docs/issues/24657#issuecomment-860517730. Probably useful in some respect.
