### ISSUE TITLE
Rspec.ps1 script enhancements for Hotspots

### ISSUE THREAD

**Issue by csaba-sagi-sonarsource** [SonarSource/sonar-dotnet#3906]
The following enhancements should be considered:
- Change the script to generate rule files for hotspots inside the Hotspots subfolder
- Hotspot rules should inherit HotspotDiagnosticAnalyzer instead of SonarDiagnosticAnalyzer
- Update the templates to comply with the active Stylecop rules
- Use expression bodied methods

**Comment by sagi1623** [comment]
@pavel-mikula-sonarsource I don't have the insight so I cannot tell for sure, but with the current destiny of hotspots, it most probably does not make sense to invest time in doing the first two bullet points. While the second two are already addressed.
I suggest closing this issue.
