### ISSUE TITLE
S2589 FP and FN: Conditional access and pattern matching

### ISSUE THREAD

**Issue by jjolidon** [SonarSource/sonar-dotnet#3910]
### Description

S2589 triggers a false positive for a null check after a first test with pattern matching.

### Repro steps

```cs
private void Test(Exception ex)
{
    if (ex?.Data["FOO"] is string myString)
    {
        // intentionally empty for the reproducer
    }
    else
    {
        if (ex != null) // This test triggers S2589
        {
            // intentionally empty for the reproducer
        }
    }
}
```

### Expected behavior

The above code should not trigger S2589

### Actual behavior

The above code triggers S2589

### Known workarounds

No known workaround

### Related information

* SonarAnalyzer.CSharp version: 8.13.0.25740
* Visual Studio version: 16.8.3
* MSBuild / dotnet version: 16.8.2.56705 / 5.0.101
* SonarScanner for .NET version (if used)
* Operating System: Win 10

**Comment by pavel-mikula-sonarsource** [comment]
Hi @jjolidon ,

Thank you for reporting this case. I can confirm it as False Positive.

**Comment by andrei-epure-sonarsource** [comment]
other conditional access FPs: #3416 ,  #2528, #2704

**Comment by mary-georgiou-sonarsource** [comment]
Fixed by https://github.com/SonarSource/sonar-dotnet/pull/7750
