### ISSUE TITLE
Add NCcover3 deprecation note in documentation

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#3934]
Here: https://docs.sonarqube.org/latest/analysis/coverage/
And here: https://community.sonarsource.com/t/coverage-test-data-generate-reports-for-c-vb-net/9871/14

**Comment by andrei-epure-sonarsource** [comment]
[Example PRs](https://github.com/SonarSource/sonar-enterprise/pulls?q=is%3Apr+is%3Aclosed+%5BDOCS%5D) for updating product docs

**Comment by costin-zaharia-sonarsource** [comment]
PR for sonarqube doc: https://github.com/SonarSource/sonar-enterprise/pull/3784

**Comment by andrei-epure-sonarsource** [comment]
this got closed in  SonarSource/sonar-enterprise#3784
