### ISSUE TITLE
Extend S5753 to support Web.{Debug,Release}.config transformations

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#3948]
RE: #3185 and https://jira.sonarsource.com/browse/RSPEC-5753

Currently it only detects the security hotspot on `web.config` files. However, developers may change the configuration for Release via XDT transformations, and make the web app vulnerable.

Probably we should ignore Debug as in development a less secure config may be used.

https://docs.microsoft.com/en-us/aspnet/web-forms/overview/deployment/visual-studio-web-deployment/web-config-transformations#default-transformation-files

**Comment by pavel-mikula-sonarsource** [comment]
We should definitely ignore the `Debug` transformation and focus primarly on `Web.Config` & `Web.Release.config`.

Question is: What should we do other transformations? There could be  `Web.{CustomConfiguration}.config`, `Web.{CustomProfile}.config` and `Web.{CompletlyCustom}.config` transformation that are applied one after another. See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/transform-webconfig?view=aspnetcore-5.0

We will probably not be able to determine correct order, but we can inspect them individually.

**Comment by pavel-mikula-sonarsource** [comment]
After taking one more look, properties can depend on `configuration` name, `profile` name, `environment` name and other explicitly provided `*.transform` files.

Let's inspect any `web.*.config` except well known `web.debug.config` file as they would be a standalone `web.config` and report on those.

As it's impossible to simulate the transformations properly, we might get some FP for `remove` transformations. But the `remove` transformation are not sure to be applied for production anyway.
