### ISSUE TITLE
Update S2259: "Null pointer dereference" CFG should ignore expressions in Debug.Assert

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-dotnet#397]
[RSPEC-2259](https://jira.sonarsource.com/browse/RSPEC-2259)

The following code should not generate branches in the CFG:

```
Debug.Assert(a != null || somethingElse);
a.Foo(); // FP, we know a cannot be null
```

Currently the code above generates branch in CFG and the exploded graph detects null dereference in one of the branches.

The referenced issue #349 should revert this change and improve the behavior.

**Comment by koczkatamas** [comment]
Also worth considering to support `Microsoft.VisualStudio.TestTools.UnitTesting.Assert` class and its methods, eg. `Assert.IsNotNull`.

Or if it's possible then find a more generic solution (if there is none exists yet) which tells the S2259 checker that "after running this method (eg. `Assert.IsNotNull`) this parameter (eg. `value`) won't be null", this way SonarSource will be more extendable and won't be opinionated towards a specific test framework.

**Comment by pavel-mikula-sonarsource** [comment]
This is not relevant anymore with Roslyn CFG in place. We'll try to take a look at #349
