### ISSUE TITLE
Fix wcf cirrus ci build

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#4003]
```
Installing dotnet cli...
Restoring BuildTools version 2.1.0-rc1-03131-06...
ERROR: Could not restore build tools correctly. See 'C:\Project\init-tools.log' for more details. 
```
https://cirrus-ci.com/task/5045919777292288?command=build#L44

**Comment by andrei-epure-sonarsource** [comment]
I had a look at `2f4548e5 - (HEAD, tag: v3.2.0-rtm)` in https://github.com/dotnet/wcf

Building by `.\build.cmd` works fine without SonarQube.

When doing the scanner begin before, the build has lots of errors for each of the roslyn diagnostics, such as 
```
C:\Workspace\external-projects\wcf\src\System.ServiceModel.Primitives\ref\System.ServiceModel.Primitives.cs(198,26): error S3925: Update this implementation of 'ISerializable' to conform to the recommended serialization pattern. [C:\Workspace\external-projects\wcf\src\System.ServiceModel.Primitives\ref\System.ServiceModel.Primitives.Ref.csproj]
```

They build stuff using powershell scripts, important files:
- `eng\build.ps1`
- `eng\common\build.ps1`
- `eng\common\tools.ps1`

**Comment by andrei-epure-sonarsource** [comment]
PR: https://github.com/SonarSource/peachee-languages/pull/83
