### ISSUE TITLE
Rule S2115: Databases should be password-protected (C# and web.config detection)

### ISSUE THREAD

**Issue by pierre-loup-tristant-sonarsource** [SonarSource/sonar-dotnet#4010]
https://jira.sonarsource.com/browse/MMF-2255
https://jira.sonarsource.com/browse/RSPEC-2115
https://github.com/SonarSource/security-expected-issues/pull/265

Steps:
- [x] C# code
- [x] web.config
- [ ] appsettings.json
- [ ] support constant propagation

**Comment by andrei-epure-sonarsource** [comment]
I closing this as being treated by #4249 and #4271.
I opened  #4298 as a follow-up for app.json
