### ISSUE TITLE
Setup PR decorations to mono-repo

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#4020]
SonarCloud:
https://community.sonarsource.com/t/monorepo-support-for-github/27353

**Comment by andrei-epure-sonarsource** [comment]
Update - pending [internal feedback](https://discuss.sonarsource.com/t/create-monorepo-from-existing-projects-i-need-help/7029)

**Comment by andrei-epure-sonarsource** [comment]
It is not possible to setup mono-repo without losing the history for at least one of our projects. At least at this moment.

**Comment by pavel-mikula-sonarsource** [comment]
I think we can sacrifice Java project history as part of this process. Martin's answer doesn't suggest any plans to support such feature.
