### ISSUE TITLE
Add IT for reading Razor results

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#4039]
Related to original issue on S4MSB side https://github.com/SonarSource/sonar-scanner-msbuild/issues/949 with targets file:

We should add IT similar to `NetCore31` without `global.json` to run on latest SDK that will blow in case the targets are changed again. See this comment: https://github.com/SonarSource/sonar-scanner-msbuild/pull/950#discussion_r570068840

**Comment by andrei-epure-sonarsource** [comment]
I don't understand very well what this IT would consist of. Could you please clarify, @pavel-mikula-sonarsource ?

**Comment by pavel-mikula-sonarsource** [comment]
While thinking about the purpose, this should be in S4NET repo.
Moved: https://github.com/SonarSource/sonar-scanner-msbuild/issues/1036
