### ISSUE TITLE
Add ITs related test projects

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#4055]
Add ITs for the 3 scenarios

**Comment by andrei-epure-sonarsource** [comment]
the 3 scenarios are [here](https://xtranet-sonarsource.atlassian.net/wiki/spaces/LANG/pages/1328775324/Test+projects+detection+in+our+.NET+offering#Functional-behavior)

**Comment by andrei-epure-sonarsource** [comment]
there's also some here https://github.com/SonarSource/sonar-dotnet/issues/4054#issuecomment-779205928

**Comment by pavel-mikula-sonarsource** [comment]
https://github.com/SonarSource/sonar-security/tree/master/its/projects/internal/InternalCSharp.UTs
