### ISSUE TITLE
Make S4261 active again (revert deprecation) and keep it out of the SonarWay default profile

### ISSUE THREAD

**Issue by craigfowler** [SonarSource/sonar-dotnet#4059]
I see that [rule S4261 has recently been deprecated](https://github.com/SonarSource/sonar-dotnet/pull/4028) and I've had a quick read around the context for this:

* https://community.sonarsource.com/t/s4261-has-incorrect-examples/36324/6
* https://github.com/SonarSource/sonar-dotnet/issues/3928

Whilst acknowledging the weaknesses in that old rule, I do still find it useful.  I'd very much like there to be a new rule added, replacing that deprecated one (albeit using the correct rule logic) which I can use instead.

**Comment by costin-zaharia-sonarsource** [comment]
Notes for the team: check the status of https://github.com/dotnet/docs/issues/22188

**Comment by StingyJack** [comment]
@costin-zaharia-sonarsource  - SonarSource really should have just removed that rule from the default SonarWay profile. Marking it as deprecated makes the UI show a big red box around the quality profile. 

Doing that gives the general user population a very clear indication that something is wrong with the quality profile and can undermine the idea that code will be analyzed fairly and correctly, and thats all the window some need to start discrediting or ignoring programs like sonar. The indication is simply not true; the rule we is correct per the new advice, and there should be no penalty should we want to include it in our QP's.  

If the roles were reversed, I'm sure the first suggestion I would get when complaining about a rule would be "you can just turn it off"

**Comment by andrei-epure-sonarsource** [comment]
We've discussed and decided to leave S4261 as an active (non-deprecated) rule and keep it out of the default quality profile.
