### ISSUE TITLE
Don't inspect assembly name in test detection

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#4062]
`Main` vs. `Test` project detection is based on several factors like assembly name and referenced projects. Assembly name was inspected to detect test projects based on presence of "Test" and "Tests" words. 

This has major drawbacks:
- Users that want to try the product will likely use "Test" as part of the testing project name.
- Behavior is inconsistent between products and tools (SonarLint, Scanner for MSBuild, Analyzer, Security engine).

We need to remove the part inspecting the assembly name.

**Comment by duncanp-sonar** [comment]
Since this ticket is publicly visible and will be referred to in the release notes, it would be helpful if it explained why this change is being made.
