### ISSUE TITLE
Fix S1172 FP: Parameter used in catch block

### ISSUE THREAD

**Issue by RobertSimonsSMA** [SonarSource/sonar-dotnet#4096]
### Description

A S1172 warning is shown for a parameter used in a catch block if there is an unconditional return inside a using block inside the try clause

### Repro steps

In this code, there is a warning shown the the parameter errorCode is unused:
```
        private int UseAndReturn(int errorCode) {
            try {
                using (var textWriter = new StreamWriter("TestOutput.txt")) {
                    textWriter.Write("There is an errorcode");

                    return 0;
                }
            } catch (Exception) {
                return errorCode;
            }
        }

```

In contrast, in this code - that does functionally the same - the warning is not raised:
```
        private int TryAndReturn(int errorCode) {
            try {
                var textWriter = new StreamWriter("TestOutput.txt");
                try {
                    textWriter.Write("There is a code");

                    return 0;
                } finally {
                    textWriter.Dispose();
                }
            } catch (Exception) {
                return errorCode;
            }
        }

```

### Expected behavior

Both code snippets should not raise the unused parameter warning.

### Actual behavior

In the first snippet the use of the parameter in the catch block is not detected and a warning for an unused parameter is shown.

### Known workarounds

Unwrap all using blocks into try-finally blocks

### Related information
* Visual Studio 16.8.6
* SonarScanner for .NET version 8.18.0.27296
* Operating System Windows 10 Version 1909

**Comment by RobertSimonsSMA** [comment]
So, will this be fixed in the foreseeable future?

Will it be weeks, months or years?

Sincerely
  Robert

**Comment by pavel-mikula-sonarsource** [comment]
Hi @RobertSimonsSMA,

This should be fixed this year as part of [MMF-2394](https://jira.sonarsource.com/browse/MMF-2394).
