### ISSUE TITLE
False Positive: [FromServices]-Attribute produces csharpsquid:S3900 (Arguments of public methods should be validated against null)

### ISSUE THREAD

**Issue by fibach** [SonarSource/sonar-dotnet#4122]
### Description

The [FromServices] Attribute (https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.fromservicesattribute?view=aspnetcore-5.0) from AspNetCore.Mvc will inject a service via dependency injection into a method of the controller. 

If you forgot to register the service in the DI container, you would get another exception ("InvalidOperationException: No service for type 'XXX' has been registered.")

### Repro steps

Basic setup of dotnet Core MVC project (https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio)

- Create Class ProductModelRequestService 
public class ProductModelRequestService
	{
		public string DoIt()
		{
			return "hello world";
		}
	}
- Register in DI container (e.g. in ApiStartup.cs
service.AddTransient<ProductModelRequestService>();
- Add a new Route in the Controller
[HttpGet]
public ProductModel GetProduct([FromServices] ProductModelRequestService productModelRequest)
{
    return productModelRequest.DoIt();
}

### Expected behavior

No Sonarqube warning will csharpsquid:S3900

### Actual behavior
"Arguments of public methods should be validated against null" code smell occures

### Known workarounds

-
EDIT:
Additional Info:
Sonarqube version: Enterprise EditionVersion 8.1 (build 31237)

**Comment by costin-zaharia-sonarsource** [comment]
Hi @fibach, 

Thanks for pointing this out. I can confirm the false positive.

**Comment by fibach** [comment]
@costin-zaharia-sonarsource thanks for tackling this issue. 
It seems you reopened it, but it seems the bug is still on done in the backlog.

KR
florian

**Comment by csaba-sagi-sonarsource** [comment]
Hi @fibach,
The issue was closed by mistake, and that is why it got reopened (and by automation it went to the done column in the backlog).
I moved it back to the false positives column in the backlog.

Thank you very much for reporting the issue in the first place and then for pointing out it was in the wrong column in the backlog.
