### ISSUE TITLE
S3928: Fix documentation

### ISSUE THREAD

**Issue by Oliver-Piorun** [SonarSource/sonar-dotnet#4127]
### Description

https://rules.sonarsource.com/csharp/RSPEC-3928

Hi! I noticed two issues in the "Compliant Solution" section of this spec.

1. Typo in `nameOf(a)`
`throw new ArgumentNullException(nameOf(a));`
should be
`throw new ArgumentNullException(nameof(a));`
2. Wrong order of arguments. `"a"` is supposed to be the `paramName` here (not the `message`)
`throw new ArgumentNullException("My error message", "a");`
should be
`throw new ArgumentNullException("a", "My error message");`
Remarks: The analysis itself seems to be fine.

For reference:
- `public ArgumentNullException (string? paramName, string? message);`
- [Documentation](https://docs.microsoft.com/en-us/dotnet/api/system.argumentnullexception.-ctor?view=net-5.0#System_ArgumentNullException__ctor_System_String_System_String_)

I can also provide a PR if you agree with this changes :)

Greetings!

**Comment by csaba-sagi-sonarsource** [comment]
Hi @Oliver-Piorun,

Thank you for sharing these issues with us.
Unfortunately you will be not able to do these changes on your own, as you do not have permission to update the Compliant Solution in every necessary place.

Best regards,
Čaba
