### ISSUE TITLE
Update peachee jobs to use MSBuild 16 by default

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#4135]
By default, our peachee jobs are using MSBuild 15.9.

We don't have jobs anymore on MSBuild 16.x (except the implicit .NET 5 ones).

We should change our [build script](https://github.com/SonarSource/peachee-languages/blob/dotnet/build.cmd) to use MSBuild 16.6+ (to benefit of [contextual information for analyzers exceptions](https://github.com/dotnet/roslyn/pull/35871)) by default. This may need an update to our [Windows VM config](https://github.com/SonarSource/peachee-languages/tree/packer/windows), to have the proper MSB installed.

And have some job in [the config](https://github.com/SonarSource/peachee-languages/blob/dotnet/.cirrus.yml)  to use MSBuild 15, too.

**Comment by andrei-epure-sonarsource** [comment]
PR: https://github.com/SonarSource/peachee-languages/pull/144

**Comment by csaba-sagi-sonarsource** [comment]
Fixed by: SonarSource/peachee-languages#144
