### ISSUE TITLE
Fix S5944 FP: With NameOf

### ISSUE THREAD

**Issue by splendid25** [SonarSource/sonar-dotnet#4159]
### Description

S5944 False positive when using NameOf, to avoid using a magic string in the first place.

### Repro steps

    Public Shared Function TestReturn() As String
        Dim result = NameOf(TestReturn)
        Return result
    End Function

### Expected behavior

No warning reported

### Actual behavior

S5944 reported

### Related information

* C#/VB.NET Plugins version 4.33.0.28535
* Visual Studio version 16.9.1
* MSBuild / dotnet version 16.9.0.11203
* Operating System Windows 10 20H2

**Comment by pavel-mikula-sonarsource** [comment]
Hi @splendid25 ,

Thank you for reporting this case. I can confirm it as False Positive.
