### ISSUE TITLE
S1854 FP useless assignment

### ISSUE THREAD

**Issue by splendid25** [SonarSource/sonar-dotnet#4163]
### Description

When setting a variable in a method, consumed only in a local function, S1854 reports a false positive.

### Repro steps

        public static void Foo()
        {
            int count = 0;
            count++;

            void Bar()
            {
                System.Diagnostics.Debug.WriteLine(count);
            }
        }

### Expected behavior

No warning, because if the variable is not set, the local function will not run properly.

### Actual behavior

S1854	Remove this useless assignment to local variable 'count'.

### Related information

* C#/VB.NET Plugins version 4.33.0.28535
* Visual Studio version 16.9.1
* MSBuild / dotnet version 16.9.0.11203
* Operating System Windows 10 20H2

**Comment by pavel-mikula-sonarsource** [comment]
Hi @splendid25 ,

Thank you for reporting this case, I can confirm it as a False Positive. We this situation already reported in #3126 that you can track so I'll close this one.
