### ISSUE TITLE
Fix S2092 FP: Default value depends on the web.config httpCookies property

### ISSUE THREAD

**Issue by eric-therond-sonarsource** [SonarSource/sonar-dotnet#4164]
Improvement for dotnet framework.

```
HttpCookie MyCookie2 = new HttpCookie("TestSecureFlag2"); // Sensitive (s2092)
```
the default value for the `Secure` property is `false`, so it's noncompliant/sensitive and equivalent to:
```
HttpCookie MyCookie2 = new HttpCookie("TestSecureFlag2");
MyCookie2.Secure = false;  // Sensitive (s2092)
```

but the default value of the `secure` flag depends on the `httpCookies` property set (or not) in the `web.config` file of the solution, if `httpCookies` property is set then the default value is equals to the one of the `requireSSL` attribute, for instance here:
```
<httpCookies httpOnlyCookies="true" requireSSL="true" />
```
it leads to:
```
HttpCookie MyCookie2 = new HttpCookie("TestSecureFlag2"); // Compliant (s2092) (requireSSL set to true)

HttpCookie MyCookie3 = new HttpCookie("TestSecureFlag3"); 
MyCookie3.Secure = false;  // Sensitive (s2092) (requireSSL set to true but it's overwritten here)
```
if `requireSSL` is set to `false` or not defined:
```
<httpCookies httpOnlyCookies="true" requireSSL="false" />
```
it leads to:
```
HttpCookie MyCookie2 = new HttpCookie("TestSecureFlag2"); // Noncompliant (s2092) (requireSSL set to false)

HttpCookie MyCookie3 = new HttpCookie("TestSecureFlag3"); 
MyCookie3.Secure = true;  // Compliant (s2092) (requireSSL set to false but it's overwritten here)
```

Code examples:
* https://github.com/SonarSource/security-expected-issues/pull/389/files
* https://github.com/SonarSource/security-expected-issues/tree/master/dotnet/NetFwk48MVC/Controllers/RSPEC_2092

**Comment by pavel-mikula-sonarsource** [comment]
This is similar to S3330 #4083
