### ISSUE TITLE
Update Scanner for .NET to 5.2 in integration tests

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#4169]
In [TestUtils](https://github.com/SonarSource/sonar-dotnet/blob/master/its/src/test/java/com/sonar/it/shared/TestUtils.java#L142)

And in the [IT project pom.xml ](https://github.com/SonarSource/sonar-dotnet/blob/master/its/pom.xml#L25)

**Comment by andrei-epure-sonarsource** [comment]
We should also have an IT with a project that has both test and main code, and verify which issues are raised on each.

**Comment by csaba-sagi-sonarsource** [comment]
with_csharp_only_test_should_not_populate_metrics() rebuilds the project instead of using the results from init(). Remove the rebuild.
