### ISSUE TITLE
Refactor ReportDiagnosticWhenActive methods to not check diagnostic scope by default

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#4173]
See rationale in this comment: https://github.com/SonarSource/sonar-dotnet/pull/4167#discussion_r598560726

WHAT

The ReportDiagnosticWhenActive* should not verify the scope of the rule by default ( see `analyzers/src/SonarAnalyzer.Common/Helpers/AnalysisContextExtensions.cs`).

Only specific overloads should do it, which should be used by classed with multiple diagnostics (where one diagnostic may be MAIN-only and one TEST-only, so the class logic will be registered all the time).

**Comment by pavel-mikula-sonarsource** [comment]
As a solution, we should be able to add optional `SonarAnalysisContext contet = null` argument with some docs to the `ReportDiagnosticWhenActive` and explain it's purpose and use caching based on it.

**Comment by andrei-epure-sonarsource** [comment]
Ok.

Some tasks here that can be done in parallel:
- for the classes that have multiple diagnostics, add tests with TEST scope to document the behavior difference
- after that, make the change (however we do it, but backed by unit tests for those rules)

**Comment by pavel-mikula-sonarsource** [comment]
Rules to cover:

SymbolicExecutionAnalyzerFactory S3655: MainTest; S3966: MainTest; S3900: MainTest; S4158: MainTest; S2583: MainTest; S2589: MainTest; S1944: MainTest; S2259: Main; S5773: Main; S3329: Main; S2053: MainTest
ClassAndMethodName S100: MainTest; S101: MainTest
CommentKeyword S1135: MainTest; S1134: MainTest
FieldShadowsParentField S2387: Main; S4025: MainTest
ClearTextProtocolsAreSensitive S5332: Main; S5332: Main
InsecureEncryptionAlgorithm S2278: Main; S5547: Main
StringFormatValidator S2275: MainTest; S3457: MainTest
UnusedPrivateMember S1144: MainTest; S4487: MainTest
UseUriInsteadOfString S3994: MainTest; S3995: MainTest; S3996: MainTest; S3997: MainTest; S4005: MainTest
CommentKeyword S1135: MainTest; S1134: MainTest
FieldShadowsParentField S2387: Main; S4025: MainTest
