### ISSUE TITLE
Fix RegEx hotspots in DotCoverReportParser

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#4194]
Remove backtracking from Regex in `DotCoverReportParser`, as found on SonarCloud:
https://sonarcloud.io/project/security_hotspots?id=org.sonarsource.dotnet%3Asonar-dotnet&sinceLeakPeriod=true#

```
private static final Pattern TITLE_PATTERN = Pattern.compile(".*?<title>(.*?)</title>.*", Pattern.DOTALL);
private static final Pattern COVERED_LINES_PATTERN_1 = Pattern.compile(
    ".*<script type=\"text/javascript\">\\s*+highlightRanges\\(\\[(.*?)\\]\\);\\s*+</script>.*",
    Pattern.DOTALL);
```

**Comment by andrei-epure-sonarsource** [comment]
For the TITLE_PATTERN, I did some tests with various options, and found that `[^<]*?<title>([^<]*+)</title>.*+` is the best option. 

Test results below. `title_nested_tag.html` contains `    <title><title></t></ti></tit></ts></titl></titles></titlee></title<</</</</</<<</<<//</</</</</</</</</</</</</</</</</</</</</</</</</titl<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<</title>` as title.

<hr>

Existing regex `.*?<title>(.*?)</title>.*`
- file valid.html, time PT3.5658434S
- file title_nested_tag.html, time PT5.489271S

Optimized in capture group: `.*?<title>([^<]*?)</title>.*`
- file valid.html, time PT3.6380489S
- file title_nested_tag.html, time PT13.372804S

Optimized in capture group with possesive quantifier: `.*?<title>([^<]*+)</title>.*+`
- file valid.html, time PT6.5417454S
- file title_nested_tag.html, time PT12.5086147S

Optimized before and inside capture group `[^<]*?<title>([^<]*+)</title>.*+`
- file valid.html, time PT0.0507758S
- file title_nested_tag.html, time PT0.0508954S

<hr>

Benchmark
```
    Instant starts = Instant.now();

    for (int i = 0; i < 1000000; i++) {
      Matcher matcher = TITLE_PATTERN.matcher(contents);
      if (matcher.matches()) {
        String lowerCaseAbsolutePath = matcher.group(1);
      }
    }

    Instant ends = Instant.now()
    System.out.println(String.format("Pattern %s, file %s, time %s", pattern, file, Duration.between(starts, ends).toString()));
```

**Comment by andrei-epure-sonarsource** [comment]
In the end, after an online discussion, I will just rely on string indexOf.

**Comment by andrei-epure-sonarsource** [comment]
This probably lead to https://community.sonarsource.com/t/stackoverflowerror-error-during-sonarscanner-execution/42089 and we reverted it for the time being.
