### ISSUE TITLE
Reduce the number of symbols retrieved by SymbolReferenceAnalyzer

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#4220]
Get the symbols only for those identifiers which appear multiple times in file (SonarQube has support only for in file highlighting).

One possible way to implement this is to register for symbols and keep a list of identifier names per file. Then, in the utility analyzers, before retrieving the symbol, check first if the identifier name is in the list of known identifiers.

**Comment by pavel-mikula-sonarsource** [comment]
Similar approach, more isolated: 
* Walk the syntax tree
* Collect names that can be translated into declared symbols (classes, members, parameters, variable declarations)
* Use this set to filter possible candidates for symbols and don't ask for symbol, if not present in the set

**Comment by pavel-mikula-sonarsource** [comment]
Going further:
* Walk the syntax tree
* Track declared symbols
* Directly use tracked symbols for standalone identifier usages

```C#
// Track triviaLines
var triviaLines = triviaContent.Split(MetricsBase.LineTerminators, StringSplitOptions.None); 

// Track triviaLineNumber
for (var triviaLineNumber = 0; triviaLineNumber < triviaLines.Length; triviaLineNumber++)
{
    // Don't ask for triviaLines symbol
    // Don't ask for triviaLineNumber symbol
    if (!IsCode(triviaLines[triviaLineNumber]))
```
