### ISSUE TITLE
Java ITs: Migrate to jUnit 5

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#4223]
In order to easily do parameterized tests and benefit of better test APIs. 

E.g. see [this code smell](https://sonarcloud.io/project/issues?id=org.sonarsource.dotnet%3Asonar-dotnet&issues=AXTHxlaBaN_sgxWhE7U2&open=AXTHxlaBaN_sgxWhE7U2)

* [x] Bump dependency to v5
* [x] Update ITs to jUnit5
* [x] Solve Orchestrator startup
* [x] Remove suite

**Comment by pavel-mikula-sonarsource** [comment]
This is now required to bump Orchestrator to 4.x series, see #7274
