### ISSUE TITLE
S2971 - do not suggest `First(...)` instead of `Where(...).First()`

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#4235]
S2971 

See [this tweet](https://twitter.com/badamczewski01/status/1381310144185839624).

This has been acknowledged by the dotnet runtime team as a "micro-optimization problem", and marked as won't fix - see From [this issue](https://github.com/dotnet/runtime/issues/19382).

Still, users may be aware of this and choose to keep the more performant version, and we shouldn't suggest this specific change.

Class to modify [CollectionQuerySimplification](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/src/SonarAnalyzer.CSharp/Rules/CollectionQuerySimplification.cs#L35)

Add test cases to [TestCases/CollectionQuerySimplification.cs](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CollectionQuerySimplification.cs)

**Comment by mary-georgiou-sonarsource** [comment]
From issues [1](https://github.com/dotnet/runtime/issues/19382), [2](https://github.com/dotnet/runtime/issues/29824), and [3](https://github.com/dotnet/runtime/issues/29824) there are benchmark tests for the overloads with predicate of `First`, `FirstOrDefault`, `Count`, `Single`

**Comment by andrei-epure-sonarsource** [comment]
My point is more about the impression we may give. The fact that, to a seasoned engineer that knows LINQ behavior, the impression might be _"ha, Sonar doesn't know this and gives bad advice"._

I am fine to close this if that's your decision based on return of investment estimation.
