### ISSUE TITLE
Skip Utility Analyzers for complex files

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#4273]
Related to  #2429. Especially [this comment ](https://github.com/SonarSource/sonar-dotnet/issues/2429#issuecomment-808374949) and [this one](https://github.com/SonarSource/sonar-dotnet/issues/2429#issuecomment-816534924).

Repro: https://github.com/costin-zaharia-sonarsource/repro-2429

## TL;DR

We should skip generating metadata for files which lead to very expensive semantic model calls. We already  have the [IsToComplex()](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/src/SonarAnalyzer.CFG/ControlFlowGraph/CSharpControlFlowGraphBuilder.cs#L500) method, and we don't generate CFGs for complex methods. 

We should do the same for Utility Analyzers.

## Longer story

> This has been raised in another community topic ([public thread](https://community.sonarsource.com/t/azure-dev-ops-c-slow-build-times/33007), and a private thread as well).
>
> The user sent us a reproducer which we can use to find the perf hotspot in our code.
>
> The file has 5800 LOC which instantiate a huge dictionary, and our analysis is put to its knees due to a single dictionary instantiation.
>
> This is likely due to us using the Semantic Model for generating the token information - we should find a way to cache this for single files, or just stop when we detect too nested syntaxes, just like we've done in [SONARSEC-1603](https://jira.sonarsource.com/browse/SONARSEC-1603).

```
  public class FooCollection<K, V> : Dictionary<K, KeyValuePair<int, FooCollection<K, V>>>
  {
    // stuff
  };

public static class Bar
  {
    public static readonly ReadOnlyDictionary<string, KeyValuePair<int, FooCollection<string, string>>> Foo = new ReadOnlyDictionary<string, KeyValuePair<int, FooCollection<string, string>>>(new FooCollection<string, string>()
    { 
   // lots and lots of nested initializations 
    }; // end of 5800 LOC
```

**Comment by costin-zaharia-sonarsource** [comment]
`TokenTypeAnalyzer` and `SymbolReferenceAnalyzer` are affected by this and most of the time is spent getting the symbol information for tokens. See [here](https://github.com/SonarSource/sonar-dotnet/blob/814b2c15a10bd83e501d3758b9625f9b1ed3cafc/analyzers/src/SonarAnalyzer.Common/Rules/Utilities/TokenTypeAnalyzerBase.cs#L155) and [here](https://github.com/SonarSource/sonar-dotnet/blob/814b2c15a10bd83e501d3758b9625f9b1ed3cafc/analyzers/src/SonarAnalyzer.Common/Rules/Utilities/SymbolReferenceAnalyzerBase.cs#L133).

**Comment by pfeigl** [comment]
We are stuck in this same situation (one File with a pretty large dictionary and builds running longer than 3h).

With hopes on this issue we installed the csharp analyzers `8.23.0.32424` which should have this fix based on your release notes.

However we still see the same 3h build times with our project. We just started a build with `/p:reportanalyzer=true` and can probably report the results if need be.

Is there anything else we can or have to do to enable this fix or should have upgrading resulted in way shorter build times?

**Comment by pavel-mikula-sonarsource** [comment]
Hi @pfeigl, there's nothing else than using 8.23 release to be done on your side to get this fix. We've put some thresholds in place to stop these analyzers from wasting time.

Can you please confirm with `/p:reportanalyzer=true` what analyzer class does takes so long?

Please copy your report to #4220 in case `TokenTypeAnalyzer` or `SymbolReferenceAnalyzer` are the ones taking too long. Otherwise feel free to submit a new issue.

**Comment by pfeigl** [comment]
Thanks for the fast response btw. From our logs it doesn't seem to be connected to those two analyzers - or atleast not exclusively.

I created #4483 with all details we have currently.
