### ISSUE TITLE
Define &, |, and ! operators for Tracker Conditions

### ISSUE THREAD

**Issue by Corniel** [SonarSource/sonar-dotnet#4305]
``` C#
public readonly struct Condition<TContext> where TContext : BaseContext
{
    public delegate bool Lamda(TContext context);

    private Lamda Lamba { get; }
    private Condition(Lamda lamda) => Lamba = lamda;

    public bool Invoke(TContext context) => !(Lamba is null) && Lamba(context);

    private Condition<TContext> Or(Condition<TContext> other)
    {
        var lambda = Lamba;
        return new Condition<TContext>((context) => lambda(context) || other.Lamba(context));
    }
    private Condition<TContext> And(Condition<TContext> other)
    {
        var lambda = Lamba;
        return new Condition<TContext>((context) => lambda(context) && other.Lamba(context));
    }
    private Condition<TContext> Not()
    {
        var lambda = Lamba;
        return new Condition<TContext>((context) => !lambda(context));
    }

    public static implicit operator Condition<TContext>(Lamda lamda) => new Condition<TContext>(lamda);
    public static Condition<TContext> operator |(Condition<TContext> l, Condition<TContext> r) => l.Or(r);
    public static Condition<TContext> operator &(Condition<TContext> l, Condition<TContext> r) => l.And(r);
    public static Condition<TContext> operator ~(Condition<TContext> l) => l.Not();
}
```

Would allow:

``` C#
using Condition = Condition<BaseContext>;
public class Conditions
{
    public static readonly Condition True = (Condition)(context => true);
    public static readonly Condition False = (Condition)(context => false);

    [Test]
    public void True_and_True_is_True()
    {
        var combined = True & True;
        Assert.That(combined.Invoke(null), Is.True);
    }

    [Test]
    public void True_and_False_is_False()
    {
        var combined = True & False;
        Assert.That(combined.Invoke(null), Is.False);
    }

    [Test]
    public void False_or_False_is_False()
    {
        var combined = False | False;
        Assert.That(combined.Invoke(null), Is.False);
    }

    [Test]
    public void True_or_False_is_True()
    {
        var combined = True | False;
        Assert.That(combined.Invoke(null), Is.True);
    }

    [Test]
    public void Not_True_is_False()
    {
        var negated = ~True;
        Assert.That(negated.Invoke(null), Is.False);
    }
}
```

I think it would increase the readability of complex conditions. Is see to (small) downsides:
1. The compiler allows to define an implicit cast, but gives a CS1660 if you apply it (so it has to be explicit).
2. You can have to use `.Invoke(context)` instead of `(context)`.

What do you think?

**Comment by pavel-mikula-sonarsource** [comment]
Hi @Corniel,

Thank you for the suggestion. We like the idea, let's give it a try.

Few points to reduce the noise in the code:
* Let's make Condition a nested type in `TrackerBase` to avoid repetition of `<TContext>` all around the place
* The implicit operator doesn't work well for delegates, let's use just a public constructor
* `Lambda` delegate would not be needed, `Func<TContext, bool>` should be enough as it's not gonna be needed outside the class anymore
* Let's use `!` instead of `~`
* The `Or`/`And`/`Not` implementations can be directly in the operators
* What's the main reason of using `struct` here?

**Comment by Corniel** [comment]
@pavel-mikula-sonarsource : well the implicit operator did not work at all, as mentioned. So you can have a explicit one, but only if you see any added value.

I agree that the delegate is not needed anymore, but I tried to keep as close to the original code, same for the generic.

About the Or/And/Not methods, that where suggestions by my IDE: [CA2225](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2225).

About the !, I was under the impression that one was not possible. It turned out, I was wrong on that one, so yes ! is preferable over ~.

About the `struct`: it is a simple wrapper around a delegate/function, that should never be `null`, and has a little overhead as possible. But a `class` is fine with me too.

About creation: new `Condition(Func<BaseContext> lambda)` is fine with me, although I think I slightly prefer ((c) => `lambda).Condition()` (so an extension method).

**Comment by pavel-mikula-sonarsource** [comment]
Unfortunately, the implicit operator doesn't work for lambas (see comment on the PR).
