### ISSUE TITLE
Fix S1450 performance regression: PrivateFieldUsedAsLocalVariable 

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#4350]
See sonar-dotnet [Performance analysis (28 April 2021)](https://xtranet-sonarsource.atlassian.net/wiki/spaces/LANG/pages/1643610461/sonar-dotnet+Performance+analysis+28+April+2021).

PrivateFieldUsedAsLocalVariable - increased from 21 seconds to 36 seconds on EfCore.

**Comment by pavel-mikula-sonarsource** [comment]
Might be related to #4589
