### ISSUE TITLE
S3168: Document behavior for virtual members

### ISSUE THREAD

**Issue by dmitry-golovinov-sonarsource** [SonarSource/sonar-dotnet#4396]
### Description

S3168 rule does not fully support new interfaces having implementation.

### Repro steps

public interface EventHandlerCasesInInterface
{
        async void MyMethod() // Compliant FN
        {
            await Task.Run(() => Console.WriteLine("test"));
        }
}

### Expected behavior

According to the rule definition, this method should be marked as problematic one, since it returns void, instead of Task

### Actual behavior

Issue is not being raised.

### Related information

* C#/VB.NET 8.22

**Comment by csaba-sagi-sonarsource** [comment]
The behavior is expected and being documented.
