### ISSUE TITLE
Fix S4507 FP: Do not raise inside StartupDevelopment class

### ISSUE THREAD

**Issue by justcoding121** [SonarSource/sonar-dotnet#4398]
### Description

If we have an override for `Startup.cs` with `StartupDevelopment.cs`, the overridden file is expected to run only on Development environment. (ASP.Net automatically does that based on ASPNETCORE_ENVIRONMENT, when it equals "Development"). In production, it won't be called.

![image](https://user-images.githubusercontent.com/2637679/117484554-744fc380-af24-11eb-8fa6-50033cd60ba1.png)

This is a false-positive for FP S4507. 

### Repro steps

Create ASP.Net core app with `Startup.cs` and override it with `StartupDevelopment.cs`. Inside the overrode call `app.UseDeveloperExceptionPage();`

### Expected behavior

If `app.UseDeveloperExceptionPage();` is called from a `StartupDevelopment.cs` file its should not trigger FP S4507

### Actual behavior

FP S4507 is raised as security bug

**Comment by pavel-mikula-sonarsource** [comment]
Hi @justcoding121, 

`ASPNETCORE_ENVIRONMENT="Development"` will provide you `env.IsDevelopment` (see [docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.hostingenvironmentextensions.isdevelopment?view=aspnetcore-5.0)). It's your responsibility to check this condition before enabling developer exception page. 

This rule found a True Positive in your case.

**Comment by pavel-mikula-sonarsource** [comment]
Hi @justcoding121,

Thank you for clarifying the root cause of your report and link to the docs. I'm reopening this as it is indeed a False Positive when the condition is placed under `StartupDevelopment` class.
