### ISSUE TITLE
S1128 UnnecessaryUsings: Whitelist namespaces that the rule should ignore

### ISSUE THREAD

**Issue by csaba-sagi-sonarsource** [SonarSource/sonar-dotnet#4456]
Make S1128 rule configurable so some commonly used namespaces could be ignored.

The related community thread can be found [here](https://community.sonarsource.com/t/add-possibility-to-have-exceptions-to-rule-s1128-unused-using-statements/42251).

**Comment by Corniel** [comment]
With the introduction of `global usings` this request have become less relevant I would argue.

**Comment by costin-zaharia-sonarsource** [comment]
Closing this, since as @Corniel mentioned the global using solves already this need.
