### ISSUE TITLE
Improve the detection time for project type (is test or main code)

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#4470]
The code which determines if a syntax tree is part of a test project or not slows down the analysis time significantly. I've done a test using `NodaTime`, `proto-actor` and `efcore` and by caching the check result we can save between 29% (`NodaTime`) to 47% (`efcore`).

![image](https://user-images.githubusercontent.com/56015273/119494347-81144a00-bd61-11eb-9db1-fb83eb1290a6.png)

**Comment by pavel-mikula-sonarsource** [comment]
As a reminder, scope of this improvement is relevant for analyzer usage in
* SonarLint 
* standalone NuGet packages. 
* SQ/SC with S4NET <= 5.0
 
SQ/SC with S4NET > 5.0  doesn't compute the `IsTest` from references (since https://github.com/SonarSource/sonar-dotnet/releases/tag/8.21.0.30542 )

**Comment by pavel-mikula-sonarsource** [comment]
Caching isn't easy to be done right.
Compilation is immutable => can't annotate.
SL/NuGet don't trigger compilation end actions to clear the cache.
Each edit in SL creates new `Compilation` instance (reused 200x in a small repro project)

**Comment by pavel-mikula-sonarsource** [comment]
Possible caching strategy: Keep last N compilations.

**Comment by pavel-mikula-sonarsource** [comment]
Possible caching strategy: Cache by `compilation.AssemblyName` for N minutes (to deal with reference changes in SL/NuGet)

**Comment by pavel-mikula-sonarsource** [comment]
For `Automapper`, the attempt to cache was inconclusive - no measurable improvement in average

**Comment by costin-zaharia-sonarsource** [comment]
Introduced by https://github.com/SonarSource/sonar-dotnet/pull/4072

**Comment by costin-zaharia-sonarsource** [comment]
> SQ/SC with S4NET > 5.0 doesn't compute the IsTest from references (since 8.21.0.30542 (release))

This means that this performance regression affects all users which:
- use versions 8.19 or 8.20 (as far as I can tell this was introduced with #4072 in 8.19)
- use a newer version of the analyzer but an old version of the scanner
- use SonarLint
- use NuGet packages

**Comment by costin-zaharia-sonarsource** [comment]
The problem is partially solved by https://github.com/SonarSource/sonar-dotnet/pull/4642 since most of the time was spent calling `.ToUpperInvariant`.

**Comment by pavel-mikula-sonarsource** [comment]
> This means that this performance regression affects all users which:

How is this a regression? `ProjectTypeHelper` was slow since it was introduced (commit history goes only as far as 03/2017)

**Comment by costin-zaharia-sonarsource** [comment]
> How is this a regression? ProjectTypeHelper was slow since it was introduced (commit history goes only as far as 03/2017)

The file was changed a couple of times. Previously there was `IsTestAssemblyName` which reduced the execution time significantly for test projects.
