### ISSUE TITLE
RSPEC-3216 Not all missing Task.ConfigureAwait(false) found by scanner

### ISSUE THREAD

**Issue by IsabelleEichbergerCyanIt** [SonarSource/sonar-dotnet#4495]
Hello,

### Description

RSPEC-3216
After updating SonarQube from version 8.8 to 8.9 suddenly more Code Smells were found than before update.
Especially blocker regarding missing Task.ConfigureAwait(false).
But we noticed that only a couple of those issues were found.
Most of that lines were passed even if ConfigureAwait(false) is missing.

### Repro steps
1. Checked in code into customers private repository (middle sized WPF application project with around 40k lines of code)
2. Jenkins build was triggered
3. SonarQube scanner was started by Jenkins build

Unfortunately we cannot share the customers project.

### Expected behavior

All lines of code with a missing Task.ConfigureAwait(false) are identified by SonarQube.

### Actual behavior

- Only a couple of lines of code with a missing Task.ConfigureAwait(false) were identified by SonarQube
- The ReSharper ConfigureAwit Checker identifies all lines locally
- We couldn't notice similar behaviour on smaller projects so far
- It seems the problem is only within the solutions startup project (but not absolutely sure)
- The startup project has 283 Files and 51 folders
- The missing ConfigureAwait(false) seems to be have found in all other projects of the solution correctly

### Known workarounds

Now workaround

### Related information

* C#/VB.NET Plugins version: 7.3
* Visual Studio version: Visual Studio Professional 2019
* MSBuild / dotnet version: .NET Framework 4.7.2
* SonarScanner for .NET version (if used): 8.9
* Operating System: Windows 10 Pro

Please let me know what further information I can provide.

Regards,
Isabelle

**Comment by pavel-mikula-sonarsource** [comment]
Hi @IsabelleEichbergerCyanIt,

We don't know where your public source code is stored and we don't have access to your private projects to identify the issue. Our GitHub template for reporting issues contains this part, that is crucial for any investigation:

### Repro steps

Please provide a minimal code snippet that compiles which reproduces the problem. Alternatively, you can share a link to the SonarCloud public project where the issue appears. If the issue requires some specific project configuration to reproduce, you can create a minimal reproducible project and share its git repository or attach it as a ZIP file.

**Comment by pavel-mikula-sonarsource** [comment]
Hi @IsabelleEichbergerCyanIt ,

>Please provide a minimal code snippet that compiles which reproduces the problem.

We really need this part to see the code in question. Without that, we have no way to know how the code looks like or what the specific case is.
