### ISSUE TITLE
Fix S1698 NullReferenceException

### ISSUE THREAD

**Issue by runehalfdan** [SonarSource/sonar-dotnet#4525]
### Description

  CSC : error AD0001: Analyzer 'SonarAnalyzer.Rules.CSharp.ReferenceEqualityCheckWhenEqualsExists' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

### Repro steps

The issues isn't stable; it only happens on build-servers, and a rebuild will resolve the issue. 

### Known workarounds

A rebuild will resolve it, only workaround is to disable check (It would have been useful to see diagnostid ID in error-message)

### Related information

Visual Studio 2019 Professional, v16.10
 .NET SDK 5.0300
SonarAnalyzer 8.23.0.32424

Rules for SonarAnalyzer are currently defined in a .ruleset file, but we are in the process of migrating rules to .globalconfig

Analyzed projects target .NET Standard 2.0 for dlls, .NET Core 2.2 on endpoints. Error occurs on both kinds of projects.

**Comment by pavel-mikula-sonarsource** [comment]
Hi @runehalfdan, 
How do you consume the analyzer? Do you use NuGet packages?
Are you sure that 8.23 is the version in your build? We've released 8.24 yesterday.
Do you have an idea for how long this issue happens already?

We saw similar issue, but we're having trouble to reproduce it as it keep disappearing when we try to reproduce it.

**Comment by runehalfdan** [comment]
> Hi @runehalfdan,
> How do you consume the analyzer? Do you use NuGet packages?
> Are you sure that 8.23 is the version in your build? We've released 8.24 yesterday.
> Do you have an idea for how long this issue happens already?
> 
> We saw similar issue, but we're having trouble to reproduce it as it keep disappearing when we try to reproduce it.

We consume the analyzer as nuget packages, using PackageReference. I'm 99% certain it started to happen after we upgraded to SonarAnalyzer 8.23, and 98% certain it was after we upgraded to Visual Studio 19 16.10 (which I think updated .NET 5 SDK to 5.0.300)

Will re-enable checks and update to SonarAnalyzer 8.24. Will report here if I see problem again.

**Comment by pavel-mikula-sonarsource** [comment]
Using 8.24 will not fix the issue. The SDK update might be the trigger.

**Comment by pavel-mikula-sonarsource** [comment]
Issue reported to .NET Roslyn: https://github.com/dotnet/roslyn/issues/53943

**Comment by runehalfdan** [comment]
> ### Description
> CSC : error AD0001: Analyzer 'SonarAnalyzer.Rules.CSharp.ReferenceEqualityCheckWhenEqualsExists' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
> 
> ### Repro steps
> The issues isn't stable; it only happens on build-servers, and a rebuild will resolve the issue.
> 
> ### Known workarounds
> A rebuild will resolve it, only workaround is to disable check (It would have been useful to see diagnostid ID in error-message)
> 
> ### Related information
> Visual Studio 2019 Professional, v16.10
> .NET SDK 5.0300
> SonarAnalyzer 8.23.0.32424
> 
> Rules for SonarAnalyzer are currently defined in a .ruleset file, but we are in the process of migrating rules to .globalconfig
> 
> Analyzed projects target .NET Standard 2.0 for dlls, .NET Core 2.2 on endpoints. Error occurs on both kinds of projects.

**Comment by runehalfdan** [comment]
Update: After upgrading to SonarAnalyzer 8.24, and .NET 5 sdk 5.0.301, we haven't seen this crash again. Not sure if coincidence or result of the updates though
