### ISSUE TITLE
S2077 rule is not triggered for EF core 3.1 and up

### ISSUE THREAD

**Issue by balteravishay** [SonarSource/sonar-dotnet#4533]
### Description

Since EFCore 3.x, rule S2077 is not triggered for sensitive code as expected, due to change of API to execute SQL commands

### Repro steps

// this code from the sonar-dotnet docs will not trigger S2077 as expected. 
context.Database.ExecuteSqlRaw(sensitiveQuery); // Sensitive

// this could would work, but is no longer valid in .net core 3.x and up.
// context.Database.ExecuteSqlCommand(sensitiveQuery); // Sensitive

### Expected behavior

Code written in .net core 3.1 where formatted SQL queries are found should trigger S2077 rule.

### Actual behavior

No error.

### Known workarounds

none

### Related information

* C#/VB.NET Plugins version: 8
* Visual Studio version: VSCode
* MSBuild / dotnet version : 3.1 and up
* SonarScanner for .NET version (if used): 8.23.0.32424
* Operating System: MacOSX

**Comment by costin-zaharia-sonarsource** [comment]
Hi @balteravishay! 

thanks for your feedback. We have a ticket to update the signatures and support additional frameworks and I have updated that one to include support for efcore 3+. You can follow the progress here: #3905
