### ISSUE TITLE
S4026: Show assembly name in the error message

### ISSUE THREAD

**Issue by lg2de** [SonarSource/sonar-dotnet#4539]
### Description

csharpsquid:S4026
Assemblies should be marked with "NeutralResourcesLanguageAttribute"

The issue is raised on a complex solution.
In SonarQube server it is not assigned to the affected assembly.
I only see the following message: `Mark this assembly with 'System.Resources.NeutralResourcesLanguageAttribute'`

![image](https://user-images.githubusercontent.com/44983012/121546734-d1e79c00-ca0b-11eb-9ded-106db96196f5.png)

### Known workarounds

N/A

### Related information

* C#/VB.NET Plugins version: SQ 8.8
* SonarScanner for .NET version: 5.0.4
* Operating System: Windows

**Comment by pavel-mikula-sonarsource** [comment]
Hi @lg2de ,

Thank you for pointing this out.

**Comment by pavel-mikula-sonarsource** [comment]
Message an implementation should be similar to `MarkAssemblyWithAssemblyVersionAttribute`
