### ISSUE TITLE
Should process AnonymousObjectMemberDeclarator in CFG

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#4555]
We don't seem to process the `AnonymousObjectMemberDeclarator` syntax at all in the CFG. 

That means that we cannot propagate values inside anonymous objects like below:
```
        var anonymous = new
        {
            IV = new byte[] { 0x00 },
            Key = new byte[] { 0x00 }
        };
```

See [sharplab snippet.](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNGSAmIDUAfAAQAYACAgRgBYBuAWACgCBmMgJhIGESBvBk/siwKUSAWQAUASh58BcgG4QEJCADsA9qoCeYdQFcoJALwlVcAO6y5/XvWv2SASQBqx0xZLAt8ANoBdHhIiAA8iUgBfJCsHfgBpOC03M3NPbzh/QJCwknDouXC6OwFc+nCgA=)

**Comment by martin-strecker-sonarsource** [comment]
New SE engine: No longer relevant.

**Comment by pavel-mikula-sonarsource** [comment]
The SE is not field sensitive, so CFG would not be enough to track this through
