### ISSUE TITLE
Update the sonar-ws version in our SQ integration tests

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#4587]

**Comment by csaba-sagi-sonarsource** [comment]
Also update [sonar.version](https://github.com/SonarSource/sonar-dotnet/blob/291daecfd1593ac49f8f1eb51db9c1804181d43a/pom.xml#L58) to the newest version.

**Comment by csaba-sagi-sonarsource** [comment]
Also update [sonar.version](https://github.com/SonarSource/sonar-dotnet/blob/291daecfd1593ac49f8f1eb51db9c1804181d43a/pom.xml#L58) for the newest version.

**Comment by costin-zaharia-sonarsource** [comment]
We are using now dependabot to keep the dependencies up to date. We will update it either when we're notified or, as needed, when working on the plugin.
