### ISSUE TITLE
Migrate S3949 to the new Symbolic Execution engine

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#4631]
Currently [S3949](https://rules.sonarsource.com/csharp/RSPEC-3949) is the only rule implemented using CBDE. 

The CBDE engine is no longer maintained and planned to be removed and reimplementing the rule will enable this.

This should be done on a feature branch.

ToDo:

- [x] Step 1:
  * Scaffold RSPEC
  * Add test cases from CBDE
  * Add missing test cases from https://github.com/SonarSource/dotnet-overflow
  * Add C# 9, C# 10, C# 11 test cases.
- [x] Step 2: Implement the rule logic
- [ ] Step 3: Implement ShouldExecute

**Comment by pavel-mikula-sonarsource** [comment]
CBDE deprecation was [announced before 9.x LTS](https://community.sonarsource.com/t/c-calculations-should-not-overflow-rule-is-changing/69553).

We will use the new Roslyn-based SE to implement the rule.

**Comment by Tim-Pohlmann** [comment]
`ShouldExecute` should skip when the method...
- ... is `GetHashCode`.
- ... contains the `unchecked` keyword.
