### ISSUE TITLE
SQ Plugin: Remove deprecated import of integration test coverage from plugins

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#4685]
We should remove them because they have been deprecated since SonarQube 6.2!

```
    if (this.isIntegrationTest) {
      LOG.warn("Starting with SonarQube 6.2 separation between Unit Tests and Integration Tests Coverage" +
        " reports is deprecated. Please move all reports specified from *.it.reportPaths into *.reportPaths.");
    }
```

Repro steps:
1. Open a project in SonarCloud/SonarQube
2. Go to Administration -> General Settings -> Languages
3. Choose C#

It shows for example
![image](https://user-images.githubusercontent.com/38876598/125745544-957a660e-9149-4154-a081-5bd0b99ddb5b.png)

However coverage for integration tests is deprecated.

The same, it shows NCover3
![image](https://user-images.githubusercontent.com/38876598/125745592-8cb427b3-db9a-4125-9bee-4ca2686a5545.png)

**Comment by pavel-mikula-sonarsource** [comment]
This should remove the properties that our plugins publish, and their processing.
