### ISSUE TITLE
New Rule Idea: Null Checking for Non-Nullable Reference Types

### ISSUE THREAD

**Issue by tom-howlett-sonarsource** [SonarSource/sonar-dotnet#4707]
See https://community.sonarsource.com/t/null-check-in-times-of-c-8-non-nullable-reference-types/14066/2

When using non-nullability feature I want to ensure I do not get null values from an outside library so all parameters should be checked for null

**Comment by pavel-mikula-sonarsource** [comment]
Merging to #7035, that has the same idea
