### ISSUE TITLE
Not generating metadata files for ASP .NET 5 MVC project

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#4709]
Reported on https://community.sonarsource.com/t/not-analyzing-cs-files-only-cshtml-js-etc/46662/6
- _update_: also reported on https://community.sonarsource.com/t/lines-of-code-blank-for-c-files-in-net-5-project/46908

Reproducer on https://github.com/andrei-epure-sonarsource/aspnet5mvc-reproducer . Repro steps in the README.

SonarQube 9.0 Developer Edition
Scanner for .NET 5.2.2 (latest)

The 2 issues (`AspNetCoreMvc5\Program.cs(12,18): warning S1118` and `AspNetCoreMvc5\Controllers\HomeController.cs(14,50): warning S4487` ) appear on the C# files, however there are no metrics and no highlighting for the C# code - the existing metrics are only for the JS code.

- Actual: no metrics, no highlighting for C# code. 
- Expected: metrics and highlighting for C# code.

The metadata protobuf files in `.sonarqube\out\0\output-cs` are empty - `metrics.pb`, `symrefs.pb`, `token-cpd.pb`, `token-type.pb`. To investigate we need to debug and/or add logging (to a local file) in the Utility Rules: https://github.com/SonarSource/sonar-dotnet/tree/master/analyzers/src/SonarAnalyzer.Common/Rules/Utilities . 

🤔 _Is there something special about the ASP .NET 5 MVC compilation of controllers and models?_

We need to investigate this as a priority.

**Comment by pavel-mikula-sonarsource** [comment]
Sounds like an issue on S4NET side with the build orchestration. There already is some logic on S4NET side to deal with that and it's probably not working probably with the latest combination of scanner/SDK/MVC or something like that.

We should not try to brute-force workaround this on analyzer side.

**Comment by nicklasjepsen** [comment]
I created the issue originally in the community forum, and just want to add that we see the same behavior when we use the VS plugin: No metrics and highlighting, except for one issue: 
`Warning S1118 Add a 'protected' constructor or the 'static' keyword to the class declaration.	...Program.cs`

**Comment by csaba-sagi-sonarsource** [comment]
The root cause of the issue is that the analzyers generating the metadata are invoked twice (once for CoreCompile nad once for RazorCoreCompile) and the second Roslyn compilation is overwriting the initial results. I opened an [issue ](https://github.com/SonarSource/sonar-scanner-msbuild/issues/1040)on scanner side, to fix this behavior.

**Comment by pavel-mikula-sonarsource** [comment]
There's no action for now for this repository.

**Comment by pavel-mikula-sonarsource** [comment]
Will be handled in https://github.com/SonarSource/sonar-scanner-msbuild/issues/1040
