### ISSUE TITLE
S3903 False Positive when using File Scoped namespaces.

### ISSUE THREAD

**Issue by AraHaan** [SonarSource/sonar-dotnet#4731]
### Description

When using file scoped namespaces in code, S3903 is emitted then on compile.

### Repro steps

Take for example this code:

```cs
global using System;

namespace TestNamespace;

public class Class1
{
    public void Test()
    {
        Console.WriteLine("Testing...");
    }
}
```

And then enable ``TreatAllWarningsAsErrors``.

### Expected behavior

No diagnostics reported for using the C# 10 File Scoped namespaces feature.

### Actual behavior

A diagnostics is reported for using the C# 10 File Scoped namespaces feature.

### Known workarounds

There are none other than not using the C# 10 feature. Which would result in a sucky experience as that would add useless indentation levels to my codebases.

### Related information

* C#/VB.NET Plugins version: None
* Visual Studio version: Currently using on Mac with the .NET CLI
* MSBuild / dotnet version: 6.0.100.rc.1 daily builds
* SonarScanner for .NET version (if used): latest
* Operating System: MacOS v12 Beta 3

**Comment by AraHaan** [comment]
Also can be reproduced in https://github.com/Elskom/Sdk/pull/244/.

**Comment by AraHaan** [comment]
cc @pavel-mikula-sonarsource Any plans to fix this as soon as possible so that way when Preview 7 goes live the analyzer would be ready for the masses that will start their migrations to file-scoped namespaces?

**Comment by csaba-sagi-sonarsource** [comment]
Hello @AraHaan 

Thank you for reporting this issue. I can confirm it as a False Positive, however I cannot give you an ETA for the fix.

**Comment by AraHaan** [comment]
Thanks, for now I worked around it by suppressing that rule. Please mention me when there is a release with a fix so then I can open an PR on my project to remove those suppressions.

**Comment by csaba-sagi-sonarsource** [comment]
Hello @AraHaan 
The fix for this issue just got merged, and it will be part of the 8.32 version of the analyzer.

**Comment by SteveDesmond-ca** [comment]
Thanks for the update, @csaba-sagi-sonarsource -- any update on when 8.32 will be released? I just updated a dozen of my projects and now they all have horrible ratings :sob:

**Comment by SteveDesmond-ca** [comment]
Sorry, NuGet was using cached metadata, I see 8.32 has been released -- thanks!

**Comment by marcin-sowa** [comment]
Do you know how we can use this latest 8.32 analyzer for our .NET Core projects?

**Comment by costin-zaharia-sonarsource** [comment]
Hi @marcin-sowa, how do you currently use the analyzer?

**Comment by marcin-sowa** [comment]
We run them in docker:

```
RUN dotnet tool install --global dotnet-sonarscanner
RUN dotnet new console
RUN dotnet sonarscanner begin  /d:sonar.host.url=URL  /d:sonar.login=TOKEN /k:test_project /d:sonar.verbose=true
RUN dotnet build
RUN dotnet sonarscanner end /d:sonar.login=TOKEN
```

**Comment by costin-zaharia-sonarsource** [comment]
Thanks for your answer. I understand from your comment that you use either SonarQube or SonarCloud.

If you use SonarCloud the changes were already deployed so you should have the latest version.

If you use SonarQube, you can download the latest version from https://www.sonarqube.org/downloads/. Currently, the latest version is 9.2 and it has the C# 8.32 analyzer embedded.

**Comment by marcin-sowa** [comment]
@costin-zaharia-sonarsource thank You very much for explaining, I use bitnami image to run Sonarqube test server.
I've try latest image from 9.1 version, but there is 8.29.0.36737 version of analyzer used.

Is there any way to update this manually, or we have to migrate?
My main server is running version 8.9, is there any option for update?

**Comment by costin-zaharia-sonarsource** [comment]
I don't know what's the proper way to update this kind of environment. I think that you can get more help asking [here](https://community.sonarsource.com/). 

One hacky way is to replace the csharp and vb plugins (path `sonarquve-{version}\lib\extensions`) with the plugin files from [our release](https://github.com/SonarSource/sonar-dotnet/releases/tag/8.32.0.39516) but this will not be supported. The best would be to ask on the forum.

**Comment by busches** [comment]
@costin-zaharia-sonarsource any reason these analyzers are not backported to the latest LTS when possible? e.g. 8.9?

**Comment by pavel-mikula-sonarsource** [comment]
@busches new features are not backported to LTS. Only blocker vulnerabilities and bugs are backported to LTS. Where `bug` means something that prevents the code from being analyzed.

You can find more information about LTS strategy here: https://www.sonarqube.org/downloads/lts/ It also explains the conceptual difference in LTS vs. the latest release.
Please check our [community forum](https://community.sonarsource.com/) if you have further questions about LTS.

**Comment by busches** [comment]
Makes sense, except this is a bug?
