### ISSUE TITLE
Improve CFG for `try` statement: connect finally statements after break/continue/goto

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-dotnet#474]
Consider the following code:
```
while (a)
{
    try
    {
        continue; // for simplicity this is not conditional
    }
    finally
    {
        ...
    }
}
```

## Actual Behavior
The `finally` block in the CFG will not be connected to the `continue` block.

## Expected Behavior
The `finally` block is connected to each path that exits the `try/catch` statement, including `return` (already handled), `continue`, `break` and `throw` for unhandled exceptions. Consider supporting `goto` as well.

## Possible Solution
We could investigate if we duplicate the `finally` block for each exit path will have negative side effects.

**Comment by andrei-epure-sonarsource** [comment]
Part of this (maybe split into sub-tasks) should be:
- remove the 2 finally catch blocks
- fix the weird shape where there is a `break` inside the try inside a loop

**Comment by andrei-epure-sonarsource** [comment]
due to the complexity of the necessary changes, we will probably need to do a sprint only on improving the CFG representation of the try.

See #2550 for explanations for the `try-catch` part. This is related.

**Comment by gregory-paidis-sonarsource** [comment]
Closed as we do not work anymore in the old SE engine.
