### ISSUE TITLE
Rule S110: should support concurrent execution

### ISSUE THREAD

**Issue by dmitry-golovinov-sonarsource** [SonarSource/sonar-dotnet#4745]
### Description

When launching test AvoidExcessiveInheritance_DefaultValues with concurrent execution on, we've got the issue, that Other_6 class (line 61) has 13 parents instead of 6 expected. This is obviously not correct and needs to be investigated and fixed. After that, concurrent execution could be enabled for that rule.

### Expected behavior

AvoidExcessiveInheritance_DefaultValues test should pass in concurrent mode.

### Related information

* C#/VB.NET Plugins version 8.27

**Comment by pavel-mikula-sonarsource** [comment]
To reproduce the issue, the whole file is currently wrapped in a namespace for concurrency. So the problem is related to double-nested namespaces.

UT should be added to `_DefaultCases.cs`.

This mign not be related to concurrency, but can be just a FP in that double-nested case.
