### ISSUE TITLE
IllegalStateException Not a JSON Object: null

### ISSUE THREAD

**Issue by YulerB** [SonarSource/sonar-dotnet#4771]
Run sequential.

### Related information

Running in Jenkins Agent
Sonarqube Server v7.9 (hosted)
Sonarqube Scanner Issue occurs with v5.2.2, v4.10.0

INFO: SonarScanner 4.6.1.2450
INFO: Java 11.0.11 Oracle Corporation (64-bit)
INFO: Linux 3.10.0-1160.24.1.el7.x86_64 amd64
INFO: Analyzing on SonarQube server 7.9.0

**Comment by pavel-mikula-sonarsource** [comment]
Hi @YulerB,

Thanks for letting us know about the cause. I'll copy it here from the PR for archeology reasons.

> @YulerB
> Closing, turns out this is an issue reading roslyn files for sonar scan, while dotnet publish is happening in parallel.
