### ISSUE TITLE
Reduce the ci pipeline running time: Improve NuGet caching

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#4798]
## The problem

Running the .Net unit tests suite takes about 85% from the total build time. 
E.g.
- 30m out of 35m for the following build: https://dev.azure.com/sonarsource/DotNetTeam%20Project/_build/results?buildId=35318&view=results
- 32m out of 37m for: https://dev.azure.com/sonarsource/DotNetTeam%20Project/_build/results?buildId=35317&view=results

## Anatomy of a build
.Net Unit tests stage takes about (30m):
- .Net UTs (28m)
	- nuget restore
	- build project to run the analysis (3m)
	- run tests for net48 (13m)
	- run tests for net5 (10m 43s)

# Improvement

Regenerate the VM image every night with a fresh NuGet cache. One option to achieve this is by using the template image as a baseline, running a master build on top of it to download the missing NuGet packages (running .Net unit tests should be enough) and building a copy image.

**Comment by pavel-mikula-sonarsource** [comment]
It's done
