### ISSUE TITLE
S1155: Implement a fix provider for C#

### ISSUE THREAD

**Issue by Corniel** [SonarSource/sonar-dotnet#4841]
Rule S1155 checks if check on the size of the enumeration is equivalent for checking for emptiness.  Based on the outcome, it rather trivial to generate a fix provider to convert the expression into a `.Any()` or not `.Any()` expression.

```  C#
item.Count() >=1;
items.Count < 1;
```
Should convert to
```
items.Any();
!items.Any();
```

**Comment by Corniel** [comment]
Why has this been closed? It has not been shipped?

**Comment by pavel-mikula-sonarsource** [comment]
I see this issue in `Open` state

**Comment by pavel-mikula-sonarsource** [comment]
Ah, it's the PR #4807  that was closed. I'll leave a note there
