### ISSUE TITLE
Improve Symbolic Execution Engine to handle '.HasValue' on nullables

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-dotnet#490]
### Description

Current implementation #485 is not learning from calls to `.HasValue`. Learning from them would allow to fix some False Negative on [EmptyNullableValueAccess.cs](https://github.com/SonarSource/sonar-csharp/blob/master/sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/EmptyNullableValueAccess.cs).

**Comment by CristianAmbrosini** [comment]
The rule has been migrated to the new Symbolic Execution engine that supports the tracking of nullable value types.
