### ISSUE TITLE
Improve Symbolic Execution Engine to unwrap inner SV and constraints

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-dotnet#491]
### Description

Current implementation #485 does not propagate correctly SV and constraints when calling `.Value` on nullable.

**Comment by Evangelink** [comment]
I haven't looked at the code base in ages, is the SE still OSS in this repo?

**Comment by pavel-mikula-sonarsource** [comment]
Hi, sure: 
https://github.com/SonarSource/sonar-dotnet/tree/master/analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn

The new implementation is based on Roslyn CFG.

**Comment by pavel-mikula-sonarsource** [comment]
And this puppy does the trick: 
https://github.com/SonarSource/sonar-dotnet/blob/4383deee2e25a3830993e5436509dc81afc72d9f/analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs#L82

**Comment by Evangelink** [comment]
> The new implementation is based on Roslyn CFG.

Glad to see you moved to Roslyn CFG <3
