### ISSUE TITLE
Modify the dev-build.ps1 script to be able to run all tests for all language versions

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#4992]
Currently [TestContextHelper](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/TestContextHelper.cs#L25) is used to determine if all language versions which are defined by a test case should be used when running the tests.

By default, this happens only on the main branch build. On local and PR env, it will only run the last version from the given list (i.e. if the test says "run with all versions From C#7", it will run only with C#9 (or whatever is newer).

We sometimes do sprints where we add support for new language features and it's easy to miss such tests. Recent PRs that broke the build : #4970, #4981.

To fix this, the most convenient way is to be able to run all tests on a Release build from the `dev-build.ps1`. It should have a new parameter to specify that the build should be executed locally like on the main branch.

**Comment by pavel-mikula-sonarsource** [comment]
@andrei-epure-sonarsource Can you please take a look at the previous message?

**Comment by costin-zaharia-sonarsource** [comment]
Ping @andrei-epure-sonarsource, is this still relevant?

**Comment by andrei-epure-sonarsource** [comment]
I apologize, I missed @pavel-mikula-sonarsource 's comment.

Indeed, it should work.
