### ISSUE TITLE
Improve S3925 message to be clear about expected action.

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#4993]
This S3925 snippet
```
public class SomeException : Exception { }
```

produces 

>S3925	Update this implementation of 'ISerializable' to conform to the recommended serialization pattern.	

There are 9 different things that can go wrong with this rule. It's not clear what action is (or what actions are) expected to be done.

**Comment by m-gallesio** [comment]
Is this being worked on?

**Comment by pavel-mikula-sonarsource** [comment]
@m-gallesio no, there's no active work on it. For now, it's recorded in the backlog.

**Comment by StingyJack** [comment]
@pavel-mikula-sonarsource  this is also happening for classes that derive from `Dictionary<Tk, Tv>`.  

![image](https://user-images.githubusercontent.com/15381181/181028854-f235936b-d2e5-4d7d-81f5-a131b136cae5.png)

**Comment by bitbonk** [comment]
This rule should be disabled for .NET Core and .NET 5 and greater.

**Comment by martin-strecker-sonarsource** [comment]
We are going to improve the primary message with details from the secondary locations. Regarding the other issues mentioned in the thread (deprecation, dictionary, etc.) please have a look at what we did in #7673 and #8377: Binary serialization is "opt-in" now and requires at least one of the serialization properties to be present (`ISerializable, or `[Serializable]` or serialization constructor).
