### ISSUE TITLE
S3442 should suggest `private protected` instead of `protected`

### ISSUE THREAD

**Issue by shuebner** [SonarSource/sonar-dotnet#5006]
### Description

S3442 suggests to make an `internal` constructor of an abstract class `protected`:

![image](https://user-images.githubusercontent.com/1770684/138837154-90ba0b76-6f4f-432d-b85e-ca0e3827a64b.png)

When the abstract class only has internal constructors, it cannot be inherited from by other assemblies.
Following the suggestion changes semantics, since now other assemblies may derive from the class.
This may not be wanted.

I propose that S3442 suggest using `private protected` instead.
This way, the `internal` aspect is not lost.

### Repro steps

```
public abstract class S3442Repro
{
    internal S3442Repro()
    {
    }
}
```

### Expected behavior

S3442 suggests using `private protected` instead of `internal`.

### Actual behavior

S3442 suggests using `protected` instead of `internal`.

### Related information

* C# analyzer 8.30.0.37606
* Visual Studio version 16.11.5
* MSBuild / dotnet version 5.0.402
* Operating System: Windows 10

**Comment by pavel-mikula-sonarsource** [comment]
Hi @shuebner,

Thank you for reporting this case. I confirm it as a thing to improve.
