### ISSUE TITLE
Enable concurrent execution by default

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#5074]
In #3164 / #4750 we enabled concurrent execution only based on an environment variable.

We wanted to wait for feedback from customers, however this did not happen (we did [the announcement in August](https://community.sonarsource.com/t/net-analyzer-supports-concurrent-execution-and-more-c-9/48015)).

Based on our initial tests, we had [mixed results](https://docs.google.com/spreadsheets/d/1AfrWu8NUQpUdXqKWyvuUvqBbT2nFxC7WY0YctAFJuqk/edit#gid=0) on whether this helps or not, especially on large projects (sometimes analysis took more time). I believe most tests were done on Peachee, where the GCP VM is n1-standard-8  (8 vCPU | RAM 30720 MiB | Storage 10Gb Standard (Non-SSD)) - it would be worth to test with more powerful machines as well.

After doing these tests, we should turn it on in our next release and deploy it on SonarCloud. We should still keep the environment variable to allow to turn the feature off in case the users have a problem. We should make this explicit in the documentation and the release announcement.

**Comment by andrei-epure-sonarsource** [comment]
I ran the peachee analysis on VMs with 32 vCPUs instead of 8 vCPUs. 

- for most jobs, w/ or w/o CONCURRENT_EXECUTION enabled, the build times are worse
- for some jobs, enabling concurrent execution improved build time, for others it did not

We need to understand better how msbuild works with concurrency, play around with max number of CPUs used by the build and:
1. see what is the best hardware configuration to improve build times w/o CONCURRENT_EXECUTION enabled
2. enable concurrent execution and see if the build times regress or improve

**Comment by costin-zaharia-sonarsource** [comment]
We did one more sprint to check the performance with concurrency enabled on different hardware configurations. The results are documented [here](https://docs.google.com/spreadsheets/d/1dLgghzl_0apOtwDXq5jtwbwWZDDdAW3mxDX4t3fxcSs/edit#gid=1786875653) (internal link).

## Conclusions

- overall, the measurements are not very precise but they are good enough to show us the trend
- concurrent analysis is slightly better
- we do a good job benefiting from the CPU number increase
- increasing the number of CPUs to 16 reduces the analysis time significantly and is the most impactful
- increasing the number of CPUs to more than 16 will further reduce the analysis time but the improvement is marginal
- memory increase does not matter that much

While doing these tests we dived a bit in the Roslyn code and we found out that:
- concurrent analysis is disabled in the IDE
- during the normal build, the analyzers are run in parallel one with another even if the `EnableConcurrentExecution()` was not called for them
- the only thing we can control with `EnableConcurrentExecution()` is letting the compile know if the analyzer can run concurrently with itself (its actions can be executed concurrently). The compiler will later decide if will run them concurrently or not.

A few examples:
![Lucene](https://user-images.githubusercontent.com/56015273/157398392-a66f9aed-bc4f-41ed-a828-8608287f88cb.png)
![BenchmarkDotNet](https://user-images.githubusercontent.com/56015273/157398394-5d70b90b-7d6e-4987-9629-efc28bc33f61.png)
![AspNetCore](https://user-images.githubusercontent.com/56015273/157398395-6c1ee5fc-2122-4bdc-b606-891f63328f06.png)

**Comment by andrei-epure-sonarsource** [comment]
As a possible explanation to why back in December the results were worse when adding more CPU - [SONARSEC-2812](https://jira.sonarsource.com/browse/SONARSEC-2812) (which has been mitigated for the moment by [SONARSEC-2848](https://jira.sonarsource.com/browse/SONARSEC-2848), hence the behavior changed during measurements).

The root cause of that problem is in the Rolsyn compiler https://github.com/dotnet/roslyn/issues/58863.
