### ISSUE TITLE
Release-Assets are broken for the latest releases > 8.30

### ISSUE THREAD

**Issue by Jazzman82** [SonarSource/sonar-dotnet#5077]
there is obviously a problem with the assets (.jars) of the latest releases which are available here: https://github.com/SonarSource/sonar-dotnet/releases

The .jars are only a few KBs of size and in fact contain some html-content.

**Comment by pavel-mikula-sonarsource** [comment]
Hi @Jazzman82, thanks for noticing! We'll take a look on what went wrong there.

**Comment by pavel-mikula-sonarsource** [comment]
@Jazzman82 Attached released artifacts are fixed now. We'll investigate how/why that happened..

**Comment by pavel-mikula-sonarsource** [comment]
@costin-zaharia-sonarsource Please review the workaround here: https://dev.azure.com/sonarsource/DotNetTeam%20Project/_releaseDefinition?definitionId=15&_a=definition-tasks&environmentId=37

**Comment by pavel-mikula-sonarsource** [comment]
The root cause was fixed in the release pipeline.
