### ISSUE TITLE
Use DocumentBasedFixAllProvider for all Code Fixes

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#5266]
`WellKnownFixAllProviders.BatchFixer` doesn't work well with many of our code fixes and cannot be used everywhere. 

It's confusing to have two different FixAllProviders in the codebase.

`DocumentBasedFixAllProvider` can highlight more code fix implementation flaws.

**Comment by costin-zaharia-sonarsource** [comment]
I think it would be great to document here a couple of unsupported scenarios to be able to remember why we took this decision and avoid some pains in the future if we will try to add this back.
