### ISSUE TITLE
SonarLint.xml: Missing options for S104 and S1541 to configure

### ISSUE THREAD

**Issue by anreton** [SonarSource/sonar-dotnet#5299]
### Description
Maximum lines count threshold for S104 and cyclomatic complexity threshold for S1541 are missing in SonarLint.xml.

### Related information
- [S104](https://rules.sonarsource.com/csharp/RSPEC-104)
- [S1541](https://rules.sonarsource.com/csharp/RSPEC-1541)
- [SonarLint.xml](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/.sonarlint/sonaranalyzer-dotnet/CSharp/SonarLint.xml)

**Comment by pavel-mikula-sonarsource** [comment]
Hi @anreton,

When using SonarQube and SonarCloud, parameters are not supposed to be emitted to the file when having default values.

This repository does not generate `SonarLint.xml` file so I'm sure there will be no further action on this ticket here. Please follow up on our [community forum](https://community.sonarsource.com/c/help/8) with other details (especially what product do you use, what version, what is your setup, how did you configure your quality gete and so on) if you need any further assistance.

**Comment by anreton** [comment]
@pavel-mikula-sonarsource, thank you for the quick response.

Sorry for not providing enough information in the description. I'm using the nuget version of SonarLint (8.34.0.42011).

In .editorconfig I can only set severity but not threshold for different analyzers. However, they can be configured via SonarLint.xml.

Since I don't use SonarQube or SonarCloud, I can only create SonarLint.xml manually. And I took  [SonarLint.xml](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/.sonarlint/sonaranalyzer-dotnet/CSharp/SonarLint.xml) as an example of such a file, believing that it contains all possible settings.

And not finding the settings for the two analyzers ([S104](https://rules.sonarsource.com/csharp/RSPEC-104), [S1541](https://rules.sonarsource.com/csharp/RSPEC-1541)), I asked myself questions:
- Can't they be customized?
- Just forgot to add to the file? If so, maybe they should be added for completeness?

**Comment by anreton** [comment]
I analyzed the source code of these analyzers and found the missing settings:
- [S104](https://github.com/SonarSource/sonar-dotnet/blob/48071ce086fbb5c564a0701310a2a68d932ab092/analyzers/src/SonarAnalyzer.Common/Rules/FileLinesBase.cs) - maximumFileLocThreshold
- [S1541](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/src/SonarAnalyzer.CSharp/Rules/FunctionComplexity.cs) - maximumFunctionComplexityThreshold

**Comment by pavel-mikula-sonarsource** [comment]
The `SonarLint.xml` you've used as a template is a configuration of our own project. It's autogenerated file that is not supposed be used as a template.

Those two rules can be customized and you can add them manually to your SonarLInt.xml

I suggest you creating a new organization on SonarCloud. It's free. Configure a quality profile there with all the settings you need. Create an empty project and run a `begin` step of the `SonarScanner for .NET` with that project. That will generate a ruleset file and `SonarLint.xml` file for you.
