### ISSUE TITLE
Unable to install or update NuGet package in Visual Studio 2022

### ISSUE THREAD

**Issue by dougwaldron** [SonarSource/sonar-dotnet#5334]
Trying to install or update the SonarAnalyzer.VisualBasic NuGet package fails in Visual Studio 2022. The error message displayed is "This package can only be installed on Visual Studio 2015 Update 3 or later." I assume the same error would occur for the SonarAnalyzer.CSharp package.

I can update the package by directly editing the "packages.config" file.

The problem seems to be [these lines in install.ps1](https://github.com/SonarSource/sonar-dotnet/blob/3a67c9104315465eaa204442ad58cca02e67f27c/analyzers/packaging/tools-vbnet/install.ps1#L5-L7):

```powershell
if ('14.0', '15.0', '16.0' -notcontains $project.DTE.Version) {
    $invalidVsVersion = $true
}
```

Visual Studio 2022 is version 17!

**Comment by pavel-mikula-sonarsource** [comment]
Hi @dougwaldron,

Thank you for catching and reporting this. 

I can reproduce it when adding package to .NET Fx project, it doesn't reproduce for .NET Core project.

**Comment by dougwaldron** [comment]
Thanks for the quick fix!

**Comment by costin-zaharia-sonarsource** [comment]
Thanks, @dougwaldron for providing the feedback. We plan to do a release on Monday and this fix will be included.
