### ISSUE TITLE
SE: add symbolic engine support for Boolean constraints

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#5380]
The engine should automatically add `True` or `False` constraints for symbols and operations which can be evaluated as `True` or `False`. E.g.: 
- literals: `true` and `false` like in `new Mutex(true)`
- simple equality checks: `1 == 1`

**Comment by pavel-mikula-sonarsource** [comment]
The `1 == 1` should work by checking every operation to see if `.ConstantValue` is `true`/`false`. It should also work for cases like
```
const int zero = 0;
var b = zero == 0;
```
