### ISSUE TITLE
Fix S1854 Performance: Rule can be very slow in some scenarios

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#5384]
### Description

Source: https://community.sonarsource.com/t/azure-devops-build-stuck-after-migrating-from-sq-9-1-to-sq-9-2/56783

When analyzing the reproducer project created by our user, the rule https://rules.sonarsource.com/csharp/RSPEC-1854 increased the build time from ~1m to ~130m. 

I can reproduce the issue on my side and it was confirmed by the user that deactivating the rule will fix the problem.

At the first glance the problem is in the new CFG generation code since `IOperationWrapperSonar` has 48.4% of the memory allocations (considering only our code):
![image](https://user-images.githubusercontent.com/56015273/153614056-5b590b58-2379-46b7-af74-7a80774e4ada.png)

and uses a significant part of the processor time:
![image](https://user-images.githubusercontent.com/56015273/153612707-915c0a47-0fdf-47ec-916b-153854688d8f.png)

### Repro steps

Analyze the repro project created by the user.

### Expected behavior

The analysis finishes in a reasonable time.

### Actual behavior

The total build time increases from 1m without the rule, to 130m when the rule is active.

### Known workarounds

Removing the rule from the quality profile.

### Related information

* C#/VB.NET Plugins version: https://github.com/SonarSource/sonar-dotnet/releases/tag/8.35.0.42613
* MSBuild / dotnet version: 6.0.101
* SonarScanner for .NET version: SonarScanner for MSBuild 5.4.1
* Operating System: Windows
* Please ask me for the reproducer.

**Comment by pavel-mikula-sonarsource** [comment]
@rauhs Can you share a reproducer with us? By public or private channel.

**Comment by pavel-mikula-sonarsource** [comment]
This doesn't reproduce on my machine. I can rebuild it with all rules in 10 minutes. There are things to improve, but they are not the root  cause of this.
