### ISSUE TITLE
Enable multiple project level issues

### ISSUE THREAD

**Issue by csaba-sagi-sonarsource** [SonarSource/sonar-dotnet#5417]
### Description

Currently if there are more than one project level issues, only the first one will be imported. There is a de-duplication logic in the SarifParserCallbackImpl (See [here](https://github.com/SonarSource/sonar-dotnet/blob/c8a7b3a72fccccf36e9825abd688e22df338d053/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SarifParserCallbackImpl.java#L81)). This means for example if there are multiple projects with S3904 violations (No AssemblyVersion attribute for the assemly), only one issue will be reported for one assembly.

### Repro steps

Add two projects that do not contain an AssemblyVersion attribute.  
Analyze the projects with rule S3904 enabled.
And only one issue will appear in SQ/SC.

### Expected behavior

All issues are correctly reported.

### Actual behavior

Only one issue is reported.

### Known workarounds

-

### Related information

* C#/VB.NET Plugins version: 8.35.0.42613

**Comment by martin-strecker-sonarsource** [comment]
Does this change also solve flaky issues like this one? (Look in the "Activities" tab)
https://peach.aws-prd.sonarsource.com/project/issues?issues=AXg6jiAvqKPOqfVzH4ae&open=AXg6jiAvqKPOqfVzH4ae&id=screentogif

![image](https://github.com/SonarSource/sonar-dotnet/assets/103252490/b02daef2-734a-4bc1-bf1e-911c552485cf)

**Comment by costin-zaharia-sonarsource** [comment]
I'm not sure (I did not manually test this, and I'm not sure if the order in which the reports are processed is consistent between the runs), but I think it might. With the previous implementation, only one of many raised issues was reported to the server.

**Comment by martin-strecker-sonarsource** [comment]
It looks like S3990 is new for the "HookTest" assembly, while S4026 was flaky.
![image](https://github.com/SonarSource/sonar-dotnet/assets/103252490/c8cf1df5-b273-4c38-91de-65cecd054bcc)
