### ISSUE TITLE
Fix VB.NET BC42376: An instance of analyzer SymbolicExecutionRunner cannot be created

### ISSUE THREAD

**Issue by dougwaldron** [SonarSource/sonar-dotnet#5436]
After updating the "SonarAnalyzer.VisualBasic" package from version 8.35.0.42613 to version 8.36.0.43782, the compiler produces this warning:

> vbc : warning BC42376: An instance of analyzer SonarAnalyzer.Rules.VisualBasic.SymbolicExecutionRunner cannot be created from {my project}\packages\SonarAnalyzer.VisualBasic.8.36.0.43782\analyzers\SonarAnalyzer.VisualBasic.dll : Could not load file or assembly 'SonarAnalyzer.CFG, Version=8.36.0.0, Culture=neutral, PublicKeyToken=c5b62af9de6d7244' or one of its dependencies. The system cannot find the file specified..

Downgrading back to 8.35 eliminates the warning. 

This is in a .NET Framework 4.8 project in Visual Studio 2022 (17.1.0).

**Comment by pavel-mikula-sonarsource** [comment]
Hi @dougwaldron,

Thank you for reporting this. It seems that we forgot to ship this dependency to the NuGet package.

**Comment by pavel-mikula-sonarsource** [comment]
It's also missing from the VBNET SQL Plugin

**Comment by pavel-mikula-sonarsource** [comment]
Related for Peach: #5437

**Comment by pavel-mikula-sonarsource** [comment]
It doesn't reproduce on SQ/SC, because VB.NET analyzer gets DLL from C# due to current S4NET behavior.

**Comment by pavel-mikula-sonarsource** [comment]
Hi @dougwaldron, you should be able to use the latest 8.36.1 version that fixes this issue.
