### ISSUE TITLE
Reduce the number of symbols retrieved by TokenTypeAnalyzer

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#5559]

**Comment by martin-strecker-sonarsource** [comment]
@costin-zaharia-sonarsource can this be closed. We did https://github.com/SonarSource/sonar-dotnet/issues/7369 which should fix this issue.

**Comment by costin-zaharia-sonarsource** [comment]
Yes. It's implemented/fixed by https://github.com/SonarSource/sonar-dotnet/issues/7369
