### ISSUE TITLE
False Positive for Remove method Parameter not used

### ISSUE THREAD

**Issue by rameshbsupekar** [SonarSource/sonar-dotnet#5567]
### Description
There is false positive happening for below rule
https://rules.sonarsource.com/csharp/RSPEC-1172
I have method which has parameter List<string> and I am using it in if condition for contains and add
### Repro steps
Create a static method which has list of string parameter perform operations of contains and add and observe sonarlint warnings
use its count
### Expected behavior
As parameter is used in contains or adding some data to it and its count is used, we cannot remove it so there should not be sonar warning for this

### Actual behavior
Sonar warning is shown even though the list parameter is used in if condition and getting count

### Known workarounds

Please provide a description of any known workarounds.

### Related information

* C#/VB.NET Plugins version 6.1.0.45913
* Visual Studio version 16.11.12
* MSBuild / dotnet version
* SonarScanner for .NET version (if used)
* Operating System

**Comment by pavel-mikula-sonarsource** [comment]
Duplicate to #5491 that was fixed last week. It will be part of the next release.
