### ISSUE TITLE
Super slow performance of sonarscanner

### ISSUE THREAD

**Issue by mlatoszek** [SonarSource/sonar-dotnet#5581]
Hi,

I'm trying to run SonarQube analysis on fairly small .net project (<40 source files). The analysis take ages to complete (already running >4h on small container and > 1h on full blown Mac). I remember on Sonar 8 running analysis on the same project using the same resources took ~1-2mins. 

SonarScanner for MSBuild 5.5.3
SonarQube Community Edition Version 8.9.7
Quality Profile: Sonar way (default)
.NET Framework Version: net6.0

I can send the project sources I'm using for deeper analysis - but don't want to attach them publicly ;)

Best regards,
Michał Latoszek

**Comment by jnikeeg** [comment]
We are currently having this same problem. Following.

**Comment by pavel-mikula-sonarsource** [comment]
Hi @mlatoszek, please open a thread on https://community.sonarsource.com/ - we can open a private conversation there to share the reproducer.

**Comment by pavel-mikula-sonarsource** [comment]
..and post a link here, so we can find it quickly :)

**Comment by mlatoszek** [comment]
Hi @pavel-mikula-sonarsource - please find it here: https://community.sonarsource.com/t/super-slow-performance-of-sonarscanner/62077?u=latoch

**Comment by andrei-epure-sonarsource** [comment]
I am closing this issue, please continue the discussion on the community forum.
