### ISSUE TITLE
Absolute coverage report paths with wildcards do not work

### ISSUE THREAD

**Issue by Roemer** [SonarSource/sonar-dotnet#5628]
### Description
When I set the `sonar.cs.nunit.reportsPaths` to an absolute path with a wildcard (eg: `f:/projects/abc/artifacts/test-results-*.xml`) it does not import any reports.
If I set them relative (e.g. `artifacts/test-results-*.xml`), it does find and import them.
Same happens with opencover reports (`sonar.cs.opencover.reportsPaths`)

### Repro steps
1. Create any project that creates nunit test projects
2. Add the nunit report xml with a wildcard as absolute path to the sonar runner.

### Expected behavior
It should find and import the report.

### Actual behavior
It does not find the report.

### Known workarounds
Use relative paths.

### Related information
* SonarScanner for MSBuild version:  4.8
* SonarQube server version: 6.7.5
* Languages in your solution: C#

**Comment by pavel-mikula-sonarsource** [comment]
This issue was moved here from sonar-scanner-msbuild repository. 

I cannot reproduce the issue with the current version of the analyzer.
