### ISSUE TITLE
Fix S2077 FN: SQL Injection Hotspot not triggered using EntityFramework

### ISSUE THREAD

**Issue by mattwatsonad** [SonarSource/sonar-dotnet#5636]
### Description

When using DataContext.TableName.FromSql("<some sql string>") sql injection hotspots are not being picked up.

### Repro steps

```
[HttpGet("search/{searchTerm}")]
public async Task<IActionResult> DoSearch(string searchTerm)
{
	var result = await DataContext.MyTable
		.FromSql($"Search { searchTerm }")
		.AsNoTracking()
		.ToListAsync();
	return Ok(result);
}
```

### Expected behavior

It should identify that that user-input is being put straight into a string executed as sql, and flag as a hotspot.

### Actual behavior

No issues of any kind detected on above snippet

### Known workarounds

None

### Related information

SonarQube Developer Edition Version 9.3 (build 51899)
ASP.NET Core 3.1 C# Project

**Comment by costin-zaharia-sonarsource** [comment]
Hi @mattwatsonad, thanks for reporting the issue. I can confirm the false negative.
