### ISSUE TITLE
csharpsquid:S2259 False positive "Null pointers should not be dereferenced"

### ISSUE THREAD

**Issue by pampua84** [SonarSource/sonar-dotnet#5649]
Hi guys,
i have a code like this:

```
IdentityResult result = null;

var genderClaim = user.Claims.FirstOrDefault(c => c.ClaimType.Equals(JwtClaimTypes.Gender));

if (genderClaim != null && !string.IsNullOrEmpty(gender))
{
    result = await _userManager.ReplaceClaimAsync(user, genderClaim.ToClaim(), new Claim(JwtClaimTypes.Gender, gender));
}

if (result is { Succeeded: false })
    throw ExceptionWithErrors(result.Errors);
```

and I have this bug report:

![image](https://user-images.githubusercontent.com/17255890/167822880-7f68de12-1731-4870-82c2-f4c623a4ccaf.png)

but with Property pattern: 

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns

this is not true.

**Comment by pavel-mikula-sonarsource** [comment]
Hi @pampua84, 

I confirm this as a False Positive. S2259 doesn't support pattern matching yet. 

I'll close this issue for now, as we have a separate effort planned to implement it in [MMF-2229](https://jira.sonarsource.com/browse/MMF-2229) (link is not public, unfortunately)

**Comment by pampua84** [comment]
Ok thanks for the immediate reply
