### ISSUE TITLE
[AD0001] S2234 throws ArgumentException when analyzing a constructor call for a type not part of the current compilation

### ISSUE THREAD

**Issue by rjgotten** [SonarSource/sonar-dotnet#5661]
### Description

S2234 throws an ArgumentException resulting in an AD0001 warning message, when it analyzes a constructor call of a type not part of the current compilation:

```
Analyzer 'SonarAnalyzer.Rules.CSharp.ParametersCorrectOrder' threw an exception of type 'System.ArgumentException' with message 'Reported diagnostic 'S2234' has a source location in file '<SolutionDir>\<ProjectDir>\Primitives\DateTimeRange.cs', which is not part of the compilation being analyzed.
Parameter name: diagnostic'.
Exception occurred with following context:
Compilation: NetMatch.Twd.WhiteLabel.Base.Tests
SyntaxTree: <SolutionDir>\Tests\<TestProjectDir>\Primitives\DateTimeRangeTests.cs
SyntaxNode: new DateTimeRange(end, start) [ObjectCreationExpressionSyntax]@[1385..1414) (35,21)-(35,50)

System.ArgumentException: Reported diagnostic 'S2234' has a source location in file '<SolutionDir>\<ProjectDir>\Primitives\DateTimeRange.cs', which is not part of the compilation being analyzed.
Parameter name: diagnostic
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalysisContextHelpers.VerifyDiagnosticLocationInCompilation(String id, Location location, Compilation compilation)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalysisContextHelpers.VerifyDiagnosticLocationsInCompilation(Diagnostic diagnostic, Compilation compilation)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalysisContextHelpers.VerifyArguments(Diagnostic diagnostic, Compilation compilation, Func`2 isSupportedDiagnostic)
   at Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext.ReportDiagnostic(Diagnostic diagnostic)
   at SonarAnalyzer.Helpers.AnalysisContextExtensions.ReportIssue(ReportingContext reportingContext, Nullable`1 isTestProject, Nullable`1 isScannerRun)
   at SonarAnalyzer.Helpers.AnalysisContextExtensions.ReportIssue(SyntaxNodeAnalysisContext context, Diagnostic diagnostic, SonarAnalysisContext verifyScopeContext)
   at SonarAnalyzer.Rules.ParametersCorrectOrderBase`1.ReportIncorrectlyOrderedParameters(SyntaxNodeAnalysisContext analysisContext, MethodParameterLookupBase`1 methodParameterLookup, SeparatedSyntaxList`1 argumentList, Func`1 getLocationToReport)
   at SonarAnalyzer.Rules.CSharp.ParametersCorrectOrder.<Initialize>b__4_1(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.DiagnosticAnalyzerContextHelper.<>c__DisplayClass1_0`1.<RegisterSyntaxNodeActionInNonGenerated>b__0(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.SonarAnalysisContext.<>c__DisplayClass47_0`1.<RegisterContextAction>b__0(TContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: S2234
```

Locally suppressing the analyzer does not avert the crash. It occurs anyway.

### Repro steps

This reproduces as part of a very large solution with many projects. So far I have not cooked an isolated repro. 

The offending code snippit is the following unit test definition, which temporarily disables S2234 precisely because it is testing that arguments passed in the wrong order throw. But even then, the rule analyzer still throws.

```cs
[Test]
public void Constructor_InvertedRange_Throws()
{
  var start = DateTime.Parse("2021-01-01T10:00", CultureInfo.InvariantCulture);
  var end   = DateTime.Parse("2021-01-01T11:00", CultureInfo.InvariantCulture);

#pragma warning disable S2234 // Parameters should be passed in the correct order
  Assert.That(() => new DateTimeRange(start, end), Throws.Nothing);
  Assert.That(() => new DateTimeRange(end, start), Throws.ArgumentException);
#pragma warning restore S2234 // Parameters should be passed in the correct order
}
``` 

### Known workarounds

None, other than removing the code that offends the analyzer rule and leads to the crash.

### Related information

* C#/VB.NET Plugins version -- whatever ships with SonarLint 6.4.1.47693
* Visual Studio version -- 2022 (v17.2)
* MSBuild / dotnet version -- dotnet SDK 6.0.300
* SonarScanner for .NET version (if used) -- whatever ships with SonarLint 6.4.1.47693
* Operating System -- Windows 10

**Comment by rjgotten** [comment]
Found the problem:

https://github.com/SonarSource/sonar-dotnet/blob/071df8117ddc6d639e04aac5f3f9c9932261f3fc/analyzers/src/SonarAnalyzer.CSharp/Rules/ParametersCorrectOrder.cs#L54-L67

Line 62 is using `objectCreationCall.Type.GetLocation()` when it should just be using `objectcreationCall.GetLocation()`.
It needs the location of the call site of the constructor. _NOT_ the location where the type being called is defined.

**Comment by rjgotten** [comment]
I can only guess as to why this has only started being a problem _now_ -- considering the analyzer rule in question hasn't been touched for a long time, but my money would be on Microsoft having changed something either with the syntax nodes and how they report location, or with additional validation of passed locations.

Which means this instance of a rule crash probably won't be the only one we'll be seeing once people start shifting onto the latest dotnet SDK and latest Visual Studio version.

**Comment by pavel-mikula-sonarsource** [comment]
Hi @rjgotten, thank you for looking into this. I unfortunately cannot reproduce it with VS 17.2.1 & SDK 6.0.300

Can you please put this line into your source code and tell us exact Roslyn version? It will be displayed as part of the error message in the IDE:
```
#error version
```

**Comment by martin-strecker-sonarsource** [comment]
@pavel-mikula-sonarsource 

The check in Roslyn that causes this error is here

https://github.com/dotnet/roslyn/blob/95675b237b1fdb6ea321b45e2aaa6bd9508acc7a/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContextHelpers.cs#L88-L100

For some reason, the SyntaxTree of the SyntaxReferences with the primary or the secondaryLocations is not from within the compilation. I tried to reproduce with a type from the BCL:
```cs
            string paramName = "", message = "";
            var cultureNotFoundException = new CultureNotFoundException(message, paramName);
```

But here, the rule triggers without exception (message, paramName are swapped). The constructed type is probably defined in another csproj (ProjectReference). I don't know if we can set up something like that with our test infrastructure. I see these ways forward from here:
* Build a test set up with two projects and try to reproduce the error
* Fix the error here by filtering locations according to the logic in Roslyn
* Do the filtering of location and secondaryLocation in `ReportIssue` for all rules at once
* Catch the error in `ReportIssue` ourselves and ignore it.

**Comment by martin-strecker-sonarsource** [comment]
@rjgotten we use a Roslyn feature called *secondaryLocations*. Each diagnostic has a location, where the IDE shows the squiggles but can also optionally have multiple secondary locations. These are ignored by the IDE (by now) but can be used by other tools like SonarQube to give a more nuanced explanation about the diagnostic by highlighting other related code locations.
In this case, we highlight the definition and the call side.

**Comment by rjgotten** [comment]
Ah. That explains why you're digging it out. Thanks.

**Comment by martin-strecker-sonarsource** [comment]
Thanks for investigating @rjgotten These are some interesting ideas to explore indeed. We will need to come up with some proper unit tests for this and we will need to make sure our postprocessing of locations can handle other locations besides SourceLocation.
