### ISSUE TITLE
Remove Repox Artifactory (releases) from nuget.config

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#5683]
See https://devblogs.microsoft.com/nuget/introducing-package-source-mapping/

This feature is compatible with the following tools:

- [Visual Studio 2022 preview 4](https://visualstudio.microsoft.com/vs/preview/) and later
- [.NET SDK 6.0.100-rc.1](https://dotnet.microsoft.com/download/dotnet/6.0) and later
- [nuget.exe 6.0.0-preview.4](https://www.nuget.org/downloads) and later

**Comment by costin-zaharia-sonarsource** [comment]
I'm not sure why we need this. We only have repox as a package source:
https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/NuGet.Config#L5-L6

**Comment by pavel-mikula-sonarsource** [comment]
Relevant sprint card: https://trello.com/c/CCmlDJkq/526-add-package-source-mapping-to-our-nugetconfig-files

**Comment by andrei-epure-sonarsource** [comment]
Hey, it's a fair point that we might revisit this.

And I'd like to revisit it because, by having the repox proxy, we actually
lose the benefit of what Package Source Mapping would bring (if it's a dumb
proxy, we're open to dependency confusion).

Andrei Epure | Sonar

Software Developer @ Languages Team

https://sonarsource.com

Are you using SonarLint <https://www.sonarlint.org> in your IDE?

**Comment by andrei-epure-sonarsource** [comment]
@pavel-mikula-sonarsource  I believe that the     

> \<add key="Repox Artifactory (releases)" value="https://repox.jfrog.io/repox/api/nuget/sonarsource-nuget-releases" />

is only used to download the CBDE binary (see [repox](https://repox.jfrog.io/ui/repos/tree/General/sonarsource-nuget-releases/SonarSource.CBDE.1.0.0.14843.nupkg)).

Once you remove CBDE, you can remove this like from the `nuget.config` and close this card.

**Comment by pavel-mikula-sonarsource** [comment]
Thanks, I've updated the title and added it to our sprint
