### ISSUE TITLE
S6354: Inconsistent analyzer title

### ISSUE THREAD

**Issue by bart-vmware** [SonarSource/sonar-dotnet#5696]
### Description

The title of S6354 ends with a dot, whereas that is not the case for all other analyzers.

![image](https://user-images.githubusercontent.com/104792814/171649846-ad8ff997-b914-404b-841d-0a4198616775.png)

**Comment by bart-vmware** [comment]
Thanks for the fix. Does this issue need to remain open? Feel free to close.

**Comment by pavel-mikula-sonarsource** [comment]
Hi @bart-vmware, #5726 needs to be merged first. That will close this issue.
