### ISSUE TITLE
Fix S4581 FP: Support target-typed new expression

### ISSUE THREAD

**Issue by sm-g** [SonarSource/sonar-dotnet#5703]
`public static readonly Guid Global = new("54972F01-2A74-4D09-AA7C-359E9C5A5B5A");`

8.40.0.48530

**Comment by Corniel** [comment]
I can confirm this issue, and have a simple fix prepared.

**Comment by pavel-mikula-sonarsource** [comment]
Thank you @sm-g for reporting this issue. It's now fixed by #5704 from @Corniel. Thank you @Corniel for your contribution.
