### ISSUE TITLE
Q: How are analyzers hidden from the VS RuleSet editor?

### ISSUE THREAD

**Issue by bart-vmware** [SonarSource/sonar-dotnet#5753]
In an attempt to sync custom Sonar rule severities in my .ruleset file with the ones in SonarCloud, I wrote a little utility that scans SonarAnalyzer.CSharp.dll for exposed rules.

In the process, I found that some of them are hidden in the Visual Studio RuleSet editor.

For example, when I call `Activator.CreateInstance()` on `SonarAnalyzer.Rules.CSharp.ClearTextProtocolsAreSensitive` (S5332), both of its `SupportedDiagnostics` have `IsEnabledByDefault` set to `true` and `DefaultSeverity` to `Warning`. I even tried calling its `Initialize()` method, feeding it a fake `AnalysisContext` that executes its `RegisterCompilationStartAction`. This doesn't change the outcome.

I'm familiar with writing roslyn analyzers, but I can't seem to find the mechanism that hides them from the RuleSet editor. How does that work?

While the following works around it, I suspect there's a more reliable way.

```c#
private static bool IsDynamicallyHidden(DiagnosticAnalyzer analyzer)
{
    // From https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/src/SonarAnalyzer.Common/Common/AnalyzerConfiguration.cs:
    //
    //   Hotspot rules are not configurable (from ruleset) to prevent them from appearing in SonarLint.
    //   They are enabled by default and we check if SonarLint.xml contains the rule key on CompilationStart
    //   to determine whether to run the analysis or not.

    Type analyzerType = analyzer.GetType();
    PropertyInfo? configurationProperty = analyzerType.GetProperty("Configuration",
        BindingFlags.NonPublic | BindingFlags.Instance);

    if (configurationProperty != null)
    {
        object? configurationValue = configurationProperty.GetValue(analyzer);

        if (configurationValue != null)
        {
            Type configurationType = configurationValue.GetType();

            if (configurationType.Name == "HotspotConfiguration")
            {
                return true;
            }
        }
    }

    return false;
}
```

**Comment by pavel-mikula-sonarsource** [comment]
Hi @bart-vmware,

Some rules are security hotspots and they have different behavior. On the Roslyn side, it's an effect of this setting:
https://github.com/SonarSource/sonar-dotnet/blob/96fe491db1228e452cc30bb7dd5f89b2a9e4e41f/analyzers/src/SonarAnalyzer.Common/DiagnosticAnalyzer/DiagnosticDescriptorBuilder.cs#L77-L86

You can inspect the Tag to recognize them.

Those rules have their own logic bound to Scanner for .NET behavior that decides if they should run or not.

**Comment by bart-vmware** [comment]
Makes perfect sense, thanks! I wasn't aware of `WellKnownDiagnosticTags`.
