### ISSUE TITLE
Rule S5542[C#]: Detect CBC mode when used with padding

### ISSUE THREAD

**Issue by pierre-loup-tristant-sonarsource** [SonarSource/sonar-dotnet#5757]
Update rule S5542 to detect precisely when CBC mode is used with padding.

## ECB & CBC

The rule raises on [System.Security.Cryptography.AESManaged](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.aesmanaged?view=net-6.0) depending on the properties it's initialized with.

The rule raises an issue when any of these conditions are met:
* `Mode` is `CipherMode.ECB`
* `Mode` is `CipherMode.CBC` and `Padding` is different than `PaddingMode.None`

By default `Mode` is `CipherMode.CBC` and `Padding` is `PaddingMode.PKCS7`

Adjust the message based on the cases (see examples)

### Examples
```csharp

// ECB
AesManaged aesECB = new AesManaged
{
    KeySize = 128,
    BlockSize = 128,
    Mode = CipherMode.ECB
}; // Noncompliant: Use a secure cipher mode.

// CBC
AesManaged aesCBCWithPadding = new AesManaged
{
    KeySize = 128,
    BlockSize = 128,
    Mode = CipherMode.CBC,
    Padding = PaddingMode.PKCS7
}; // Noncompliant: Use another cipher mode or disable padding.

AesManaged aesCBCDefaultPadding = new AesManaged
{
    KeySize = 128,
    BlockSize = 128,
    Mode = CipherMode.CBC
}; // Noncompliant: Padding is enabled by default. Use another cipher mode or disable padding.

AesManaged aesDefaultModeAndPadding = new AesManaged
{
    KeySize = 128,
    BlockSize = 128,
}; // Noncompliant: CBC with padding is enabled by default. Use another cipher mode or disable padding.

AesManaged aesCBCNoPadding = new AesManaged
{
    KeySize = 128,
    BlockSize = 128,
    Mode = CipherMode.CBC,
    Padding = PaddingMode.None
}; // Compliant: No padding
```

## RSA

Continue raising issues wherever unsafe RSA OAEP padding is disabled.
Update the issue message to "Use a secure padding scheme."

## RSPEC
When implemented merger [this RSPEC PR](https://github.com/SonarSource/rspec/pull/1065)

**Comment by pavel-mikula-sonarsource** [comment]
MMF-2826

**Comment by andrei-epure-sonarsource** [comment]
Existing implementation:
- https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/src/SonarAnalyzer.Common/Rules/EncryptionAlgorithmsShouldBeSecureBase.cs
- https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/src/SonarAnalyzer.CSharp/Rules/EncryptionAlgorithmsShouldBeSecure.cs

**Comment by pierre-loup-tristant-sonarsource** [comment]
We (AppSec Bubble) want to put this change on hold and close the ticket. We have decided to move cryptography-related hardening to a separate sprint in 2023. A bigger refactor will be done for S5542 and related rules.
