### ISSUE TITLE
ERROR: Error during SonarScanner execution

### ISSUE THREAD

**Issue by supriyapatil2018** [SonarSource/sonar-dotnet#5817]
### [error]at org.sonarsource.dotnet.shared.sarif.SarifParser10.uriToAbsolutePath(SarifParser10.java:226
@sonarcloud 

We are facing a issue with SonarQube analysis. 

```
##[error]ERROR: Error during SonarScanner execution
ERROR: Error during SonarScanner execution
##[error]java.lang.IllegalArgumentException: URI is not absolute
```

SonarQube Version- 7.9.1

**Comment by andrei-epure-sonarsource** [comment]
Hello @supriyapatil2018 

As mentioned in the issue templates (when you opened the issue you had to choose between 4 templates: https://github.com/SonarSource/sonar-dotnet/issues/new/choose) , for help questions 

> We strongly recommend that you ask support questions in the [Community Forum](https://community.sonarsource.com/).

You will get much better visibility there.
