### ISSUE TITLE
S4057 performance improvement.

### ISSUE THREAD

**Issue by mary-georgiou-sonarsource** [SonarSource/sonar-dotnet#5821]
Rule S4057 is [querying ](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/src/SonarAnalyzer.CSharp/Rules/SetLocaleForDataTypes.cs#L68) the semantic model for every object creation node, while the rule is interested only in two specific types of objects.
Maybe it's better to do some more filtering on a syntax level before calling the semantic model for the symbol of object creation.

Same [here](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/src/SonarAnalyzer.CSharp/Rules/SetLocaleForDataTypes.cs#L82), it seems that the semantic model is called for every `AssignmentExpressionSyntax` node. Might be also possible to find a solution using the AST or do some filtering before calling the semantic model.

**Comment by gregory-paidis-sonarsource** [comment]
@mary-georgiou-sonarsource  isn't this a duplicate of https://github.com/SonarSource/sonar-dotnet/issues/5924?
If yes, please close it as duplicate.
