### ISSUE TITLE
How to debug aspx.vb file using Visual Studio 2017

### ISSUE THREAD

**Issue by monishakhapali** [SonarSource/sonar-dotnet#5825]
### Description

Getting a message at the breakpoint, the breakpoint will not currently be hit. No symbols have been loaded for this document. Target Framework - .Net framework 3.5

### Repro steps

Please provide a minimal code snippet that compiles which reproduces the problem. Alternatively, you can share a link to the SonarCloud public project where the issue appears. If the issue requires some specific project configuration to reproduce, you can create a minimal reproducible project and share its git repository or attach it as a ZIP file.

### Expected behavior

Please provide a description of the behavior you expect.

### Known workarounds

Please provide a description of any known workarounds.

### Related information

* C#/VB.NET Plugins version
* Visual Studio version
* MSBuild / dotnet version
* SonarScanner for .NET version (if used)
* Operating System

**Comment by pavel-mikula-sonarsource** [comment]
Hi @monishakhapali,

Your report doesn't seem to be related to our project or this repository. You're probably looking for https://github.com/dotnet/roslyn and at the same time VS 2017 and .NET Fx 3.5 are out of support so you should not expect any changes there either.
