### ISSUE TITLE
Improvement: Add some helper methods from Roslyn for handling of conditional access patterns

### ISSUE THREAD

**Issue by martin-strecker-sonarsource** [SonarSource/sonar-dotnet#5832]
## Rational

Handling of conditional access is complex (see, e.g., the comments in [GetParentConditionalAccessExpression](https://github.com/dotnet/roslyn/blob/2aed89bfee5d5318cb62108be76365befb656c38/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxNodeExtensions.cs#L295-L371]). We should rely on the implementation of Roslyn to handle any cases properly. We should therefore copy

* GetRootConditionalAccessExpression
* GetParentConditionalAccessExpression
* GetInnerMostConditionalAccessExpression

from Roslyn [SyntaxNodeExtensions.cs](https://github.com/dotnet/roslyn/blob/main/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxNodeExtensions.cs).

Especially GetRootConditionalAccessExpression is helpful in many scenarios.

**Comment by pavel-mikula-sonarsource** [comment]
..without the `Get` prefix
