### ISSUE TITLE
Prepare migration of S2259 to support C# 9 and C# 10 syntax

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#5862]
Migrate S2259 to the new Symbolic Execution engine.

* [x] Follow the file structure and principles of `DeadStore` rules.
* [x] Create copy of UTs with `FIXME Non-compliant` annotations.
* [x] Create two set of UTs.
* [x] Integrate `NullPointerDereference` with `AllRules` concept in `SymblicExecutionRunner`
* [x] Use SonarCFG-based SE for ITs and production. Use Roslyn-based in UTs. It will be swapped by #5863

**Comment by martin-strecker-sonarsource** [comment]
> Follow the file structure and principles of DeadStore rules

I looked into DeadStore, and it seems to be related to LiveVariableAnalysis. From what you told me yesterday I think LocksReleasedAllPaths is a better blueprint  (e.g. derives from `SymbolicRuleCheck`). Can you please confirm which rule is the template to follow?

**Comment by pavel-mikula-sonarsource** [comment]
The idea was to follow test naming convention, file naming convention, partial classes structure (not necessary follow it 100%, but get inspired how to split the code - definitely put the Sonar-CFG version into separate file and consider it secondary). So we don't reinvent the wheel.

It will not fully follow DeadStore, as it is not a SE rule.

**Comment by martin-strecker-sonarsource** [comment]
From the description of the issue, it could be closed, but the title says something completely different.

**Comment by pavel-mikula-sonarsource** [comment]
I've renamed it so we can close it

**Comment by pavel-mikula-sonarsource** [comment]
Will continue in #5973
