### ISSUE TITLE
Rules support PCI DSS Security Standard

### ISSUE THREAD

**Issue by agigleux** [SonarSource/sonar-dotnet#5929]
Rules metadata .json files should contain the new PCI DSS standard categorization. 

This will require updating sonar-plugin-api to 9.8+ (see https://github.com/SonarSource/sonar-plugin-api/blob/master/sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java#L527

**Comment by pavel-mikula-sonarsource** [comment]
Previous work for inspiration: #5467
