### ISSUE TITLE
Move diagnostic creation in `AnalysisContextExtensions.ReportIssue`

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#5931]
# Why

Currently, the diagnostic creation is done by the rules, and the reporting by the `AnalysisContextExtensions.ReportIssue` method overloads. On the plus side, the responsibilities are decoupled but this has the side effect that the issue validation is split between all these. 

We need a single layer (a single entry point) for issue reporting where we can have complete control for validation. This can hide the complexity of diagnostic creation from the rules.

# How 

`AnalysisContextExtensions.ReportIssue` method overloads should take the needed parameters and take care of diagnostic validation and creation.

**Comment by pavel-mikula-sonarsource** [comment]
Closing, as it was already done by now
