### ISSUE TITLE
New Rule: Use ContainsKey instead of Keys.Contains() on dictionaries

### ISSUE THREAD

**Issue by Corniel** [SonarSource/sonar-dotnet#6009]
#Description

A dictionary is a data structure that is optimized to access items based on their keys. A check if a dictionary contains a specific key is therefor cheap. By using `Keys.Contains()` however, the LINQ extension is used that has to perform a full scan.

## Noncompliant Code Example
``` C#
using System.Collections.Generic;
using System.Linq;

bool HasTheAnswer()
{ 
    var dict = new Dictionary<int, int>();
    return dict.Keys.Contains(42); 
}
```

``` VB.NET
Imports System.Collections.Generic
Imports System.Linq

Function HasTheAnswer() As Boolean
    Dim dict = New Dictionary(Of Integer, Integer)
    Return dict.Keys.Contains(42)
End Function
```

## Compliant Solution

``` C#
using System.Collections.Generic;
using System.Linq;

bool HasTheAnswer()
{ 
    var dict = new Dictionary<int, int>();
    return dict.ContainsKey(42); 
}
```

``` VB.NET
Imports System.Collections.Generic
Imports System.Linq

Function HasTheAnswer() As Boolean
    Dim dict = New Dictionary(Of Integer, Integer)
    Return dict.ContainsKey(42)
End Function
```

**Comment by Sjlver** [comment]
This exists in dotnet's built-in code analysis: https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1841

**Comment by Corniel** [comment]
@Sjlver Strange, I found this violation in a project of my company, and CA1841 was not raised. Anyway, let's not redo MS work.

**Comment by Sjlver** [comment]
@Corniel you might have to enable it, by adding something like the following to your `.editorconfig` file:

```
# CA1841: Prefer Dictionary.Contains methods
dotnet_diagnostic.CA1841.severity = warning
```

See also https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview#enable-additional-rules

**Comment by Corniel** [comment]
> @Corniel you might have to enable it, by adding something like the following to your `.editorconfig` file:

I was surprised to find that the default severity of this rule was hidden, instead of warning.
