### ISSUE TITLE
problems with test report

### ISSUE THREAD

**Issue by Noga-smile92** [SonarSource/sonar-dotnet#6035]
# must be unique in a given SonarQube instance
sonar.projectKey=my:eeeeeeeeeeeeeeeeeee

sonar.sources=css/,admin/,project/,config/
#sonar.tests=tests/unit
sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=execution-result.xml

# --- optional properties ---

# defaults to project key
#sonar.projectName=studentee
# defaults to 'not provided'
sonar.projectVersion=1.0
#sonar.scm.exclusions.disabled = true
# Path is relative to the sonar-project.properties file. Defaults to .

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

Failed to resolve 2 file path(s) in PHPUnit tests execution-result.xml report. Nothing is imported related to file(s): C:\wamp64\www\Student Services\tests\unit\ServiceTest.php;C:\wamp64\www\Student Services\tests\unit\connectionTest.php
Missing blame information for 26 files. This may lead to some features not working correctly. Please check the analysis logs and refer to [the documentation](http://localhost:9000/documentation/analysis/scm-integration/).

**Comment by pavel-mikula-sonarsource** [comment]
Hi @Noga-smile92, 

This repository is not related to PHP. Please write a full question on our https://community.sonarsource.com/

Also, I don't understand what the problem is. Please clarify your question there.
