### ISSUE TITLE
Fix S2930 FN: Track System.Threading.CancellationTokenSource

### ISSUE THREAD

**Issue by fraser-lowndes** [SonarSource/sonar-dotnet#6050]
`System.Threading.CancellationTokenSource` implements `IDisposable` but isn't tracked by S2930. This may not have been a 'blocker' when the rule was originally added however, due to [an optimisation added in .NET Core 2.1](https://github.com/dotnet/coreclr/pull/12819), instantiating a `CancellationTokenSource` creates objects (`Linked1CancellationTokenSource`, `CallbackNode`) which are never GC'd. This leads to a memory leak, as has happened to me as well as numerous other projects, including the .NET MongoDB driver.

Given the impact of not disposing these objects, I propose they're added to S2930. If this is OK'd I should be able to get it done.

**Comment by andrei-epure-sonarsource** [comment]
Thank you for opening this issue, @fraser-lowndes . Your feedback helps us improve our products. 

We will look at it as soon as possible. After we confirm the issue, we will add labels and put it in our backlog. Once it's triaged by us, you can open a PR for it.

**Comment by pavel-mikula-sonarsource** [comment]
Hi @fraser-lowndes ,

Thank you for suggesting this idea. I'm confirming this as False Negative and we'd like to add that into our rule.

We'd also welcome your contribution on this topic if you'd like to create a PR. You will need these files:
* Add test cases into this file [DisposableNotDisposed.cs](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DisposableNotDisposed.cs)
* That should fail tests in [DisposableNotDisposedTest.cs](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/tests/SonarAnalyzer.UnitTest/Rules/DisposableNotDisposedTest.cs)
* Update implementation to make the test happy [DisposableNotDisposed.cs](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/src/SonarAnalyzer.CSharp/Rules/DisposableNotDisposed.cs)
