### ISSUE TITLE
[SARIF] Investigate if we handle /errorlog:[file][,version] parameter correctly

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#6079]
Scanner4net is not handling this properly. We need to check the behavior in sonar-dotnet too.

Similar with: https://github.com/SonarSource/sonar-scanner-msbuild/issues/1176

**Comment by pavel-mikula-sonarsource** [comment]
There's no handling on sonar-dotnet side AFAICT. It's S4NET responsibility to handle this parameter correctly.

Suppporting Sarif 2.0 or Sarif 2.1 is a different story / MMF (that will not work without support on S4NET side)
