### ISSUE TITLE
S2259: Reset constraints on calls in static methods

### ISSUE THREAD

**Issue by martin-strecker-sonarsource** [SonarSource/sonar-dotnet#6100]
Same as calls with a `this` receiver (aka instance methods) reset field constraints, calls to static methods should also reset field constraints:
```cs
public class C
{
  static object field;
  static void M()
  {
    field = null; // learn about field
    OtherStaticMethod();
    field.ToString(); // Compliant
  }
}
```

**Comment by pavel-mikula-sonarsource** [comment]
These should reset static fields only. Static method cannot change instance fields
