### ISSUE TITLE
S5332 FP: should ignore for xml definitions

### ISSUE THREAD

**Issue by GeertvanHorrik** [SonarSource/sonar-dotnet#6141]
### Description

The rule is S5332 ("Using clear-text protocols is security-sensitive")

### Repro steps

When developing a WPF component or app, it will create security hotspots for these items:

```
[assembly: XmlnsPrefix("http://schemas.catelproject.com", "catel")]
[assembly: XmlnsDefinition("http://schemas.catelproject.com", "Catel.MVVM")]
```

In case of xml namespaces, does it really need to create these issues (is it a true risk)? If not, then maybe the XmlnsPrefix and XmlnsDefinition can be used to exclude this?

* C#/VB.NET Plugins version (C# 11)
* Visual Studio version (VS 2022)
* MSBuild / dotnet version (.NET 6)
* SonarScanner for .NET version (if used) (5.8.0)

**Comment by pavel-mikula-sonarsource** [comment]
Hi @GeertvanHorrik,

Thank you for reporting this case. Xml namespaces indeed should not be reported and I confirm it as FP.

**Comment by pavel-mikula-sonarsource** [comment]
Namespace: System.Windows.Markup

**Comment by martin-strecker-sonarsource** [comment]
Also
* [XmlnsCompatibleWithAttribute(String, String) Constructor](https://learn.microsoft.com/en-us/dotnet/api/system.windows.markup.xmlnscompatiblewithattribute.-ctor?view=windowsdesktop-6.0)
* [XmlnsDictionary](https://learn.microsoft.com/dotnet/api/system.windows.markup.xmlnsdictionary)
* [XmlSerializerNamespaces](https://learn.microsoft.com/dotnet/api/system.xml.serialization.xmlserializernamespaces)
* [XmlAttributeAttribute.Namespace](https://learn.microsoft.com/dotnet/api/system.xml.serialization.xmlattributeattribute.namespace?view=net-6.0)
  * XmlArrayItemAttribute.Namespace
  * XmlAnyElementAttribute.Namespace
  * XmlArrayAttribute.Namespace
  * XmlElementAttribute.Namespace
  * XmlRootAttribute.Namespace
  * XmlTypeAttribute.Namespace
* [XmlQualifiedName construktor](https://learn.microsoft.com/de-de/dotnet/api/system.xml.xmlqualifiedname.-ctor?view=net-6.0#system-xml-xmlqualifiedname-ctor(system-string-system-string))
* [XmlNamespaceManager Class (System.Xml)](https://learn.microsoft.com/en-us/dotnet/api/system.xml.xmlnamespacemanager?view=net-6.0)
* [XmlAttribute(String, String, String, XmlDocument) Constructor (System.Xml) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/system.xml.xmlattribute.-ctor?view=net-6.0#system-xml-xmlattribute-ctor(system-string-system-string-system-string-system-xml-xmldocument))
* [XmlElement(String, String, String, XmlDocument) Constructor (System.Xml) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/system.xml.xmlelement.-ctor?view=net-6.0#system-xml-xmlelement-ctor(system-string-system-string-system-string-system-xml-xmldocument))

**Comment by martin-strecker-sonarsource** [comment]
Created #6223 as a follow-up.
