### ISSUE TITLE
S2259 false positive after null check with null-condition operator

### ISSUE THREAD

**Issue by peet-brits** [SonarSource/sonar-dotnet#6149]
### Description

Rule: [S2259](https://sonarsource.github.io/rspec/#/rspec/S2259/csharp)

False positive when the code already checks for null references using null-condition operators.

### Repro steps

    class MyClass
    {
        public byte[] Buffer { get; set; }
    }

    MyClass debug = null;

    if (debug?.Buffer?.Length > 0)
    {
        return debug.Buffer[0];
    }

### Expected behavior

The null check already happened and there should not be any warnings.

### Actual behavior

The code generates a warning at the `debug` part of the `return` statement.

### Related information

* This is for release version [8.45.0.54064](https://github.com/SonarSource/sonar-dotnet/releases/tag/8.45.0.54064)
* Visual Studio Professional 2022
* C# .NET 6
* Windows 10

**Comment by peet-brits** [comment]
Another example.

The warning is at the line `return demo.Data;`

> 'demo' is null on at least one execution path.

    static byte[] Test(Demo demo)
    {
        if (demo?.IsSuccessful == true)
        {
            return demo.Data;
        }
        else
        {
            return null;
        }
    }

    class Demo
    {
        public bool IsSuccessful { get; set; }
        public byte[] Data { get; set; }
    }

**Comment by mary-georgiou-sonarsource** [comment]
Thank you for opening this issue, @peet-brits. Your feedback helps us improve our products.

We will look at it as soon as possible. After we confirm the issue, we will add labels and put it in our backlog.

**Comment by pavel-mikula-sonarsource** [comment]
Hi @peet-brits,

Thank you for reporting this. It was fixed in 8.46 release.

**Comment by snakefoot** [comment]
@pavel-mikula-sonarsource Will this also fix this false-positive:

https://sonarcloud.io/project/issues?resolved=false&types=BUG&branch=dev&id=nlog2&open=AYP2NU0SZinl2h1ztXSa

**Comment by pavel-mikula-sonarsource** [comment]
Hi @snakefoot,

No, that is another problem. Please create a new issue for it. 

Just from looking at the code, the situation looks rather simple and should not raise.
