### ISSUE TITLE
Fix S2259 FP: Recognize NotNull results of String methods

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#6158]
Methods like `str.Trim()` never return null. We should learn that from their invocations. It's similar to what we do for Linq Enumerable.

We need to go through the methods and identify those that never return null like Trim, SubString, and so on

It will fix this issue from Peach: https://peach.sonarsource.com/project/issues?issues=AYORbz8FkNA1ahe47Aev&open=AYORbz8FkNA1ahe47Aev&id=dotnet-runtime

```
        internal static Grammar Create(string grammarName, string ruleName)
        {
            grammarName = grammarName.Trim();
            Uri uriGrammar;
            bool hasUri = Uri.TryCreate(grammarName, UriKind.Absolute, out uriGrammar); // Is annotated with NotNullWhenAttribute, we learn Null and NotNull cases
            int posDll = grammarName.IndexOf(".dll", StringComparison.OrdinalIgnoreCase); // FP
```

**Comment by martin-strecker-sonarsource** [comment]
According to https://raw.githubusercontent.com/dotnet/runtime/main/src/libraries/System.Runtime/ref/System.Runtime.cs there is only one method that may return null: [string.IsInterned](https://learn.microsoft.com/dotnet/api/system.string.isinterned). It seems that whitelisting "IsInterned" is the easiest way for string.

**Comment by mary-georgiou-sonarsource** [comment]
> According to https://raw.githubusercontent.com/dotnet/runtime/main/src/libraries/System.Runtime/ref/System.Runtime.cs there is only one method that may return null: [string.IsInterned](https://learn.microsoft.com/dotnet/api/system.string.isinterned). It seems that whitelisting "IsInterned" is the easiest way for string.

Maybe it's better to actually list the methods instead of just exclude one because in case a new String method is added that returns null we'll have an error.
