### ISSUE TITLE
Rule S2252: Loop conditions should be true at least once

### ISSUE THREAD

**Issue by michalb-sonar** [SonarSource/sonar-dotnet#616]
[RSPEC-2252](https://jira.sonarsource.com/browse/RSPEC-2252)

If a for loop's condition is false before the first loop iteration, the loop will never be executed. Such loops are almost always bugs, particularly when the initial value and stop conditions are hard-coded.

**Comment by christophe-zurn-sonarsource** [comment]
Separate ticket created for VB.NET implementation:  #2648
