### ISSUE TITLE
S4158 FP: Collection filled in a for loop reported to be empty

### ISSUE THREAD

**Issue by Keke71** [SonarSource/sonar-dotnet#6179]
### Description

Sonar Analyzer incorrectly reports S4158 for the code below. My original code is actually more complex. However, this simplified example also reports S4158.

### Repro steps

    public void FalsePositive()
    {
        var data = new[] { 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0 };
        var rising = new List<List<int>>();
        List<int> currentBin = null;
        for (var i = 0; i < data.Length; i++)
        {
            if (data[i] == 0)
            {
                if (currentBin != null)
                {
                    rising.Add(currentBin);
                    currentBin = null;
                }
        
                continue;
            }
        
            currentBin ??= new List<int>();
            currentBin.Add(i);
        }
        
        for (var i = 0; i < rising.Count; i++)
        {
            // SonarAnalyzer reports S4158 here:
            Console.WriteLine($"{rising[i].Count}");
        }
    }

### Expected behavior

As the collection is not empty, no issue should be reported.

### Actual behavior

S4158 is reported.

### Known workarounds

Using a foreach loop in the lower part, does not report the issue. However, in my original code this is not possible, as I actually have two collections that I have to access with indices.

### Related information

Environment:
    - Visual Studio Enterprise 17.3.0
    - SonarAnalyzer.CSharp 8.46.0.54807
    - .NET Framework 4.8
    - Windows 10 x64

**Comment by pavel-mikula-sonarsource** [comment]
Hi @Keke71,

Thank you for reporting this, as discussed on the other thread, I confirm it as a False Positive.

For archeology: MMF-2402 (nonpublic link) will migrate this rule to the new engine
