### ISSUE TITLE
Rule S3949: Calculations should not overflow

### ISSUE THREAD

**Issue by michalb-sonar** [SonarSource/sonar-dotnet#619]
[RSPEC-3949](https://jira.sonarsource.com/browse/RSPEC-3949)

Numbers are infinite, but the types that hold them are not, Each numeric type has hard upper and lower bounds. Try to calculate or assign numbers beyond those bounds, and the result will be a value that has silently wrapped around from the expected positive value to a negative one, or vice versa.

**Comment by andrei-epure-sonarsource** [comment]
Fixed by #2477
