### ISSUE TITLE
FP S5332: Improve detection of namespace uris

### ISSUE THREAD

**Issue by martin-strecker-sonarsource** [SonarSource/sonar-dotnet#6223]
Uris used for namespaces start with `http` and are not reported by S5332. The detection of namespace uris can be improved:

Copied from 
https://github.com/SonarSource/sonar-dotnet/issues/6141#issuecomment-1277250021

* [x] [XmlnsDictionary](https://learn.microsoft.com/dotnet/api/system.windows.markup.xmlnsdictionary)
* [x] [XmlSerializerNamespaces](https://learn.microsoft.com/dotnet/api/system.xml.serialization.xmlserializernamespaces)
* [x] [XmlQualifiedName construktor](https://learn.microsoft.com/de-de/dotnet/api/system.xml.xmlqualifiedname.-ctor?view=net-6.0#system-xml-xmlqualifiedname-ctor(system-string-system-string))
* [x] [XmlNamespaceManager Class (System.Xml)](https://learn.microsoft.com/en-us/dotnet/api/system.xml.xmlnamespacemanager?view=net-6.0)
* [x] [XmlAttribute(String, String, String, XmlDocument) Constructor (System.Xml) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/system.xml.xmlattribute.-ctor?view=net-6.0#system-xml-xmlattribute-ctor(system-string-system-string-system-string-system-xml-xmldocument))
* [x] [XmlElement(String, String, String, XmlDocument) Constructor (System.Xml) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/system.xml.xmlelement.-ctor?view=net-6.0#system-xml-xmlelement-ctor(system-string-system-string-system-string-system-xml-xmldocument))
* [x] [XmlWriter.WriteStartElement Method (System.Xml)](https://learn.microsoft.com/en-us/dotnet/api/system.xml.xmlwriter.writestartelement?view=net-6.0#system-xml-xmlwriter-writestartelement(system-string-system-string))
* [x] [XmlWriter.WriteElementString Method (System.Xml) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/system.xml.xmlwriter.writeelementstring?view=net-6.0#system-xml-xmlwriter-writeelementstring(system-string-system-string-system-string))
* [x] [XmlSerializationWriter.WriteElementStringRaw Method (System.Xml.Serialization) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmlserializationwriter.writeelementstringraw?view=netcore-3.1)

Update list of well-known namespaces
* [x] https://referencesource.microsoft.com/#system.xml/System/Xml/XmlReservedNs.cs
* [x] Add oasis-open.org namespaces (e.g. wss, see e.g. [peach](https://peach.sonarsource.com/security_hotspots?id=wcf&hotspots=AXddXtF0Po2w9IEVshSJ)):
http://docs.oasis-open.org/wss/2004/01/
* [x] Add ws-i.org namespaces http://ws-i.org/ e.g. [peach](https://peach.sonarsource.com/security_hotspots?id=wcf&hotspots=AXZ4YUlp7R5umuxffeXo)

**Comment by rjgotten** [comment]
FWIW, the check list does not yet reference [`XNamespace`](https://learn.microsoft.com/en-us/dotnet/api/system.xml.linq.xnamespace), which is also affected by the false positive.


And your list of well-known namespaces could also have sitemaps added:
`http://www.sitemaps.org/schemas/sitemap/0.9`

**Comment by martin-strecker-sonarsource** [comment]
Thank you @rjgotten for reporting. The sitemap namespace will be added. Support for the XNamespace API will also be added, but with some limitations. See the test case for details:
https://github.com/SonarSource/sonar-dotnet/pull/7482/files#diff-9d22fd8dc259a8a9bcc0bacccf088e947ebd6f9f1d01a2a327c9f7c53031cfcbR362-R369
