### ISSUE TITLE
S2259 ignores [DoesNotReturn]

### ISSUE THREAD

**Issue by YuriiBabenko** [SonarSource/sonar-dotnet#6264]
### Description

I get issue csharpsquid:S2259 when I replace `throw new Exception()` with calling method marked with `[DoesNotReturn]` attribute. If I replace it back to `throw new Exception()` warning is gone.

### Repro steps

```
public async Task MyBusinessLogic(SomeRequest request)
    {
        if (request is null)
        {
            RaiseModelError(nameof(request), "Error message");
        }

        // i get S2259 on request here, but there is no way request is null here
        if (string.IsNullOrEmpty(request.Provider))
        {
            // some action
        }
        else
        {
            // some another action
        }
    }

    [DoesNotReturn]
    private static void RaiseModelError(string paramName, string errorMessage) =>
        throw new ModelErrorException(new Dictionary<string, string>()
        {
            {
                paramName,
                errorMessage
            }
        });
```

### Expected behavior

I do not get a "Null pointers should not be dereferenced" warning, because there is no way `request` might be `null`, if `RaiseModelError` was called. In shorter words, I expect the same behaviour as if I wrote `throw new ModelErrorException()` directly

### Actual behavior

I get a "bug" warning, because sonar thinks that there is a way `request` object may be null when I access the `Provider` property

### Known workarounds

If I replace calling method with `[DoesNotReturn]` attribute with `throw new Exception();` everything works as it should do.

### Related information

* C# version: 10
* SonarLint version: 7.1.1.54565
* Visual Studio version: Rider 2022.2.3
* .NET version 6.0.8
* Operating System: Windows 10

**Comment by YuriiBabenko** [comment]
interesting observation: in this case i do not get the warning, but the logic is the same

```
public async Task MyBusinessLogic(SomeRequest request)
    {
        RaiseModelError(request is not null, nameof(request), "Error message");

        // the logic is exact the same, but i DO NOT get S2259 on request here
        if (string.IsNullOrEmpty(request.Provider))
        {
            // some action
        }
        else
        {
            // some another action
        }
    }

    private static void RaiseModelError([DoesNotReturnIf(false)] bool result, string paramName, string errorMessage)
    {
        if (!result)
        {
            throw new ModelErrorException(new Dictionary<string, string>()
            {
                {
                    paramName,
                    errorMessage
                }
            });
        }
    }
```

**Comment by pavel-mikula-sonarsource** [comment]
Hi @YuriiBabenko,

Support of `DoesNotReturnAttribute` was added in version [8.46](https://github.com/SonarSource/sonar-dotnet/releases/tag/8.46.0.54807) of our analyzer. That will be part of SonarLint for Rider 7.2 that is not released yet, see [SLI-762](https://sonarsource.atlassian.net/browse/SLI-762)

For the record, the latest release [8.47](https://github.com/SonarSource/sonar-dotnet/releases/tag/8.47.0.55603) contains many further improvements of S2259 rule. You can track [SLI-800](https://sonarsource.atlassian.net/browse/SLI-800) to see what SonarLint version it will be shipped with.

**Comment by YuriiBabenko** [comment]
ok, thanks
