### ISSUE TITLE
Add repository link to NuGet packages

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#6338]
@teo-tsirpanis wrote:

Hello, where is the package's source code? It is marked as licensed under the GNU LGPL v3, which requires you to share the source code.

While the source code is public (see this repo 😄 ), link is not present in NuGet website. It should be somewhere in the right column.
https://www.nuget.org/packages/SonarAnalyzer.CSharp/8.48.0.56517

**Comment by andrei-epure-sonarsource** [comment]
It is present in the release notes... We could add it to the README (see https://trello.com/c/aInbyMcc/207-package-readme-on-nugetorg).

Docs:
- https://learn.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices#repository-type-and-url
- https://learn.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org

Note: the `PackageProjectUrl` is currently linking to the SonarLint site (which is not quite accurate, but well it's some promotion). Before that, it was linking to the C# page on the sonarsource.com website. Either way, it should be a high-level overview of what we offer.

This ticket should only add the `RepositoryUrl` to the nuget config.

**Comment by teo-tsirpanis** [comment]
Thanks for the quick resolution!
