### ISSUE TITLE
Fix S1067 FP: Conditionals in pattern should not be considered as a unit for the whole pattern

### ISSUE THREAD

**Issue by martin-strecker-sonarsource** [SonarSource/sonar-dotnet#6429]
### Description

In pattern like this:
```cs
_ = new Exception() is ArgumentException // Noncompliant FP
{
    Message: "A" or "B" or "C",
    InnerException:
    {
        Message: "D" or "E" or "F",
    }
};
```
The `or` patterns are counted as a single group and S1067 is raised because more than 3 `or` are present. Because the two checks don't belong together directly the property patterns should be considered a "conditional root". Also, note that other sub-pattern kinds are also roots (declaration pattern, var pattern, list pattern, and maybe more).

Some test cases were added in #6428

C# 11 list pattern are also affected
```cs
_ = new[] { 1, 2, 3 } is [1 or 2 or 3, 1 or 2 or 3, _]; // Noncompliant FP
```

**Comment by martin-strecker-sonarsource** [comment]
Preliminary Peach validation until AX0U1INEAng_OcXOZhgF:

### Lost: Tenary operator condition (Not exactly defined by the RSpec)

https://peach.sonarsource.com/code?id=dnn&selected=dnn%3ADNN+Platform%2FLibrary%2FEntities%2FUsers%2FUserController.cs&line=1674

if the conditions appear in the "Condition" of the ternary, then the ternary is ignored, because we do not step only into the WhenTrue and WhenFalse part but not the Condition part.

```cs
var userId = user != null && user.UserID > 0 && !user.IsDeleted && (showSuperUsers || !user.IsSuperUser) 
    ? user.UserID
    : 0;
```
More:
https://peach.sonarsource.com/code?id=dnn&selected=dnn%3ADNN+Platform%2FLibrary%2FServices%2FAuthentication%2FAuthenticationController.cs&line=259

https://peach.sonarsource.com/code?id=dnspy&selected=dnspy%3AdnSpy%2FdnSpy%2FText%2FFormatting%2FWpfTextViewLine.cs&line=651

https://peach.sonarsource.com/code?id=dotnet-runtime&selected=dotnet-runtime%3Asrc%2Flibraries%2FMicrosoft.Bcl.AsyncInterfaces%2Fsrc%2FSystem%2FThreading%2FTasks%2FSources%2FManualResetValueTaskSourceCore.cs&line=91

https://peach.sonarsource.com/code?id=dotnet-runtime&selected=dotnet-runtime%3Asrc%2Flibraries%2FSystem.ComponentModel.TypeConverter%2Fsrc%2FMS%2FInternal%2FXml%2FLinq%2FComponentModel%2FXComponentModel.cs&line=311

https://peach.sonarsource.com/code?id=dotnet-runtime&selected=dotnet-runtime%3Asrc%2Flibraries%2FSystem.Data.Common%2Fsrc%2FSystem%2FData%2FDataRowCollection.cs&line=102

https://peach.sonarsource.com/code?id=dotnet-runtime&selected=dotnet-runtime%3Asrc%2Flibraries%2FSystem.Data.Common%2Fsrc%2FSystem%2FData%2FSelect.cs&line=695

https://peach.sonarsource.com/code?id=dotnet-runtime&selected=dotnet-runtime%3Asrc%2Flibraries%2FSystem.Linq.Expressions%2Fsrc%2FSystem%2FLinq%2FExpressions%2FCompiler%2FILGen.cs&line=802

### Lost: XOR (Not specified by the RSpec)

https://peach.sonarsource.com/code?id=dnspy&selected=dnspy%3AdnSpy%2FdnSpy.Contracts.Debugger%2FBreakpoints%2FModules%2FDbgModuleBreakpointSettings.cs&line=99

https://peach.sonarsource.com/code?id=dnspy&selected=dnspy%3AdnSpy%2FdnSpy.Contracts.DnSpy%2FHex%2FEditor%2FHexGroups%2FLocalGroupOptions.cs&line=159

https://peach.sonarsource.com/code?id=dotnet-runtime&selected=dotnet-runtime%3Asrc%2Flibraries%2FSystem.Net.Http%2Fsrc%2FSystem%2FNet%2FHttp%2FHeaders%2FCacheControlHeaderValue.cs&line=333

### Lost: Nested in other binary expression

https://peach.sonarsource.com/code?id=dnspy&selected=dnspy%3AExtensions%2FILSpy.Decompiler%2FICSharpCode.Decompiler%2FICSharpCode.Decompiler%2FILAst%2FInitializerPeepholeTransforms.cs&line=341

Ternary is on the right-hand side of a `!=` expression. We should step into all kinds of binary expressions but not count them as complexity-increasing.

```cs
recheck =
    inlining.numLdloc.GetOrDefault(v) != 1 ||
    inlining.numLdloca.GetOrDefault(v) != totalElementCount + (expr.Code == ILCode.Call ? 1 : 0)) ||
    (inlining.numStloc.GetOrDefault(v) != (expr.Code == ILCode.Call ? 0 : 1));
```

More
https://peach.sonarsource.com/code?id=dnspy&selected=dnspy%3ALibraries%2FICSharpCode.TreeView%2FFlatListTreeNode.cs&line=58

https://peach.sonarsource.com/code?id=dotnet-runtime&selected=dotnet-runtime%3Asrc%2Flibraries%2FMicrosoft.CSharp%2Fsrc%2FMicrosoft%2FCSharp%2FRuntimeBinder%2FSemantics%2FMemberLookup.cs&line=176

### `&` and `|`

https://peach.sonarsource.com/code?id=dotnet-runtime&selected=dotnet-runtime%3Asrc%2Flibraries%2FMicrosoft.CSharp%2Fsrc%2FMicrosoft%2FCSharp%2FRuntimeBinder%2FSymbolTable.cs&line=117

https://peach.sonarsource.com/code?id=dotnet-runtime&selected=dotnet-runtime%3Asrc%2Flibraries%2FSystem.Composition.TypedParts%2Fsrc%2FSystem%2FComposition%2FTypedParts%2FActivationFeatures%2FOnImportsSatisfiedFeature.cs&line=42

https://peach.sonarsource.com/code?id=dotnet-runtime&selected=dotnet-runtime%3Asrc%2Flibraries%2FSystem.Configuration.ConfigurationManager%2Fsrc%2FSystem%2FConfiguration%2FConfigurationElement.cs&line=645

### Lost: In invocation arguments (TP)

We need to consider some expressions as "begins a new tree". Invocation arguments belong here.

https://peach.sonarsource.com/code?id=dotnet-runtime&selected=dotnet-runtime%3Asrc%2Flibraries%2FSystem.Data.Common%2Fsrc%2FSystem%2FData%2FSQLTypes%2FSQLBoolean.cs&line=280

https://peach.sonarsource.com/code?id=dotnet-runtime&selected=dotnet-runtime%3Asrc%2Flibraries%2FSystem.Data.Common%2Fsrc%2FSystem%2FData%2FSQLTypes%2FSQLDateTime.cs&line=522

**Comment by andrei-epure-sonarsource** [comment]
do you plan to make a fix for these @martin-strecker-sonarsource (as it was a side-effect of the refactoring)?

**Comment by martin-strecker-sonarsource** [comment]
For the first one we need to do something (the condition part of an outermost ternary is not checked at all at the moment). For the others, I would define other binaries as "transparent" (except maybe XOR, `|` and `&`). Invocation arguments start a new root IMO on the other hand (TP).

**Comment by andrei-epure-sonarsource** [comment]
I agree that invocation arguments start a new root.

**Comment by martin-strecker-sonarsource** [comment]
Second peach validation run:

### if directive conditions

The rule should not raise in `#if` and `#elif` context. See e.g.:

https://peach.sonarsource.com/project/issues?issues=AYUVHDDKlZ5lVLD55SRL&open=AYUVHDDKlZ5lVLD55SRL&id=dnn

https://peach.sonarsource.com/project/issues?issues=AYUVHDEplZ5lVLD55SW4&open=AYUVHDEplZ5lVLD55SW4&id=dnn

Issue https://github.com/SonarSource/sonar-dotnet/issues/6574
