### ISSUE TITLE
Fix S1905 FP: Nullability context and array of anonymous types

### ISSUE THREAD

**Issue by paulhickman-a365** [SonarSource/sonar-dotnet#6438]
### Description

In a .net 6 project where nullable reference types is enabled, in the example below the casts to string? are necessary, otherwise the nullability of x in the two array elements doesn't match and this produces a  CS8206 error 

### Repro steps

````
var anon = new[] { new { x = (string?)"foo" }, new { x = (string?)null } };
````

### Expected behavior

No S1905 warning is produced

### Actual behavior

S1905 warning is produced

### Known workarounds

Don't use anonymous types and create a class with a property x of type string? and declare the array of that type

### Related information

* C# 8 with nullable reference types on
* VS 2022 19.4.0
* SonarScanner 8.49.0.57237
* Operating System Windows Server 2022

**Comment by mary-georgiou-sonarsource** [comment]
Hello, again @paulhickman-a365, and thanks for opening this issue. Your feedback helps us improve our products. We will look at it as soon as possible. After we confirm the issue, we will add labels and put it in our backlog

**Comment by pavel-mikula-sonarsource** [comment]
Hi @paulhickman-a365,

Thank you for reporting this, I confirm it as FP.

It also reproduces with `#nullable enable`
