### ISSUE TITLE
Mediatr C# plugin on SonarQube scanner

### ISSUE THREAD

**Issue by dmitriy-pisarevskiy** [SonarSource/sonar-dotnet#6446]
Hey! How we can detect Mediatr issues on some command handler ? for example recursion:
![image](https://user-images.githubusercontent.com/70516019/204009845-b1d654a3-040b-412a-a9c4-13f04311b8f5.png)

Thanks!

**Comment by costin-zaharia-sonarsource** [comment]
Hi @dmitriy-pisarevskiy,

for this kind of questions please use the community forum: https://community.sonarsource.com/
