### ISSUE TITLE
C# `record` with implicit constructors and null-guarded `init` are not properly handled

### ISSUE THREAD

**Issue by SimonRansonCalyx** [SonarSource/sonar-dotnet#6472]
### Description

Records with implicit constructors and null-guarded inits are not properly handled by csharpsquid:S3928

### Repro steps

      namespace BusinessOperations.Application.Models
      {
       public record CreateUserValidationRowRequest(string firstName) : IRequest<ResponseBodyModel<CreateUserValidationRowResponse>>
       {
           public string FirstName { get; init; } = firstName ?? throw new ArgumentNullException(nameof(firstName));
       }
      }

### Expected behavior

Parameter names declared in implicit ctor used in ArgumentException constructors should be checked correctly

### Actual behavior

`nameof(firstName)` is flagged as invalid

### Known workarounds

Fully declare ctor and do null-guarding in there instead

**Comment by mary-georgiou-sonarsource** [comment]
Thank you for opening this issue, @SimonRansonCalyx. Your feedback helps us improve our products.

This issue has been fixed since version 8.44 of the analyzer (see https://github.com/SonarSource/sonar-dotnet/issues/5094).
How do you use the analyzer? (SonarLint, SonarQube, NuGet package?)

Cheers
Mary

**Comment by SimonRansonCalyx** [comment]
@mary-georgiou-sonarsource 
Cheers, this is occurring in SonarQube Enterprise Edition Version 9.6.1 (build 59531).
Am I out of date?

**Comment by mary-georgiou-sonarsource** [comment]
@SimonRansonCalyx SonarQube Enterprise Edition Version 9.6.1 comes with sonar-donet 8.43.
SQ Enterprise Latest (9.7.1) contains the updated analyzer (sonar-dotnet 8.46) that includes the fix for this issue.

**Comment by SimonRansonCalyx** [comment]
Awesome thanks!
