### ISSUE TITLE
FN S1481: Support linq range variables

### ISSUE THREAD

**Issue by martin-strecker-sonarsource** [SonarSource/sonar-dotnet#6479]
### Description

S1481 (Unused local variables should be removed) should support query comprehension range variables too:

```cs
        _ = from a in byteArray
            let b = true
            let c = false
            group c by c into g
            join d in new object[0] on g equals d into f
            select g into e
            select true;
```

In the example above `a`, `b`, `, `e`, and `f` are range variables that are unused. There might be cases where range variables `g` (likely) and `d` (most likely not) can also be unused.

**Comment by alex-meseldzija-sonarsource** [comment]
Implemented with NET-304
