### ISSUE TITLE
FN S4784: Add support for StringSyntaxAttribute.Regex

### ISSUE THREAD

**Issue by martin-strecker-sonarsource** [SonarSource/sonar-dotnet#6482]
### Description

*Note:* Rule is deprecated

.Net 7 introduced [StringSyntaxAttribute.Regex Field (System.Diagnostics.CodeAnalysis)](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.stringsyntaxattribute.regex?view=net-7.0) which can be used to mark parameters as excepting regular expressions. It is used e.g. in the new [GeneratedRegexAttribute](
https://github.com/dotnet/runtime/blob/5df8e75ffeb67e49e097b38013de5b676ca24ba9/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/GeneratedRegexAttribute.cs#L30) to mark the pattern parameter. S4784 (Using regular expressions is security-sensitive) should be extended to also look for suspicious regex in invocations with arguments corresponding to a parameter marked with the StringSyntaxAttribute.Regex attribute.
S4784 should also be extended to look into attribute arguments marked with that attribute.

**Comment by martin-strecker-sonarsource** [comment]
@andrei-epure-sonarsource the rule affected is deprecated and the replacement rules are not implemented in this analyzer. Should I close the issue?

**Comment by andrei-epure-sonarsource** [comment]
yes, let's code this. We should not touch deprecated rules.

**Comment by andrei-epure-sonarsource** [comment]
@martin-strecker-sonarsource is S2631 affected?

**Comment by martin-strecker-sonarsource** [comment]
I think [S2631](https://sonarsource.github.io/rspec/#/rspec/S2631) is in security and I haven't checked that.
