### ISSUE TITLE
Support for F#

### ISSUE THREAD

**Issue by rolyv** [SonarSource/sonar-dotnet#6554]
There is a small group within the F# community that is willing to work on adding this. The purpose of this issue is mainly to understand if this would be something that you would potentially consider accepting via PR to consolidate under the `dotnet` umbrella. And if so, would you have any guidance on what you would want to see to consider accepting such a PR?

**Comment by abelbraaksma** [comment]
Chiming in here. Currently two plugins exist (one for security, one for linting/coverage) that are a bit outdated, but could be a starting point for doing this. I've looked at it and it wasn't immediately obvious how they could be unified.

It'd be interesting to hear from the `dotnet sonar` team to hear what their preferred approach is to add it. I think it would go a long way to add this kind of F# support to SonarQube through this repo.

**Comment by pavel-mikula-sonarsource** [comment]
Hi,

Please create a topic on http://community.sonarsource.com/ where it has better visibility for our product managers.

As far as I know, F# is not a Roslyn-based language and the analyzer would not live in this repository.

Our plugin SDK is also available to build custom plugin for your SonarQube instance (not SonarCloud, not SonarLint)

**Comment by abelbraaksma** [comment]
@pavel-mikula-sonarsource, you’re right, F# isn’t Roslyn based. But considering this repo is called ‘sonar-dotnet’, it feels like the right place to bring all (MS) dotnet technologies under the same roof.

But if it’s impossible to hook up a different language + analyser, that’s not possible then…

**Comment by jkone27** [comment]
Maybe relevant for who is interested in implementing smt : https://medium.com/lambda-factory/introducing-f-analyzers-772487889429
