### ISSUE TITLE
Performance: UtilityAnalyzerBase calls GetSemanticModel for each SyntaxTree

### ISSUE THREAD

**Issue by martin-strecker-sonarsource** [SonarSource/sonar-dotnet#6558]
`UtilityAnalyzerBase` calls `Compilation.GetSematicModel(syntaxTree)` here

https://github.com/SonarSource/sonar-dotnet/blob/f6a6857245b7ae96c7083ddbb8eebf06b30a4054/analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs#L98-L100

This is such a big performance issue that the Roslyn team wrote an analyzer [RS1030](https://github.com/dotnet/roslyn-analyzers/blob/main/src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.md#rs1030-do-not-invoke-compilationgetsemanticmodel-method-within-a-diagnostic-analyzer) to flag its use. We should consider looking for a better approach as described by the message of that rule:

https://github.com/dotnet/roslyn-analyzers/issues/3114#issuecomment-674199811

**Comment by andrei-epure-sonarsource** [comment]
(off-topic from this issue) @martin-strecker-sonarsource from this POV, should we use `RegisterSemanticModelAction` for all our rules?

**Comment by martin-strecker-sonarsource** [comment]
> should we use RegisterSemanticModelAction for all our rules?

Not in general, but we should look for violations of [RS1030](https://github.com/dotnet/roslyn-analyzers/blob/main/src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.md#rs1030-do-not-invoke-compilationgetsemanticmodel-method-within-a-diagnostic-analyzer).

There are some use cases where you have no other option than to call `Compilation.GetSemanticModel(SyntaxTree)`. e.g. if you have an invocation node in the current tree and you get the `IMethodSymbol` of the invoked method and you call  `IMethodSymbol.DeclaringSyntaxReferences` and you want to query some semantic model based on the syntax found, it might be that the method is defined in another file and therefore another SyntaxTree and you have to call `Compilation.GetSemanticModel(SyntaxTree)` to get the right SemanticModel. This is what `GetSemanticModelOrDefault` is for in our codebase.

https://github.com/SonarSource/sonar-dotnet/blob/543953bc48d99d393505d9ec467159dbb945a8cb/analyzers/src/SonarAnalyzer.Common/Helpers/SemanticModelHelper.cs#L25-L36

**Comment by martin-strecker-sonarsource** [comment]
>  should we use RegisterSemanticModelAction for all our rules?

We should definitely think about some RegisterSyntaxTree analyzer. If we call the semanticModel in 99% of the cases for such a rule, we are better off with using RegisterSemanticModel instead. The reason is that "SyntxTreeAction" gets called right after the AST is produced. Then the compiler does in parallel the binding (which takes a long time). If you call the semanticModel, you will have to wait until the binding is finished basically blocking the thread.
If we use RegisterSemanticModel in such a case, no blocking occurs because the action is called when the binding is done.

I'm not really sure if the above is exactly right as the documentation doesn't tell about these specifics. The best I could find was this: https://github.com/dotnet/roslyn/blob/main/docs/analyzers/Analyzer%20Actions%20Semantics.md

**Comment by pavel-mikula-sonarsource** [comment]
On Akka.Net, I did not see any change in performance, the semantic models are most likely cached as they are queried by different rules of the same analysis:
Before: 67s. 65s. 67s
After: 62s, 66s, 69s

**Comment by pavel-mikula-sonarsource** [comment]
Results for lucenenet - small improvement
Before
1:48
1:29
1:30
1:35
1:34

After
1:47
1:27
1:31
1:28
1:29

**Comment by martin-strecker-sonarsource** [comment]
Reopened
