### ISSUE TITLE
Is it possible to create ClassInitialize methods in one class and call that method in multiple class to avoid duplication

### ISSUE THREAD

**Issue by manurajvr** [SonarSource/sonar-dotnet#6619]
Hello,

I have a lot of classes in my project and each class has TestInitialize method at the top of the class.  Sonar Cloud analyzing this as a duplication. Is there any way to overcome that?

**Comment by pavel-mikula-sonarsource** [comment]
So you have duplicated [TestInitialize] method in each class? As the syntax is duplicated, it should be reported as such. 

You can ask for a way to suppress these in https://community.sonarsource.com/ if you provide more detailed description, as such feature would not be part of this repository.
