### ISSUE TITLE
Fix S3415 FP/FN: Support named arguments 

### ISSUE THREAD

**Issue by cristian-ambrosini-sonarsource** [SonarSource/sonar-dotnet#6630]
### Description

S3415 doesn't support named arguments and considers only the positions of those, resulting in the following FN/FP:

```cs
var str = "";
Assert.AreEqual(actual: "", expected: str); // Compliant FN
Assert.AreEqual(expected: "", actual: str); // Compliant
Assert.AreEqual(actual: str, expected: ""); // Noncompliant FP
Assert.AreEqual(expected: str, actual: ""); // Noncompliant
```

**Comment by martin-strecker-sonarsource** [comment]
The issue should be solved by using 

https://github.com/SonarSource/sonar-dotnet/blob/49f172c22abe04172b3e8e0cab99e21e5fe33999/analyzers/src/SonarAnalyzer.Common/Helpers/MethodParameterLookupBase.cs#L23
