### ISSUE TITLE
New rule S1133: Deprecated code should be removed

### ISSUE THREAD

**Issue by cristian-ambrosini-sonarsource** [SonarSource/sonar-dotnet#6656]
S1133

RSpec change: https://github.com/SonarSource/rspec/pull/1512

**Comment by Corniel** [comment]
What is the difference between this one and [CS0612](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0612)?

**Comment by martin-strecker-sonarsource** [comment]
[CS0612](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0612) is raised on the call side while S1133 is raised on the declaration. S1133 is meant to be a reminder to remove the deprecated member with e.g. the next major version release.

**Comment by Corniel** [comment]
@martin-strecker-sonarsource That makes a lot of sense! It might be worth to explain that difference in the documentation and reference SC0612.
