### ISSUE TITLE
New rule S2198: Silly mathematical comparisons should not be made

### ISSUE THREAD

**Issue by cristian-ambrosini-sonarsource** [SonarSource/sonar-dotnet#6658]
S2198
RSPEC PR: https://github.com/SonarSource/rspec/pull/1534

**Comment by gregory-paidis-sonarsource** [comment]
Maybe this could be a part of S2437.

Or even better, the other way around, we could merge the rules and have different diagnostics.

**Comment by gregory-paidis-sonarsource** [comment]
Looking a bit at what this rule covers, as well as some testing:

- comparing a byte with an int or long constant that’s outside the byte range

This is covered by [CS0652](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0652?f1url=%3FappId%3Droslyn%26k%3Dk(CS0652)) for all types of of comparisons (<, <=, >, >=, ==)

- comparing an int with a long constant that’s outside the int range

This is covered by [CS0652](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0652?f1url=%3FappId%3Droslyn%26k%3Dk(CS0652)) for all types of of comparisons (<, <=, >, >=, ==)

- comparing a value guaranteed to be negative with a one that’s guaranteed to be non-negative

This is covered by [CS0652](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0652?f1url=%3FappId%3Droslyn%26k%3Dk(CS0652)) for comparing a `uint` with a constant negative int. I cannot think of any other usecases. 

- comparing aByte <= Byte.MAX_VALUE and aByte >= Byte.MIN_VALUE

Not covered.

- comparing anInt <= Integer.MAX_VALUE and anInt >= Integer.MIN_VALUE

Not covered.

- comparing aLong <= Long.MAX_VALUE and aLong >= Long.MIN_VALLUE

Not covered.

- Additional notes

Maybe we can implement a comparison between `float` and constant `double` that is `> float.MaxValue`.

**Comment by gregory-paidis-sonarsource** [comment]
We decided to implement only the parts that are NOT covered by [CS0652](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0652?f1url=%3FappId%3Droslyn%26k%3Dk(CS0652)), meaning:

- comparing aByte <= `byte.MaxValue` and aByte >= `byte.MinValue`
- comparing anInt <= `int.MaxValue` and anInt >= `int.MinValue`
- comparing aLong <= `long.MaxValue` and aLong >= `long.MinValue`
- comparing a float with a constant double outside of float's range

Also, to cut branches we will only implement the C# part of the rule, at least at first.

Also, it will indeed be part of [S2437](https://sonarsource.github.io/rspec/#/rspec/S2437/csharp).
