### ISSUE TITLE
New rule S2970: Assertions should be complete

### ISSUE THREAD

**Issue by gregory-paidis-sonarsource** [SonarSource/sonar-dotnet#6662]
[S2970](https://sonarsource.github.io/rspec/#/rspec/S2970)
RSpec change: https://github.com/SonarSource/rspec/pull/1518

Related rule S2699 implemented in [TestMethodShouldContainAssertion](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldContainAssertion.cs)

Methods/Props without "continuation" that should be detected:

* ~MSTest:~ Update: `Assert.That` is a property and can not be misused.
  * https://learn.microsoft.com/dotnet/api/microsoft.visualstudio.testtools.unittesting.assert.that `Assert.That`
  * https://learn.microsoft.com/dotnet/api/microsoft.visualstudio.testtools.unittesting.stringassert.that `StringAssert.That`
  * https://learn.microsoft.com/dotnet/api/microsoft.visualstudio.testtools.unittesting.collectionassert.that `CollectionAssert.That`
* Fluent Assertions: https://fluentassertions.com/introduction `Should()`
* NFluent: https://www.n-fluent.net `Check.That()`
* NSubstitute: https://nsubstitute.github.io/help/received-calls `Received()` and related like `DidNotReceiveWithAnyArgs()`

Unaffected libraries:
* NUnit
* xUnit
* Shoudly

Existing rules in the testing libs:

* NFluent: https://github.com/tpierrain/NFluent/blob/9fa14534df80d129149f32204848b12a57aac98a/code/src/Analyzer/NFluent.Analyzer/NFluent.Analyzer/NFluentAnalyzer.cs#L96-L104
* NSubstitute: https://github.com/nsubstitute/NSubstitute.Analyzers/blob/dev/documentation/rules/NS5000.md

**Comment by gregory-paidis-sonarsource** [comment]
This rule could be implemented as an additional diagnostic inside of S2699.
This will improve the precision of the rule's raised diagnostic, while also being faster than implementing similar logic twice, at least up until a point.

**Comment by martin-strecker-sonarsource** [comment]
MSTest was removed because `Assert.That` is a property and can not be used as a standalone statement.
