### ISSUE TITLE
New Rule S2445: Blocks should be synchronized on read-only fields

### ISSUE THREAD

**Issue by zsolt-kolbay-sonarsource** [SonarSource/sonar-dotnet#6701]
Implement S2445 for C#

The check for `private` has been removed, following the outcome of the discussion [here](https://github.com/SonarSource/rspec/pull/1570#discussion_r1115676243), summarized [here](https://github.com/SonarSource/rspec/pull/1570#issue-1582097418).

**Comment by pavel-mikula-sonarsource** [comment]
We need to rename the rule to C# syntax

**Comment by antonioaversa** [comment]
Results of Peach Validation: many FP found on "locking of local variables" for "advanced" synchronization scenarios such as:
- fine graned synchronization via collections of lock objects;
- renaming of a `readonly` field in the context of the current method;
- locking inside a loop, on the iteration variable.

A new rule S6507 has been created (https://github.com/SonarSource/sonar-dotnet/pull/6854), to extract the offending check from S2445. S6507 is still a BUG, but it is not in the Sonar Way.
