### ISSUE TITLE
[TEST] Fixing Rule Specification Backlog

### ISSUE THREAD

**Issue by gregory-paidis-sonarsource** [SonarSource/sonar-dotnet#6742]
**To be deleted**

**Comment by pavel-mikula-sonarsource** [comment]
Rule specification is not automated.
.NET Bubble Backlog is (partially) automated. It should auto-assign the status - it was working with the old board, it doesn't with the current due to different GitHub API

**Comment by gregory-paidis-sonarsource** [comment]
Hey @pavel-mikula-sonarsource , thanks for making it clear, I had this exact question.

Also, this is a pet issue that I use to understand how the backlog works, so feel free to unsubscribe from it (useless email noise).
