### ISSUE TITLE
Improve S2589: Detect comparison between constant values

### ISSUE THREAD

**Issue by gregory-paidis-sonarsource** [SonarSource/sonar-dotnet#6745]
Comparing a `constant` value with another `constant` value does not make much sense.
The evaluation yields exclusively `true` or `false`, meaning the "conditional" code is always/never executed.

```csharp
            const int constant1 = 42;
            const int constant2 = 42;
            const int constant3 = 43;

            if (constant1 == constant2) // Noncompliant, always true
            {
                DoWork(); // Always executed
            }

            if (constant1 == constant3) // Noncompliant, always false
            {
                DoWork(); // Never executed
            }
```

**Comment by pavel-mikula-sonarsource** [comment]
This should just start working out of the box when migrating to the new engine, as we already compute BoolConstraint from NumberConstraint comparisons.

**Comment by mary-georgiou-sonarsource** [comment]
Fixed by https://github.com/SonarSource/sonar-dotnet/pull/7750
