### ISSUE TITLE
Performance validation log parsing fails with "Version is missing" on Cirrus CI

### ISSUE THREAD

**Issue by antonioaversa** [SonarSource/sonar-dotnet#6767]
The majority of analyses of projects on peach fail with the following issue:
```
Parsing build.binlog...
Unhandled exception. System.IO.InvalidDataException: Version is missing.
   at ParseBuildOutput.LogParsing.ParseResult.Analyzer..ctor(String version, String commitHash) in C:\Windows\TEMP\cirrus-ci-build\ParseBuildOutput\ParseBuildOutput\LogParsing\ParseResult.cs:line 69
``` 

That blocks the release of v. 8.53 of the C# and VB.NET analyzers.

Example of failing build: https://cirrus-ci.com/build/6272950563766272

15 Feb https://cirrus-ci.com/build/6692363783897088 => OK
16 Feb https://cirrus-ci.com/build/5395613366353920 => Build stopped
17 Feb https://cirrus-ci.com/build/6201194612260864 => KO

All on the same peachee-languages commit https://github.com/SonarSource/peachee-languages/commit/62c36a3078b57deeee0e23f70eaf6da932bc8462

Latest change on https://github.com/SonarSource/peachee-languages/tree/dotnet on Feb 13:
https://github.com/SonarSource/peachee-languages/commit/62c36a3078b57deeee0e23f70eaf6da932bc8462
(which produced a working build on Feb 15).

Related PR: https://github.com/SonarSource/peachee-languages/pull/372

**Comment by andrei-epure-sonarsource** [comment]
ToDo: @antonioaversa found out that the version is read from `SonarQubeAnalysisConfig.xml`.

The failures are stochastic. ToDo: "cat" the output in the script for this XML file to see if sometimes it gets corrupted.

Until we fix this, we've removed the performance checks on Peachee : https://github.com/SonarSource/peachee-languages/pull/388

**Comment by martin-strecker-sonarsource** [comment]
Most likely this issue is caused by a failure in the begin step:
https://cirrus-ci.com/task/5924296661401600?logs=scanner_begin#L14
The download of the plugins from the server failed.

**Comment by antonioaversa** [comment]
@martin-strecker-sonarsource 
Indeed, lack of analyzers during the build, as reported in https://cirrus-ci.com/task/6178354580160512?logs=build#L81 (which was not a problem before, c.p. https://cirrus-ci.com/task/5945471521259520?logs=build#L0), seems to produce a `.sonarqube\conf\SonarQubeAnalysisConfig.xml` which lacks the `Analysers`:
```xml
<AnalyzerPlugins>
        <AnalyzerPlugin Key="csharp" Version="8.52.0.60960" StaticResourceName="SonarAnalyzer-8.52.0.60960.zip">
          <AssemblyPaths>
            <Path>C:\Users\antonio.aversa\AppData\Local\Temp\.sonarqube\resources\0\Google.Protobuf.dll</Path>
            <Path>C:\Users\antonio.aversa\AppData\Local\Temp\.sonarqube\resources\0\SonarAnalyzer.CFG.dll</Path>
            <Path>C:\Users\antonio.aversa\AppData\Local\Temp\.sonarqube\resources\0\SonarAnalyzer.CSharp.dll</Path>
            <Path>C:\Users\antonio.aversa\AppData\Local\Temp\.sonarqube\resources\0\SonarAnalyzer.dll</Path>
            <Path>C:\Users\antonio.aversa\AppData\Local\Temp\.sonarqube\resources\0\THIRD-PARTY-NOTICES.txt</Path>
          </AssemblyPaths>
        </AnalyzerPlugin>
        <AnalyzerPlugin Key="vbnet" Version="8.52.0.60960" StaticResourceName="SonarAnalyzer-8.52.0.60960.zip">
          <AssemblyPaths>
            <Path>C:\Users\antonio.aversa\AppData\Local\Temp\.sonarqube\resources\1\Google.Protobuf.dll</Path>
            <Path>C:\Users\antonio.aversa\AppData\Local\Temp\.sonarqube\resources\1\SonarAnalyzer.CFG.dll</Path>
            <Path>C:\Users\antonio.aversa\AppData\Local\Temp\.sonarqube\resources\1\SonarAnalyzer.dll</Path>
            <Path>C:\Users\antonio.aversa\AppData\Local\Temp\.sonarqube\resources\1\SonarAnalyzer.VisualBasic.dll</Path>
            <Path>C:\Users\antonio.aversa\AppData\Local\Temp\.sonarqube\resources\1\THIRD-PARTY-NOTICES.txt</Path>
          </AssemblyPaths>
        </AnalyzerPlugin>
        <AnalyzerPlugin Key="securitycsharpfrontend" Version="9.9.0.19083" StaticResourceName="SonarAnalyzer.Security-9.9.0.19083.zip">
          <AssemblyPaths>
            <Path>C:\Users\antonio.aversa\AppData\Local\Temp\.sonarqube\resources\2\Google.Protobuf.License.txt</Path>
            <Path>C:\Users\antonio.aversa\AppData\Local\Temp\.sonarqube\resources\2\Microsoft.AspNetCore.Razor.Language.dll</Path>
            <Path>C:\Users\antonio.aversa\AppData\Local\Temp\.sonarqube\resources\2\SonarAnalyzer.Security.dll</Path>
          </AssemblyPaths>
        </AnalyzerPlugin>
      </AnalyzerPlugins>
```
This xml is read by the `ParseBuildOutput` tool during the `Run log_parser` instruction of the build on Cirrus CI, which looks for the version of the plugin:
```cs
        private static string? GetVersion(XContainer container, string pluginKey) =>
            container.Descendants()
                     .FirstOrDefault(element => element.Name.LocalName == "AnalyzerPlugin" && element.Attribute("Key")?.Value == pluginKey)
                     ?.Attribute("Version")
                     ?.Value;
```

And that fails, producing the issue on this task.

**Comment by antonioaversa** [comment]
Last build on Cirrus CI is green: https://cirrus-ci.com/build/6707898076626944

`Run log_parser` is executed correctly on all checked Cirrus CI instructions, e.g. https://cirrus-ci.com/task/4646034802999296?logs=build#L0

Closing this GitHub issue.
