### ISSUE TITLE
ITs: update Net5 test cases

### ISSUE THREAD

**Issue by zsolt-kolbay-sonarsource** [SonarSource/sonar-dotnet#6769]
Some of the .NET test cases are not up to date.
e.g. [Module Initializers](https://khalidabuhakmeh.com/module-initializers-in-csharp-9) were introduced in C# 9.0, but currently _analyzers/its/sources/Net5/Net5/ModuleInitializers.cs_ looks like this:
```
namespace Net5
{
    public class ModuleInitializers
    {
        // The feature is in progress

        //[ModuleInitializer]
        //internal static void Initializer()
        //{
        //}
    }
}
```
All test cases under the _Net5_ folder (as well as _Net6_, and _Net7_) in _analyzers/its/sources_ need to be double-checked and updated if necessary.

**Comment by pavel-mikula-sonarsource** [comment]
@zsolt-kolbay-sonarsource Can you please clarify the title of this card? The example resembles a project from our ITs only, the title suggest our UTs/TestCases.

Only `Type: Tooling` label is relevant here. This doesn't affect rules or any specific C# version of a rule.

**Comment by CristianAmbrosini** [comment]
We don't have those projects anymore on our ITs, they were cleaned up and simplified during the recent C#13/NET9 support sprint

The projects have been removed from our ITs as part of the recent C# 13/.NET 9 support sprint, during which we cleaned up and simplified the its folder
