### ISSUE TITLE
Fix S4507 FP: Error raised on .NET 7 although the debug feature is deactivated

### ISSUE THREAD

**Issue by VianneyDoleans** [SonarSource/sonar-dotnet#6772]
### Description

I migrate a project to .NET 7. The error S4507 is raised although the debug feature is desactivated in production mode.

### Repro steps

Code inside ``program.cs`` : 

```c#
var builder = WebApplication.CreateBuilder(args);
```

```c#
var app = builder.Build();

app.UseExceptionHandler("/error");
if (app.Environment.IsDevelopment())
    app.UseDeveloperExceptionPage();
else
    app.UseHsts();
```

Link to the SonarCloud public project where the issue appears : [link](https://sonarcloud.io/project/security_hotspots?id=VianneyDoleans_BlogCore)

### Expected behavior

Code is already deactivated so it should not be highlighted

### Actual behavior

 The error S4507 is raised.

### Related information

* .NET 7
* I suppose the problem is related to [minimal hosting model introduced with .NET 6](https://learn.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-7.0).

**Comment by martin-strecker-sonarsource** [comment]
Thanks for the reporting and the detailed description @VianneyDoleans. I created a reproducer in #6777 on our side and confirm this being an FP.

**Comment by antonioaversa** [comment]
@zsolt-kolbay-sonarsource We are releasing 9.19 for SQ 10.4, and this issue is not going to make it into the release.
I am removing the `Sprint: Hardening` label to close the sprint.
