### ISSUE TITLE
Expand the ShimLayer with ITypeSymbol.NullableAnnotation

### ISSUE THREAD

**Issue by Tim-Pohlmann** [SonarSource/sonar-dotnet#6825]
[ITypeSymbol.NullableAnnotation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.itypesymbol.nullableannotation?view=roslyn-dotnet-4.3.0) is currently not part of the ShimLayer. Adding it, will make checking for Nullables easier and more robust.
See also:
https://github.com/SonarSource/sonar-dotnet/issues/3273#issuecomment-606693989
https://github.com/SonarSource/sonar-dotnet/pull/6753#discussion_r1107184744

**Comment by martin-strecker-sonarsource** [comment]
Something like in TypeInfoExtensions needs to be created:

```cs
public static class ITypeSymbolExtensions
{
    public NullableAnnotation NullableAnnotation(this ITypeSymbol symbol) { }
}
```

It is a bit easier as `TypeInfoExtensions.Nullability(this TypeInfo typeInfo)` but still needs the enum to enum conversion. Maybe one of the `LightupHelpers.CreateSyntaxPropertyAccessor` already does what we need (there is an overload that takes a type and calls Convert).

**Comment by Tim-Pohlmann** [comment]
That's great news. Thank you!
