### ISSUE TITLE
New annotation for checking if CFG is created

### ISSUE THREAD

**Issue by zsolt-kolbay-sonarsource** [SonarSource/sonar-dotnet#6846]
Using the new Symbolic Execution engine, each rule which uses SE derives from the `SymbolicRuleCheck` class.
This abstract class provides the `ShouldExecute()` method, which - when implemented in the derived class - tells whether it's worth creating a Control Flow Graph for the given method.
Building a CFG is at least a magnitude slower than performing analysis on the Syntax Tree or the Semantic Model, therefore it's worth investing time to add proper checks and avoid building the CFG when we know for sure that SE has no chance of finding any issues in the given method.
Performing this check can be quite simple or very complex, it depends on the specific rule.
Therefore it would be advantageous if we could automatically test whether an analyzer using SE skips the creation of the CFG for a method. Currently, when a method is marked with the Compliant comment (or not marked at all), we don't really know if the SE phase was skipped or it was performed and it raised no issues.

**For example**: rule S3900 is looking for parameters of publicly accessible methods for which a null check was not performed before being dereferenced. 
Some of the obvious scenarios when the CFG does not need to be built: the method is private or it doesn't have parameters. A new annotation can be introduced for this for our test cases: `SkipCFG`, `NoCFG`, or something with a similar name.

```
public class MyClass
{
	private void PrivateMethod(string s)  // SkipCFG - method is not publicly accessible
	{
		Console.WriteLine(s.Length);
	}

	public void NoParams()                // SkipCFG - method has no parameters
	{
		Console.WriteLine("Hello!"); 
	}
}
```

**Comment by pavel-mikula-sonarsource** [comment]
Given the way how we test the rules, there's no reasonably easy way how to test this.


As the test framework doesn't know about the reasoning why a certain thing was not done
