### ISSUE TITLE
S1854 FP: `try` block not connected to `catch` when exception is thrown inside

### ISSUE THREAD

**Issue by ohadschn** [SonarSource/sonar-dotnet#697]
### Description

Variables that are only used in exception filters incorrectly trigger S1854

### Repro steps

```cs
bool shouldCatch = false;
try
{
    shouldCatch = true; //S1854 Remove this useless assignment to local variable 'shouldCatch'
    throw new InvalidOperationException("bar");
}
catch (Exception) when(shouldCatch)
{
    Console.WriteLine("Error");
}
```
### Expected behavior

S1854 should not trigger because the `shouldCatch` assignment is not useless. Indeed, without it the exception would pass through.

### Actual behavior

S1854 is triggered.

### Related information

* SonarC# Version 6.3.0.2862
* Visual Studio Version 2017 (15.2)

**Comment by Evangelink** [comment]
Hi @ohadschn.
Thanks for the feedback. This is going to be tricky to fix but we will see what we can do.

**Comment by killergege** [comment]
The issue is still there. Found a fix ? 
My case : 
        public static void RetryOnException(int retries, TimeSpan delay, Action operation)
        {
            var attempts = 0;
            do
            {
                try
                {
                    attempts++; //Remove this useless assignment to local variable 'attempts'.
                    operation();
                    break;
                }
                catch (Exception ex)
                {
                    if (attempts > retries)
                        throw;
                    Task.Delay(delay).Wait();
                }
            } while (true);
        }

**Comment by andrei-epure-sonarsource** [comment]
This problem with the shape of the CFG may have some connection with #2490 and  #2393

**Comment by andrei-epure-sonarsource** [comment]
Moving @killergege 's example to #2393 because it's a separate root cause (`try-catch` inside a loop vs `try-catch` with a `throw` inside the `try`, as in this original ticket problem), and we need to keep concerns separate between tickets.
