### ISSUE TITLE
Improve TokenTypeAnalyzerBase performance

### ISSUE THREAD

**Issue by mary-georgiou-sonarsource** [SonarSource/sonar-dotnet#6975]
Partially fixes #6974.

In the [TokenTypeAnalyzerBase class](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/src/SonarAnalyzer.Common/Rules/Utilities/TokenTypeAnalyzerBase.cs) the two `ClassifyIdentifier` methods ([here ](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/src/SonarAnalyzer.Common/Rules/Utilities/TokenTypeAnalyzerBase.cs#L140) and [here](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/src/SonarAnalyzer.Common/Rules/Utilities/TokenTypeAnalyzerBase.cs#L156)) are heavily based on the Semantic Model. 

These checks need to be substituted with syntax ones as much as possible to improve performance.

Some examples of the TokenTypeAnalyzer performance before and after https://github.com/SonarSource/sonar-dotnet/pull/6576:

| Project  | Before #6576 (seconds)  | After #6576 (seconds) |
|---|---|---|
| fluentassertions  | 11.8  | 115.9  |
| ravendb  |  32.5 | 135.8  |
| akka.net  | 25.5  | 47.7  |

**Comment by martin-strecker-sonarsource** [comment]
https://github.com/SonarSource/sonar-dotnet/pull/7108 contributes to this change

**Comment by martin-strecker-sonarsource** [comment]
Fixed by https://github.com/SonarSource/sonar-dotnet/issues/7369
