### ISSUE TITLE
Fix S2583/S2589 FP: When tuple deconstruction is used

### ISSUE THREAD

**Issue by paulhickman-a365** [SonarSource/sonar-dotnet#7057]
In the example below, ````Bar```` incorrectly has warning S2583 "Change this condition so that it does not always evaluate to true" on the ````while```` condition, but ````Bar2```` which does not use tuple deconstruction correctly has no warning.

````c#
private (string?,int) Foo() => ("hello",1);

public void Bar() 
{
    string? current = null;
    string? last;

    do
    {
        last = current;
        (current, _) = Foo();
    }
    while (last == null);
}

private string? Foo2() => "hello";

public void Bar2()
{
    string? current = null;
    string? last;

    do
    {
        last = current;
        current = Foo2();
    }
    while (last == null);
}
````

Language C#, .Net 6
Sonar Analzyer Version: 8.55.0.65544
Visual Studio: 17.5.3

**Comment by cristian-ambrosini-sonarsource** [comment]
Thank you for opening this issue, @paulhickman-a365. Your feedback helps us improve our products. We will look at it as soon as possible. After we confirm the issue, we will add labels and put it in our backlog

**Comment by pavel-mikula-sonarsource** [comment]
Hi @paulhickman-a365,

Thank you for reporting this, I confirm it as FP.
