### ISSUE TITLE
New rule S6588: Use `DateTime(Offset).UnixEpoch` instead of pointing to that date using the constructor

### ISSUE THREAD

**Issue by mary-georgiou-sonarsource** [SonarSource/sonar-dotnet#7080]
Implement new rule [S6588: Use DateTime(Offset).UnixEpoch instead of pointing to that date using the constructor](https://github.com/SonarSource/rspec/pull/1747).

This rule should raise when a new `DateTime`, `DateTimeOffset` or `DateOnly` object is created with Date 1-1-1970. 

- [ ] Implement Rule S6588 for C#
- [ ] Implement Rule S6588 for VB.NET

**Comment by csaba-sagi-sonarsource** [comment]
The rule should not cover DateOnly, because it does not have a UnixEpoch field that could be used instead.
