### ISSUE TITLE
Fix AD0001 Bug: SymbolicExecution throws ArgumentNullException

### ISSUE THREAD

**Issue by martin-strecker-sonarsource** [SonarSource/sonar-dotnet#7097]
Running the analyzer runner with `AnalyzerRunner.exe C:\Projects\sonar-dotnet\analyzers\packaging\binaries "C:\Projects\DeepSast\Dapper\Dapper.sln" /a SymbolicExecutionRunner` against this version of dapper:

https://github.com/DapperLib/Dapper/tree/a31dfd3dd4d7f3f2580bd33c877199d7ef3e3ef9

produces 232 AD0001 errors.

The log is attached:

[log.txt](https://github.com/SonarSource/sonar-dotnet/files/11264136/log.txt)

The stack trace always looks like so:
```
Inner exception: System.ArgumentNullException: Value cannot be null. 
 Parameter name: type 
    at SonarAnalyzer.SymbolicExecution.Roslyn.ExceptionState..ctor(ITypeSymbol type) 
    at SonarAnalyzer.SymbolicExecution.Roslyn.ExceptionCandidate.FromConversion(IOperationWrapperSonar operation) 
    at SonarAnalyzer.SymbolicExecution.Roslyn.ExceptionCandidate.FromOperation(ProgramState state, IOperationWrapperSonar operation) 
    at SonarAnalyzer.SymbolicExecution.Roslyn.RoslynSymbolicExecution.<ProcessOperation>d__15.MoveNext() 
    at SonarAnalyzer.SymbolicExecution.Roslyn.RoslynSymbolicExecution.Execute() 
    at SonarAnalyzer.Rules.SymbolicExecutionRunnerBase.AnalyzeRoslyn(SonarAnalysisContext analysisContext, SonarSyntaxNodeReportingContext nodeContext, SyntaxNode body, ISymbol symbol)'.
```

One sample method is Dapper\Dapper\SqlMapper.GridReader.cs#L423
```cs
[MethodImpl(MethodImplOptions.AggressiveInlining)]
private static T ConvertTo<T>(object value) => value switch
{
    T typed => typed,
    null or DBNull => default,
    _ => (T)Convert.ChangeType(value, Nullable.GetUnderlyingType(typeof(T)) ?? typeof(T), CultureInfo.InvariantCulture),
};
```

Others
```cs
        private readonly Dictionary<string, ParamInfo> parameters = new Dictionary<string, ParamInfo>();

        object SqlMapper.IParameterLookup.this[string name] => // This one
            parameters.TryGetValue(name, out ParamInfo param) ? param.Value : null;

        
        public void SetValue(IDbDataParameter parameter, object value) // This one
        {
            TableValuedParameter.Set(parameter, value as DataTable, null);
        }
```

Root cause is propably:
In `new ExceptionState(typeCatalog.SystemInvalidCastException)` `typeCatalog.SystemInvalidCastException` seems to be null in some cases.

https://github.com/SonarSource/sonar-dotnet/blob/e53da03d17d59b3fd5a93c63bc4cf4f8e3ed3f1c/analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ExceptionCandidate.cs#L60

This might only happen when using the analyzer runner and needs to be confirmed with a scanner run.

**Comment by pavel-mikula-sonarsource** [comment]
`AnalyzerRunner` is unreliable tool that fails on many scenarios and is known to produce AD0001 that are not reproducible in normal builds.

The AD0001 doesn't is not reproducible with normal build => we don't want to make `AnalyzerRunner` working.
