### ISSUE TITLE
Replace org.sonar.api.utils.log.Logger

### ISSUE THREAD

**Issue by Tim-Pohlmann** [SonarSource/sonar-dotnet#7115]
In `sonar-csharp-plugin` and `sonar-dotnet-shared-library`, we use `org.sonar.api.utils.log.Logger` and `org.sonar.api.utils.log.Loggers`, which are deprecated. We should find an appropriate replacement.

See issues about it here:
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=org.sonarsource.dotnet%3Asonar-dotnet&open=AYd0BDcQ8Q_NY1Er7OPf
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=org.sonarsource.dotnet%3Asonar-dotnet&open=AYd0BDNX8Q_NY1Er7OOr

**Comment by pavel-mikula-sonarsource** [comment]
Should be replaced with SLF4J, see https://github.com/SonarSource/sonar-plugin-api/blob/master/CHANGELOG.md#915
