### ISSUE TITLE
NuGet: Replace broken `projectUrl` link

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#7119]
The current link from the nuspec files [(here, C# one)](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/packaging/SonarAnalyzer.CSharp.nuspec) is pointing to https://www.sonarlint.org/visualstudio/ which is broken.

We should keep it simple and use the redirect link: https://redirect.sonarsource.com/doc/sonar-visualstudio.html

**Comment by pavel-mikula-sonarsource** [comment]
Does this intentionally change the landing page from SonarLint to C# analyzer?

Logically, it makes sense. The question is why it was pointing to SonarLint before? Were there maybe some marketing reasons for it?

**Comment by pavel-mikula-sonarsource** [comment]
Redirect for SL: https://redirect.sonarsource.com/doc/sonar-visualstudio.html

**Comment by pavel-mikula-sonarsource** [comment]
Same for VB.NET: https://redirect.sonarsource.com/plugins/vbnet.html (redirect itself should point to a different page, dogfood created)

**Comment by andrei-epure-sonarsource** [comment]
@pavel-mikula-sonarsource I had the wrong impression that I changed that in the past and that initially it was pointing to the language page.

> The question is why it was pointing to SonarLint before? Were there maybe some marketing reasons for it?

I looked back an even [in 2018](https://github.com/SonarSource/sonar-dotnet/pull/3558) is was still pointing to SonarLint.

So, indeed, the SL redirect should be used.

**Comment by pavel-mikula-sonarsource** [comment]
Ok,

Let's ask @tom-howlett-sonarsource if we want to change it towards specific language or keep SonarLint there :)

**Comment by tom-howlett-sonarsource** [comment]
I think SonarLint is good, its a good upgrade from just using a standalone analyser ;-)

**Comment by andrei-epure-sonarsource** [comment]
The only limitation is that now we also support Rider. But that's overthinking at this point, this is anyway replacing a broken link
