### ISSUE TITLE
New rule S6602: "Find" method should be used instead of the "FirstOrDefault" extension

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#7121]
https://sonarsource.github.io/rspec/#/rspec/S6602/csharp

[MMF-3069](https://sonarsource.atlassian.net/browse/MMF-3069)

[MMF-3069]: https://sonarsource.atlassian.net/browse/MMF-3069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by at-andreas** [comment]
Be careful, Microsoft has made improvements with Framework 9 that make FirstOrDefault faster than Find!! This rule should be applied with caution if you plan to update to Framework 9.

**Comment by CristianAmbrosini** [comment]
Hi @at-andreas, we are currently re-running all the benchmarks with .NET 9 and comparing the results. Based on the outcomes, we plan to implement exclusions for frameworks >= .NET 9 where applicable, within the next few weeks. Thanks for raising awareness!
