### ISSUE TITLE
New rule S6608: Indexing should be used instead of "Enumerable" methods on types implementing "IList"

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#7125]
https://sonarsource.github.io/rspec/#/rspec/S6608/csharp

[MMF-3069](https://sonarsource.atlassian.net/browse/MMF-3069)

[MMF-3069]: https://sonarsource.atlassian.net/browse/MMF-3069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by snakefoot** [comment]
Consider also `IReadOnlyList<T>`
