### ISSUE TITLE
Fix AD0001 in S138: NullReferenceException

### ISSUE THREAD

**Issue by Tim-Pohlmann** [SonarSource/sonar-dotnet#7134]
### Description

The error appears in the project JellyFin, which I recently added to peachee-dotnet.
```
CSC : error AD0001: Analyzer 'SonarAnalyzer.Rules.CSharp.MethodsShouldNotHaveTooManyLines' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\Project\Jellyfin.Server\Jellyfin.Server.csproj]
```

### Repro steps

JellyFin GitHub: https://github.com/jellyfin/jellyfin
Error Log: https://cirrus-ci.com/task/4552322081095680?logs=build#L2576
Peach configuration: https://github.com/SonarSource/peachee-dotnet/blob/b8a849c086699dfb1ec9340a26eaef1ac1e636b6/.cirrus.yml#L258-L259

### Related information

* .NET 6

**Comment by antonioaversa** [comment]
The exception is produced in
```cs
        private static IEnumerable<SyntaxToken> GetMethodTokens(LocalFunctionStatementSyntaxWrapper wrapper) =>
            wrapper.ExpressionBody?.Expression.DescendantTokens()
            ?? wrapper.Body.Statements.SelectMany(s => s.DescendantTokens());
```

Due to `Body` being null, in presence of `extern` local functions, which don't have body.
```cs
#pragma warning disable SA1300 // Entrypoint is case sensitive.
[DllImport("libc")]
static extern int chmod(string pathname, int mode);
#pragma warning restore SA1300
``` 

Example in `.\Jellyfin.Server\Program.cs`.
