### ISSUE TITLE
SE: Add BinaryOperation for literals: arithmetic and logic

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#7141]
Process arithmetic binary operations in the SE

* [x] Support+ -
* [x] Support *
* [x] Support %
* [x] Support &
* [x] Support |

Be careful about multiplying be a negative number, or subtracting that reverts min&max values. 

CBDE implementation of operations: [RangeConstraint.cpp](https://github.com/SonarSource/SonarCBDE/blob/master/symbolicExecution/src/RangeConstraint.cpp)
CBDE UTs: [RangeConstraintTest.cpp](https://github.com/SonarSource/SonarCBDE/blob/master/symbolicExecution/test/RangeConstraintTest.cpp)

**Comment by Tim-Pohlmann** [comment]
I have split the tasks further because bit operations are complicated to reason about.

**Comment by antonioaversa** [comment]
Split into two: reminder of the issue is in https://github.com/SonarSource/sonar-dotnet/issues/7267
