### ISSUE TITLE
Add support for progressive education format

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#7150]
Ensure that C# and VB.Net rules specified in the new progressive education format are displayed correctly (separated in the new sections) on SQ/SC/SL.

1. [x] [Remove language suffix from rspec-generated html and json](https://github.com/SonarSource/sonar-dotnet/pull/7154)
2. [x] [Use RuleMetadataLoader to load the rule description](https://github.com/SonarSource/sonar-dotnet/pull/7158)

**Comment by pavel-mikula-sonarsource** [comment]
Can this be closed now? And the `Sprint: Rule Format` deleted, as the sprint is done?
