### ISSUE TITLE
Improve S2302 Message: Use NameOf for VB.NET

### ISSUE THREAD

**Issue by PavlinII** [SonarSource/sonar-dotnet#7197]
S2302 suggests
> Replace the string 'ArgName' with 'nameof(ArgName)'.

Instead, it should suggest this for VB.NET
> Replace the string 'ArgName' with 'NameOf(ArgName)'.

**Comment by cristian-ambrosini-sonarsource** [comment]
Hi @PavlinII! Thanks for the suggestion: you should be able to see the new message starting from the next release. 
Thanks again for your contribution!
