### ISSUE TITLE
Investigate why changing to SemanticModelAction caused a regression

### ISSUE THREAD

**Issue by csaba-sagi-sonarsource** [SonarSource/sonar-dotnet#7237]
Investigate why [this](https://github.com/SonarSource/sonar-dotnet/commit/bb07dd6ba10c33a4ede0830f0dc1411e6cc0e96b) commit introduced a performance regression.

**Comment by mary-georgiou-sonarsource** [comment]
See the conclusion in the comment [here](https://github.com/SonarSource/sonar-dotnet/pull/7262#pullrequestreview-1443952588).
