### ISSUE TITLE
SE: Add BinaryOperation for literals: division, remainder, xor

### ISSUE THREAD

**Issue by antonioaversa** [SonarSource/sonar-dotnet#7267]
Continuation of https://github.com/SonarSource/sonar-dotnet/issues/7141

- [x] Support /
- [x] Support remainder
- [x] Support ^

See CBDE implementation below for reference.

In case division proves itself to be too difficult, just reset the constraint - see CBDE implementation below for reference.

CBDE implementation of operations: [RangeConstraint.cpp](https://github.com/SonarSource/SonarCBDE/blob/master/symbolicExecution/src/RangeConstraint.cpp)
CBDE UTs: [RangeConstraintTest.cpp](https://github.com/SonarSource/SonarCBDE/blob/master/symbolicExecution/test/RangeConstraintTest.cpp)

**Comment by antonioaversa** [comment]
Shifts operations extracted out into a dedicated issue: https://github.com/SonarSource/sonar-dotnet/issues/7284

**Comment by mary-georgiou-sonarsource** [comment]
This issue is done.
