### ISSUE TITLE
Migrate S3966 to the new Symbolic Execution engine

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#7302]
Migrate `ObjectsShouldNotBeDisposedMoreThanOnce`

Split the work in 3 PRs:
* [x] Scaffold the rule
  * Prepare empty rule with `ShouldExecute` false
  * Prepare tests and test cases - mark old `Noncompliant` as `FIXME Non-compliant`
  * Do not register in `SymbolicExecutionRunner` (yet)
* [x] Implement 
  * Implement rule logic, switch `ShouldExecute` to true
  * Register in `SymbolicExecutionRunner`
  * Update ITs
* [x] Finish the rule
  * Implement `ShouldExecute`
  * Remove all `FIXME` from test cases, mark them as FNs or Compliant
  

  Additional steps to improve the rule:
- [ ] Implement different messages according to the issue raised.  One message for double disposal through the user calling `Dispose` or `Close` twice and one for the `using statement`, where the `Dispose` is called in `Finally` hidden behind using.

**Comment by mary-georgiou-sonarsource** [comment]
The last point is nice to have and will be implemented in follow-up PR (if time allows it - otherwise I'll remove it from here)
