### ISSUE TITLE
New Rule S2373: Generic type parameter names should comply with a naming convention

### ISSUE THREAD

**Issue by antonioaversa** [SonarSource/sonar-dotnet#7377]
The rule exists and is implemented for VB.NET, and seems to make sense for C# too.

RSPEC draft of [S2373](https://sonarsource.github.io/rspec/#/rspec/S2373/csharp) was deleted as non-implemented.

It was the same as for VB.NET anyway.

Naming conventions on generic parameters should be consistent across languages, so the specs defined for VB.NET apply to C# too.

**Comment by cristian-ambrosini-sonarsource** [comment]
Closing this issue since S2373 is now deprecated. I created [another issue](https://github.com/SonarSource/sonar-dotnet/issues/7576) for extending S119.
