### ISSUE TITLE
HasMatchingScope should not allocate a new delegate on every call

### ISSUE THREAD

**Issue by sharwell** [SonarSource/sonar-dotnet#7438]
Found during review of https://developercommunity.visualstudio.com/t/Visual-Studio-2022:-High-CPU-usage-by-Se/10378039. Accounts for 213MB allocations.

https://github.com/SonarSource/sonar-dotnet/blob/ab9c515a82f421588a480496f5138f5cfb3526b8/analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs#L109

**Comment by pavel-mikula-sonarsource** [comment]
Thank you for reporting this! It's a nice catch
