### ISSUE TITLE
Avoid capturing and delegate allocations in SonarAnalysisContextBase

### ISSUE THREAD

**Issue by sharwell** [SonarSource/sonar-dotnet#7439]
1. 333MB in IsExcluded
    https://github.com/SonarSource/sonar-dotnet/blob/ab9c515a82f421588a480496f5138f5cfb3526b8/analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs#L128

1. 935MB in AdditionalFile
    https://github.com/SonarSource/sonar-dotnet/blob/ab9c515a82f421588a480496f5138f5cfb3526b8/analyzers/src/SonarAnalyzer.Common/Extensions/AnalyzerOptionsExtensions.cs#L37

3. 229MB in IsUnchanged
    https://github.com/SonarSource/sonar-dotnet/blob/ab9c515a82f421588a480496f5138f5cfb3526b8/analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs#L106

4. 191MB in IsGenerated
    https://github.com/SonarSource/sonar-dotnet/blob/ab9c515a82f421588a480496f5138f5cfb3526b8/analyzers/src/SonarAnalyzer.Common/Extensions/SyntaxTreeExtensions.cs#L37

**Comment by pavel-mikula-sonarsource** [comment]
Thank you for reporting these!


2. Might go away by caching the results, see #7440
The rest will need some investigation

**Comment by martin-strecker-sonarsource** [comment]
Fixed in
1. #7656
2. #7652
3. #7664
4. #7655
