### ISSUE TITLE
Avoid calling Path.GetFileName in AdditionalFile

### ISSUE THREAD

**Issue by sharwell** [SonarSource/sonar-dotnet#7440]
Accounts for 5037MB allocations in https://developercommunity.visualstudio.com/t/Visual-Studio-2022:-High-CPU-usage-by-Se/10378039

https://github.com/SonarSource/sonar-dotnet/blob/ab9c515a82f421588a480496f5138f5cfb3526b8/analyzers/src/SonarAnalyzer.Common/Extensions/AnalyzerOptionsExtensions.cs#L37

**Comment by pavel-mikula-sonarsource** [comment]
This is a great catch! Thank you for reporting it.

Do you know from user logs how many additional files user had? 
We could add case insensitive `.EndsWith` pre-check, but if he has 1 or 2 files, it will not fix the problem. 
We could not use the API and do our own string-only based check too.

I have a feeling that we call that method way too often and fine-tuning the implementation could have no impact. What do you think of caching the value and using `AnalyzerOptions` as a key? In practice, the cache would never get purged (unless we purge it above a certain size). At the same time, the naive idea is that there shouldn't be too many different sets of `AdditionalFiles` during the memory lifetime of the analyzer. Or is there? As we would prevent GC from collecting the unique instances.

**Comment by sharwell** [comment]
It should be possible to slice the string after the final `\` or `/` and compare the resulting `ReadOnlySpan<char>`, instead of allocating a substring.

**Comment by martin-strecker-sonarsource** [comment]
For my measurement of a `dotnet build` of akka with `dotnet sonarscanner begin` of a SC EE instance and "Sonar Way" profile, the found that `Path.GetFileName` (allocates strings) and `AdditionalFiles.FirstOrDefault` (allocates a delegate and/or capture class) are the main source of allocations by far:
![image](https://github.com/SonarSource/sonar-dotnet/assets/103252490/4538e80d-4f73-492a-aa45-0663d8261b41)

These two allocations contribute to 1GB string + 700MB delegate out of 11,3 GB total.

Note: I stopped capturing in the middle of the build after 30 minutes.

**Comment by martin-strecker-sonarsource** [comment]
> We could add case insensitive .EndsWith pre-check, but if he has 1 or 2 files, it will not fix the problem.

There is an overload that takes a `StringComparison` so we should be fine. There are just two things to do:
* Unroll FirstOrDefault to a `foreach` to avoid the delegate and capture class allocations (1GB saving).
* Use `EndsWith(StringComparison.OrdinalIgnoreCase)` instead of `Path.GetFileName`.
