### ISSUE TITLE
Fix S6605 FP: Should not fire in expressions

### ISSUE THREAD

**Issue by DrummingBeb** [SonarSource/sonar-dotnet#7508]
### Description

As I understand, rule S6605 suggests the use of the collection-specific "Exists" method for performance reasons. It becomes a problem when the "Any" extension method is used in an expression because switching to the "Exists" method changes the expression (e. g. the [C# MongoDb Driver](https://www.mongodb.com/docs/drivers/csharp/current/) supports Any but not Exists). There are also no performance benefits unless the expression is compiled and executed which should not be done anyways when performance is important.

### Repro steps

`Expression<Func<List<int>, bool>> containsThree = list => list.Any(el => el == 3);`

### Expected behavior

The rule should not fire.

### Actual behavior

The rule fires.

### Related information

* C# Plugin version 9.4.0.72892
* JetBrains Rider version 2023.1.1
* MSBuild / dotnet version 7.0.305
* Operating System macOS Ventura 13.4.1

**Comment by martin-strecker-sonarsource** [comment]
Thank you @DrummingBeb for bringing this up. Linq expressions are indeed a special case and we should not raise in that context as they are almost always not executed but translated.

Note to the implementer: We have the `IsInExpressionTree` helper methods for that.

**Comment by martin-strecker-sonarsource** [comment]
See also https://github.com/SonarSource/sonar-dotnet/issues/7286
@sebastien-marichal is this already fixed by #7286? If so, you may use `IsInExpressionTree` instead of the custom logic you used.

**Comment by sebastien-marichal** [comment]
@martin-strecker-sonarsource The fix in #7332 only checks if `Any` is used within an EntityFramework context.
Using `IsInExpressionTree` would prevent a broader range of false positives indeed.
