### ISSUE TITLE
New Rule Idea: Add "max-depth" rule similar to ESLint

### ISSUE THREAD

**Issue by marco-carvalho** [SonarSource/sonar-dotnet#7532]
This rule is inspired by the [max-depth](https://eslint.org/docs/latest/rules/max-depth) rule in ESLint, which enforces a maximum block depth to aid in maintaining readable and maintainable code. It checks for the maximum depth of nested blocks in the code.

Noncompliant Code Example:
```cs
if (condition1)  // depth 1
{  
  if (condition2)  // depth 2
  {  
    if (condition3)  // depth 3
    {  
      // this code is too deep
    }
  }
}
```

Compliant Code Example:
```cs
if (condition1)  // depth 1
{  
  if (condition2)  // depth 2
  {  
    // this code is not too deep
  }
}
```

Block depth can be a relevant indicator of your code’s readability. Keeping the maximum depth low can help in maintaining the code's simplicity, readability, and maintainability. Having such a rule for C# would be beneficial for developers aiming to uphold high code quality standards.

**Comment by sebastien-marichal** [comment]
Hello @marco-carvalho,

Thank you for your contribution.

We already cover it with this rule [S134](https://rules.sonarsource.com/csharp/RSPEC-134/).
However, this rule is not enabled by default.

Note that we also have [S3776](https://rules.sonarsource.com/csharp/RSPEC-3776/) which covers the cognitive complexity of a method and includes in its calculation the depth of blocks.
This rule is enabled by default.

You can find more information about cognitive complexity [here](https://www.sonarsource.com/resources/cognitive-complexity/).
