### ISSUE TITLE
Warning error DateTime

### ISSUE THREAD

**Issue by soufianelb** [SonarSource/sonar-dotnet#7569]
### Description
 Since today, i get a warning on DateTime when i initilize a DateTime object. Provide the "DateTimeKind" when creating this object

* C#/VB.NET Plugins version
* Visual Studio version
* MSBuild / dotnet version
* SonarScanner for .NET version (if used)
* Operating System

**Comment by csaba-sagi-sonarsource** [comment]
Hello @soufianelb, 

That is expected, in version 9.5 of the analyzer which was released on Friday, we have introduced a new rule S6562 that raises in that scenario.
