### ISSUE TITLE
Java UTs: Migrate to jUnit 5

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#7595]
Prerequisite: #7600 

While we reference jUnit5, we execute them via `junit-vintage-engine`, effectively running them on jUnit5.

To migrate it, we need to rename jUnit annotation to the new ones and replace creation of resources same as in ITs.

This blogpost has some IntelliJ tricks how to make stuff in batches:
https://blog.jetbrains.com/idea/2020/08/migrating-from-junit-4-to-junit-5/

Same as #4223, we need to:

* [ ] Update UTs - shared
* [ ] Update UTs - C#
* [ ] Update UTs - VB.NET
* [ ] Remove `junit-vintage-engine` dependency

**Comment by mary-georgiou-sonarsource** [comment]
Check also https://github.com/SonarSource/sonar-dotnet/pull/9476

**Comment by mary-georgiou-sonarsource** [comment]
https://github.com/SonarSource/sonar-dotnet/pull/7863 -> Remove junit-vintage-engine dependency
https://github.com/SonarSource/sonar-dotnet/pull/8033 -> Update Java UTs to Junit5
