### ISSUE TITLE
Java UTs: Replace LogTester with slf4j

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#7600]
As per sonar-plugin-api 9.15 change log:
https://github.com/SonarSource/sonar-plugin-api/blob/master/CHANGELOG.md#915

We need to remove usages of `LogTester`

This is a prerequisite for #7595

**Comment by pavel-mikula-sonarsource** [comment]
Example of sonar-java PR: https://github.com/SonarSource/sonar-java/pull/4416

They migrated:

| Package | From | To |
|--------|--------|--------|
| sonar-plugin-api | 9.13.0.360 | 10.0.0.695
| sonar-plugin-api-impl | 9.5.0.56709 | 9.9.1.69595
| sonar-testing-harness | 9.5.0.56709 | 9.9.1.69595

Forced breaking changes:
* LogTesterJUnit5 has been moved:
  * The package has changed from org.sonar.api.utils.log to org.sonar.api.testfixtures.log
  * The LogTesterJUnit5 class is now in a new artifact that we have added sonar-plugin-api-test-fixtures 10.0.0.695
* Replace usage of org.sonar.api.utils.log.LoggerLevel with matching elements of org.slf4j.event.Level.
* Now LogTester only collects INFO by default, we use new LogTesterJUnit5().setLevel(Level.DEBUG) to also collect DEBUG
* org.sonar.api.SonarPlugin has been removed, we now use org.sonar.api.Plugin.
* We have to implement the new InputFile#md5Hash() method
* Rule repository name changes from SonarQube to Sonar

Deprecation changes:
* Replace thousands of calls to org.sonar.api.utils.log.Logger#get with org.slf4j.LoggerFactory.getLogger from a new provided dependency org.slf4j:slf4j-api:1.7.30

**Comment by mary-georgiou-sonarsource** [comment]
this has been already done in https://github.com/SonarSource/sonar-dotnet/pull/7777
thanks @costin-zaharia-sonarsource!
