### ISSUE TITLE
New Rule Idea: too many logging calls within a method block

### ISSUE THREAD

**Issue by cristian-ambrosini-sonarsource** [SonarSource/sonar-dotnet#7653]
The rule, similar to S6664 (see [specification PR](https://github.com/SonarSource/rspec/pull/2494)), should raise an issue when a method block contains too many logging statements of a specific level (not resetting the count for each [code block](https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/program-building-blocks#statements).

**Comment by costin-zaharia-sonarsource** [comment]
Will be implemented by #8845
