### ISSUE TITLE
Fix S3928 FP: Parameter names used into ArgumentException constructors should match an existing one

### ISSUE THREAD

**Issue by kimbirkelund** [SonarSource/sonar-dotnet#7714]
### Description

When validating a parameter from a class primary constructor the parameter name is not correctly recognized.

### Repro steps

```
public class Class(string s)
{
    private readonly string _s = s ?? throw new ArgumentNullException(nameof(s));
}
```

<img width="830" alt="image" src="https://github.com/SonarSource/sonar-dotnet/assets/1884017/ae9eabd8-ddbc-4a01-bbd4-99270f047b8e">

### Related information

* C# language version set to _preview_
* Visual Studio version: 17.6.5
* dotnet version: 7.0.306
* sonarlint version: 7.1.0.75242

**Comment by Tim-Pohlmann** [comment]
I confirm this as an FP. Thanks for the report!
