### ISSUE TITLE
Improve S4004: Exclude properties annotated with JsonProperty / JsonPropertyName

### ISSUE THREAD

**Issue by gbtb** [SonarSource/sonar-dotnet#7720]
### Description

Hello :wave: 

I'd like to suggest extending list of attributes that prevent rule S4004 from triggering to also include property attributes from modern serializers like Newtonsoft.Json and System.Text.Json . Right now this rule excludes classes annotated with Serializable attribute and properties with DataMember attribute.

### Known workarounds

Use IEnumerable instead of ICollection types, ignore files in Sonarqube settings based on some pattern (**/Dto/*)

### Related information

* Sonar.CSharp 9.5
* Rider 2022.3
* MSBuild 17 / dotnet 7
* SonarScanner for .NET version (if used)
* Windows 10

**Comment by Tim-Pohlmann** [comment]
Hi! Can you elaborate on why this would be necessary? Both Newtonsoft.Json and System.Text.Json support private setters:
Newtonsoft.Json: https://www.newtonsoft.com/json/help/html/SerializationGuide.htm#Objects
System.Text.Json: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/immutability?pivots=dotnet-7-0#non-public-property-accessors

**Comment by gbtb** [comment]
Hi.

> Both Newtonsoft.Json and System.Text.Json support private setters

Yes, I somehow completely missed the fact that these serializers have such capabilities :sweat_smile: 
```csharp
public class Foo
    {
        [JsonProperty("fooBar")] 
        [JsonPropertyName("fooBar"), JsonInclude]
        public List<string> FooBar { get; private set; } = new List<string>();
    }
```
Property, annotated this way will be correctly deserialized by both serializers and diagnostics will not be triggered.

Thank you for your time, the issue can be closed.
