### ISSUE TITLE
Enable code generated analysis for all analyzers

### ISSUE THREAD

**Issue by sebastien-marichal** [SonarSource/sonar-dotnet#7734]
- [x] Enable code generated analysis by calling the [ConfigureGeneratedCodeAnalysis](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.diagnostics.analysiscontext.configuregeneratedcodeanalysis)
- [x] Add Razor files exception to `GeneratedCodeRecognizer `

**Comment by csaba-sagi-sonarsource** [comment]
Reopening until it gets merged to master.
