### ISSUE TITLE
Investigate test infrastructure of dotnet/razor

### ISSUE THREAD

**Issue by antonioaversa** [SonarSource/sonar-dotnet#7772]
## Questions to be answered
- how tests are defined and executed in https://github.com/dotnet/razor?
- can we do something similar in sonar-dotnet?
- does this strategy goes in the direction of https://github.com/SonarSource/sonar-dotnet/issues/7739?

## Answers
- `dotnet-razor` generates templates in their ITs: `dotnet-razor\src\Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.csproj`
- all tests in this projects inherit from [RazorIntegrationTestBase](https://github.com/dotnet/razor/blob/f72cc5b96599c5d1de7fa8dcfb1da9ac82ddb0e4/src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/RazorIntegrationTestBase.cs#L27)
- in the `Initialize` the following operations are performed:
   - a `RazorProjectEngine` instance is created and configured 
   (similar to [Seb's prototype here](https://github.com/sebastien-marichal/Razor.Analyzers/blob/main/Razor.Generator/Program.cs#L8C14-L8C32))
   - the instance refers to a `VirtualRazorProjectFileSystem`, which is a `RazorProjectFileSystem` derivation, internal to `Microsoft.AspNetCore.Razor.Language`, simulating a unix-like FS, which we would need to replicate ourselves in our UTs infrastructure
   - the `RazorProjectEngine` is instrumented with features, like [so](https://github.com/dotnet/razor/blob/f72cc5b96599c5d1de7fa8dcfb1da9ac82ddb0e4/src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/RazorIntegrationTestBase.cs#L125): some of them may be superfluous for our needs, some of them may be necessary...
   - the `RazorProjectEngine` is also instrumented with metadata references, some of which may be necessary for the good compilation of razor templates
   - a `RazorDocument` is added to the `RazorProjectEngine` with the Razor template to generate
   - `GeneratedCode` compiles the Razor template into a generated cs file
   - there are two ways: single pass and double pass - check the paragraphs below
- for each test suite defined in `dotnet-razor\src\Compiler\Microsoft.AspNetCore.Razor.Language\test\IntegrationTests\`, there are generated code under `dotnet-razor\src\Compiler\Microsoft.AspNetCore.Razor.Language\test\TestFiles\IntegrationTests\CodeGenerationIntegrationTest\`
- the result of `GeneratedCode` is compared against the files under `TestFiles`, to make sure that template generation works correctly

### Single pass vs Double pass
- Single pass is as in Seb's prototype.
- `dotnet-razor` ITs seem to never use a single pass (i.e. all `UseTwoPhaseCompilation` are overridden to `true`)
- The double pass has as a first phase which won't include any metadata references for component discovery. This **mirrors** what the build does - it doesn't do a proper full build.
- The second phase includes metadata references and decorates the previously generated `Compilation` with the new syntax trees
- the method works, as shown by all the generated code baselines [here](https://github.com/dotnet/razor/tree/f72cc5b96599c5d1de7fa8dcfb1da9ac82ddb0e4/src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest)
- the double pass compilation is probably the key to fix template compilation issues when `@bind` or `onclick=@method` are used, referring to the `cs` part of a Razor component
- a single pass compilation doesn't seem to compile such template correctly, as it never resolves inline Razor directive

### Conclusions
- Razor tests don't use the build as a blackbox, but replicate part of it with a very complex infrastructure
- the fact that Razor template compilation replicates build aspects such as the double pass, would make our UTs infrastructure quite dependent on internal aspects of the Razor compilation, which we don't want to depend on
- the way Razor templates are compiled have changed with the introduction of .NET Core, and has also changed in recent versions of .NET
- moreover, it may change some more in upcoming versions of .NET, taking advantage of the work done in source generators
- we don't want our ITs infrastructure to break when the details of how Razor templates are compiled into generated sources will be changed
- so, while we could something similar in `sonar-dotnet`, it's probably more advisable to keep a black-box approach and build a project on disk, delegating the entire build to the `MSBuildWorkspace`

**Comment by cristian-ambrosini-sonarsource** [comment]
As a result of the investigation, while we could do something similar in sonar-dotnet, we will keep it simple and delegate the entire build to the MSBuildWorkspace.
