### ISSUE TITLE
Investigate bUnit

### ISSUE THREAD

**Issue by antonioaversa** [SonarSource/sonar-dotnet#7773]
Questions to be answered:
- how does https://steven-giesel.com/portfolio/projects/3 accomplishes testing of razor and cshtml files
- can we do something similar in sonar-dotnet?
- does this strategy goes in the direction of https://github.com/SonarSource/sonar-dotnet/issues/7739?

**Comment by cristian-ambrosini-sonarsource** [comment]
Closing this issue as we have decided not to investigate bUnit at this time. It does not seem worth the effort right now, so we will continue with our current approach.
