### ISSUE TITLE
Fix S1144: Nested type constructor accessibility is wrong in the rule message

### ISSUE THREAD

**Issue by neman** [SonarSource/sonar-dotnet#7774]
### Description

The message I got in VS IDE is:
![image](https://github.com/SonarSource/sonar-dotnet/assets/350314/4c3fa38c-6bab-4e35-b5d4-5badf1d511b6)

This is not private ctor, but public.
And also this private class is used.

### Repro steps

This is the code example

```csharp
public class TagDto
{
    public int Id { get; set; }
    public string? Name { get; set; }
    public bool System { get; set; }
    public bool Active { get; set; }
    public DateTime? SynchronizedOn { get; set; }

    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<Tag, TagDto>();
        }
    }
}
```

And this is used as

`.ProjectTo<TagDto>(_mapper.ConfigurationProvider),`

### Related information

* C#/VB.NET Plugins version: SonarAnalyzer.CSharp Version 9.7.0.75501
* Visual Studio version: Version 17.7.0 Preview 5.0
* MSBuild / dotnet version: .NET 8 Preview 5
* Operating System: Windows

**Comment by martin-strecker-sonarsource** [comment]
Thank you @neman for the report. The message is indeed wrong. Regarding the second issue:

> And also this private class is used.

Do you use [assembly scanning](https://docs.automapper.org/en/stable/Configuration.html#assembly-scanning-for-auto-configuration) via `AddMaps` like e.g. so: 
```cs
var configuration = new MapperConfiguration(cfg => cfg.AddMaps(myAssembly));
```
If so, there is nothing we can do about it at the moment. Automapper uses reflection at runtime to find the type and create an instance of it. There are no compile-time dependencies on the constructor.

If you are using .Net 5 or above, we could consider adding support for the [DynamicallyAccessedMembersAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.dynamicallyaccessedmembersattribute?view=net-7.0) that is used by e.g. the trimmer for such cases:

```cs
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.NonPublicNestedTypes)]
public class TagDto
{
    public int Id { get; set; }

    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<Tag, TagDto>();
        }
    }
}
```

Would you apply this attribute to your Dtos to help our analyzer? If so, I would create a new issue to add support for that attribute.

**Comment by neman** [comment]
I can try to add that attribute, although I do not like to add to my code more than required for the implementation.
Adding additional code just for the sake of the tooling is code smell :)

Is it possible to exclude some classes from analyzer (I am using SonarCloud) e.g. using asterisk and create some rule to exclude all *Dto from this concrete rule?

**Comment by Tim-Pohlmann** [comment]
The constructor's effective visibility is `private` since it lives in a `private class`. The wording is not optimal, but I'm struggling to find a better one. Any suggestions?

**Comment by martin-strecker-sonarsource** [comment]
We and Roslyn call it EffectiveAccessibility

https://github.com/dotnet/roslyn/blob/b67df4c5e39ac1a104b2e573542211d4d6b1cd1d/src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs#L891

https://github.com/SonarSource/sonar-dotnet/blob/d67b08b453612d5d724763cbd5e70c44cb837c01/analyzers/src/SonarAnalyzer.Common/Helpers/SymbolHelper.cs#L149

Given that I would say "Remove this effectively private constructor" if the modifier does not match the effective accessibility.

**Comment by martin-strecker-sonarsource** [comment]
> I can try to add that attribute, although I do not like to add to my code more than required for the implementation. Adding additional code just for the sake of the 3rd party tooling is code smell.

The documentation for [DynamicallyAccessedMembersAttribute ](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.dynamicallyaccessedmembersattribute?view=net-7.0) states

> Indicates that certain members on a specified [Type](https://learn.microsoft.com/en-us/dotnet/api/system.type?view=net-7.0) are accessed dynamically, for example, through [System.Reflection](https://learn.microsoft.com/en-us/dotnet/api/system.reflection?view=net-7.0).

Adding this attribute is more than just pleasing a third-party tool. It indicates that this seemingly unused class is accessed via reflection at runtime. It therefore also serves documentation purposes to any code reader and satisfies the "clear" clean-code-attribute.

> Clear: The code is self-explanatory, transparently communicating its functionality. It is written in a straightforward way that minimizes ambiguity, avoiding unnecessary clever or intricate solutions.

[Source](https://docs.sonarsource.com/sonarqube/10.2/user-guide/clean-code/)

**Comment by cristian-ambrosini-sonarsource** [comment]
> We and Roslyn call it EffectiveAccessibility
> 
> https://github.com/dotnet/roslyn/blob/b67df4c5e39ac1a104b2e573542211d4d6b1cd1d/src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs#L891
> 
> https://github.com/SonarSource/sonar-dotnet/blob/d67b08b453612d5d724763cbd5e70c44cb837c01/analyzers/src/SonarAnalyzer.Common/Helpers/SymbolHelper.cs#L149
> 
> Given that I would say "Remove this effectively private constructor" if the modifier does not match the effective accessibility.

I think you forgot the "unused" word, so it will be something like: `Remove the unused, effectively private constructor `x``
Which sounds a bit weird to me.
