### ISSUE TITLE
About Rule of C# Language: Hard-coded credentials are security-sensitive

### ISSUE THREAD

**Issue by NPC-RX** [SonarSource/sonar-dotnet#7784]
We recently have a requirement to scan for hard-coded credentials in the code. I found a rule for this in Sonar, but after testing, I found that it can only perform partial matches on the keywords I added. 
For example, the keyword "**password**" can match "**user_password**," but not "**userpassword**".

Do we have any plans to enhance the matching functionality of this rule? Such as:

1.Enabling comprehensive exact keyword matching.
2.Allowing customization to add regular expressions.

**Comment by gregory-paidis-sonarsource** [comment]
Hey @NPC-RX ,

Thanks for the suggestion, I understand your problem.
I think parametrized regular expressions is not the best user experience, but I definitely think we could match the keywords a bit more aggressively.

For more details, see the issue #7801 I created to track the progress of your request.
