### ISSUE TITLE
Fix S2699 FP: Support Moq

### ISSUE THREAD

**Issue by bdovaz** [SonarSource/sonar-dotnet#7961]
S2699 
### Description

The following rule supports several frameworks but Moq is not among them:

https://rules.sonarsource.com/csharp/RSPEC-2699/

As you can see in the examples, it allows to verify for example that a method or event call is made:

https://github.com/moq/moq

But not being an `Assert` throws this rule as a false positive and forces to do ugly things like `Assert.True(true)`.

### Repro steps

Create a minimal example of Moq by taking it from the Readme.md file in repository and see how it throws the false positive of the mentioned rule.

**Comment by Tim-Pohlmann** [comment]
Hi @bdovaz, thanks for bringing this to our attention.

**Comment by AraHaan** [comment]
This issue still happens for my type of tests as well (specifically Diagnostic Analyzer/source generator) tests which uses the default verifier (which does the assertions for the user).

https://github.com/Elskom/IDisposableGenerator/blob/main/tests/CSGeneratorTest.cs
https://github.com/Elskom/IDisposableGenerator/blob/main/tests/VBGeneratorTest.cs
https://github.com/Elskom/IDisposableGenerator/blob/main/tests/CSharpIncrementalGeneratorTest.cs
https://github.com/Elskom/IDisposableGenerator/blob/main/tests/VisualBasicIncrementalGeneratorTest.cs
https://github.com/Elskom/IDisposableGenerator/blob/main/tests/IGeneratorTestBase.cs
https://github.com/Elskom/IDisposableGenerator/blob/main/tests/ConfigOptions.cs
https://github.com/Elskom/IDisposableGenerator/blob/main/tests/OptionsProvider.cs

Specifically down the line in the ``Microsoft.CodeAnalysis.*.SourceGenerators.Testing`` packages from Microsoft.

Here is an idea: have the analyzer package have an ``internal`` attribute it adds to the Compilation that when used tells the analyzer "this is a valid assertion method that eventually calls an assert somewhere down its call-stack."

**Comment by mary-georgiou** [comment]
Hello @AraHaan can you please open a new issue and reference this one in there?
Thanks!
