### ISSUE TITLE
Fix S6602 FP: "Find" method should not be used for EF Core queries

### ISSUE THREAD

**Issue by pampua84** [SonarSource/sonar-dotnet#7964]
This type of suggestion when applied to linq queries that are used by EF Core can lead to throwing exceptions of the type:

> System.InvalidOperationException: The LINQ expression 'DbSet<Users>().... could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

So this thing should at least be specified in the documentation.

**Comment by Tim-Pohlmann** [comment]
Hi @pampua84, good catch! Thanks for bringing it to our attention.

**Comment by Tim-Pohlmann** [comment]
For reference; Similar issues have been resolved for S6605 and S6617:
https://github.com/SonarSource/sonar-dotnet/issues/7286

**Comment by pampua84** [comment]
HI @sebastien-marichal,
what exactly should I do? If I can help you I'll gladly do it.

**Comment by pampua84** [comment]
I don't know if only this snippet is good, otherwise if I need a repository with a working application I need more time.

**Comment by sebastien-marichal** [comment]
Thank you @pampua84!

I am assuming `Person.Properties` is one of the following types:

- `List<T>`
- `Array`
- `ImmutableList<T>`

If this is the case, I am all good!

**Comment by pampua84** [comment]
Hi @sebastien-marichal ,
I confirm that the object is a List<T>.
