### ISSUE TITLE
Bug: S1125 code fix does not add ! when transforming x == false.

### ISSUE THREAD

**Issue by urmel9** [SonarSource/sonar-dotnet#7999]
* Operating system: Microsoft Visual Studio Community 2022 (64-Bit) - Current
Version 17.7.0
* SonarLint plugin version: 9.8.0.76515
* Programming language you're coding in: C#
* Is connected mode used: No
* [Link to SonarCommunity](https://community.sonarsource.com/t/bug-autofix-of-s1125-in-c-is-wrong-and-leads-to-bad-results/99185)

Hello,
we use SonarLint with StyleCop in our company. Because there are many small warning that could be autofixed on save, we use the feature "clean-code on save". 

Here is the **problem**:
The Autofix of [S1125](https://rules.sonarsource.com/csharp/RSPEC-1125/) is wrong. The rule and the description are definitely correct, but the autofix function is wrong. It changes *if (testBool == false)* to *if (testBool)*. Screenshot are attached.

This is the **fix**:
Autofix should have this result:
 *if (!testBool)*

We had some bugs because SonarLint changed it wrong and is missing the exclamation mark on negative boolean literals. Could you please fix this? We will use the rule quick then again. Thank you! :slight_smile: 

Before:
![sonarLint_s1125-before](https://github.com/SonarSource/sonarlint-visualstudio/assets/67114570/8e24c775-c02f-437c-b15b-c3b0ef5a1bd4)

After clean-code on save
![sonarLint_s1125-after](https://github.com/SonarSource/sonarlint-visualstudio/assets/67114570/3a89c9d0-0376-469e-a4a0-2a2413d2d60a)

**Comment by mary-georgiou-sonarsource** [comment]
Hello @urmel9 and thanks for your report.
I confirm this is a bug.
I added this issue to our backlog to tackle as soon as we can.

**Comment by urmel9** [comment]
Hello @mary-georgiou-sonarsource are there any updates about this? Is it fixed now, or do I have to wait until the next release? 
Thank you! :)

**Comment by mary-georgiou-sonarsource** [comment]
Hello, @urmel9! 
Not yet - we need to plan to fix this during a future sprint.
Please follow the issue so you'll be updated once it's fixed!

**Comment by msedi** [comment]
Just a question, why has the Bug label be removed? I think it is a bug, right?

**Comment by urmel9** [comment]
@msedi I agree. It is unexpected behavior and leads to bug in your own code, when you use autoformat. Even the sugestion is confusing.

**Comment by HipDragon** [comment]
Any idea of when this will be fixed? 

It would be nice if this autofix was disabled while this was being resolved. Better to leave the code alone and working as developers originally wrote it. Then to have developers tempted to use the autofix and have it possibility change the logic of the code. 

If there is a way to disable specific autofixes in SonarLint I would like to know. Thanks in advance.

**Comment by urmel9** [comment]
@richardissimo Thank you for your detailed answer. 

@HipDragon Imho you it feels wrong to turn off a whole rule because the autofix is wrong. Unfortunately, right now, there isn't a possibility to turn off the autofix. I created an [issue for Roslyn](https://github.com/dotnet/roslyn/issues/70428) because SonarLint said it isn't their [problem](https://community.sonarsource.com/t/new-feature-disable-autofix-for-specific-rules-in-editorconfig/102315/21)

**Comment by mary-georgiou-sonarsource** [comment]
Hello everyone and thank you for your comments.
We increased the priority of this issue and we will tackle it in the next 3-4 months during our next planned hardening sprint.
Thank you!

**Comment by costin-zaharia-sonarsource** [comment]
Hi @p1luz,

Do you mean [SonarLint for Visual Studio](https://marketplace.visualstudio.com/items?itemName=SonarSource.SonarLintforVisualStudio2022)?

If yes, this version should be included in the next version. I do not have though an ETA yet.

**Comment by p1luz** [comment]
@mary-georgiou-sonarsource @costin-zaharia-sonarsource yes, that one.
Ok, thanks
