### ISSUE TITLE
S2589: Improve message in the case of null propagating operator 

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#8010]
### Description

In some cases, the problem is hard to understand and we should make this more visible for the users.

### Repro steps

` _componentPage = (_component?.Type == null) ? _parentComponent?.Name : _component?.Name;`

or

```
if (_component?.Type != null)
  return $"components/{_component?.Link}";
```
![image](https://github.com/SonarSource/sonar-dotnet/assets/56015273/a49996b5-1bac-4d46-8355-a0f74348408f)

### Expected behavior

For the given examples, the message should make it clear that the null propagating operator is redundant.

### Actual behavior

The raised message is "Change this expression which always evaluates to the same result." highlighting the identifier, not the operator, which can be confusing.

**Comment by rjgotten** [comment]
> null coalescence operator

The `?.` operator is called the null propagating operator.
The null coalescencing operator is `??`

**Comment by costin-zaharia-sonarsource** [comment]
Oh yes, thanks. It seems I was with my mind in another place :)
