### ISSUE TITLE
Fix S2589 FP: Switch Expression when using 'or' returns false positive

### ISSUE THREAD

**Issue by Daeymon** [SonarSource/sonar-dotnet#8012]
### Description

When using switch expressions with an 'or' in the final case, triggers the false positive for S2589

### Repro steps

```
public class SwitchTest
{
    private readonly string ModeName;

    public enum Mode
    {
        Mode1,
        Mode2,
        Mode3Dead,
    }

    public SwitchTest(Mode mode)
    {
        this.ModeName = mode switch
        {
            Mode.Mode1 => "Mode One",
            Mode.Mode2 => "Mode Two",
            Mode.Mode3Dead or _ => throw new NotImplementedException(),
        };
    }
}
```

### Expected behavior

[S2589](https://sonarsource.github.io/rspec/#/rspec/S2589/csharp) is not raised.

### Actual behavior

[S2589](https://sonarsource.github.io/rspec/#/rspec/S2589/csharp) is raised on the final case.

### Known workarounds

Throw the DRY principle to the wind and duplicate the final case.

```
    public SwitchTest(Mode mode)
    {
        this.ModeName = mode switch
        {
            Mode.Mode1 => "Mode One",
            Mode.Mode2 => "Mode Two",
            Mode.Mode3Dead => throw new NotImplementedException(),
            _ => throw new NotImplementedException(),
        };
    }
```

### Related information

* C#/VB.NET Plugins version: SonarAnalyzer.CSharp v9.9.0.77355
* Visual Studio version: VS2022 v17.7.4
* MSBuild / dotnet version: .NET SDK 7.0.401 / .Net6.0
* SonarScanner for .NET version (if used): N/A
* Operating System: Windows 10 Enterprise 21H2

**Comment by rjgotten** [comment]
`_` is a catch-all.
Combining it with any other pattern via `or` is gratuitous.
The rule is correct in this case.

**Comment by gregory-paidis-sonarsource** [comment]
Hey @Daeymon,

As @rjgotten just mentioned, what is the point of the `or` here?
Is there any reason you would not always refactor it to this?

```csharp
ModeName = mode switch
{
    Mode.Mode1 => "Mode One",
    Mode.Mode2 => "Mode Two",
    _ => throw new NotImplementedException(),
};

```

**Comment by Daeymon** [comment]
Just trying to keep all the analysers happy. Removing Mode.Mode3Dead from the switch expression triggers 
[IDE0072](https://learn.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/style-rules/ide0072).

**Comment by gregory-paidis-sonarsource** [comment]
Hey again,

Thanks for the quick reply :)
I understand your pain, but I think the IDE analyzer is on the wrong in this one, since you are clearly covering all the cases with the wildcard `_` catch-all case.

I would suggest making an issue on [dotnet/roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers), since in my opinion they should not raise in this case.
