### ISSUE TITLE
Optimization: Enable on-demand plugin download

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#8038]
We need to add `Plugin-RequiredForLanguages` to plugin manifest file to enable SC optimize download sizes.

Exact values needs to be verified with SC team (see Cody's email `Optimizing Language Plugin Downloads`). 

The impact on download is significant.

Example PR (unfortunately from Gradle): https://github.com/SonarSource/sonar-kotlin/pull/366/files

ToDo: Ping @cody-simms-sonarsource before release, so SC can do additional testing.

**Comment by pavel-mikula-sonarsource** [comment]
From #8053

Applicable immediately in SonarCloud and scheduled for SQ 10.4.

Related: https://sonarsource.atlassian.net/browse/SC-8970

On hold until we clarify how this will play with incremental PR analysis and files like CSHTML, JSON, XML which are not C# language.

**Comment by andrei-epure-sonarsource** [comment]
From the discussions with @dbmeneses 

- our .NET plugins only declare .cs, .vb and .razor suffixes but are able to analyze also .XML, .json and .cshtml files.
- the new feature in the the scanner-cli takes into account all files, even in PRs. 
  - however note that if the plugin is optimized and there are no vb razor and cs files and there are XML files, the plugin won't be downloaded and the XML files won't be analyzed by it.
  - Indeed, a project ("solution" in .NET vocabulary) with only CSHTML, XML and JSON won't be analyzed by sonar-dotnet.

**Comment by pavel-mikula-sonarsource** [comment]
If there's no CS/VB file, the .NET compilation will not happen and XML/JSON will not be analyzed anyway.

I'm not sure CSHTML behaves after the latest changes. Although valuable CSHTML without sounds CS unlikely.
