### ISSUE TITLE
Fix S4158 FP: The analyzer incorrectly concludes the HashSet is guaranteed to be empty

### ISSUE THREAD

**Issue by JelkeH** [SonarSource/sonar-dotnet#8041]
### Description

HashSet.Remove causes [S4158](https://sonarsource.github.io/rspec/#/rspec/S4158/csharp) on an empty HashSet. It should not.

### Repro steps

I tried to remove parts of this repro, but I could not make it cleaner without loosing the FP. `_ = toDoLater.Remove(item);` issues  [S4158](https://sonarsource.github.io/rspec/#/rspec/S4158/csharp)

```
    public interface IFoo<T>
    {
        public bool someProperty { get; }

        public IEnumerable<T> Successors { get; }
    }

    public static void Func<T>(this ICollection<T> toDo)
        where T : class, IFoo<T>
    {
        Queue<T> toDoNow = new();
        HashSet<T> toDoLater = new();

        foreach (T item in toDo)
        {
            if (item.someProperty)
            {
                toDoNow.Enqueue(item);
            }
            else
            {
                _ = toDoLater.Add(item);
            }
        }

        while (toDoNow.Count > 0)
        {
            T current = toDoNow.Dequeue();

            // Handle current

            foreach (T item in current.Successors)
            {
                _ = toDoLater.Remove(item);
                toDoNow.Enqueue(item);
            }
        }
    }
```

### Expected behavior

[S4158](https://sonarsource.github.io/rspec/#/rspec/S4158/csharp) is not issued as the HashSet is not guaranteed to be empty

### Actual behavior

[S4158](https://sonarsource.github.io/rspec/#/rspec/S4158/csharp) is issued.

### Known workarounds

Suppress the issued warning.

### Related information

SonarAnalyzer version 9.7.0.75501

**Comment by Tim-Pohlmann** [comment]
Hi @JelkeH, thanks for the report. I confirm this as an FP and created a PR to fix it. You can follow the progress here:
#8066
