### ISSUE TITLE
Support on-demand plugin downloading

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#8053]
by adding Plugin-RequiredForLanguages manifest metadata for C# and VB .NET.

Applicable immediately in SonarCloud and scheduled for SQ 10.4.

Related: https://sonarsource.atlassian.net/browse/SC-8970

See similar Kotlin change: https://github.com/SonarSource/sonar-kotlin/pull/366

**Comment by andrei-epure-sonarsource** [comment]
On hold until we clarify how this will play with incremental PR analysis and files like CSHTML, JSON, XML which are not C# language.

**Comment by pavel-mikula-sonarsource** [comment]
Duplicate: https://github.com/SonarSource/sonar-dotnet/issues/8038
