### ISSUE TITLE
Bump dotnet runtime for test projects to v8

### ISSUE THREAD

**Issue by antonioaversa** [SonarSource/sonar-dotnet#8136]
The corresponding issue for v7: https://github.com/SonarSource/sonar-dotnet/pull/6155
To be done after the release of .NET 8.
Previous attempt at performing this task, before the release of .NET 8, has resulted into a failure: https://github.com/SonarSource/sonar-dotnet/pull/8132
Details about the issue encountered are reported [here](https://trello.com/c/6K0EezU7/21-support-net8-uts-for-scenarios-with-inlinearrayattribute#).

**Comment by pavel-mikula-sonarsource** [comment]
This was already done
