### ISSUE TITLE
Improve S2930: Update RSPEC by describing which types are tracked

### ISSUE THREAD

**Issue by BaranovskiyNE** [SonarSource/sonar-dotnet#8141]
"IDisposables" should be disposed" (S2930) is only checking for a select few types that implement `IDisposable` (e.g. `System.IO.FileStream`), but this is not reflected in the RSPEC, so someone reading the description of the rule might think it will raise for any object that implements `IDisposable`.

Update the RSPEC: list all [the types that are tracked by the rule](https://github.com/SonarSource/sonar-dotnet/blob/6360ba4e9082955a18f9fc24a9e381632dadbecb/analyzers/src/SonarAnalyzer.CSharp/Rules/DisposableNotDisposed.cs#L31).

**Comment by BaranovskiyNE** [comment]
MemoryStream is just sample, does SonarCube analize is there unmanaged code inside any IDisposables objects? 
Anyway name "IDisposables" should be disposed" means that Dispose should be called for IDisposables not matter does it use anything unmanaged inside.

**Comment by zsolt-kolbay-sonarsource** [comment]
S2930 doesn't track every object that implements `IDisposable`, only specific ones like `FileStream` or `Bitmap`. 
So I wouldn't call this a False Negative, but rather the rule has an inaccurate description of what it does.
I'll update the issue to reflect that and we'll update the specification (however the implementation of the rule won't change, it will only keep track of a few pre-defined types as it does now).
Thank you for reporting it.

**Comment by BaranovskiyNE** [comment]
Don't you think that it is better to rename this rule, because it does not reflect real functionality?

**Comment by BaranovskiyNE** [comment]
Hi, colleges.
It would be a very good rule to check if Dispose called for all IDisposable. Can you answer, are you going to implement it?
