### ISSUE TITLE
Add .NET 8 to peach

### ISSUE THREAD

**Issue by antonioaversa** [SonarSource/sonar-dotnet#8168]
https://github.com/SonarSource/peachee-dotnet/tree/dotnet should include .NET 8 projects, not only to be able to test .NET 8-only features of C# 12, such as [Inline arrays](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12#inline-arrays) and [Zero-overhead member access](https://github.com/dotnet/runtime/issues/81741), but also to be able to compile C# 12 projects on previous versions of .NET.

This requires:
- adding `.\dotnet-install.ps1 -Version 8.0.100-rc.1.23463.5` to the relevant `re-ci-images` AMI
  - PR on `re-ci-images`: https://github.com/SonarSource/re-ci-images/pull/368 
- ~adding a `net8-solution` project~: already done previously
- ~adding the analysis of this project on `peachee-dotnet/dotnet` and update the relevant script in the `peachee-dotnet` repo, to support the .NET 8 toolchain~
  - ~PR on `peachee-dotnet`: https://github.com/SonarSource/peachee-dotnet/pull/44 ~

UPDATE: after the decision to remove `netX-solution` projects from peach (see discussion [here](https://sonarsource.slack.com/archives/C012KBFFYD6/p1697718852374029?thread_ts=1697633135.537269&cid=C012KBFFYD6)), the PR on `peachee-dotnet` (https://github.com/SonarSource/peachee-dotnet/pull/44) is not required anymore.

The extension of the `build.cmd` script, to include the case `"%BUILD_TOOL_VERSION%" == "NET8"`, is done in https://github.com/SonarSource/sonar-dotnet/issues/8170.

So this issue now only includes PR adding .NET 8 preview to the image in `re-ci-images` (https://github.com/SonarSource/re-ci-images/pull/368).

Notice that the PR reverting the use of Golden AMI in `peachee-windows-dotnet` (https://github.com/SonarSource/re-ci-images/pull/380) hasn't reverted the content of the PR adding .NET 8 preview to the image (https://github.com/SonarSource/re-ci-images/pull/368).

**Comment by pavel-mikula-sonarsource** [comment]
We already have .NET 8 on Peach, we'll add .NET 9 soon(ish)
