### ISSUE TITLE
Update test framework: extract the Verifier, VerifierBuilder + extensions and ParseOptionsHelper in own project

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonar-dotnet#8237]
This will allow us to have a better unit test organization in separate and dedicated projects. This new project should be considered "main code" that needs to be tested as well.

**Comment by andrei-epure-sonarsource** [comment]
> This will allow us to have a better unit test organization in separate and dedicated projects. 

This seems to be a sprint, do we have a trello card for it?

**Comment by costin-zaharia-sonarsource** [comment]
I've added one. Thanks

**Comment by costin-zaharia-sonarsource** [comment]
Closing this as done.
