### ISSUE TITLE
Fix S3353 FP: Performance Tag Clarification

### ISSUE THREAD

**Issue by marco-carvalho** [SonarSource/sonar-dotnet#8265]
Hello SonarQube Team.

I'm writing to request clarification about rule [S3353 - Unchanged variables should be marked as "const"](https://sonarsource.github.io/rspec/#/rspec/S3353/csharp) which has been tagged as "Performance". While I've been using SonarQube for static code analysis, I've come across this rule but I couldn't find explicit information about how this particular rule contributes to the improvement of code performance.

I think the correlation between this practice and performance enhancement isn't directly clear in the provided documentation.

Could you please provide more details about how following this rule might help improve performance? More specifically, how would proper usage aid in enhancing performance?

It would be really helpful to have these details for me and others who are using your tool for code quality analysis to better understand and justify the enforcement of this rule in our code.

I appreciate your time and effort in addressing this issue.

**Comment by martin-strecker-sonarsource** [comment]
Hello @marco-carvalho 

First of all S3352 is categorized with the [clean code attribute](https://docs.sonarsource.com/sonarqube/latest/user-guide/clean-code/#clean-code-attributes) "clean" which states:

> The code is self-explanatory, transparently communicating its functionality. It is written in a straightforward way that minimizes ambiguity, avoiding unnecessary clever or intricate solutions.

This is the primary motivation for the rule. The performance benefits you may see are minimal. To give you an example:

```cs
public class C
{
    readonly string myVar = "Hello";
    public void M() 
    {        
        System.Console.WriteLine(myVar);
    }
}
```

This generates the following IL (see this [sharplab.io](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAIGYAEGBMOAwgLABQA3uTjTgE4CmEAJgPYwoCeeAjAAw4wnAGoQ6OALw4ARAAkGKFK2kBuarWx4ALDgCyACgCUOdTQq0LJspY08AdBh4BOfUNF1Da67QC+5H0A) for the whole generated IL):

In the instance constructor, the field is initialized:
```
        IL_0000: ldarg.0
        IL_0001: ldstr "Hello"
        IL_0006: stfld string C::myVar // this.myVar = "Hello"
        IL_000b: ldarg.0
        IL_000c: call instance void [System.Runtime]System.Object::.ctor() // base constructor call
        IL_0011: ret
```

In the method M:
```
        IL_0000: ldarg.0
        IL_0001: ldfld string C::myVar // this.myVar field access
        IL_0006: call void [System.Console]System.Console::WriteLine(string)
        IL_000b: ret
```

If you turn the field in a const like so ([sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAIGYAEGBMOAwgLABQA3uTjTgMYD2MAzgngIwAMOYAngGoQATjgC8OAEQAJAKYoUDCQG5qtbHgAsOALIAKAJSqaFWqZxGzGdgDorATl19BQ/SrKmAvuQ9A=)):

```cs
public class C
{
    const string myVar = "Hello"; // readonly -> const
    public void M() 
    {        
        System.Console.WriteLine(myVar);
    }
}
```

The constructor only contains the `base` call:
````
        IL_0000: ldarg.0
        IL_0001: call instance void [System.Runtime]System.Object::.ctor()
        IL_0006: ret
````
and method M() does not have field access but loads the value from the literal
```
        IL_0000: ldstr "Hello"
        IL_0005: call void [System.Console]System.Console::WriteLine(string)
        IL_000a: ret
```

So you save performance-wise:
* class `C` is smaller as the field `myVar` is not stored in the instance
* The string "Hello" is not allocated in the constructor. This may save an object allocation (but there is also [string interning](https://learn.microsoft.com/en-us/dotnet/api/system.string.intern?view=net-7.0&redirectedfrom=MSDN#remarks), so you may not save memory here).
* The field access in `M` (`this.myVar`) is a double pointer dereference (this pointer + field offset gets the field address. The field has a pointer into the data region of the program where "Hello" is stored). With `const`, it becomes a single dereference into the data region (You can see this in the IL ASM view in Sharplab).

The benefits are marginal. They become even smaller or disappear if you turn the field into a `readonly static`. There is almost no difference for value types like `int` or `float`.

I haven't checked for `const` on locals, but I would assume the differences are equally small.

As mentioned in the beginning, the rule's primary purpose is clarity, and there is a small bonus of some minor optimizations done by the compiler and the JIT.

**Comment by martin-strecker-sonarsource** [comment]
I will close the issue as there is nothing to be done. We may update the documentation with samples about the performance benefits, but the differences are hard to explain and marginal. We should consider removing the `Performance` tag and the performance part from the rule description or adding links to some StackOverflow answers like [this one](https://stackoverflow.com/a/6926426) in the future if such a question arises again.
