### ISSUE TITLE
Fix S2259 FP: SE engine doesn't take into account element existence collection methods 

### ISSUE THREAD

**Issue by sebastien-marichal** [SonarSource/sonar-dotnet#8266]
From this [community post](https://community.sonarsource.com/t/upgrade-sonarqube-9-9-to-10-2-now-see-more-bugs-when-reviewing-the-c-code/103255/3).

This might be fixed as part of #7457:
> Learn from well-known (extension-) methods like list.Any()

```cs
void Method(Exception[] array)
{
    if (array.Any())
    {
        Exception exception = array.FirstOrDefault();
        Console.WriteLine(exception.Message); // Noncompliant - FP if Any is true, FirstOrDefault will never return null
    }
}
```

**Comment by Tim-Pohlmann** [comment]
This requires the mentioned step from #7457 + extra logic for `FirstOrDefault`. Should be straight-forward after #7866

**Comment by mary-georgiou-sonarsource** [comment]
@Tim-Pohlmann @sebastien-marichal For the record, this example is a true positive, as FirstOrDefault can return null even if the collection is not empty for reference types.

**Comment by Tim-Pohlmann** [comment]
@mary-georgiou-sonarsource That's a Good catch. The engine needs to learn `unknown` and not `NotNull` here. This means it is still an FP because S2259 does not raise on `unknown`.
