### ISSUE TITLE
Add check for Blazor context during analysis

### ISSUE THREAD

**Issue by sebastien-marichal** [SonarSource/sonar-dotnet#8273]
Possible solutions:

- Check for use of `using Microsoft.AspNetCore.Components` (syntax)
  - Maybe at `CompilationStart`?
    - Can we exclude files from the analysis? (not registering `SyntaxNode` for specific files)
- Check for `IComponent` implementation in the hierarchy (semantic)

Those solutions are not exclusive.

- [ ] Check whether to use `CompilationStart`
- [ ] Check whether to use caching

**Comment by antonioaversa** [comment]
Not needed anymore, since the rules implemented in the sprint don't require a specific "in blazor" check.
