### ISSUE TITLE
New rule S6802: Using lambda expressions in loops should be avoided in Blazor markup section

### ISSUE THREAD

**Issue by sebastien-marichal** [SonarSource/sonar-dotnet#8277]
S6802: https://github.com/SonarSource/rspec/pull/3215

**Comment by antonioaversa** [comment]
@sebastien-marichal I think we may have a few FPs on `mudblazor`
In [this scenario](https://peach.sonarsource.com/issues?resolved=false&rules=csharpsquid%3AS6802&open=AYvvUNbCPFv2Bq7h-rhn), the lambda applies to the collection being iterated, that is evaluated only once, and the `@foreach` is outer-most, as far as I can tell.
Same applies [here](https://peach.sonarsource.com/issues?resolved=false&rules=csharpsquid%3AS6802&open=AYvvUNq9PFv2Bq7h-rho) and [here](https://peach.sonarsource.com/issues?resolved=false&rules=csharpsquid%3AS6802&open=AYvvUNq9PFv2Bq7h-rhp).

I think the `IsWithinLoop` check is a bit too generic:
```cs
node.AncestorsAndSelf().Any(x => x is ForStatementSyntax or ForEachStatementSyntax or WhileStatementSyntax or DoStatementSyntax)
```

```cs
foreach (var item in Collection.Where(x => x.Id == "idToFind")) {}
```
![image](https://github.com/SonarSource/sonar-dotnet/assets/2676742/bbce1192-1227-453b-8aac-9d1851166741)
