### ISSUE TITLE
SourceGenerators: Put generated files under source control

### ISSUE THREAD

**Issue by Tim-Pohlmann** [SonarSource/sonar-dotnet#8284]
StyleCop has their [generated files under source control](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/tree/master/StyleCop.Analyzers/StyleCop.Analyzers/Lightup/.generated/StyleCop.Analyzers.CodeGeneration/StyleCop.Analyzers.CodeGeneration.OperationLightupGenerator). This is useful to see the impact of changes in the source generation.
To do the same, we can take a look [here](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/1dd5ced072d7d870f6dd698a6c02ad509a122452/StyleCop.Analyzers/StyleCop.Analyzers/StyleCop.Analyzers.csproj#L27C25-L27C25).

**Comment by Tim-Pohlmann** [comment]
IIRC, I intended to have visibility in PRs for reviews and archeology. The need for this comes up only rarely, though.
I think @martin-strecker-sonarsource prompted me to create this issue. What are your opinions?

**Comment by martin-strecker-sonarsource** [comment]
I have no strong opinion on this topic. Either way is fine for me.
