### ISSUE TITLE
Add timeouts to all regular expressions

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#8314]
We have [22 security hotspots](https://sonarcloud.io/project/security_hotspots?id=sonaranalyzer-dotnet) because of not using regex timeouts.

We should use a timeout for all. I'd say that 500 ms should ensure we won't be too strict without having some data to rely on. We don't search for patterns in whole files, we only limit it to syntax nodes. Even 500 ms seems a lot, but we 'd need to do tests on various hardware to find a good value.

The source generator should be treated separately.

**Comment by martin-strecker-sonarsource** [comment]
We already have:
https://github.com/SonarSource/sonar-dotnet/blob/1820ab24df967658e2fe299629811f2d7a719a25/analyzers/src/SonarAnalyzer.Common/Common/RegexConstants.cs#L25
