### ISSUE TITLE
Implement `RegisterSymbolStartAction` wrapper

### ISSUE THREAD

**Issue by sebastien-marichal** [SonarSource/sonar-dotnet#8315]
Blazor rules would benefit a lot from registering to the `SymbolStartAction`:
- S6798
- S6800
- S6802

Other rules that could benefit from this implementation:
- S1117 (see @martin-strecker-sonarsource [comments](https://github.com/SonarSource/sonar-dotnet/pull/8251#discussion_r1371343596))

**Comment by sebastien-marichal** [comment]
Impossible to implement at the moment as we rely on version 1.3.4 of Roslyn which does not contain `RegisterSymbolStartAction`. Included in version starting 3.0.0 based on [documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.diagnostics.analysiscontext.registersymbolstartaction?view=roslyn-dotnet-4.6.0#applies-to).
Might be possible once the support of .NET Fx 4.6 is dropped.

**Comment by gregory-paidis-sonarsource** [comment]
Closing this as completed, it has been implemented by Martin and Antonio and this card was forgotten open.
