### ISSUE TITLE
Migrate `SonarAnalyzer.UnitTest` project target framewrok from `net7.0` to `net8.0`

### ISSUE THREAD

**Issue by sebastien-marichal** [SonarSource/sonar-dotnet#8363]
- Revert this changes: #8362
- Update `SonarAnalyzer.UnitTest` target frameworks from `net48;net7.0` to `net48;net8.0`
- Move tests from `SonarAnalyzer.Net8.UnitTest` to `SonarAnalyzer.UnitTest`
- Remove `SonarAnalyzer.Net8.UnitTest`

This migration needs to ensure that all Razor unit tests work as expected. We had issues in the past when starting to use .NET 8 preview, and those tests started failing.

**Comment by andrei-epure-sonarsource** [comment]
Hey @sebastien-marichal - could you please sync with @costin-zaharia-sonarsource on what we want to do?

It seems that this ticket suggest removing the `Net8.UnitTest`, and [this comment](https://github.com/SonarSource/sonar-dotnet/pull/8236#issuecomment-1778668822) says that we should not remove it. 

What is said inside an issue takes precedence over what is said only in a comment, but I'd still like a common understanding.

I would like to have a clear plan at squad level.

**Comment by costin-zaharia-sonarsource** [comment]
Closing this as done.

**Comment by costin-zaharia-sonarsource** [comment]
We still need to do the revert.

**Comment by pavel-mikula-sonarsource** [comment]
@costin-zaharia-sonarsource Can we close this now?

**Comment by costin-zaharia-sonarsource** [comment]
Yes 🥳
