### ISSUE TITLE
S4039: Update RSPEC to align with rule implementation

### ISSUE THREAD

**Issue by lg2de** [SonarSource/sonar-dotnet#8372]
### Description

S4039 should not be raised for explicitly implementing internal interfaces.
According to the description, the rule is intended for public interfaces.

### Repro steps

internal interface IMyInternalInterface
{
  void InternalMethod();
}

public class TheImplementation : IMyInternalInterface
{
  void IMyInternalInterface.InternalMethod() // S4039 should not be raised here
  {
    // foo
  }
}

### Expected behavior

S4039 should not be raised for explicitly implementing internal interfaces.

### Actual behavior

S4039 raised.

### Known workarounds

N/A

### Related information

* C#/VB.NET Plugins version: Rider SonarLint plugin 10.0.1.77000
* Operating System: Windows 11

**Comment by sebastien-marichal** [comment]
Hello @lg2de,

Thank you for pointing this issue to us and sorry for the delay.

I believe this is raised correctly, the rule is about avoiding making members inaccessible during interface implementation.
Whether the interface is internal or public should not make a difference.

However, as you pointed out, the rule description does not match the actual behavior.
