### ISSUE TITLE
Fix S3925 FP: BinaryFormatter serialization is deprecated, should be handled differently for >= .NET 8

### ISSUE THREAD

**Issue by gregory-paidis-sonarsource** [SonarSource/sonar-dotnet#8377]
This is a remainder from preparing for the .NET8 release.
Microsoft has been gradually dropping support for the `BinaryFormatter`, so the best practises referenced in this rule are different post-NET8.

Initially raised on [this community post](https://community.sonarsource.com/t/s3925-should-be-reconsidered-for-implementing-iserializable/104433/1) by Corniel.

See more discussion [here](https://sonarsource.slack.com/archives/CPZPQ8T17/p1700206679375859) (internal click)

S3925 Needs specification.

Relevant information:

- https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/5.0/binaryformatter-serialization-obsolete
- https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md
- https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/serialization#supporting-runtime-serialization

Expected behaviour of the rule:
* Only raise issues when the user explicitly opts-in for serialization of the concrete type by either (see also RSpec)
  * Applying the [Serializable] attribute
  * Having `ISerializable` in the base type list (it is explicitly mentioned in the current types base type list)
  * Declaring a [serialization constructor](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/serialization#supporting-runtime-serialization)
* If the user opts-in for serialization, the old rules apply without modification. The new .Net warnings need to be dealt with by the user as described by Microsoft.

**Comment by Corniel** [comment]
@andrei-epure-sonarsource officially, this is not C#12 but .NET 8 related.

**Comment by martin-strecker-sonarsource** [comment]
The current implementation of S3925 requires the user to opt-in for serialization on the concrete type:
https://github.com/SonarSource/sonar-dotnet/blob/6d42fec3508dae1dd5585bae62969f61a90f4fd9/analyzers/tests/SonarAnalyzer.Test/TestCases/ImplementISerializableCorrectly.cs#L256-L257

https://github.com/SonarSource/sonar-dotnet/blob/6d42fec3508dae1dd5585bae62969f61a90f4fd9/analyzers/tests/SonarAnalyzer.Test/TestCases/ImplementISerializableCorrectly.cs#L266

If the user opts-in, he needs to follow the old guidelines. This rule already behaves as described in the issue description and the RSpec already mentions the opt-in behavior. There is nothing to change for this rule at the moment.

**Comment by martin-strecker-sonarsource** [comment]
@cristian-ambrosini-sonarsource I think we looked at everything here and just forgot to close the issue, right?

**Comment by cristian-ambrosini-sonarsource** [comment]
Yes, we can close this issue.

**Comment by mu88** [comment]
FYI @gregory-paidis-sonarsource: I'm still seeing this warning being raised for my .NET 9 app analyzed on `Community Edition
v10.6 (92116)`:  
![image](https://github.com/user-attachments/assets/db685fca-6381-46c2-bc94-c87938a9c876)

However, adding this `protector ctor` triggers the build warning `SYSLIB0051`.
