### ISSUE TITLE
Fix S3928 FP: `throw new ArgumentOutOfRangeException(nameof(param), param)`

### ISSUE THREAD

**Issue by n0099** [SonarSource/sonar-dotnet#8386]
### Description

https://rules.sonarsource.com/csharp/RSPEC-3928/
> Exceptions
> The rule won’t raise an issue if the parameter name is not a constant value (inline declaration, nameof() or const variable).

### Repro steps

https://github.com/n0099/open-tbm/blob/af3fe85e196e0ffaa0fa881e86b2c23999e0f736/c%23/imagePipeline/src/Ocr/TesseractRecognizer.cs#L19

### Expected behavior

Not reporting since using `nameof()`

### Actual behavior

FP

### Known workarounds

It's seems only appeared when the given `param` is a readonly field or [primary constructor](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors) parameter.

### Related information
        
* C#/VB.NET Plugins version `<PackageReference Include="SonarAnalyzer.CSharp" Version="9.12.0.78982" ExcludeAssets="compile" />`
* Visual Studio version `VS2022 17.6.5`
* MSBuild / dotnet version `.NET 7.0.306`
* SonarScanner for .NET version (if used)
* Operating System `Windows 8.1`

**Comment by n0099** [comment]
After updated to `9.15`, there's still another FP when the param is a instance field: https://github.com/n0099/open-tbm/blob/78adbae5caa5dbf3e5abe5db6882e50e95dcc61f/c%23/imagePipeline/src/Ocr/PaddleOcrRecognizerAndDetector.cs#L34

**Comment by cristian-ambrosini-sonarsource** [comment]
Hi @n0099, this appears not to be related to the same issue/ticket since it's not about primary constructor parameters. 
Please open a new one describing the new scenario. Thank you!
