### ISSUE TITLE
Improve Java ITs: Replace deprecated `setProfile` by `associateProjectToQualityProfile`

### ISSUE THREAD

**Issue by sebastien-marichal** [SonarSource/sonar-dotnet#8389]
In [Tests.analyzeProject](https://github.com/SonarSource/sonar-dotnet/blob/9f6edc4e9b8d046b4e0dbfb17d1eb766022442ce/its/src/test/java/com/sonar/it/csharp/Tests.java#L86), we use `setProfile` which is deprecated and probably not even compatible with S4NET (I am not sure we use the `sonar.profile` option).

It is not as simple as replacing the call, `associateProjectToQualityProfile` requires the project to already exist as it calls the `api/qualityprofiles/add_project` endpoint which assumes that the project exists.

One approach could be:

```java
  public static BuildResult analyzeProject(String projectKey, Path temp, String projectDir, @Nullable String profileKey, String... keyValues) throws IOException {
    Path projectFullPath = TestUtils.projectDir(temp, projectDir);

    if (profileKey != null) {
      ORCHESTRATOR.getServer().provisionProject(projectKey, projectKey); // Create the project
      ORCHESTRATOR.getServer().associateProjectToQualityProfile(projectKey, "cs", profileKey); // Bind the profile to it
    }

    ScannerForMSBuild beginStep = TestUtils.createBeginStep(projectKey, projectFullPath)
      .setProperties(keyValues);

    ORCHESTRATOR.executeBuild(beginStep);
    TestUtils.runBuild(projectFullPath);
    return ORCHESTRATOR.executeBuild(TestUtils.createEndStep(projectFullPath));
  }
```

The same goes for the [VBNET version](https://github.com/SonarSource/sonar-dotnet/blob/9f6edc4e9b8d046b4e0dbfb17d1eb766022442ce/its/src/test/java/com/sonar/it/vbnet/Tests.java#L64-L73).
Usage outside the [Tests](https://github.com/SonarSource/sonar-dotnet/blob/9f6edc4e9b8d046b4e0dbfb17d1eb766022442ce/its/src/test/java/com/sonar/it/csharp/Tests.java) class should be checked as well.

**Comment by pavel-mikula-sonarsource** [comment]
@sebastien-marichal Isn't this duplicate of #3102 ?

**Comment by sebastien-marichal** [comment]
Probably, although this ticket seems to be more up-to-date.
`setProfile` does not seem to be as used in test classes as it was back in 2020.

**Comment by pavel-mikula-sonarsource** [comment]
Please move relevant parts there and close this one

**Comment by sebastien-marichal** [comment]
Close as duplicate of #3102
