### ISSUE TITLE
Add authentication to NuGet config

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#8404]
Currently, the C# frontend NuGet config is using anonymous access to download the Nuget packages from artifactory.
While this works, it does not provide the Artifactory logs with enough information about the requests received (See [this thread for more info](https://discuss.sonarsource.com/t/disabling-anonymous-access-to-jfrog-artifactory-repox-1st-sprint-information-gathering)).

The appropriate credentials should be added to the NuGet config.

[Instructions to add credentials.](https://xtranet-sonarsource.atlassian.net/wiki/spaces/RE/pages/2972123145/JFrog+Artifactory+repox+authentication#NuGet) - we should use the Repox Artifactory NuGet token already present in Vault.

Related tickets:
- https://sonarsource.atlassian.net/browse/SONARSEC-4673
- https://sonarsource.atlassian.net/browse/BUILD-3140

**Comment by marqustd** [comment]
Any update on this? Is this the issue meant in the last Release note?
> Please note that the NuGet packages are not been validated yet from nuget.org in this version because of infrastructure problems, that we are currently trying to address.

**Comment by andrei-epure-sonarsource** [comment]
No @marqustd , this is related to our internal Nuget proxy.

What is mentioned in the release notes is due to nuget.org returning an error when we try to push our package. The NuGet folks haven't replied to our emails yet. They've been having an incident regarding package publishing for the past 10 days (https://status.nuget.org/), I am not sure if it's related or not.

**Comment by marqustd** [comment]
Ok. :) Thank you for very fast answer, @andrei-epure-sonarsource!
