### ISSUE TITLE
RSPEC-6602 documentation is misleading

### ISSUE THREAD

**Issue by Carbion** [SonarSource/sonar-dotnet#8442]
The RSPEC-6602 rule suggest that Find can be simply replace FirstOrDefault with better performance.

In my opinion the rule should mentioned that Find will raise an exception if no matching element can be found.
This is a breaking change and needs more code change than only replacing the method name.

**Comment by mary-georgiou-sonarsource** [comment]
Hello @Carbion,

Thanks for raising this.
As far as I saw in the [Microsoft docs](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.find?view=net-8.0), the `Find` method does not throw an exception in case no matching element is found - it just returns the default value (`null` in case of objects or the default value in case of structs). I also tested this practically.

Could you please provide me with a snippet of code demonstrating the issue in case I did not understand your message well?

Thanks.

**Comment by Carbion** [comment]
Thank you for your comment and my apologies, I misread the documentation. 
You are right the Find is a adequate replacement.
