### ISSUE TITLE
Fix S3928 FP: `throw new ArgumentOutOfRangeException(nameof(_instanceField), _instanceField)`

### ISSUE THREAD

**Issue by n0099** [SonarSource/sonar-dotnet#8462]
### Description

https://github.com/SonarSource/sonar-dotnet/issues/8386#issuecomment-1847872210
https://rules.sonarsource.com/csharp/RSPEC-3928/
> Exceptions
> The rule won’t raise an issue if the parameter name is not a constant value (inline declaration, nameof() or const variable).

### Repro steps

https://github.com/n0099/open-tbm/blob/4062d0b2e5582d4c67fa10825ee9faf3efd42c6d/c%23/imagePipeline/src/Ocr/PaddleOcrRecognizerAndDetector.cs#L35

### Expected behavior

Not reporting since using nameof()

### Actual behavior

FP

### Known workarounds

None

### Related information

* C#/VB.NET Plugins version `<PackageReference Include="SonarAnalyzer.CSharp" Version="9.15.0.81779" ExcludeAssets="compile" />`
* Visual Studio version `VS2022 LTSC 17.6.10`
* MSBuild / dotnet version `.NET 7.0.311`
* SonarScanner for .NET version (if used)
* Operating System `Windows 8.1`

**Comment by pavel-mikula-sonarsource** [comment]
Hi @n0099,

This is actually a true positive. 

The problem is that the rule description is out-of-date. `nameof` is a compile-time constant and is supported now. It's actually the recommended way of passing argument names to their respective exceptions.

**Comment by pavel-mikula-sonarsource** [comment]
PR to fix the description: https://github.com/SonarSource/rspec/pull/3500
