### ISSUE TITLE
Fix S2589 FP: Rule should not raise in case of var pattern where the variable is later used in the same conditional expression

### ISSUE THREAD

**Issue by sagi1623** [SonarSource/sonar-dotnet#8502]
### Description

Rule should not raise in case of var pattern where the variable is later used in the same conditional expression

### Repro steps

https://sonarcloud.io/project/issues?issues=AYon5-dgmw8zdopbp6Ko&open=AYon5-dgmw8zdopbp6Ko&id=sonaranalyzer-dotnet

### Expected behavior

No issue should be raised.

### Actual behavior

An issue is raised.

### Known workarounds

None

### Related information

* C#/VB.NET Plugins version: 9.16

**Comment by pavel-mikula-sonarsource** [comment]
Hi, 
this was fixed in yesterday's release. It will be on SC in January
https://github.com/SonarSource/sonar-dotnet/issues/8326
