### ISSUE TITLE
Fix S3220 FP: Rule does not take into account generics

### ISSUE THREAD

**Issue by RenderMichael** [SonarSource/sonar-dotnet#8522]
### Description

The following code produces a S3220 warning at the `Caller.Test<T>(string key)` method, even though the generic parameter is crucial to the method's execution.

### Repro steps

``` csharp
internal static class Called
{
    public static T? Get<T>(params string[] key)
    {
        ArgumentNullException.ThrowIfNull(key);
        return default;
    }

    public static string? Get(string key)
    {
        ArgumentNullException.ThrowIfNull(key);
        return default;
    }
}

internal static class Caller
{
    public static T? Test<T>(string key)
    {
        return Called.Get<T>(key);
    }
}

```
### Expected behavior

No warning.

### Actual behavior

Warning.

### Known workarounds

Not without violating S3878.

### Related information

I'm using the Visual Studio extension, version 7.5.0.82292

**Comment by Tim-Pohlmann** [comment]
Hi @RenderMichael, very good catch! We will address this in a future hardening sprint. Thanks for the report!
