### ISSUE TITLE
dotnet sonarscanner did not find java but JAVA_HOME exists. Tried jre 11,13, 17 on ubuntu 20.04.3

### ISSUE THREAD

**Issue by AlexNetCooler** [SonarSource/sonar-dotnet#8552]
Hi! I am starting proper command

~/project$ /usr/bin/dotnet sonarscanner end /d:sonar.login="admin" /d:sonar.password="user"

and got the java error on ubuntu 20.04.3

SonarScanner for MSBuild 5.2.2 Using the .NET Core version of the Scanner for MSBuild Post-processing started. Calling the SonarScanner CLI... Could not find 'java' executable in JAVA_HOME or PATH. The SonarScanner did not complete successfully 20:05:32.56 Post-processing failed. Exit code: 1

There are SonarQube 8.9.10 in docker and .net 5 global tool sonarscanner 5.2.2.

JAVA_HOME and PATH were set to the same java elf dynamic shared object with chmod +x. What's wrong? Thank you.

java --version

openjdk 11.0.21 2023-10-17 OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-0ubuntu120.04) OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)

echo $PATH

/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-11-openjdk-amd64/bin/java

echo $JAVA_HOME

/usr/lib/jvm/java-11-openjdk-amd64/bin/java

Applied sudo chmod +x /usr/lib/jvm/java-11-openjdk-amd64/bin/java

It is default-jre.

Do I need to build C#plugin and put it into SQ docker? How properly make it for these versions?

**Comment by mary-georgiou-sonarsource** [comment]
Hello, @AlexNetCooler, and thanks a lot for reporting this.
 Could you please make [a post here on our community forum](https://community.sonarsource.com/) regarding this?
This repo is for reporting issues related to the analyzer rather than the scanner.
Meanwhile, we'll start looking into it.
Thanks a lot!

**Comment by AlexNetCooler** [comment]
https://community.sonarsource.com/t/dotnet-sonarscanner-5-2-2-on-ubuntu-20-04-3-with-net-5-show-error-on-end-post-processing-about-java/107441
