### ISSUE TITLE
Fix S3267 FP: Refactor loop to use Where on IAsyncEnumerable

### ISSUE THREAD

**Issue by paulhickman-ec** [SonarSource/sonar-dotnet#8566]
### Description

S3267 erroneously fires suggesting code be refactored to use LINQ ```where``` on an ```await foreach``` statement. ```Where()``` does not exist on ```IAsyncEnumerable<T>``` so the code the fixer generates fails to compile.

### Repro steps

````c#
class FooBar
{
    class Item { }

    IAsyncEnumerable<Item> Bar() => throw new NotImplementedException();

    bool Test(Item item) => throw new NotImplementedException();

    public async Task<int> Foo()
    {
        int count = 0;
        await foreach (var item in Bar())
        {
            if (Test(item))
            {
                count++;
            }
        }
        return count;
    }
}
````

The S3267 fixer rewrites ```Foo``` to:

````c#
    public async Task<int> Foo()
    {
        return (from item in Bar()
                where Test(item)
                select item).Count();
    }
````

Which has error CS1936 on the call to ```Bar()``` and also lacks the ```await```, or if you choose call form:

````c#
    public async Task<int> Foo()
    {
        return Bar().Where(item => Test(item)).Count();
    }
````
Which has error CS1061 and also lacks any await

### Expected behavior

Rule does not fire on an "await foreach" statement.

### Actual behavior

Rule does fire on an "await foreach" statement.

### Known workarounds

Suppress S3264

### Related information

* C#/VB.NET Plugins version: 9,17,9,82934
* .Net Version: 6 (c# 10)
* Visual Studio version: 17.8.3
* Operating System: Windows 11

**Comment by cristian-ambrosini-sonarsource** [comment]
Hi @paulhickman-ec, I confirm this as a FP.
I'll add a reproducer on our repository in a bit, we will address this in a future hardening sprint.

Thank you!

**Comment by cristian-ambrosini-sonarsource** [comment]
Hi @paulhickman-ec, I'm coming back to this after a colleague suggested using the [System.Linq.Async](https://www.nuget.org/packages/System.Linq.Async) package from Nuget. 
I was not aware of this package but it should do the trick and allow a more concise and easier-to-read version of the code:

```cs
public async Task<int> Foo()
{
    return await Bar().Where(Test).CountAsync();
}
```

Unfortunately, the code fix is on Microsoft's side so we cannot do much about that. 
To summarize, the rule is indeed correct in raising awareness about a more concise way of doing the same thing, in this case through the [System.Linq.Async](https://www.nuget.org/packages/System.Linq.Async) package. Therefore, I will proceed to close this issue.
