### ISSUE TITLE
Fix S1643 FP: Recommends use of StringBuilder when string is used in the loop

### ISSUE THREAD

**Issue by paulhickman-ec** [SonarSource/sonar-dotnet#8569]
### Description

In the code below, S1643 fires recommending a StringBuilder is used, despite the string being passed to another method on each loop iteration.

### Repro steps

````c#

void Bar(string x) => throw new NotImplementedException();

void Foo()
{
    string x = "";
    for(int i=1;i<10;i++)
    {
        x += 'x';
        Bar(x);
    }
}
````

### Expected behavior

S1643 should not be raised as x is passed to the ```Bar(x)``` method which would require many ToString() calls on a StringBuilder if one was used.

### Actual behavior

S1643 is raised.

### Known workarounds

Suppress S1643.

### Related information

C#/VB.NET Plugins version: 9,17,9,82934
.Net Version: 6 (c# 10)
Visual Studio version: 17.8.3
Operating System: Windows 11

**Comment by cristian-ambrosini-sonarsource** [comment]
Hi @paulhickman-ec! 
I ran a quick benchmark between:
```cs
void Bar(string x) => throw new NotImplementedException();

void Foo()
{
    StringBuilder x = new StringBuilder();
    for(int i=1;i<10;i++)
    {
        x.Append('x');
        Bar(x.ToString());
    }
}
```
and
```cs
void Bar(string x) => throw new NotImplementedException();

void Foo()
{
    string x = "";
    for(int i=1;i<10;i++)
    {
        x += 'x';
        Bar(x);
    }
}
```
And the StringBuilder seems more performant for an appreciable amount of iterations. 
Do you have different data?

**Comment by cristian-ambrosini-sonarsource** [comment]
I'll close this for now as the benchmark results shared [here](https://github.com/SonarSource/sonar-dotnet/issues/8569#issuecomment-1907749947) appear to validate that StringBuilder remains a more efficient option than concatenations within a loop.
