### ISSUE TITLE
Fix S2589 FP: List count with AddRange()

### ISSUE THREAD

**Issue by rodchenkov** [SonarSource/sonar-dotnet#8570]
### Description

I have warning **S2589** for `list.Count == 0` but I'm sure it is false positive.

### Repro steps

Please find code below:
```csharp
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            ArgumentNullException.ThrowIfNull(operation);
            ArgumentNullException.ThrowIfNull(context);

            if (Array.Exists(context.MethodInfo.GetCustomAttributes(true), x => x is AllowAnonymousAttribute)) return;

            var authorizeAttributes = new List<AuthorizeAttribute>();
            var swaggerSecurityAttributes = new List<SwaggerSecurityAttribute>();

            // Get method attributes
            authorizeAttributes.AddRange(context.MethodInfo.GetCustomAttributes(true).OfType<AuthorizeAttribute>());
            swaggerSecurityAttributes.AddRange(context.MethodInfo.GetCustomAttributes(true).OfType<SwaggerSecurityAttribute>());

            // Get class attributes
            if (context.MethodInfo.DeclaringType != null)
            {
                authorizeAttributes.AddRange(context.MethodInfo.DeclaringType.GetCustomAttributes(true).OfType<AuthorizeAttribute>());
                swaggerSecurityAttributes.AddRange(context.MethodInfo.DeclaringType.GetCustomAttributes(true).OfType<SwaggerSecurityAttribute>());
            }

#pragma warning disable S2589
            if (authorizeAttributes.Count == 0) return;
#pragma warning restore S2589

            ...

         }
```

### Expected behavior

No warning **S2589** for line `if (authorizeAttributes.Count == 0) return;`

### Actual behavior

Warning **S2589** for line `if (authorizeAttributes.Count == 0) return;`

### Known workarounds

Only suppress warning

### Related information

* C#
* Visual Studio 2022
* dotnet 6/7/8
* SonarScanner for .NET version 9.16.0.82469
* Linux

**Comment by gregory-paidis-sonarsource** [comment]
Hey @rodchenkov ,
I confirm that this is a false positive.
I added it to our backlog, where it will be taken care of along other S2589 FPs soon.
Thanks for raising this.

**Comment by gregory-paidis-sonarsource** [comment]
Something to add, implementation-wise:
In the expression `first.AddRange(second)`, second is cleared of `CollectionConstraint` because it's used as `Argument`.
This might be problematic when trying to establish when `AddRange` should influence the `CollectionConstraint` of `first`.

**Comment by devedse** [comment]
I also ran into this issue, wouldn't it be better to disable this rule for now until it's fixed?

Here's another simple scenario to reproduce it:

```
namespace SonarQubeRulesTest;

internal class Program
{
    static void Main(string[] args)
    {
        var theList = new List<int>();

        theList.AddRange(GetNumbers());

        if (theList.Any())
        {
            Console.WriteLine("Numbers found");
        }
        else
        {
            Console.WriteLine("No numbers found");
        }

    }

    public static IEnumerable<int> GetNumbers()
    {
        return new List<int> { };
    }
}
```

**Comment by Tim-Pohlmann** [comment]
Another [user report](https://community.sonarsource.com/t/s2589-always-triggers-with-addrange/124281/7)
