### ISSUE TITLE
Fix S5332 FP: Rule should not trigger on iTunes namespaces

### ISSUE THREAD

**Issue by dougwaldron** [SonarSource/sonar-dotnet#8776]
See #4171 for background: "No issue should be raised if the domain is one of the following as they are commonly used for XML or similar namespaces."

I'm getting a FP for `http://www.itunes.com/dtds/podcast-1.0.dtd`. This namespace is [required by Apple](https://podcasters.apple.com/support/823-podcast-requirements) for podcast RSS feeds.

**Comment by gregory-paidis-sonarsource** [comment]
Hey @dougwaldron , 
Thanks for raising this, I confirm it as a FP.
The fix seems easy enough, so I already make a PR for it.
You can track the effort there, and this issue will follow the lifetime of the PR, meaning it will be closed as completed when the PR is merged.
You will see the fix on the next versions of SonarLint and/or SonarQube/SonarCloud. :)
