### ISSUE TITLE
Remove directory from sonar analyzer

### ISSUE THREAD

**Issue by rafaelpavao** [SonarSource/sonar-dotnet#8856]
How can I exclude a directory from SonarAnalyzer analysis, considering that I am only using the SonarAnalyzer.CSharp package, without SonarQube or SonarCloud?

I tried this, but the more specific rules overwrote it:
```
# Ignore paths
[**/Migrations/*.cs]
dotnet_diagnostic.severity = none
```

**Comment by pavel-mikula-sonarsource** [comment]
Hi @rafaelpavao,

https://community.sonarsource.com/ is the best place to ask for help with our products.

Personally, I'm not sure that Microsoft supports `dotnet_diagnostic.severity = none` in the editor config file. You should follow Microsoft documentation about `.editorconfig` and rule activation.
