### ISSUE TITLE
Fix S2259 FP: Engine does not learn `NotNull` from LINQ methods

### ISSUE THREAD

**Issue by Tim-Pohlmann** [SonarSource/sonar-dotnet#8907]
Most LINQ methods like `.Count()` do [throw](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.count?view=net-8.0) when the collection is `null`. The engine should learn `NotNull` when a method like this is invoked to avoid FPs (e.g., for S2259).

```
private void Foo(string[] values)
{
    if (values == null)
    {
        Console.WriteLine("Oops!");
    }
    if (5 < values.Count())         // FN, will throw when values is null; separate issue, see #8908
    {
        _ = values[5].ToString();   // Noncompliant FP, we do not learn NotNull from LINQ methods
    }
}
```
Related: #8908

**Comment by antonioaversa** [comment]
Handing over this work to @Tim-Pohlmann, who will bring it to completion.
