### ISSUE TITLE
Exception on numeric comparison switch expression

### ISSUE THREAD

**Issue by 1619digital** [SonarSource/sonar-dotnet#8927]
### Description

A `SymbolicExecutionException `is thrown on certain switch expression with a combination of non-integers and greater than / less than

### Repro steps

```
	public static bool IsGreaterThanTen(decimal n) => n switch
	{
		> 10M => true,
		_ => false
	};
	
	public static bool IsGreaterThanATenth(double n) => n switch
	{
		> 0.1 => true,
		_ => false
	};

```

### Known workarounds

Both these will fail. In the first example the literal seems to be causing the issue; in the second it fails because it's not an integer. My guess is that the expression needs to be whole number non-literal; negative integer seem ok.

### Related information

Sonarlint plugin for Visual Studio 7.7.0.86423

**Comment by Tim-Pohlmann** [comment]
Hi @1619digital, and thanks for the report!
This is the same problem as in #8787. The fix has been released in version 9.21 of our analyzer, which should be shipped with the next version of SonarLint. Sorry for the inconvenience!
