### ISSUE TITLE
Update release pipeline to publish SonarAnalyzer.CSharp.Styling NuGet

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#9036]

**Comment by pavel-mikula-sonarsource** [comment]
@sebastien-marichal To review:

As the existing task uses `SonarAnalyzer.CSharp.*.nupkg` to select package(s) to publish, there should be no additional changes needed.

![image](https://github.com/SonarSource/sonar-dotnet/assets/57188685/02887e74-ad1a-4403-8d18-60a997e91cec)

**Comment by sebastien-marichal** [comment]
Indeed, we can close this as there is nothing more to do.
