### ISSUE TITLE
New rule S6960 for C#: Controllers should not have too many responsibilities

### ISSUE THREAD

**Issue by mary-georgiou-sonarsource** [SonarSource/sonar-dotnet#9089]
RSPEC PR: https://github.com/SonarSource/rspec/pull/3845

Parts:
- [x] Disjoint Sets primitives: https://github.com/SonarSource/sonar-dotnet/pull/9145
- [x] Basic implementation: https://github.com/SonarSource/sonar-dotnet/pull/9111
  - [x] Support for `Func<service>` and `Lazy<service>`: Service should not be well-known
  - [x] Support injected classed with "service" as suffix
  - [x] Support indexers (treated as methods, not as properties)
  - [x] Method overloads are handled as a single group
  - [x] Filter out groups of actions not using any service
  - [x] Change message from "Belongs to responsibility #X" to "May belong to responsibility #X"
  - [x] Fix ASP.NET 4x wrongly detected as good candidate for the rule
  - [x] Exclude `IHttpClientFactory` (consider as well-known dependency)
  - [x] Fix numbering of responsibilities in presence of unused services
  - [x] Change behavior to include all classes and remove the "service suffix" exception
  - ~[ ] Introduce `S6960IncludeAttribute` and `S6960ExcludeAttribute`~
  - [x] Exclude `abstract` controllers (because of scenarios like [this one](https://peach.aws-prd.sonarsource.com/issues?projects=umbraco&resolved=false&rules=csharpsquid%3AS6960&open=AY8vNwRCr4ooVA6A4A34))
  - [x] Exclude controllers that don't inherit directly from ControllerBase
  - ~[ ]Exclude inherited methods (because there is no option than to implement them)~ this is canceled by previous task
- [ ] Deeper tests of shared fields not of type interface 
- [ ] Deeper tests of static properties, methods and constructors

**Comment by antonioaversa** [comment]
>  Exclude inherited methods (because there is no option for the user than to implement them)

This may reduce the reach a lot, as many of the big projects have hierarchies of controllers. If there is an `abstract` base class and there is at least an method which is `abstract`, there is indeed no option for the user and we may want to exclude the controller altogether.

**Comment by denis-troller** [comment]
An issue with static methods in file https://peach.aws-prd.sonarsource.com/issues?projects=umbraco&resolved=false&rules=csharpsquid%3AS6960&open=AY8vNwi3r4ooVA6A4A55

Should we exclude static methods?
