### ISSUE TITLE
Fix S1144 FP: Getters/Setters of property with attribute are being flagged

### ISSUE THREAD

**Issue by Daeymon** [SonarSource/sonar-dotnet#9219]
### Description

Members with an attribute are being flagged. The documentation states they should be exceptions to the rule.
![image](https://github.com/SonarSource/sonar-dotnet/assets/29780145/68e26207-8659-4a09-b4ae-98eaca959403)

### Repro steps

![image](https://github.com/SonarSource/sonar-dotnet/assets/29780145/d4a36ba2-4e96-4739-a3b0-89b015df4081)

### Expected behavior
The setter should not be flagged.

### Actual behavior
The setter is flagged.

### Related information
SonarAnalyzer.CSharp: 9.24.0.89429
Visual Studio: 17.9.6
Dotnet version: .NET 8
Operating System: Windows 10 Enterprise, 21H2

**Comment by gregory-paidis-sonarsource** [comment]
Hey there,
I can confirm this is an FP, and I added it to our backlog to track it.
I will try to come up with a fix for you soon, as the case seems isolated to properties.

Thanks for raising this!
 Feel free to track this ticket, it will be closed when the fix is merged.
