### ISSUE TITLE
Some codes not showing on Visual Studio

### ISSUE THREAD

**Issue by will-bfr** [SonarSource/sonar-dotnet#9317]
I'm using the most recent package for SonarAnalyzer.CSharp (9.25.0.90414) and I don't have the warning of some errors that the sonarqube finds, for example the warning 109 does not show in my IDE. 
What am I doing wrong?

**Comment by pavel-mikula-sonarsource** [comment]
Hi,

Please make sure you have SonarLint installed and you've set up Connected Mode, so your instance is aware of your server settings.

Please refer to https://community.sonarsource.com/ for further assistance.
