### ISSUE TITLE
Fix T0004 FP: Do not raise in codebase missing RegexExtension.SafeIsMatch

### ISSUE THREAD

**Issue by sebastien-marichal** [SonarSource/sonar-dotnet#9328]
The rule should not raise if the [RegexExtension](https://github.com/SonarSource/sonar-dotnet/blob/8a5a8435f105fbf2ebcde81af108f13ab268347d/analyzers/src/SonarAnalyzer.Common/Extensions/RegexExtensions.cs) class is missing from the current codebase.
Now it should only be raised in sonar-dotnet.

**Comment by alex-meseldzija-sonarsource** [comment]
Implemented with NET-264
