### ISSUE TITLE
Fix S6966 FP: FluentValidation ValidateAsync should not be proposed

### ISSUE THREAD

**Issue by martin-strecker-sonarsource** [SonarSource/sonar-dotnet#9339]
Originally reported at https://community.sonarsource.com/t/c-s6966-with-fluentvalidation/116030.

### Description

Fluent validation supports asynchronous validation rules as described [here](https://docs.fluentvalidation.net/en/latest/async.html).
The validator fails with an exception if asynchronous rules are present and `Validate()` is called. In most cases, validation is synchronous, and sometimes, the context requires synchronous processing:
> Warning
If your validator contains asynchronous validators or asynchronous conditions, it’s important that you always call ValidateAsync on your validator and never Validate. If you call Validate, then an exception will be thrown.
You should not use asynchronous rules when [using automatic validation with ASP.NET](https://docs.fluentvalidation.net/en/latest/aspnet.html) as ASP.NET’s validation pipeline is not asynchronous. If you use asynchronous rules with ASP.NET’s automatic validation, they will always be run synchronously (10.x and older) or throw an exception (11.x and newer).

[Source](https://docs.fluentvalidation.net/en/latest/async.html)

FluentValidation has built-in guards about properly using "Validate vs. ValidateAsync". ValidateAsync is even the wrong choice in some circumstances, so S6966 has a high false positive ratio for this API.

**Comment by coyoteecd** [comment]
@martin-strecker-sonarsource exactly the same issue occurs for FluentValidation's `ValidateAndThrow` method. This is just a helper and is subject to the same rules as Validate vs ValidateAsync. Is it possible to ignore this as well?

**Comment by martin-strecker-sonarsource** [comment]
Thanks for reporting @coyoteecd. We seem to have missed this. I have created a new ticket: #9589
