### ISSUE TITLE
Disabling the "Skip unchanged files mechanism"

### ISSUE THREAD

**Issue by Bouke** [SonarSource/sonar-dotnet#9532]
Currently SonarAnalyzer will skip producing warnings for unchanged files. This is IMO fundamentally incorrect; changes to one file could introduce warnings in other unchanged files. Therefore I want to disable the "Skip unchanged files mechanism". The [documentation][1] shows how to do this for Java, but how can I do this for SonarAnalyzer?

As an added benefit I'll get to use [BuildQualityChecks][0] to enforce the total number of warnings to go down.

[0]: https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md
[1]: https://docs.sonarsource.com/sonarcloud/advanced-setup/incremental-analysis-mechanisms/#disable-skip-unchanged

**Comment by pavel-mikula-sonarsource** [comment]
Hi @Bouke,

https://community.sonarsource.com/ is the best place to ask similar questions.
