### ISSUE TITLE
Fix S2629 FP: Do not raise on log4net.Error(Exception)

### ISSUE THREAD

**Issue by gregory-paidis-sonarsource** [SonarSource/sonar-dotnet#9547]
### Description

`log4net` has a method to log exceptions directly. In that case, we should not raise S2629, as there is no way to pass both an exception and the format arguments.

### Repro steps

```csharp
void Repro(ILog logger, string filePath, Exception ex)
{
     logger.Error($"Error while loading file '{filePath}'!", ex); // Noncompliant FP
 }
```

We should exclude the overload that takes an exception from the list of raising methods.

Originally raised on [community](https://community.sonarsource.com/t/no-good-solution-for-avoiding-s2629-when-trying-to-log-exception-and-additional-args-with-log4net/119384).

**Comment by CrushaKRool** [comment]
It's probably self-evident, but just to make sure I would like to point out that I've only used the `Error(object, Exception)` method as an example. The solution that avoids the FP should also cover the additional methods `Debug(object, Exception)`, `Info(object, Exception)`, `Warn(object, Exception)` and `Fatal(object, Exception)`.

**Comment by alex-meseldzija-sonarsource** [comment]
Implemented with NET-278
