### ISSUE TITLE
Load STIG standard after ACOMMONS-11 is done

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#9558]
Next week, a new version of analyzer commons will be added via https://sonarsource.atlassian.net/browse/ACOMMONS-11 to enable the import of a new security standard.

As part of the SQ plugin hardening sprint, we should update Analyzer commons and call the metadata API.

~~Check the PR for adding support for ASVS  standard - should be the same thing as in https://github.com/SonarSource/sonar-dotnet/pull/5941~~
Edit by Mary: Functionality of this PR is no longer valid. We use the common functionality to add security standards by sonar-commons-io. Should be enough to update the package sonar-commons-io and add tests.

- [ ] Add a check for the SonarQube version (it will be shipped in 10.7 in September). On SonarCloud it's already supported.
- [ ] Tests are in [CSharpSonarRulesDefinitionTest ](https://github.com/SonarSource/sonar-dotnet/blob/9.30.0.95878/sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpSonarRulesDefinitionTest.java#L91).

**Comment by mary-georgiou-sonarsource** [comment]
sonar-commons should be released today or tomorrow; however, we also need this PR to be merged https://github.com/SonarSource/rspec/pull/4098 in order to be able to close this issue.
