### ISSUE TITLE
SQ Plugin: Remove RoslynProfileExporter

### ISSUE THREAD

**Issue by mary-georgiou-sonarsource** [SonarSource/sonar-dotnet#9564]
Profile exporters [have been deprecated](https://sonarsource.atlassian.net/browse/SONAR-15195) and should be removed in the near future. *

Once the feature is removed from SQ, we should remove the [RoslynProfileExporter](https://github.com/SonarSource/sonar-dotnet/blob/de411dbdcd403cde5b00b20cb833131f0ef5516e/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/RoslynProfileExporter.java) class and its tests from the plugin.
Note that S4MSB does not use this class since [this commit.](https://github.com/SonarSource/sonar-scanner-msbuild/commit/ce945d).

~~_I'll add a link to the jira ticket related to the profile exporter removal once it's created by the SQ platform team._~~

update after ~~Pavel's comment below~~ checking the deprecation policy on xtranet and discussing with Pavel:
Exporters have been deprecated since 9.1 and, according to the [SQ deprecation policy ](https://xtranet-sonarsource.atlassian.net/wiki/spaces/SQ/pages/2494496836/SonarQube+Deprecation+Policy), can be removed in any version after 10.1.

This means we can safely remove them as of now.

- [ ] Refactor [sonarLintRepositoryProperties](https://github.com/SonarSource/sonar-dotnet/blob/13646f5b086ce67c7732c1e0e7d467f39179f502/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/RoslynProfileExporter.java#L87): This method is executed on the SQ server side and it's used to compute the response of  the[ /api/settings/values](https://next.sonarqube.com/sonarqube/web_api/api/settings/set) endpoint. It should be moved to a more appropriate location and renamed to reflect better what it does and commented to mention where it's used and how.
- [ ] Delete [RoslynProfileExporter](https://github.com/SonarSource/sonar-dotnet/blob/13646f5b086ce67c7732c1e0e7d467f39179f502/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/RoslynProfileExporter.java#L63) and its tests.
- [ ] Delete [SonarLintProfileExporter](https://github.com/SonarSource/sonar-dotnet/blob/13646f5b086ce67c7732c1e0e7d467f39179f502/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SonarLintProfileExporter.java#L24) and tests (rulesets are deprecated and users should opt for connected mode)

**Comment by pavel-mikula-sonarsource** [comment]
We don't need to wait for the removal of the base functionality from products. We can remove this anytime after SQL 10.x LTA release. So this could be removed in 11.0 on our side

**Comment by andrei-epure-sonarsource** [comment]
I am confused. If we want to remove this **after** the LTA, why is this ticket still in progress and has a PR that will close it in this sprint?

**Comment by mary-georgiou-sonarsource** [comment]
@andrei-epure-sonarsource 
[In the deprecation policy of SQ it's mentioned](https://xtranet-sonarsource.atlassian.net/wiki/spaces/SQ/pages/2494496836/SonarQube+Deprecation+Policy)

```
Something deprecated in 8.X can only be removed in 9.X, to give enough time for users to adapt and so that users can choose when to upgrade.

Example: deprecate in 8.8 and remove in 9.0 - Not ideal but possible and would allow us to bring new features in the next major version. It also depends on how impactful those changes are and how long it takes for users to adapt to them.
```

This feature [has been deprecated since 9.1](https://sonarsource.atlassian.net/browse/SONAR-15195) so my understanding is that we can remove it since 10.X.
Additionally, this feature works with dependency injection, it appears because we publish it from the plugin, so it's on our side to remove it (SQ does not break, analysis does not break).
So, being past the deprecation policy and not needing something from SQ IMO, we can safely remove this. 

Let me know if I've understood something totally wrong.


Now, regarding this ticket in practice: the `RoslynProfileExporter` won't be removed in this release as the class is not only used to help with profile export in SQ but also write the ruleset files during the begin step of the scanner in the `.sonarqube` folder. My plan for now is to fully understand where and how this is happening - document it here so we can delete the needed code and tests and refactor accordingly (I'll update the open PR accordingly to make it clear, I forgot to do so on Wednesday).
However, I'd like to clarify my understanding of the deprecation for future removal of features.

**Comment by andrei-epure-sonarsource** [comment]
> My plan for now is to fully understand where and how this is happening - document it here so we can delete the needed code and tests and refactor accordingly (I'll update the open PR accordingly to make it clear, I forgot to do so on Wednesday).

Great.

> Additionally, this feature works with dependency injection, it appears because we publish it from the plugin, so it's on our side to remove it (SQ does not break, analysis does not break).

If it's not used in any functionality exposed by SQ as an API (e.g. users downloading the profile for whatever reason) - then there's no problem in removing. You could send an email to our support colleagues - if they have no idea about this functionality, we can safely remove it.

> However, I'd like to clarify my understanding of the deprecation for future removal of features.

The page says _"Ideally, those changes should be done in 9.0 so that they can keep upgrading in 9.X without more breaking changes and for consistency with versioning best practices"_

Versioning best practice means any breaking change requires a major version update.
If we introduce breaking changes from 10.6 to 10.7, even if it's for removing deprecated APIs, it's can be a friction points for users updating.

All in all, here I think you are correct saying that from 9.1 users had plenty of time to see the deprecated API and react.

**Comment by pavel-mikula-sonarsource** [comment]
https://sonarsource.atlassian.net/browse/NET-735
