### ISSUE TITLE
Roslyn analyzer - `Suggestion` severity mapped to `Medium` severity in SonarQube

### ISSUE THREAD

**Issue by im-aIex** [SonarSource/sonar-dotnet#9639]
### Description

When enabling the external Roslyn analyzer and configuring specific rules within a `.editorconfig` to be `suggestion`, the severity in SonarQube is showing as `Medium`. This is counter intuitive as the `suggestion` is generally not enforced to the same extent as `Medium` severity.

### Repro steps

![image](https://github.com/user-attachments/assets/bca9a48e-1116-4ef0-81ca-99e082f0aa74)

![image](https://github.com/user-attachments/assets/fce24735-7897-420e-a41a-afa4e67bcffa)

### Expected behavior

`suggestion` severity roslyn rules should be mapped to `low` within sonarqube, or there should be the ability to configure the severity of external rules to align with configured `.editorconfig`

### Actual behavior

`suggestion` severity rule is mapped to `medium` severity in sonarqube.

### Known workarounds

Disable roslyn analyzer.

**Comment by sebastien-marichal** [comment]
Hello @im-aIex,

I am not able to reproduce the issue.

Can you provide the following information:
- Your `.editorconfig`?
- The build command
- If not using SonarCloud, the version of the SonarQube or the sonar-dotnet analyzer you are using

Thank you,
