### ISSUE TITLE
Fix S6667 FP: The catch block is going to rethrow, therefore no need to log the exception

### ISSUE THREAD

**Issue by ltvan** [SonarSource/sonar-dotnet#9666]
### Description

I tried to log some activities in case that a specific exception raised, and re-throw it. But the analyzer reports that S6667: Logging in a catch clause should pass the caught exception as a parameter.

If I put the exception as a parameter, S2139 will be triggered. 

### Repro steps

```csharp
try
{
//...
}
catch (SomeException)
{
    _logger.LogError("Some logging...")
    throw;
}
```

### Expected behavior

If the exception is going to be re-thrown, S6667 should not be triggered.

### Actual behavior

S6667 is still triggered in the case that the exception is going to be re-thrown.

### Known workarounds

N/A

### Related information

* SonarAnalyzer.CSharp Version="9.32.0.97167"
* Visual Studio 17.10.6
* dotnet 8
* Operating System: Windows

**Comment by sebastien-marichal** [comment]
Hello @ltvan,

Thank you for reporting this issue.
This has already been reported to us and confirmed as being an FP.

You can see the details in this [community post](https://community.sonarsource.com/t/s6667-versus-s2139/121059).

Have a good day!
