### ISSUE TITLE
Fix S6960 FP: Falsely detects MVC controller as API controller

### ISSUE THREAD

**Issue by rjgotten** [SonarSource/sonar-dotnet#9684]
### Description

S6960 is described as only applying to API controllers, but the rule seems to not care for the (non-)presence of an `[ApiController]` attribute, which is formally how a controller states that it is an API controller. Instead, it seems to rely on the fact that the controller inherits from `ControllerBase` and this causes it to also apply to regular MVC controllers inheriting from `ControllerBase` because they have no need of the support to render views. (E.g. because they only implement post-redirect-get patterns to other controllers.)

### Repro steps

Create any controller inheriting from `ControllerBase` _without_ an `[ApiController]` attribute on it, and trip the other conditions for S6960 to apply.

### Expected behavior

S6960 is not raised, because the controller is not an API controller.

### Actual behavior

S6960 is raised, even though the controller is not an API controller.

### Known workarounds

Suppress the rule.

### Related information

* C#/VB.NET Plugins version : whatever ships with SonarLint 8.3.0.10161
* Visual Studio version : VS 2022 v17.11.5
* MSBuild / dotnet version : MSBuild 17.11.9 / dotnet 8.0.403
* SonarScanner for .NET version (if used) : N/A
* Operating System : Windows 11

**Comment by rjgotten** [comment]
>It is quite hard to make sure that a controller is an API controller and not an MVC controller

No it's not.
If it has the `[ApiController]` attribute, it's an API controller. Otherwise it's not. Period.
The fact that users _think_ they're creating API controllers by just inheriting from `ControllerBase` doesn't mean they _are_.
They just get away with it, because topically the most important things kind-of-sort-of work -- thanks to (Or perhaps 'due to'? Matter of perspective?) Microsoft having consciously blurred the line between normal MVC controllers and API controllers.


> You can use [filters](https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/filters) or custom middleware to achieve the same redirection logic

Middleware is not the proper composable solution for endpoints any longer.
Endpoint routing is. Controllers are the de-facto easiest way to integrate with those, as they wire up automatically.

If you perform `MapControllers()` on an endpoint builder it will automatically discover all implementations of `IController` and wire them up. Using endpoint handlers directly is possible; but requires manually maintaining mappings.
On top of that; if you are building an application along a certain line of architecture, it's best for discoverability to other team members as well as - and probably in particular - those freshly on-boarding to not break from that line unless you have to.


> Can you think of another case where you would not derive from Controller, but instead from ControllerBase in MVC context?

Basic YAGNI.
If I have a controller that doesn't need to do anything special but take in some data and perform a redirect based on that data, then I'd rather use `ControllerBase` than `Controller` because:
1. The intent is to never have it support views; and this makes that separation of concerns clear.
2. `Controller` actually does more than just add support for views. It implements also `IActionFilter`, `IAsyncActionFilter` and `IDisposable`. The latter is a small cost, but the former can spend real effort doing nothing, since it involves aspect-oriented programming to run filters before/after execution of the main action method body.

**Comment by gregory-paidis-sonarsource** [comment]
> Microsoft having consciously blurred the line between normal MVC controllers and API controllers

I think that's the main point.
Right now, there are three "categories", broadly, for controllers:

- Clear cut API Controllers
- Clear cut View Controllers
- Something blurry in the middle

This case belongs to the third case.

> The fact that users think they're creating API controllers by just inheriting from ControllerBase doesn't mean they are.

Actually, for all senses and purposes, it does.
There is no reason to necessarily use the `ApiController` attribute.
This is the [convention](https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/actions?view=aspnetcore-8.0#what-is-a-controller) according to Microsoft for _view_ controllers. Notice that they mention deriving from `Controller` by convention.

And this is [how they hint](https://learn.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-8.0#:~:text=A%20controller%2Dbased%20web%20API%20consists%20of%20one%20or%20more%20controller%20classes%20that%20derive%20from%20ControllerBase.) to the same heuristic we are using in the code:

> A controller-based web API consists of one or more controller classes that derive from [ControllerBase](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase).

Also [here](https://learn.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-8.0#:~:text=Web%20API%20controllers%20should%20typically%20derive%20from%20ControllerBase%20rather%20from%20Controller.%20Controller%20derives%20from%20ControllerBase%20and%20adds%20support%20for%20views%2C%20so%20it%27s%20for%20handling%20web%20pages%2C%20not%20web%20API%20requests.%20If%20the%20same%20controller%20must%20support%20views%20and%20web%20APIs%2C%20derive%20from%20Controller.):

> Web API controllers should typically derive from [ControllerBase](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase) rather from [Controller](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controller). Controller derives from [ControllerBase](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase) and adds support for views, so it's for handling web pages, not web API requests. If the same controller must support views and web APIs, derive from Controller.

The `ApiController` attribute is mentioned as optional [here](https://learn.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-8.0#apicontroller-attribute):

>The [[ApiController]](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.apicontrollerattribute) attribute _can_ be applied to a controller class to enable the following opinionated, API-specific behaviors.

As Microsoft suggests, it's an optional, opinionated feature that you may or may not want to use.

In any case, I agree that this is a blurry line.
This means that we have to go about it in a best-effort way, and statistically speaking, if you inherit from `ControllerBase`, you are most probably intending to make an API Controller.
