### ISSUE TITLE
Enterprise Sonarqube DB export from existing instance to new instance

### ISSUE THREAD

**Issue by venkatjk** [SonarSource/sonar-dotnet#9686]
Hello

we are running Enterprise sonarqube 9.9 LTS version with Postgres database we were setting up another sonarqube instance and wanted to export data from running sonarqube to new sonarqube. 
we tried exporting db dump from existing SQ to new SQ with pg_restore and got following errors. Can  someone please advise if there are different methods to export the data and if anyone had got the below error messages while running pg_restore command.

****It throws errors stating - table/index already exists or user does not have privilege**.**

**Comment by costin-zaharia-sonarsource** [comment]
Hi @venkatjk,

This repository is strictly related to dotnet analyzers, and we cannot help with this kind of problem.

Could you please open a thread on https://community.sonarsource.com?
