### ISSUE TITLE
Fix S4275 FP: Support &= assignment

### ISSUE THREAD

**Issue by keith-softsure** [SonarSource/sonar-dotnet#9688]
SonarLint does not recognise &= operator as assignment

S4275 fails the SET statement and suggests that _feedback parameter is not assigned a value in this line:
 _feedback &= value

### Repro steps

    Friend Property Feedback As String
        Get
            Return _feedback
        End Get
        Private Set(value As String)
            value = Trim(value).Trim()
            Debug.Print(value)
            If _feedback <> Nothing Then _feedback &= vbCrLf
            _feedback &= value ' original Code
            ' _feedback = _feedback & value ' SonarLint compliant code
        End Set
    End Property
    Private _feedback As String

### Expected behavior

   _feedback &= value ' original Code 
         should be acceptable

### Actual behavior

  _feedback &= value ' original Code
 generates S4275 error

### Known workarounds

       _feedback = _feedback & value ' SonarLint compliant code

### Related information

* C#/VB.NET Plugins version ... 8.5.0.10497
* Visual Studio version ... 17.11.5
* MSBuild / dotnet version ... 4.8.09037
* Using SonarLint & Sonar Cloud
* Operating System ... Windows 10

**Comment by CristianAmbrosini** [comment]
Hi @keith-softsure! I confirm this as a false positive. I'll add a reproducer to our repository shortly. Thanks for the feedback!

**Comment by keith-softsure** [comment]
Thanks Cristian,

We really appreciate the feedback. And your good work. Cheers Keith

**Comment by CristianAmbrosini** [comment]
Done and released
